### ISSUE TITLE
http_error_default

### ISSUE THREAD

**Issue by rexmorgan99** [pytube/pytube#1015]
**********  Code   **********

import pytube

input_string = input("Enter a list of youtube videos that you want to download separated by a space ")
print("\n")

URL_List = input_string.split()
print("Video list consists of ", URL_List)

for url in URL_List:
    youtube = pytube.YouTube(url)
    print("\n")
    print("Downloading " + youtube.title)
    video = youtube.streams.get_highest_resolution().download('../Video')
    download_update = "Done downloading " + youtube.title
    print(download_update, "\n")
    

print(URL_List, "videos in the list have been downloaded. ")

**********    Errors listed in the Command Line    **********

Video list consists of  ['https://youtu.be/eykENwWAXbk']
Traceback (most recent call last):

  File "C:\Users\rexmo\Documents\Training\Python\church_youtube_download.py", line 20, in <module>
    youtube = pytube.YouTube(url)

  File "C:\Users\rexmo\anaconda3\lib\site-packages\pytube\__main__.py", line 104, in __init__
    self.prefetch()

  File "C:\Users\rexmo\anaconda3\lib\site-packages\pytube\__main__.py", line 221, in prefetch
    self.vid_info_raw = request.get(self.vid_info_url)

  File "C:\Users\rexmo\anaconda3\lib\site-packages\pytube\request.py", line 42, in get
    return _execute_request(url, headers=extra_headers).read().decode("utf-8")

  File "C:\Users\rexmo\anaconda3\lib\site-packages\pytube\request.py", line 26, in _execute_request
    return urlopen(request)  # nosec

  File "C:\Users\rexmo\anaconda3\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)

  File "C:\Users\rexmo\anaconda3\lib\urllib\request.py", line 531, in open
    response = meth(req, response)

  File "C:\Users\rexmo\anaconda3\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(

  File "C:\Users\rexmo\anaconda3\lib\urllib\request.py", line 563, in error
    result = self._call_chain(*args)

  File "C:\Users\rexmo\anaconda3\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)

  File "C:\Users\rexmo\anaconda3\lib\urllib\request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)

  File "C:\Users\rexmo\anaconda3\lib\urllib\request.py", line 531, in open
    response = meth(req, response)

  File "C:\Users\rexmo\anaconda3\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(

  File "C:\Users\rexmo\anaconda3\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)

  File "C:\Users\rexmo\anaconda3\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)

  File "C:\Users\rexmo\anaconda3\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

HTTPError: Not Found

**Comment by tfdahlin** [comment]
hi @rexmorgan99, this issue was fixed in a more recent version of pytube. Please update to the latest version by using this command: `python -m pip install --upgrade pytube`. At the time of writing this comment, the most recent version is 10.8.4, and it looks like you're running a version <10.6.0.

**Comment by clausagerskov** [comment]
also having this issue, in the most recent version of pytube:

Traceback (most recent call last):

  File "C:\Users\claus\Dropbox\00Language\02 Polish\tvp\youtube_dl.py", line 13, in <module>
    yt = YouTube(vid)

  File "C:\Users\claus\anaconda3\lib\site-packages\pytube\__main__.py", line 104, in __init__
    self.prefetch()

  File "C:\Users\claus\anaconda3\lib\site-packages\pytube\__main__.py", line 221, in prefetch
    self.vid_info_raw = request.get(self.vid_info_url)

  File "C:\Users\claus\anaconda3\lib\site-packages\pytube\request.py", line 47, in get
    return _execute_request(url, headers=extra_headers).read().decode("utf-8")

  File "C:\Users\claus\anaconda3\lib\site-packages\pytube\request.py", line 31, in _execute_request
    return urlopen(request)  # nosec

  File "C:\Users\claus\anaconda3\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)

  File "C:\Users\claus\anaconda3\lib\urllib\request.py", line 531, in open
    response = meth(req, response)

  File "C:\Users\claus\anaconda3\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(

  File "C:\Users\claus\anaconda3\lib\urllib\request.py", line 563, in error
    result = self._call_chain(*args)

  File "C:\Users\claus\anaconda3\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)

  File "C:\Users\claus\anaconda3\lib\urllib\request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)

  File "C:\Users\claus\anaconda3\lib\urllib\request.py", line 531, in open
    response = meth(req, response)

  File "C:\Users\claus\anaconda3\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(

  File "C:\Users\claus\anaconda3\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)

  File "C:\Users\claus\anaconda3\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)

  File "C:\Users\claus\anaconda3\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

HTTPError: Not Found

**Comment by tfdahlin** [comment]
hi @clausagerskov; you aren't running the most recent version of pytube. In the second line of that error, I see a call to the `.prefetch()` function which was removed in v10.6.0
