### ISSUE TITLE
[BUG] An error will be reported after downloading for a period of time

### ISSUE THREAD

**Issue by ArtomYuan** [pytube/pytube#1039]
An error will be reported after downloading for a period of time

When I download the playlist, I always report an error for a period of time

https://www.youtube.com/playlist?list=UUnK6aCU0ZTRXyrKkaXd-RMg

Traceback (most recent call last):
  File "c:\users\artom\appdata\local\programs\python\python39\lib\http\client.py", line 556, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "c:\users\artom\appdata\local\programs\python\python39\lib\http\client.py", line 523, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\artom\appdata\local\programs\python\python39\lib\http\client.py", line 573, in _readall_chunked
    chunk_left = self._get_chunk_left()
  File "c:\users\artom\appdata\local\programs\python\python39\lib\http\client.py", line 558, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\artom\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\artom\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Artom\AppData\Local\Programs\Python\Python39\Scripts\pytube.exe\__main__.py", line 7, in <module>
  File "c:\users\artom\appdata\local\programs\python\python39\lib\site-packages\pytube\cli.py", line 43, in main
    _perform_args_on_youtube(youtube_video, args)
  File "c:\users\artom\appdata\local\programs\python\python39\lib\site-packages\pytube\cli.py", line 57, in _perform_args_on_youtube
    download_highest_resolution_progressive(
  File "c:\users\artom\appdata\local\programs\python\python39\lib\site-packages\pytube\cli.py", line 472, in download_highest_resolution_progressive
    stream = youtube.streams.get_highest_resolution()
  File "c:\users\artom\appdata\local\programs\python\python39\lib\site-packages\pytube\__main__.py", line 308, in streams
    return StreamQuery(self.fmt_streams)
  File "c:\users\artom\appdata\local\programs\python\python39\lib\site-packages\pytube\__main__.py", line 211, in fmt_streams
    if "adaptive_fmts" in self.player_config_args:
  File "c:\users\artom\appdata\local\programs\python\python39\lib\site-packages\pytube\__main__.py", line 185, in player_config_args
    self._player_config_args = self.vid_info
  File "c:\users\artom\appdata\local\programs\python\python39\lib\site-packages\pytube\__main__.py", line 278, in vid_info
    return dict(parse_qsl(self.vid_info_raw))
  File "c:\users\artom\appdata\local\programs\python\python39\lib\site-packages\pytube\__main__.py", line 106, in vid_info_raw
    self._vid_info_raw = request.get(self.vid_info_url)
  File "c:\users\artom\appdata\local\programs\python\python39\lib\site-packages\pytube\request.py", line 53, in get
    return response.read().decode("utf-8")
  File "c:\users\artom\appdata\local\programs\python\python39\lib\http\client.py", line 466, in read
    return self._readall_chunked()
  File "c:\users\artom\appdata\local\programs\python\python39\lib\http\client.py", line 580, in _readall_chunked
    raise IncompleteRead(b''.join(value))
http.client.IncompleteRead: IncompleteRead(24100 bytes read)

Hope to download a complete playlist stably

- Python version (3.9)
- Pytube version (10.8.5)
- python -m pip install pytube

**Comment by tfdahlin** [comment]
hi @ArtomYuan this is likely caused by an unstable internet connection, but I know how to make it possible to work with. It looks like you're using the CLI, is that correct?

I need to add some additional handling for `IncompleteRead` errors to videos, add support for retries, and then add some CLI args so that you can enable retries and request timeouts. I'll try to get to this when I'm able to.

**Comment by ArtomYuan** [comment]
> hi @ArtomYuan this is likely caused by an unstable internet connection, but I know how to make it possible to work with. It looks like you're using the CLI, is that correct?
> 
> I need to add some additional handling for errors to videos, add support for retries, and then add some CLI args so that you can enable retries and request timeouts. I'll try to get to this when I'm able to.`IncompleteRead`

I use Windows terminal to operate pytube
