### ISSUE TITLE
[BUG] Rejected links when downloading YouTube playlists

### ISSUE THREAD

**Issue by ArtomYuan** [pytube/pytube#1043]
**Describe the bug**
When I downloaded a play list and downloaded three or four videos, YouTube rejected my connection

**To Reproduce**
Please provide the following information:
https://www.youtube.com/playlist?list=UU_a1ZYZ8ZTXpjg9xUY9sj8w

Traceback (most recent call last):              | 29.7%
  File "/home/ydx/.local/bin/pytube", line 8, in <module>
    sys.exit(main())
  File "/home/ydx/.local/lib/python3.8/site-packages/pytube/cli.py", line 43, in main
    _perform_args_on_youtube(youtube_video, args)
  File "/home/ydx/.local/lib/python3.8/site-packages/pytube/cli.py", line 57, in _perform_args_on_youtube
    download_highest_resolution_progressive(
  File "/home/ydx/.local/lib/python3.8/site-packages/pytube/cli.py", line 477, in download_highest_resolution_progressive
    _download(stream, target=target)
  File "/home/ydx/.local/lib/python3.8/site-packages/pytube/cli.py", line 261, in _download
    stream.download(output_path=target, filename=filename)
  File "/home/ydx/.local/lib/python3.8/site-packages/pytube/streams.py", line 258, in download
    for chunk in request.stream(
  File "/home/ydx/.local/lib/python3.8/site-packages/pytube/request.py", line 181, in stream
    chunk = response.read()
  File "/usr/lib/python3.8/http/client.py", line 468, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.8/http/client.py", line 611, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(9422768 bytes read, 14416 more expected)

**Expected behavior**
I hope to solve the problem of refusing to connect. I think we should set an interval between each download

**System information**
Please provide the following information:
- Python version (Python 3.9)
- Pytube version (Pytube 10.8.5)
- python3 -m pip install pytube

**Comment by tfdahlin** [comment]
Working on a fix for this in #1045
