### ISSUE TITLE
[BUG] Unhandled exception when video is not completely available

### ISSUE THREAD

**Issue by Faylixe** [pytube/pytube#1049]
**Version**

```bash
$ pytube --version
10.8.5
```

**Describe the bug**

I have an exception which is not handled, here is the stack trace:

```python
Loading video...
Traceback (most recent call last):
  File "/Users/fvoituret/Library/Python/3.8/bin/pytube", line 8, in <module>
    sys.exit(main())
  File "/Users/fvoituret/Library/Python/3.8/lib/python/site-packages/pytube/cli.py", line 50, in main
    _perform_args_on_youtube(youtube, args)
  File "/Users/fvoituret/Library/Python/3.8/lib/python/site-packages/pytube/cli.py", line 57, in _perform_args_on_youtube
    download_highest_resolution_progressive(
  File "/Users/fvoituret/Library/Python/3.8/lib/python/site-packages/pytube/cli.py", line 477, in download_highest_resolution_progressive
    _download(stream, target=target)
  File "/Users/fvoituret/Library/Python/3.8/lib/python/site-packages/pytube/cli.py", line 254, in _download
    filesize_megabytes = stream.filesize // 1048576
AttributeError: 'NoneType' object has no attribute 'filesize'
```

This is happening under specific condition, I watch a non listed livestream video on YouTube, then after the livestream can be watched again, but If I try to run *pytube* right after the livestream is finished I got the mentioned error (I think this is due to the fact that the video is not really ready / entirely encoded from Youtube side). If I retry later, I would work as expected.

Although the error can be confusing, maybe there is a way to catch it and make it more explicit :).

**To Reproduce**
Just livestream or upload and try to pytube CLI directly after.

**Expected behavior**
A cleaner message which would indicate to retry later.

**Output**
@see above

**System information**
Install using `pip` with Python 3.8, version 10.8.5

**Comment by tfdahlin** [comment]
I'll try to investigate a way to fix this when I have the time to do so

**Comment by Faylixe** [comment]
> I'll try to investigate a way to fix this when I have the time to do so

Sure, no worries, it was more a suggestion for improvement than a critical fix. I guess you have already a lot in your plate with 404 error issues :)

**Comment by Kirkman** [comment]
This is still an issue. Wanted to try to download a livestream today.
