### ISSUE TITLE
[BUG] not callable error

### ISSUE THREAD

**Issue by Jrkej** [pytube/pytube#1053]
The library is great but there are many videos in which i get an error when i try to download them.
`Traceback (most recent call last):
  File "c:\Users\User\Desktop\left_things\trying.py", line 19, in <module>
    video = youtube.streams.first()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__main__.py", line 311, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__main__.py", line 223, in fmt_streams
    extract.apply_signature(self.player_config_args, fmt, self.js)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\extract.py", line 476, in apply_signature
    new_n = cipher.calculate_n(initial_n)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\cipher.py", line 63, in calculate_n
    raise TypeError(f'{curr_func} is not callable.')
TypeError: 302823254 is not callable.`

The main error is when i call = 'youtube.streams'
It happens in many videos while works in other.

**Comment by bigbear22941** [comment]
here the same....

**Comment by TheLoki2020** [comment]
Same here

**Comment by benz206** [comment]
Have the same issue
Pip is up to date and latest version downloaded.
Some videos work, some don't

**Comment by TomRaz** [comment]
same here

**Comment by glubsy** [comment]
Duplicate of #1054

**Comment by tfdahlin** [comment]
Looks like youtube must have changed something, I'll try to get this fixed

**Comment by tfdahlin** [comment]
Closing this, because #1054 is the same issue, but followed the issue template.

**Comment by tfdahlin** [comment]
Following up here for more eyes: is this still an ongoing problem for anybody? I cannot reproduce this problem any more, and I'm unsure if it's just me.

**Comment by Jrkej** [comment]
> Following up here for more eyes: is this still an ongoing problem for anybody? I cannot reproduce this problem any more, and I'm unsure if it's just me.

It looks fixed even i am not facing that! Thanks
