### ISSUE TITLE
its not setting up connection for some resome[BUG]

### ISSUE THREAD

**Issue by pravinshinde215** [pytube/pytube#1062]
Traceback (most recent call last):
  File "e:/youtube vide downloader/videotuber.py", line 11, in <module>   
    print(my_video.title)
  File "e:\youtube vide downloader\pytube\__main__.py", line 366, in title
    self._title = self.player_response['videoDetails']['title']
  File "e:\youtube vide downloader\pytube\__main__.py", line 168, in player_response
    if isinstance(self.player_config_args["player_response"], str):
  File "e:\youtube vide downloader\pytube\__main__.py", line 188, in player_config_args
    self._player_config_args = self.vid_info
  File "e:\youtube vide downloader\pytube\__main__.py", line 291, in vid_info
    return dict(parse_qsl(self.vid_info_raw))
  File "e:\youtube vide downloader\pytube\__main__.py", line 109, in vid_info_raw
    self._vid_info_raw = request.get(self.vid_info_url)
  File "e:\youtube vide downloader\pytube\request.py", line 53, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "e:\youtube vide downloader\pytube\request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "C:\Users\MY PC\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\MY PC\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\MY PC\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\MY PC\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\MY PC\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\MY PC\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

this is what i am facing

**Comment by tznoordsij4** [comment]
People had the same issue in #1060, it has to do with YouTube changing something on their end where requests library can no longer access the video links. No immediate fix for it as of now.

**Comment by tfdahlin** [comment]
Closing because this is a duplicate.
