### ISSUE TITLE
[BUG] Calling any function from pytube object is returning urllib error HTTP Error 404

### ISSUE THREAD

**Issue by haq3rgaming** [pytube/pytube#1064]
**Describe the bug**
Pytube object (named yt in the code below) is returning urllib error 404 (urllib.error.HTTPError: HTTP Error 404: Not Found)
from any youtube link after any call of the object like yt.title or yt.streams

**To Reproduce**
Video: Any
Example: https://www.youtube.com/watch?v=Wgw6tJ8yz9M
Code: https://pastebin.com/h3ftdk55 (I know it is a mess)

**Expected behavior**
Pytube object returns the title of the video

**Output**
Traceback (most recent call last):
  File "D:\ploch2\VS_projects\Python\YT_Downloader\YT_Downloader\YT_Downloader.py", line 93, in <module>
    main()
  File "D:\ploch2\VS_projects\Python\YT_Downloader\YT_Downloader\YT_Downloader.py", line 82, in main
    title = yt.title
  File "C:\Users\DELL\AppData\Roaming\Python\Python37\site-packages\pytube\__main__.py", line 351, in title
    self._title = self.player_response['videoDetails']['title']
  File "C:\Users\DELL\AppData\Roaming\Python\Python37\site-packages\pytube\__main__.py", line 165, in player_response
    if isinstance(self.player_config_args["player_response"], str):
  File "C:\Users\DELL\AppData\Roaming\Python\Python37\site-packages\pytube\__main__.py", line 185, in player_config_args
    self._player_config_args = self.vid_info
  File "C:\Users\DELL\AppData\Roaming\Python\Python37\site-packages\pytube\__main__.py", line 278, in vid_info
    return dict(parse_qsl(self.vid_info_raw))
  File "C:\Users\DELL\AppData\Roaming\Python\Python37\site-packages\pytube\__main__.py", line 106, in vid_info_raw
    self._vid_info_raw = request.get(self.vid_info_url)
  File "C:\Users\DELL\AppData\Roaming\Python\Python37\site-packages\pytube\request.py", line 52, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "C:\Users\DELL\AppData\Roaming\Python\Python37\site-packages\pytube\request.py", line 36, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**System information**
- Python 3.7.8
- Pytube version: 10.9.3
- Command to install: python -m pip install git+https://github.com/pytube/pytube

**Comment by SuperZombi** [comment]
I Have the same problem. pls fix it

**Comment by marcofaga** [comment]
Same problem!

**Comment by kylebruder** [comment]
same

**Comment by JacquesJacob** [comment]
same issue here....

**Comment by johann-lau** [comment]
YouTube constantly updates its API to avoid libraries like this, that's why.

**Comment by zhuozj** [comment]
the url api in pytube/extract.py failured
``` 
def _video_info_url(params: OrderedDict) -> str:                                                                                                                              
    return "https://www.youtube.com/get_video_info?" + urlencode(params)
```

**Comment by Argentu** [comment]
I have same problem

import pytube as pt
vid = pt.YouTube("https://www.youtube.com/watch?v=bGOUNhRaK3U")
print(vid.title)

urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by tfdahlin** [comment]
Closing because this is a duplicate.
