### ISSUE TITLE
Trouble while string to download (videos or music)

### ISSUE THREAD

**Issue by Arvinth-Krishna** [pytube/pytube#1073]
Traceback (most recent call last):
File "c:\Users\krish\cmd files\GAKs PC Controller\lib\helpers.py", line 26, in run
return await f(*args,**kwargs)
File "c:\Users\krish\cmd files\GAKs PC Controller\reco.pyw", line 285, in m
await music_module.music(ctx, text)
File "c:\Users\krish\cmd files\GAKs PC Controller\modules\music_module.py", line 114, in music
stream = yt.streams.filter(only_audio=True).first()
File "C:\Users\krish\AppData\Roaming\Python\Python39\site-packages\pytube_main_.py", line 311, in streams
return StreamQuery(self.fmt_streams)
File "C:\Users\krish\AppData\Roaming\Python\Python39\site-packages\pytube_main_.py", line 214, in fmt_streams
if "adaptive_fmts" in self.player_config_args:
File "C:\Users\krish\AppData\Roaming\Python\Python39\site-packages\pytube_main_.py", line 188, in player_config_args
self.player_config_args = self.vid_info
File "C:\Users\krish\AppData\Roaming\Python\Python39\site-packages\pytube_main.py", line 281, in vid_info
return dict(parse_qsl(self.vid_info_raw))
File "C:\Users\krish\AppData\Roaming\Python\Python39\site-packages\pytube_main_.py", line 109, in vid_info_raw
self._vid_info_raw = request.get(self.vid_info_url)
File "C:\Users\krish\AppData\Roaming\Python\Python39\site-packages\pytube\request.py", line 53, in get
response = _execute_request(url, headers=extra_headers, timeout=timeout)
File "C:\Users\krish\AppData\Roaming\Python\Python39\site-packages\pytube\request.py", line 37, in _execute_request
return urlopen(request, timeout=timeout) # nosec
File "C:\Users\krish\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen
return opener.open(url, data, timeout)
File "C:\Users\krish\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
response = meth(req, response)
File "C:\Users\krish\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
response = self.parent.error(
File "C:\Users\krish\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error
return self._call_chain(*args)
File "C:\Users\krish\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
result = func(*args)
File "C:\Users\krish\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

why I'm getting errors while using Pytube (version 10.9.2)? Please help...

**Comment by tfdahlin** [comment]
Duplicate: see #1060
