### ISSUE TITLE
[BUG] Generating srt Captions

### ISSUE THREAD

**Issue by ladm99** [pytube/pytube#1077]
I am having issues with generating srt captions. 

My Code: 
```
yt = YouTube('https://youtu.be/NUZPcLTIgjk') 
x = yt.captions['en'].generate_srt_captions()
```

The error I receive: 
```
Traceback (most recent call last):
  File "C:\Users\Luis\Desktop\Code\Python\videos\yt-dl\x.py", line 6, in <module>
    x = yt.captions['en'].generate_srt_captions()
  File "C:\Users\Luis\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\captions.py", line 51, in generate_srt_captions
    return self.xml_caption_to_srt(self.xml_captions)
  File "C:\Users\Luis\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\captions.py", line 83, in xml_caption_to_srt
    start = float(child.attrib["start"])
KeyError: 'start'
```
I am using the fix#1060 version.

I think YouTube might have changed how they format the xml captions so that might have broken `generate_srt_captions()`

**Comment by GPRicci** [comment]
I tried downloading a caption just as an XML an it worked, but it seems that they have indeed changed the format.
Here's an example:
```XML
<?xml version="1.0" encoding="utf-8" ?><timedtext format="3">
<body>
<p t="2254" d="2872">FRIDAY</p>
<p t="33434" d="1193">IT IS TIME FOR THE BOYS</p>
</body>
</timedtext>

```
It seems they are using `t` instead of `start` and `d` instead of `dur` for the duration of the text.
Also the root element, in this case `timedtext` has only one child `body`, so the iteration in `xml_caption_to_srt` has to be done for the elements of `body`.

**Comment by milkymilky0116** [comment]
I had a same problem to call generate_srt_captions() but i fixed it temporarily. based on above investigation, i changed code a bit.

In `captions.py` | line 76

`for i, child in enumerate(list(root)):`

change to

`for i, child in enumerate(list(root.findall('body/p'))):`

and change duration, start variables to

`duration = float(child.attrib["d"])`

`start = float(child.attrib["t"])`

and after that, it works fine just like as it was. hopefully you could fix this problem :)

**Comment by ladm99** [comment]
That fixed it, thanks

**Comment by ladm99** [comment]
well now I can download the captions as an srt file but it seems like there's an issue with the timestamp conversions. 

Here's a portion of the xml file (I didn't include the whole thing because its long):

```
<?xml version="1.0" encoding="UTF-8"?>

-<timedtext format="3">


-<body>

<p d="3570" t="60">- This is the most dangerous problem in mathematics,</p>

<p d="2430" t="3630">one that young mathematicians are warned</p>

<p d="1990" t="6060">not to waste their time on.</p>
```

Here's what I get when I use `generate_srt_captions()`:
```
1
00:01:00,000 --> 01:00:30,000
- This is the most dangerous problem in mathematics,

2
01:00:30,000 --> 01:41:00,000
one that young mathematicians are warned

3
01:41:00,000 --> 02:14:10,000
not to waste their time on.
```

And here is what I get when I run the xml caption file through an online converter:
```
1
00:00:00,060 --> 00:00:03,630
- This is the most dangerous
problem in mathematics,

2
00:00:03,630 --> 00:00:06,060
one that young
mathematicians are warned

3
00:00:06,060 --> 00:00:08,050
not to waste their time on.
```
So I think there's also an issue `float_to_srt_time_format()`. 
I'm not very knowledgeable on this kind of conversion but I am trying to see if I can figure it out

**Comment by GPRicci** [comment]
> well now I can download the captions as an srt file but it seems like there's an issue with the timestamp conversions.
> 
> Here's a portion of the xml file (I didn't include the whole thing because its long):
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> 
> -<timedtext format="3">
> 
> 
> -<body>
> 
> <p d="3570" t="60">- This is the most dangerous problem in mathematics,</p>
> 
> <p d="2430" t="3630">one that young mathematicians are warned</p>
> 
> <p d="1990" t="6060">not to waste their time on.</p>
> ```
> 
> Here's what I get when I use `generate_srt_captions()`:
> 
> ```
> 1
> 00:01:00,000 --> 01:00:30,000
> - This is the most dangerous problem in mathematics,
> 
> 2
> 01:00:30,000 --> 01:41:00,000
> one that young mathematicians are warned
> 
> 3
> 01:41:00,000 --> 02:14:10,000
> not to waste their time on.
> ```
> 
> And here is what I get when I run the xml caption file through an online converter:
> 
> ```
> 1
> 00:00:00,060 --> 00:00:03,630
> - This is the most dangerous
> problem in mathematics,
> 
> 2
> 00:00:03,630 --> 00:00:06,060
> one that young
> mathematicians are warned
> 
> 3
> 00:00:06,060 --> 00:00:08,050
> not to waste their time on.
> ```
> 
> So I think there's also an issue `float_to_srt_time_format()`.
> I'm not very knowledgeable on this kind of conversion but I am trying to see if I can figure it out

It seems that the numbers in the `t` and `d` attributes are in milliseconds, so then the first caption `<p d="3570" t="60">- This is the most dangerous problem in mathematics,</p>` starts 60 milliseconds into the video and lasts 3 seconds and 570 milliseconds, which is consistent with `00:00:00,060 --> 00:00:03,630`

**Comment by ladm99** [comment]
> It seems that the numbers in the `t` and `d` attributes are in milliseconds, so then the first caption `<p d="3570" t="60">- This is the most dangerous problem in mathematics,</p>` starts 60 milliseconds into the video and lasts 3 seconds and 570 milliseconds, which is consistent with `00:00:00,060 --> 00:00:03,630`

Thanks for the reply, seems like I fixed it by changing line 63  in captions.py `fraction, whole = math.modf(d)` to 
`fraction, whole = math.modf(d/1000)`. Just have to change milliseconds to seconds. Works with all the videos I've tested so far. Thanks for the help y'all.

**Comment by nikoszka** [comment]
It is a really nice fix but it wont work on videos with auto-generated captions. Currently working on a solution.
The XML of the auto-generated caption has a format like this :
```xml
<?xml version="1.0" encoding="utf-8"?>
<timedtext format="3">
 <head>
  <ws id="0"/>
  <ws id="1" ju="0" mh="2" sd="3"/>
  <wp id="0"/>
  <wp ah="20" ap="6" av="100" cc="40" id="1" rc="2"/>
 </head>
 <body>
  <w id="1" t="0" wp="1" ws="1"/>
  <p d="4200" t="30" w="1">
   <s ac="242">
    no
   </s>
   <s ac="235" t="450">
    motorcycle
   </s>
   <s ac="133" t="810">
    is
   </s>
   <s ac="246" t="1230">
    without
   </s>
   <s ac="245" t="1500">
    issues
   </s>
   <s ac="252" t="1890">
    and
   </s>
   <s ac="229" t="2129">
    this
   </s>
  </p>

**Comment by panda-34** [comment]
> The XML of the auto-generated caption has a format like this :

you can change
`text = child.text or ""`
to
```
            text = ''.join(child.itertext()).strip()
            if not text:
                continue

```

**Comment by ladm99** [comment]
> > The XML of the auto-generated caption has a format like this :
> 
> you can change
> `text = child.text or ""`
> to
> 
> ```
>             text = ''.join(child.itertext()).strip()
>             if not text:
>                 continue
> ```

Just tested that and it seems like its working. Thanks a lot.
