### ISSUE TITLE
[BUG] urlopen error [Errno 111] Connection refused

### ISSUE THREAD

**Issue by aplnx** [pytube/pytube#1080]
I just installed an updated version of pytube. I went though the following commands:

>>> from pytube import YouTube
>>> YouTube('https://youtu.be/9bZkp7q19f0').streams.first().download()

Which produced the following error python log:
Traceback (most recent call last):
  File "/usr/lib/python3.7/urllib/request.py", line 1324, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.7/http/client.py", line 1260, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1306, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1255, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1030, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 970, in send
    self.connect()
  File "/usr/lib/python3.7/http/client.py", line 1415, in connect
    super().connect()
  File "/usr/lib/python3.7/http/client.py", line 942, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cfd/.local/lib/python3.7/site-packages/pytube/streams.py", line 255, in download
    max_retries=max_retries
  File "/home/cfd/.local/lib/python3.7/site-packages/pytube/request.py", line 161, in stream
    timeout=timeout
  File "/home/cfd/.local/lib/python3.7/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 1367, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.7/urllib/request.py", line 1326, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

**Expected behavior**
I was expecting the file to be downloaded.

**Output**
Pytube at least create the output file but with zero bytes.

**System information**
Please provide the following information:
- Python version 3.7.3
- Pytube version 11.0.0
- Command used to install pytube: python3 -m pip install git+https://github.com/pytube/pytube

**Comment by aplnx** [comment]
Hello! Sorry for reporting this problem. It is not related to Pytube bug. I am using pihole ad blocking system. I just needed to deactivate it and pytube worked fine.

I am suggesting that developers put this hint to advice users to be aware of this problem. I think this bug report can be closed.

**Comment by tfdahlin** [comment]
Unfortunately, we can't really provide hints about what causes this issue as part of pytube, because it is in a lower level library. There are too many potential reasons for a problem like this (your pihole blocking it, other firewall configurations, ip address blocking, etc), and trying to exhaustively list them isn't something we can reasonably do. Additionally, it's generally considered more pythonic for the user to handle exceptions themselves, so catching all exceptions, printing our guesses about how to fix them, then raising them again isn't really advised. I will keep this in mind though in case future users experience a similar issue.
