### ISSUE TITLE
KeyError: 'twoColumnSearchResultsRenderer' and KeyError: 'onResponseReceivedCommands' on Search().results

### ISSUE THREAD

**Issue by jimmyjohnjr1203** [pytube/pytube#1083]
I was testing out the search example from the documentation:

`from pytube import Search 
s = Search('Youtube Rewind')
len(s.results)`

and at that last line I get the following error:

```Traceback (most recent call last):
  File "C:\Users\jackl\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\contrib\search.py", line 94, in fetch_and_parse
    sections = raw_results['contents']['twoColumnSearchResultsRenderer'][
KeyError: 'twoColumnSearchResultsRenderer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jackl\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\contrib\search.py", line 62, in results    videos, continuation = self.fetch_and_parse()
  File "C:\Users\jackl\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\contrib\search.py", line 97, in fetch_and_parse
    sections = raw_results['onResponseReceivedCommands'][0][
KeyError: 'onResponseReceivedCommands'```


I also get the same results using Search().fetch_and_parse() but not with Search().fetch_query()

**Comment by jimmyjohnjr1203** [comment]
This is #1082
