### ISSUE TITLE
[BUG] Playlist.last_updated() does not work

### ISSUE THREAD

**Issue by EgorVoron** [pytube/pytube#1087]
**code:**
```
from pytube import Playlist

url = 'https://www.youtube.com/playlist?list=PLsRNoUx8w3rNnR8L2QdV33RPv42XqZBJ6'
pl = Playlist(url)
print(pl.last_updated)
```

**error:**
```
Traceback (most recent call last):
  File "Test/test.py", line 5, in <module>
    print(pl.last_updated)
  File "<...>\miniconda3\lib\site-packages\pytube\contrib\playlist.py", line 329, in last_updated
    day = date_components[1].strip(',')
IndexError: list index out of range
```
pytube version is 11.0.0

**Comment by walshyb** [comment]
Seems like YouTube changed their playlist API. When I make a fetch request to `https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&maxResults=50&playlistId={playlist_id}&key={api_key}` in my project, I get: 
```
raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 400 Client Error: Bad Request for url:
```

Not sure if pytube is using the exact link I mentioned above, but seems like it might be a similar issue?
