### ISSUE TITLE
[BUG] HTTP Error 410

### ISSUE THREAD

**Issue by klint-k** [pytube/pytube#1092]
**Before creating an issue**
I checked and there was no open issues
This is a new install.  

**To Reproduce**
from pytube import YouTube
yt_url = 'https://www.youtube.com/watch?v=8PYhirFS2gQ'
youtube = YouTube(url)

**Expected behavior**
i have not even down loaded one youtube.

**Output**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/klint/.local/lib/python3.9/site-packages/pytube/__main__.py", line 91, in __init__
    self.prefetch()
  File "/home/klint/.local/lib/python3.9/site-packages/pytube/__main__.py", line 181, in prefetch
    self.vid_info_raw = request.get(self.vid_info_url)
  File "/home/klint/.local/lib/python3.9/site-packages/pytube/request.py", line 36, in get
    return _execute_request(url).read().decode("utf-8")
  File "/home/klint/.local/lib/python3.9/site-packages/pytube/request.py", line 24, in _execute_request
    return urlopen(request)  # nosec
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 555, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 747, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: Gone

```

**System information**
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux

```pytube.__version__ is '9.6.4'```

python3 -m pip install pytube

**Comment by EgorVoron** [comment]
In pytube==11.0.0 this code works

**Comment by virtualramblas** [comment]
I faced the same issue today from the CLI. I can confirm that upgrading to release 11.0.0 it works again.

**Comment by sokol8** [comment]
1) I can confirm that upgrading to release 11.0.0 it works again.

2) I actually git stuck with version 9.x.x which pip didn't want to upgrade. Had to completely uninstall pytube using pip and then install it again.

3) Using pip3 and pytube3 actually produced errors I could not resolve yet step 2 worked for me and solved the error

**Comment by tfdahlin** [comment]
hi @klint-k, as others have said, this is an issue with older version of pytube. Please update to the latest version (now v11.0.1) to fix this problem.

**Comment by RoselinP** [comment]
I am using a MAC , python version 3.9.6
my first issue was : urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)> Exception in Tkinter callback.

Solution: Opening Python application and then running the file: Install Certificates.command

then I got the error message: urllib.error.HTTPError: HTTP Error 410: Gone 

Solution: Installed pytube 11.0.1
I copied the file from this website https://pypi.org/project/pytube/
and paste it into my terminal.

Thank you very much for the help...

**Comment by smsprovider290** [comment]
With pytube 11.0.2, we are again getting the same error . "HTTPError: HTTP Error 410: Gone"
