### ISSUE TITLE
Syntax error on Ubuntu

### ISSUE THREAD

**Issue by LarsonAustin** [pytube/pytube#1095]
I installed pytube3, and I get this error whenever trying to create any `YouTube` object.
`Traceback (most recent call last):
  File "/home/austin/Desktop/test.py", line 1, in <module>
    import pytube
  File "/home/austin/.local/lib/python3.5/site-packages/pytube/__init__.py", line 13, in <module>
    from pytube.streams import Stream
  File "/home/austin/.local/lib/python3.5/site-packages/pytube/streams.py", line 61
    self.is_otf: bool = stream["is_otf"]
               ^
SyntaxError: invalid syntax`

**Comment by glubsy** [comment]
From the README.md:

> Pytube requires an installation of python 3.6 or greater

Upgrade Python.
