### ISSUE TITLE
[BUG] pytube.exceptions.RegexMatchError: channel_name: could not find match for patterns

### ISSUE THREAD

**Issue by ArchAngel727** [pytube/pytube#1103]
[main.zip](https://github.com/pytube/pytube/files/7063420/main.zip)
**Describe the bug**
When using `Channel()` and assigning the result to a variable it throws the error `pytube.exceptions.RegexMatchError: channel_name: could not find match for patterns`.

**To Reproduce**
```
import os
from pytube import Channel

os.system("cls")

chlist = ["https://www.youtube.com/channel/UCoSrY_IQQVpmIRZ9Xf-y93g",
"https://www.youtube.com/channel/UCyl1z3jo3XHR1riLFKG5UAg",
"https://www.youtube.com/channel/UCMwGHR0BTZuLsmjY_NT5Pwg",
"https://www.youtube.com/channel/UCL_qhgtOy0dy1Agp8vkySQg",
"https://www.youtube.com/channel/UCHsx4Hqa-1ORjQTh9TYDhww",
"https://www.youtube.com/channel/UC8rcEBzJSleTkf_-agPM20g",
"https://www.youtube.com/channel/UCO_aKKYxn4tvrqPjcTzZ6EQ",
"https://www.youtube.com/channel/UC3n5uGu18FoCy23ggWWp8tA",
"https://www.youtube.com/channel/UCmbs8T6MWqUHP1tIQvSgKrg",
"https://www.youtube.com/channel/UCgmPnx-EEeOrZSg5Tiw7ZRQ",
"https://www.youtube.com/channel/UCsUj0dszADCGbF3gNrQEuSQ"]

def YTData(x):
    data = {}
    for i in range(len(x)):
        c = Channel(x[i])
        a = c.about_html
        b = a[:a.find("subscribers")]
        x = b[-50:].rsplit('"')
        subs = x[len(x)-1]
        data["id"] = i
        data["data"] = Channel(x[i]).channel_name
    return data

print(YTData(chlist))
```

**Expected behavior**
Print the channel name and sub count for the given urls

**Output**
```
Traceback (most recent call last):
  File "c:\Users\milan\Documents\Git Repo\Programing\Code\Python\Pytube\main.py", line 30, in <module>
    print(YTData(chlist))
  File "c:\Users\milan\Documents\Git Repo\Programing\Code\Python\Pytube\main.py", line 27, in YTData
    data["data"] = Channel(x[i]).channel_name
  File "C:\Users\milan\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\contrib\channel.py", line 24, in __init__
    self.channel_uri = extract.channel_name(url)
  File "C:\Users\milan\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\extract.py", line 185, in channel_name   
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: channel_name: could not find match for patterns
```
**System information**
Please provide the following information:
- Python 3.9.0
- 11.0.0
- `pip install pytube` (didn't work), `python -m pip install git+https://github.com/pytube/pytube` (didn't work), `pip3 install pytube` (didn't work), `pip install --upgrade pytube` (didn't work).

**Comment by tfdahlin** [comment]
Which of the channels is this failing on?

**Comment by lavanyascyberlife** [comment]
I had same issue when i was using pytube 11.0.0

so found out that there is a regular expression filter mismatch in pytube library in cipher.py class

function_patterns = [

    r'a\.C&&\(b=a\.get\("n"\)\)&&\(b=([^(]+)\(b\),a\.set\("n",b\)\)}};',
]
Now there is a update of pytube code yesterday to 11.0.1

function_patterns = [

    r'a\.[A-Z]&&\(b=a\.get\("n"\)\)&&\(b=([^(]+)\(b\)',
]

**Comment by ericwijaya001** [comment]
try this:
git+https://github.com/rishabh3354/pytube@master

**Comment by tfdahlin** [comment]
The previous two comments were related to a different RegexMatchError issue, so I have hidden them to avoid confusion.

**Comment by ArchAngel727** [comment]
Hello,

I used this list of channels and it didnt work, i haven't tried it with a different list.

```
chlist = ["https://www.youtube.com/channel/UCoSrY_IQQVpmIRZ9Xf-y93g",
"https://www.youtube.com/channel/UCyl1z3jo3XHR1riLFKG5UAg",
"https://www.youtube.com/channel/UCMwGHR0BTZuLsmjY_NT5Pwg",
"https://www.youtube.com/channel/UCL_qhgtOy0dy1Agp8vkySQg",
"https://www.youtube.com/channel/UCHsx4Hqa-1ORjQTh9TYDhww",
"https://www.youtube.com/channel/UC8rcEBzJSleTkf_-agPM20g",
"https://www.youtube.com/channel/UCO_aKKYxn4tvrqPjcTzZ6EQ",
"https://www.youtube.com/channel/UC3n5uGu18FoCy23ggWWp8tA",
"https://www.youtube.com/channel/UCmbs8T6MWqUHP1tIQvSgKrg",
"https://www.youtube.com/channel/UCgmPnx-EEeOrZSg5Tiw7ZRQ",
"https://www.youtube.com/channel/UCsUj0dszADCGbF3gNrQEuSQ"]
```
