### ISSUE TITLE
No such file or directory (missing .mp4 suffix) [BUG]

### ISSUE THREAD

**Issue by TommasoBendinelli** [pytube/pytube#1109]
I have installed pytube via `python -m pip install git+https://github.com/pytube/pytube`.`

**Describe the bug**
Video and Audio files are saved without suffix (i.e. without .mp4). however Pytube expects them with the suffix (for preprocessing I guess?) and then breaks.

**To Reproduce**
pytube "https://www.youtube.com/watch?v=NLfCPcnns10" -f 360p

**Expected behavior**
Having the my folder a .mp4 that contains both audio and video 

**Output**
```
Traceback (most recent call last):
  File "/usr/local/bin/pytube", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/pytube/cli.py", line 53, in main
    _perform_args_on_youtube(youtube, args)
  File "/usr/local/lib/python3.9/site-packages/pytube/cli.py", line 84, in _perform_args_on_youtube
    ffmpeg_process(
  File "/usr/local/lib/python3.9/site-packages/pytube/cli.py", line 342, in ffmpeg_process
    _ffmpeg_downloader(
  File "/usr/local/lib/python3.9/site-packages/pytube/cli.py", line 401, in _ffmpeg_downloader
    os.unlink(video_path)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tommaso/Equilibrium Models in Deep Learning_video_0.mp4'
```

**System information**
Please provide the following information:
- Python version 3.91.
- Pytube version 11.0.1
- Command used to install  python3 -m pip install git+https://github.com/pytube/pytube

**Comment by unaimillan** [comment]
Experiencing the same issue, thank you for reporting!

**Comment by Axer128** [comment]
Same issue.

You also can't work around this by renaming the resulting file to *.mp4, as when you run the command again, it will see the mp4, and than append a video1, video2, etc suffix so it still doesn't match.

Odd such a simple issue has been here unfixed so many months, especially since we need ffmpeg mux to get the highest video quality for most videos these days.

**Comment by amansrivastava** [comment]
Making these changes working for me.
```
diff --git a/pytube/cli.py b/pytube/cli.py
index 7a98854..a7cd48a 100755
--- a/pytube/cli.py
+++ b/pytube/cli.py
@@ -377,10 +377,10 @@ def _ffmpeg_downloader(
     _download(stream=audio_stream, target=target, filename=audio_unique_name)
 
     video_path = os.path.join(
-        target, f"{video_unique_name}.{video_stream.subtype}"
+        target, f"{video_unique_name}"
     )
     audio_path = os.path.join(
-        target, f"{audio_unique_name}.{audio_stream.subtype}"
+        target, f"{audio_unique_name}"
     )
     final_path = os.path.join(
         target, f"{safe_filename(video_stream.title)}.{video_stream.subtype}"
```
