### ISSUE TITLE
HTTP Error 410: Gone [BUG]

### ISSUE THREAD

**Issue by qkqsb** [pytube/pytube#1113]
Hello, when I try to call any URL in a playlist to be downloaded it invariably does not work. I am using Python 3.9.6 and Pytube 11.0.1 installed using pip install pytube. I'm expecting the for loop in the code below to just cycle through the URLs in the provided playlist, but this error always comes up:

Exception has occurred: HTTPError
HTTP Error 410: Gone
  File "C:\Users\Main\Documents\PyTube\playlistRipper.py", line 7, in <module>
    video.streams.first().download()

**Here is the code:**
from pytube import Playlist

playlist = Playlist('https://www.youtube.com/playlist?list=PL-osiE80TeTskrapNbzXhwoFUiLCjGgY7')

for video in playlist.videos:
    video.streams.first().download()

I know that pytube is actually working, because when I go into the command prompt and run pytube (insert any video url you like here) it works just fine, I have not seen a single URL, including ones in the playlist provided in my code fail. Any ideas what could be causing this?

**Comment by saeedrafieyan** [comment]
I have the same problem!

```
Traceback (most recent call last):
  File "more_interactive.py", line 45, in <module>
    video_downloader(link=link, save_path=save_path)
  File "more_interactive.py", line 34, in video_downloader
    name = YouTube(link).title
  File "C:\Users\Saeed Rafieyan\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__main__.py", line 367, in title        
    self._title = self.player_response['videoDetails']['title']
  File "C:\Users\Saeed Rafieyan\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__main__.py", line 183, in player_response
    if isinstance(self.player_config_args["player_response"], str):
  File "C:\Users\Saeed Rafieyan\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__main__.py", line 203, in player_config_args
    self._player_config_args = self.vid_info
  File "C:\Users\Saeed Rafieyan\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__main__.py", line 294, in vid_info     
    return dict(parse_qsl(self.vid_info_raw))
  File "C:\Users\Saeed Rafieyan\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__main__.py", line 124, in vid_info_raw 
    self._vid_info_raw = request.get(self.vid_info_url)
  File "C:\Users\Saeed Rafieyan\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\request.py", line 47, in get
    return _execute_request(url, headers=extra_headers).read().decode("utf-8")
  File "C:\Users\Saeed Rafieyan\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\request.py", line 31, in _execute_request
    return urlopen(request)  # nosec
  File "C:\Users\Saeed Rafieyan\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Saeed Rafieyan\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\Saeed Rafieyan\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\Saeed Rafieyan\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 563, in error
    result = self._call_chain(*args)
  File "C:\Users\Saeed Rafieyan\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\Saeed Rafieyan\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\Saeed Rafieyan\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\Saeed Rafieyan\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\Saeed Rafieyan\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\Saeed Rafieyan\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\Saeed Rafieyan\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: Gone
```

**Comment by SwissCorePy** [comment]
Get the same `urllib.error.HTTPError: HTTP Error 410: Gone` error using the following code:
```python
from pytube import Playlist

dl = "Downloads/ZHT5/"
url = "https://www.youtube.com/playlist?list=OLAK5uy_mKrSW05llpmYMQKMu5LTOL4PYP8lI8JQc"
[v.streams.filter(only_audio=True).first().download(dl) for v in Playlist(url).videos]

```

**Comment by huynguyencong** [comment]
I got the same error. `urllib.error.HTTPError: HTTP Error 410: Gone`

```
from pytube import YouTube

yt = YouTube('https://www.youtube.com/watch?v=AvDmYT-c8RA')
yt.title
```

**Comment by saeedrafieyan** [comment]
I solved this problem by updating Pytube:

`pip upgrade pytube`

**Comment by SwissCorePy** [comment]
> I solved this problem by updating Pytube:
> 
> `pip upgrade pytube`

Worked! The error seems no longer to happen in pytube-11.0.1 👍 but it happened in pytube-10.8.5

**Comment by huynguyencong** [comment]
Yes, it worked for me when upgrade to version 11.0.1.

**Comment by qkqsb** [comment]
I am on 11.0.1 and it does not work for me. Troubleshooting recommendations would be appreciated.

**Comment by saeedrafieyan** [comment]
try this:
first, uninstall the Pytube and then install that with this command:
`pip install git+https://github.com/pytube/pytube.git`

**Comment by qkqsb** [comment]
@saeedrafieyan I just did as you instructed, nothing has changed when running the example code I provided in my original comment.

**Comment by saeedrafieyan** [comment]
I tested your code, and it seems to work without any problem. Are you using proxy or something like that?

> @saeedrafieyan I just did as you instructed, nothing has changed when running the example code I provided in my original comment.

**Comment by qkqsb** [comment]
@saeedrafieyan No proxy or VPN is in use when this program is running.

**Comment by qkqsb** [comment]
I just successfully ran the code I previously posted in this thread on a different computer, so I'm not sure what is different between the two. Any ideas for what to look for in terms of differences would be appreciated.

**Comment by sadircardosojr** [comment]
Changing DNS to 8.8.8.8 resolved the issue.

**Comment by PR0G4M3R** [comment]
> Changing DNS to 8.8.8.8 resolved the issue.

How
