### ISSUE TITLE
[BUG] http.client.IncompleteRead: IncompleteRead

### ISSUE THREAD

**Issue by chen97** [pytube/pytube#1129]
I am facing the issue below when trying to download a private video. 

I saw there is the same issue posted here. https://github.com/pytube/pytube/issues/1012#issuecomment-858173976
I have tried the reporter's video, triggering the same error I faced in the private video scenario.

I'm sure this is not a network issue, as I have tried it out in different networks.

Thanks for helping me to check out this issue. Appreciate it!

**Below is my sample code:**
```
from pytube import YouTube

url = "https://www.youtube.com/watch?v=Q5hNbAaR6tE"

print("[playlist.py]: New video found! URL:"+url)
YouTube(url).streams.filter(progressive=True, file_extension='mp4').get_by_resolution("720p").download()
```

**Below is the error:**
[playlist.py]: New video found! URL:https://www.youtube.com/watch?v=Q5hNbAaR6tE
Traceback (most recent call last):
  File "downloadvideo.py", line 6, in <module>
    YouTube(url).streams.filter(progressive=True, file_extension='mp4').get_by_resolution("720p").download()
  File "/Users/mac/Documents/Project/Teletube/pyenv/lib/python3.7/site-packages/pytube/streams.py", line 255, in download
    max_retries=max_retries
  File "/Users/mac/Documents/Project/Teletube/pyenv/lib/python3.7/site-packages/pytube/request.py", line 185, in stream
    chunk = response.read()
  File "/Users/mac/opt/anaconda3/lib/python3.7/http/client.py", line 474, in read
    s = self._safe_read(self.length)
  File "/Users/mac/opt/anaconda3/lib/python3.7/http/client.py", line 626, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(76612 bytes read, 9360572 more expected)

**Comment by jsharmashell** [comment]
https://www.youtube.com/watch?v=zbWAVGQJlt4 
I am facing same issue with this video. It is not downloading and throwing IncompleteRead  exception  more like above. 

I did try changing default chunk size `pytube.request.default_range_size ` but nothing worked .
 Appreciate if anybody know the fix  or any workaround  to download  these type of videos.

Thanks in advance.

**Comment by glubsy** [comment]
You could try changing [these lines](https://github.com/pytube/pytube/blob/f06e0710dcf5089e582487fee94f7bb0afbf7ba9/pytube/request.py#L184-L190) to something like this (have not tested but it should work):

```python
        while True:
            try:
                chunk = response.read()
            except:
                break
            if not chunk:
                break
            downloaded += len(chunk)
            yield chunk
    return  # pylint: disable=R1711
```

And it works, you could submit it as a merge request.

**Comment by jsharmashell** [comment]
> You could try changing [these lines](https://github.com/pytube/pytube/blob/f06e0710dcf5089e582487fee94f7bb0afbf7ba9/pytube/request.py#L184-L190) to something like this (have not tested but it should work):
> 
> ```python
>         while True:
>             try:
>                 chunk = response.read()
>             except:
>                 break
>             if not chunk:
>                 break
>             downloaded += len(chunk)
>             yield chunk
>     return  # pylint: disable=R1711
> ```
> 
> And it works, you could submit it as a merge request.

hi , thanks for reply ,unfortunately above code change did not work :(

I did try handling of incomplete read exception on request obj  call using this [https://stackoverflow.com/questions/14442222/how-to-handle-incompleteread-in-python](url) but no luck , it is crashing after considerable waiting time.

**Comment by rajeshp2408** [comment]
> You could try changing [these lines](https://github.com/pytube/pytube/blob/f06e0710dcf5089e582487fee94f7bb0afbf7ba9/pytube/request.py#L184-L190) to something like this (have not tested but it should work):
> 
> ```python
>         while True:
>             try:
>                 chunk = response.read()
>             except:
>                 break
>             if not chunk:
>                 break
>             downloaded += len(chunk)
>             yield chunk
>     return  # pylint: disable=R1711
> ```
> 
> And it works, you could submit it as a merge request.

Thanks it works for me
