### ISSUE TITLE
[BUG] KeyError: 'streamingData' for video removed for violating YouTube's Terms of Service

### ISSUE THREAD

**Issue by belgeu** [pytube/pytube#1149]
**Describe the bug**
pytube.exceptions.PytubeError: Traceback while accessing title of https://youtube.com/watch?v=32nkdvLq3oQ.

**To Reproduce**
```
$ python3
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pytube import YouTube
>>> YouTube('https://youtube.com/watch?v=32nkdvLq3oQ').streams
```

**Expected behavior**
Handled in pytube.exceptions.

**Output**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\__main__.py", line 292, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\__main__.py", line 172, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\__main__.py", line 157, in streaming_data
    return self.vid_info['streamingData']
KeyError: 'streamingData'
```

**System information**
Please provide the following information:
Python 3.7.4
pytube 11.0.1
pip3 install pytube

**Comment by Nathan1258** [comment]
May be similar to my issue. Pytube has suddenly decided to crash instead of catching errors where it can't fetch the video if it's private, unavailable or just taken down.

**Comment by omkarpyc** [comment]
I finally got a solution for this KeyError: 'Streaming Data'.
This error arises if you are trying to download videos that require a sign in / login for example Age Restricted videos require sign in or login. I tried to keep an exception for Age Restricted from pytube.exceptions but the error still persists because the statement for exception didn't actually run for some reason. Actually this is not even an error but a bug.

Solution
I included several exception in below example i am trying to download the Youtube 8m dataset.

    for video_id in video_id_list:
        try:
            YouTube('http://youtube.com/watch?v=' + video_id).streams.get_highest_resolution().download(vedio_dir)
        except (VideoUnavailable, HTTPError, ConnectionError,RemoteDisconnected, ConnectTimeout, InvalidURL, ProtocolError, AgeRestrictedError, VideoRegionBlocked, LiveStreamError, RecordingUnavailable, MembersOnly, VideoPrivate, Exception):
            try:
                YouTube('http://youtube.com/watch?v=' + video_id).streams.get_highest_resolution().download(vedio_dir)
            except (VideoUnavailable, HTTPError, ConnectionError,RemoteDisconnected, ConnectTimeout, InvalidURL, ProtocolError, AgeRestrictedError, VideoRegionBlocked, LiveStreamError, RecordingUnavailable, MembersOnly, VideoPrivate, Exception):
                print(' http://youtube.com/watch?v=' + video_id)


This made me download those videos without problem.
Kindly try even if my solution looks silly.
