### ISSUE TITLE
yt = YouTube("https://www.youtube.com/watch?v=iCwMQJnKk2c&list=PL-wATfeyAMNqIee7cH3q1bh4QJFAaeNv0&index=2")  caption = yt.captions.get_by_language_code('a.en')  caption.generate_srt_captions()

### ISSUE THREAD

**Issue by acgmusic** [pytube/pytube#1154]
There is something wrong when I try to download captions from this video.

Maybe youtube has changed the format of the xml file?

**Comment by vj68** [comment]
I get this error while following the official [doc](https://pytube.io/en/latest/user/captions.html)

```python
>>> print(caption.generate_srt_captions())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rrajvija/Desktop/LEARNING/uw/youtube-video-analysis/env/lib/python3.8/site-packages/pytube/captions.py", line 51, in generate_srt_captions
    return self.xml_caption_to_srt(self.xml_captions)
  File "/Users/rrajvija/Desktop/LEARNING/uw/youtube-video-analysis/env/lib/python3.8/site-packages/pytube/captions.py", line 83, in xml_caption_to_srt
    start = float(child.attrib["start"])
KeyError: 'start'
>>> 
```

XML captions work fine
```python
>>> pprint(caption.xml_captions)
('<?xml version="1.0" encoding="utf-8" ?><timedtext format="3">\n'
 '<body>\n'
 '<p t="10200" d="940">K-pop!</p>\n'
 '<p t="13400" d="2800">That is so awkward to watch.</p>\n'
 '<p t="16200" d="2080">YouTube Rewind 2018.</p>\n'
 '<p t="18480" d="3520">The most disliked video\n'
 'in the history of YouTube.</p>\n'
 '<p t="22780" d="2220">In 2018, we made something\n'
```

**Comment by LuisMiguelSS** [comment]
This issue has been described [here](https://github.com/pytube/pytube/issues/1085) with a pending pull request. Sad to see no action.
