### ISSUE TITLE
[BUG] KeyError: 'sidebar'

### ISSUE THREAD

**Issue by DarkSpeedKiller** [pytube/pytube#1159]
**Describe the bug**

> Most of the playlist work fine but i found out this one and similar to this one raise this error

**To Reproduce**

> https://www.youtube.com/watch?v=RzprboY79U4&list=RDGMEM6ijAnFTG9nX1G-kbWBUCJAVMnPOdiUcboqs&index=2

**Expected behavior**

> Normal download

**Output**
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\..\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\...\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:/Users/...", line 190, in playlist_downloader_mp3
    text='Playlist : {} \nNumber of videos in playlist : %s'.format(playlist.title) % len(playlist.video_urls),
  File "C:\Users\...\lib\site-packages\pytube\contrib\playlist.py", line 351, in title
    return self.sidebar_info[0]['playlistSidebarPrimaryInfoRenderer'][
  File "C:\Users\....\lib\site-packages\pytube\contrib\playlist.py", line 93, in sidebar_info
    self._sidebar_info = self.initial_data['sidebar'][
KeyError: 'sidebar'
```

**Comment by Saikat299792458** [comment]
Check if the playlist is private. BTW, the error should contain more information. The hell is sidebar?

**Comment by lionderful** [comment]
many KeyError: 'sidebar' happen when you do a API test for Channel Object, for example:
last_updated, length, owner, owner_id, owner_url, sidebar_info, title, views
where is the "sidebar"? Is there anyone kindly to fix this bug?
all API above could not work as Docs show.

**Comment by mhrezaiek** [comment]
Hey, I have the same issue. When I try to get playlist.description I get the same error. :
C:\Users\Owner\AppData\Local\Programs\Python\Python310\python.exe D:/src/MARZ/ML_data_pipline/src/scripts/PlaylistDownloader.py 
Traceback (most recent call last):
  File "D:\src\MARZ\ML_data_pipline\src\scripts\PlaylistDownloader.py", line 80, in <module>
    playlistDownloader("https://www.youtube.com/watch?v=rZgUo3Io2C4&list=PLJCcQ-fZ-_eJuGuajVYcNdLmB0i-EDSkv")
  File "D:\src\MARZ\ML_data_pipline\src\scripts\PlaylistDownloader.py", line 62, in playlistDownloader
    "description":playlist.description,
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\contrib\playlist.py", line 356, in description
    return self.sidebar_info[0]['playlistSidebarPrimaryInfoRenderer'][
KeyError: 'simpleText'

**Comment by pedrocaribe** [comment]
I'm getting the same error. Could we get a review on this?

Code:

`from youtubesearchpython import *
import json


url = 'https://www.youtube.com/watch?v=d1s7IbguHv4&list=RDd1s7IbguHv4'
playlist = Playlist.getVideos(url)

print(playlist)`

Results (tried with url being hardcoded into Playlist.getVideos() as well as a variable. Same error:

PS C:\--\--\Documents\BOT> python .\test_Youtube.py
Traceback (most recent call last):
  File "C:\--\--\Documents\BOT\test_Youtube.py", line 6, in <module>
    playlist = Playlist.getVideos(f'{url}')
  File "C:\--\--\AppData\Local\Programs\Python\Python310\lib\site-packages\youtubesearchpython\extras.py", line 1707, in getVideos
    ps.sync_create()
  File "C:\--\--\AppData\Local\Programs\Python\Python310\lib\site-packages\youtubesearchpython\core\playlist.py", line 41, in sync_create
    self.post_processing()
  File "C:\--\--\AppData\Local\Programs\Python\Python310\lib\site-packages\youtubesearchpython\core\playlist.py", line 32, in post_processing
    self.__getComponents()
  File "C:\--\--\AppData\Local\Programs\Python\Python310\lib\site-packages\youtubesearchpython\core\playlist.py", line 135, in __getComponents
    sidebar = self.responseSource["sidebar"]["playlistSidebarRenderer"]["items"]
KeyError: 'sidebar'

**Comment by lionderful** [comment]
> 
try this one: 
https://github.com/dermasmid/scrapetube

**Comment by AleixMT** [comment]
I am having the same problem here.

My output:

```
Traceback (most recent call last):
  File "/home/aleixmt/.local/bin/pytube", line 8, in <module>
    sys.exit(main())
  File "/home/aleixmt/.local/lib/python3.8/site-packages/pytube/cli.py", line 43, in main
    args.target = safe_filename(playlist.title)
  File "/home/aleixmt/.local/lib/python3.8/site-packages/pytube/contrib/playlist.py", line 351, in title
    return self.sidebar_info[0]['playlistSidebarPrimaryInfoRenderer'][
  File "/home/aleixmt/.local/lib/python3.8/site-packages/pytube/contrib/playlist.py", line 93, in sidebar_info
    self._sidebar_info = self.initial_data['sidebar'][
KeyError: 'sidebar'
```

What I am trying to do:
```
pytube https://www.youtube.com/playlist?list=PLsS6gopj1BA0hCo27eqw1eB6lLK6Fu-9Z -a 
```

**Comment by nosrevelc** [comment]
I beleve this property no more exist in youtub

I don't know how to fix this

![image](https://user-images.githubusercontent.com/45327773/236635083-29929837-38c3-4b87-938a-0d326334d5ff.png)

**Comment by AleixMT** [comment]
Is anyone maintaining this software? If you need help contact me.
