### ISSUE TITLE
KeyError: 'slug'

### ISSUE THREAD

**Issue by logston** [pytube/pytube#116]
```
CRITICAL: KeyError: 'slug'
Traceback (most recent call last):
  File "/Users/paul/.pyenv/versions/pytube/bin/pelican", line 11, in <module>
    sys.exit(main())
  File "/Users/paul/.pyenv/versions/3.5.1/envs/pytube/lib/python3.5/site-packages/pelican/__init__.py", line 478, in main
    pelican.run()
  File "/Users/paul/.pyenv/versions/3.5.1/envs/pytube/lib/python3.5/site-packages/pelican/__init__.py", line 175, in run
    p.generate_context()
  File "/Users/paul/.pyenv/versions/3.5.1/envs/pytube/lib/python3.5/site-packages/pelican/generators.py", line 583, in generate_context
    signals.article_generator_finalized.send(self)
  File "/Users/paul/.pyenv/versions/3.5.1/envs/pytube/lib/python3.5/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/Users/paul/.pyenv/versions/3.5.1/envs/pytube/lib/python3.5/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/Users/paul/Code/pytube/plugins/event_info.py", line 42, in _collect_event_info
    events = _load_events()
  File "/Users/paul/Code/pytube/plugins/event_info.py", line 61, in _load_events
    slug = data['slug']
KeyError: 'slug'
```

**Comment by logston** [comment]
This issue is due to the `content/conferences/.schemas/category.json` confusing the `event_info` plugin.
