### ISSUE TITLE
ERROR 'NoneType' object has no attribute 'span' [BUG]

### ISSUE THREAD

**Issue by DiyRex** [pytube/pytube#1167]
**Before creating an issue**

Please confirm that you are on the latest version of pytube by installing from the source.
You can do this by running `python -m pip install git+https://github.com/pytube/pytube`.
Sometimes, the pypi library repository is not up to date, and your issue may have been fixed already!

**Describe the bug**

**To Reproduce**
Please provide the following information:
- The video or playlist url that is causing the error.
- The code where the problem is occurring.

**Expected behavior**

**Output**
If pytube raises an exception, please provide the full traceback for the exception.

**System information**
Please provide the following information:
- Python version (run `python --version`)
- Pytube version (run `print(pytube.__version__)` in python)
- Command used to install pytube

**Comment by glubsy** [comment]
At least have the decency of editing the template before posting.

Duplicate of #1163.

**Comment by Justxd22** [comment]
Got the same,

    $ python test/test.py

    Traceback (most recent call last):
      File "/data/data/com.termux/files/test/test.py", line 15, in <module>
        i()
      File "/data/data/com.termux/files/test/test.py", line 10, in i
        s = youtubeHandler.streams
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pytube/__main__.py", line 292, in streams
        return StreamQuery(self.fmt_streams)
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pytube/__main__.py", line 177, in fmt_streams
        extract.apply_signature(stream_manifest, self.vid_info, self.js)
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pytube/extract.py", line 409, in apply_signature
        cipher = Cipher(js=js)
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pytube/cipher.py", line 44, in __init__
    self.throttling_array = get_throttling_function_array(js)
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pytube/cipher.py", line 323, in get_throttling_function_array
        str_array = throttling_array_split(array_raw)
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pytube/parser.py", line 158, in throttling_array_split
        match_start, match_end = match.span()
    AttributeError: 'NoneType' object has no attribute 'span'


Where test/test.py contains: 

    from pytube.__main__ import YouTube

    def io(q, w, e):
        print(q.filesize, len(w), len(w)/q.filesize*90)

    def down():
        youtubeHandler =   YouTube(url="https://www.youtube.com/watch?v=bsD8twtYzK8", on_progress_callback = io)
        s = youtubeHandler.streams
        a = s.filter(only_audio=True).order_by("bitrate").last()
        a.download()


    down()


Not sure what's the problem,  tried on different devices and different networks same problem with this link? I think

**Comment by escaleatomique** [comment]
Thank you man for contribution !
