### ISSUE TITLE
[BUG] yt.streams  Error

### ISSUE THREAD

**Issue by senanoguz** [pytube/pytube#1168]
match_start, match_end = match.span()
AttributeError: 'NoneType' object has no attribute 'span'

Found this issue

in C:\Python38\lib\site-packages\pytube\parser.py

Change this line:

152: func_regex = re.compile(r"function\([^)]+\)")

to this:

152: func_regex = re.compile(r"function\([^)]?\)")

The issue is that the regex expects a function with an argument, but I guess youtube added some src that includes non-paramterized functions.

**Comment by marnagy** [comment]
I am having the same issue, but after your fix, the following error occurs for input URL ´https://www.youtube.com/watch?v=9cBtJYI6itg´:

`Traceback (most recent call last):
  File "C:\Users\mnagy\Projects\Python\yt_downloader\main.py", line 260, in <module>
    main()
  File "C:\Users\mnagy\Projects\Python\yt_downloader\main.py", line 148, in main
    all_streams = yt.streams
  File "c:\Users\mnagy\miniconda3\envs\yt\lib\site-packages\pytube\__main__.py", line 292, in streams
    return StreamQuery(self.fmt_streams)
  File "c:\Users\mnagy\miniconda3\envs\yt\lib\site-packages\pytube\__main__.py", line 177, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "c:\Users\mnagy\miniconda3\envs\yt\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "c:\Users\mnagy\miniconda3\envs\yt\lib\site-packages\pytube\cipher.py", line 44, in __init__
    self.throttling_array = get_throttling_function_array(js)
  File "c:\Users\mnagy\miniconda3\envs\yt\lib\site-packages\pytube\cipher.py", line 323, in get_throttling_function_array
    str_array = throttling_array_split(array_raw)
  File "c:\Users\mnagy\miniconda3\envs\yt\lib\site-packages\pytube\parser.py", line 160, in throttling_array_split
    function_text = find_object_from_startpoint(curr_substring, match.span()[1])
  File "c:\Users\mnagy\miniconda3\envs\yt\lib\site-packages\pytube\parser.py", line 73, in find_object_from_startpoint
    raise HTMLParseError(f'Invalid start point. Start of HTML:\n{html[:20]}')
pytube.exceptions.HTMLParseError: Invalid start point. Start of HTML:
){for(var d=64,e=[];`

**Comment by glubsy** [comment]
Duplicate of #1163

**Comment by senanoguz** [comment]
> I am having the same issue, but after your fix, the following error occurs for input URL ´[https://www.youtube.com/watch?v=9cBtJYI6itg´](https://www.youtube.com/watch?v=9cBtJYI6itg%C2%B4):
> 
> `Traceback (most recent call last): File "C:\Users\mnagy\Projects\Python\yt_downloader\main.py", line 260, in <module> main() File "C:\Users\mnagy\Projects\Python\yt_downloader\main.py", line 148, in main all_streams = yt.streams File "c:\Users\mnagy\miniconda3\envs\yt\lib\site-packages\pytube\__main__.py", line 292, in streams return StreamQuery(self.fmt_streams) File "c:\Users\mnagy\miniconda3\envs\yt\lib\site-packages\pytube\__main__.py", line 177, in fmt_streams extract.apply_signature(stream_manifest, self.vid_info, self.js) File "c:\Users\mnagy\miniconda3\envs\yt\lib\site-packages\pytube\extract.py", line 409, in apply_signature cipher = Cipher(js=js) File "c:\Users\mnagy\miniconda3\envs\yt\lib\site-packages\pytube\cipher.py", line 44, in __init__ self.throttling_array = get_throttling_function_array(js) File "c:\Users\mnagy\miniconda3\envs\yt\lib\site-packages\pytube\cipher.py", line 323, in get_throttling_function_array str_array = throttling_array_split(array_raw) File "c:\Users\mnagy\miniconda3\envs\yt\lib\site-packages\pytube\parser.py", line 160, in throttling_array_split function_text = find_object_from_startpoint(curr_substring, match.span()[1]) File "c:\Users\mnagy\miniconda3\envs\yt\lib\site-packages\pytube\parser.py", line 73, in find_object_from_startpoint raise HTMLParseError(f'Invalid start point. Start of HTML:\n{html[:20]}') pytube.exceptions.HTMLParseError: Invalid start point. Start of HTML: ){for(var d=64,e=[];`

Hello everyone. I also got the same error today.
I'm not sure why that happens.
But I just added an exception and it was available for download.

https://github.com/pytube/pytube/blob/master/pytube/parser.py#L158

while len(curr_substring) > 0:
        if curr_substring.startswith('function'):
            # Handle functions separately. These can contain commas
            match = func_regex.search(curr_substring)
            match_start, match_end = match.span()
to

while len(curr_substring) > 0:
        if curr_substring.startswith('function'):
            # Handle functions separately. These can contain commas
            match = func_regex.search(curr_substring)
            if not match:
                        break        
            match_start, match_end = match.span()
However, this is a temporary way, must be added better way.

**Comment by glubsy** [comment]
```python 
if not match:
    break
```
I have not carefully looked at the function, but I have a feeling that breaking here will actually break the expected output from the function. As it is not covered by tests it's hard to tell.

**Comment by TechNotebookYT** [comment]
Yeah, I'm having the same issue as well

`AttributeError: 'NoneType' object has no attribute 'span'`

**Comment by quenrythane** [comment]
> > I am having the same issue, but after your fix, the following error occurs for input URL ´[https://www.youtube.com/watch?v=9cBtJYI6itg´](https://www.youtube.com/watch?v=9cBtJYI6itg%C2%B4):
> > `Traceback (most recent call last): File "C:\Users\mnagy\Projects\Python\yt_downloader\main.py", line 260, in <module> main() File "C:\Users\mnagy\Projects\Python\yt_downloader\main.py", line 148, in main all_streams = yt.streams File "c:\Users\mnagy\miniconda3\envs\yt\lib\site-packages\pytube\__main__.py", line 292, in streams return StreamQuery(self.fmt_streams) File "c:\Users\mnagy\miniconda3\envs\yt\lib\site-packages\pytube\__main__.py", line 177, in fmt_streams extract.apply_signature(stream_manifest, self.vid_info, self.js) File "c:\Users\mnagy\miniconda3\envs\yt\lib\site-packages\pytube\extract.py", line 409, in apply_signature cipher = Cipher(js=js) File "c:\Users\mnagy\miniconda3\envs\yt\lib\site-packages\pytube\cipher.py", line 44, in __init__ self.throttling_array = get_throttling_function_array(js) File "c:\Users\mnagy\miniconda3\envs\yt\lib\site-packages\pytube\cipher.py", line 323, in get_throttling_function_array str_array = throttling_array_split(array_raw) File "c:\Users\mnagy\miniconda3\envs\yt\lib\site-packages\pytube\parser.py", line 160, in throttling_array_split function_text = find_object_from_startpoint(curr_substring, match.span()[1]) File "c:\Users\mnagy\miniconda3\envs\yt\lib\site-packages\pytube\parser.py", line 73, in find_object_from_startpoint raise HTMLParseError(f'Invalid start point. Start of HTML:\n{html[:20]}') pytube.exceptions.HTMLParseError: Invalid start point. Start of HTML: ){for(var d=64,e=[];`
> 
> Hello everyone. I also got the same error today. I'm not sure why that happens. But I just added an exception and it was available for download.
> 
> https://github.com/pytube/pytube/blob/master/pytube/parser.py#L158
> 
> while len(curr_substring) > 0: if curr_substring.startswith('function'): # Handle functions separately. These can contain commas match = func_regex.search(curr_substring) match_start, match_end = match.span() to
> 
> while len(curr_substring) > 0: if curr_substring.startswith('function'): # Handle functions separately. These can contain commas match = func_regex.search(curr_substring) if not match: break match_start, match_end = match.span() However, this is a temporary way, must be added better way.

Thanks a lot bro! This solve my problem
