### ISSUE TITLE
raise HTTPError(req.full_url, code, msg, hdrs, fp) urllib.error.HTTPError: HTTP Error 410: Gone

### ISSUE THREAD

**Issue by httpanand** [pytube/pytube#1170]
``` 
 line 5, in <module>
    vdo = yt.streams.first()


raise HTTPError(req.full_url, code, msg, hdrs, fp) urllib.error.HTTPError: HTTP Error 410: Gone
``` 
How to fix this ? This was working , 5 months back .. : (

**Comment by 89z** [comment]
Please provide example video

**Comment by solomsk** [comment]
代码是：
`from pytube import YouTube

yt = YouTube("http://www.youtube.com/watch?v=Ik-RsDGPI5Y")
print(yt.streams.all())
`
报错日志是：
/Applications/anaconda3/bin/python3 /Users/solo/Documents/TestWorkSpace/AA_000通用test/AA_pytube_test/pytube_test.py
Traceback (most recent call last):
  File "/Users/solo/Documents/TestWorkSpace/AA_000通用test/AA_pytube_test/pytube_test.py", line 4, in <module>
    print(yt.streams.all())
  File "/Applications/anaconda3/lib/python3.8/site-packages/pytube/__main__.py", line 311, in streams
    return StreamQuery(self.fmt_streams)
  File "/Applications/anaconda3/lib/python3.8/site-packages/pytube/__main__.py", line 214, in fmt_streams
    if "adaptive_fmts" in self.player_config_args:
  File "/Applications/anaconda3/lib/python3.8/site-packages/pytube/__main__.py", line 188, in player_config_args
    self._player_config_args = self.vid_info
  File "/Applications/anaconda3/lib/python3.8/site-packages/pytube/__main__.py", line 281, in vid_info
    return dict(parse_qsl(self.vid_info_raw))
  File "/Applications/anaconda3/lib/python3.8/site-packages/pytube/__main__.py", line 109, in vid_info_raw
    self._vid_info_raw = request.get(self.vid_info_url)
  File "/Applications/anaconda3/lib/python3.8/site-packages/pytube/request.py", line 53, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "/Applications/anaconda3/lib/python3.8/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "/Applications/anaconda3/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Applications/anaconda3/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Applications/anaconda3/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/Applications/anaconda3/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Applications/anaconda3/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Applications/anaconda3/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: Gone

Process finished with exit code 1

**Comment by httpanand** [comment]
I dont think ,  this module is maintained now !

**Comment by 89z** [comment]
I have alternate tool:

~~~
youtube Ik-RsDGPI5Y
~~~

https://github.com/89z/mech

**Comment by httpanand** [comment]
Bruh ? Its go and not python !

**Comment by httpanand** [comment]
No response from maintainers :(
