### ISSUE TITLE
File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/parser.py", line 158, in throttling_array_split     match_start, match_end = match.span() AttributeError: 'NoneType' object has no attribute 'span'

### ISSUE THREAD

**Issue by bubersome** [pytube/pytube#1179]
(venv) ➜  pytube pytube https://www.youtube.com/watch\?v\=M1KwzaKVFNA
Loading video...
Traceback (most recent call last):
  File "/Users/32uni/PycharmProjects/pytube/venv/bin/pytube", line 8, in <module>
    sys.exit(main())
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/cli.py", line 53, in main
    _perform_args_on_youtube(youtube, args)
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/cli.py", line 60, in _perform_args_on_youtube
    download_highest_resolution_progressive(
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/cli.py", line 474, in download_highest_resolution_progressive
    stream = youtube.streams.get_highest_resolution()
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/__main__.py", line 292, in streams
    return StreamQuery(self.fmt_streams)
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/__main__.py", line 177, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/cipher.py", line 44, in __init__
    self.throttling_array = get_throttling_function_array(js)
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/cipher.py", line 323, in get_throttling_function_array
    str_array = throttling_array_split(array_raw)
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/parser.py", line 158, in throttling_array_split
    match_start, match_end = match.span()
AttributeError: 'NoneType' object has no attribute 'span'
(venv) ➜  pytube pytube https://www.youtube.com/watch\?v\=M1KwzaKVFNA -l
Loading video...
Traceback (most recent call last):
  File "/Users/32uni/PycharmProjects/pytube/venv/bin/pytube", line 8, in <module>
    sys.exit(main())
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/cli.py", line 53, in main
    _perform_args_on_youtube(youtube, args)
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/cli.py", line 66, in _perform_args_on_youtube
    display_streams(youtube)
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/cli.py", line 491, in display_streams
    for stream in youtube.streams:
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/__main__.py", line 292, in streams
    return StreamQuery(self.fmt_streams)
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/__main__.py", line 177, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/cipher.py", line 44, in __init__
    self.throttling_array = get_throttling_function_array(js)
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/cipher.py", line 323, in get_throttling_function_array
    str_array = throttling_array_split(array_raw)
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/parser.py", line 158, in throttling_array_split
    match_start, match_end = match.span()
AttributeError: 'NoneType' object has no attribute 'span'
(venv) ➜  pytube

**Comment by 89z** [comment]
Link is not valid:

https://www.youtube.com/watch\?v\=M1KwzaKVFNA

**Comment by bubersome** [comment]
I am logged in to my Google account. It seems that the link address obtained after logging in to the account is different.
