### ISSUE TITLE
urllib2.URLError

### ISSUE THREAD

**Issue by playerkk** [pytube/pytube#118]
I searched over all issues. Seems nobody encountered this problem before. I apologize if I missed something. 

When I run the command in the terminal "pytube -e mp4 -r 720p http://www.youtube.com/watch?v=Ik-RsDGPI5Y", I got the following errors (I installed pytube using "pip install -U pytube").
Traceback (most recent call last):
  File "/usr/local/bin/pytube", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/pytube/__main__.py", line 30, in main
    yt = YouTube(args.url)
  File "/usr/local/lib/python2.7/site-packages/pytube/api.py", line 66, in __init__
    self.from_url(url)
  File "/usr/local/lib/python2.7/site-packages/pytube/api.py", line 189, in from_url
    signature = self._get_cipher(stream_map["s"][i], js_url)
  File "/usr/local/lib/python2.7/site-packages/pytube/api.py", line 363, in _get_cipher
    response = urlopen(url)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 427, in open
    req = meth(req)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1126, in do_request_
    raise URLError('no host given')
urllib2.URLError: <urlopen error no host given>

Thanks a lot for the help.

**Comment by playerkk** [comment]
Found a solution in another issue https://github.com/nficano/pytube/issues/117.
