### ISSUE TITLE
'Stream' object has no attribute 'fps'

### ISSUE THREAD

**Issue by chen-WR** [pytube/pytube#1181]
pytube 11.0.2, python 3.10.1

Trying to filter YouTube streams by fps and got  Error.

Input: YouTube("https://www.youtube.com/watch?v=xIANCyXGN5I").streams.filter(fps=30)
Ouput: AttributeError: 'Stream' object has no attribute 'fps'

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Main\Desktop\youtubeDL\lib\site-packages\pytube\query.py", line 175, in filter
    return self._filter(filters)
  File "C:\Users\Main\Desktop\youtubeDL\lib\site-packages\pytube\query.py", line 181, in _filter
    return StreamQuery(list(fmt_streams))
  File "C:\Users\Main\Desktop\youtubeDL\lib\site-packages\pytube\query.py", line 129, in <lambda>
    filters.append(lambda s: s.fps == fps)
AttributeError: 'Stream' object has no attribute 'fps'

**Comment by gaetan1903** [comment]
![image](https://user-images.githubusercontent.com/43904633/147510072-bce174bb-fc7b-44eb-8b8e-076bcf41003f.png)
There is object doesn't have a fps attribut

**Comment by ghost** [comment]
Did you fix it? fps attribute is still missing from stream.

**Comment by gaetan1903** [comment]
@ardpeiris i have had already do a PR  but not yet merged
#1188

**Comment by rmruss2022** [comment]
Still having this problem in 23 :D

**Comment by devokd** [comment]
I am still facing the issue
