### ISSUE TITLE
I'm Getting 'urllib.error.URLError: <urlopen error no host given>'

### ISSUE THREAD

**Issue by MotorCityCobra** [pytube/pytube#119]
from pytube import YouTube
from pprint import pprint

yt = YouTube("http://www.youtube.com/watch?v=Ik-RsDGPI5Y")

Just a script with the above, or importing the module in the python commandline then typing yt = YouTube("http://www.youtube.com/watch?v=Ik-RsDGPI5Y")

Gives me the error below. I've tried this in python 3 and python 2. Is there something incompatible with virtualenv?

(venv) MY-MBP:new ME$ python3 yt.py
Traceback (most recent call last):
  File "yt.py", line 4, in <module>
    yt = YouTube("http://www.youtube.com/watch?v=Ik-RsDGPI5Y")
  File "/Users/MY/new/venv/lib/python3.4/site-packages/pytube/api.py", line 66, in __init__
    self.from_url(url)
  File "/Users/MY/new/venv/lib/python3.4/site-packages/pytube/api.py", line 189, in from_url
    signature = self._get_cipher(stream_map["s"][i], js_url)
  File "/Users/MY/new/venv/lib/python3.4/site-packages/pytube/api.py", line 363, in _get_cipher
    response = urlopen(url)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 462, in open
    req = meth(req)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 1106, in do_request_
    raise URLError('no host given')
urllib.error.URLError: <urlopen error no host given>
(venv) MYs-MBP:new ME$

**Comment by rotemvilsa** [comment]
Take a look at #117, I solved this issue there.
