### ISSUE TITLE
[BUG] Pytube stopped working, did not update, did not change the code.

### ISSUE THREAD

**Issue by iBlz** [pytube/pytube#1205]
So i wanted to download a playlist using my software QuickTransfer, i first tried to do this on my ubuntu container, i was on the lastest version, did not work. Then i tried on my laptop, lastest version again, did not work. I tried again on my rpi, did not work. I did not change any code in my program, and i also did not update. Can someone help me? Did youtube make a api change?

My version : 11.0.2
Python version : Python 3.9.2

If you need more info, ask me in the comments.

**Comment by rishabh3354** [comment]
Fixed in this branch
https://github.com/pytube/pytube/issues/1199#issuecomment-1017190777

**Comment by iBlz** [comment]
thanks!

**Comment by iBlz** [comment]
hello, i tried that fix, but there is just another error : 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pytube/__main__.py", line 177, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/usr/local/lib/python3.8/dist-packages/pytube/extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "/usr/local/lib/python3.8/dist-packages/pytube/cipher.py", line 37, in __init__
    self.transform_map = get_transform_map(js, var)
  File "/usr/local/lib/python3.8/dist-packages/pytube/cipher.py", line 245, in get_transform_map
    transform_object = get_transform_object(js, var)
  File "/usr/local/lib/python3.8/dist-packages/pytube/cipher.py", line 227, in get_transform_object
    raise RegexMatchError(caller="get_transform_object", pattern=pattern)
pytube.exceptions.RegexMatchError: get_transform_object: could not find match for var ={(.*?)};

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 2, in <module>
    YouTube('https://www.youtube.com/watch?v=dQw4w9WgXcQ').streams.first().download()
  File "/usr/local/lib/python3.8/dist-packages/pytube/__main__.py", line 292, in streams
    return StreamQuery(self.fmt_streams)
  File "/usr/local/lib/python3.8/dist-packages/pytube/__main__.py", line 184, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/usr/local/lib/python3.8/dist-packages/pytube/extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "/usr/local/lib/python3.8/dist-packages/pytube/cipher.py", line 37, in __init__
    self.transform_map = get_transform_map(js, var)
  File "/usr/local/lib/python3.8/dist-packages/pytube/cipher.py", line 245, in get_transform_map
    transform_object = get_transform_object(js, var)
  File "/usr/local/lib/python3.8/dist-packages/pytube/cipher.py", line 227, in get_transform_object
    raise RegexMatchError(caller="get_transform_object", pattern=pattern)
pytube.exceptions.RegexMatchError: get_transform_object: could not find match for var ={(.*?)};

```

**Comment by iBlz** [comment]
I fixed it myself. I changed "var_regex = re.compile(r"^$*\w+\W")" on the 30th line of "/usr/local/lib/python3.9/dist-packages/pytube/cipher.py"
Thanks for the help...

**Comment by Maxawa** [comment]
> I fixed it myself. I changed "var_regex = re.compile(r"^$*\w+\W")" on the 30th line of "/usr/local/lib/python3.9/dist-packages/pytube/cipher.py" Thanks for the help...

what did you change it to
