### ISSUE TITLE
Unable to get any streams.

### ISSUE THREAD

**Issue by Bloemenpot** [pytube/pytube#1207]
Hey. I am trying to learn how to do stuff in python and this looked like a great starting place for me because it seems like a fun project. Everything seemed to work at first. Have been trying to make stuff with this just for personal interest for about a month now. But all of a sudden it just stopped working. 

After tracing back where it stops working it seems it is unable to get the streams for some reason.
I made a quick showcase of where it gives the error:

from pytube import YouTube
import pytube
print(pytube.__version__)
yt = YouTube("https://www.youtube.com/watch?v=9aRIvdYx2R4")
print(yt.title)
print(yt.streams)

and this is the response i get:

PS D:\Keuzedeel-Python> & D:/Python/python.exe "d:/Keuzedeel-Python/Youtube Video Downloader/downloader.py"
11.0.1
“My Friends Call Me…” (Dubbed)
Traceback (most recent call last):
  File "d:\Keuzedeel-Python\Youtube Video Downloader\downloader.py", line 6, in <module>
    print(yt.streams)
  File "D:\Python\lib\site-packages\pytube\__main__.py", line 292, in streams
    return StreamQuery(self.fmt_streams)
  File "D:\Python\lib\site-packages\pytube\__main__.py", line 177, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "D:\Python\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "D:\Python\lib\site-packages\pytube\cipher.py", line 44, in __init__
    self.throttling_array = get_throttling_function_array(js)
  File "D:\Python\lib\site-packages\pytube\cipher.py", line 323, in get_throttling_function_array
    str_array = throttling_array_split(array_raw)
  File "D:\Python\lib\site-packages\pytube\parser.py", line 158, in throttling_array_split
    match_start, match_end = match.span()
AttributeError: 'NoneType' object has no attribute 'span'

I can see the final error at the end but im not that experienced with python or pytube to know how to fix this.
Any help will be extremely helpful! Thanks :D

**Comment by SuperZombi** [comment]
same

**Comment by victorhernandezm** [comment]
I have the same issue
UPDATE:
@Bloemenpot I think that you need to update the pytube version. I had 11.0.1 version but upgrading to 11.0.2 fixed this issue to me.

**Comment by Bloemenpot** [comment]
> 

Ah, i thought 11.0.1 was the most recent version haha. Thanks for the help :D it works now
