### ISSUE TITLE
[BUG] AttributeError: 'NoneType' object has no attribute 'span'

### ISSUE THREAD

**Issue by LightPat** [pytube/pytube#1224]
**Describe the bug**
Calling YouTube(link).streams is not returning a list of streams, it is returning a nonetype object.

**To Reproduce**
Please provide the following information:
[- The video or playlist url that is causing the error.](https://www.youtube.com/watch?v=J2K7HAr0yjk)
Command where bug occurs: yt.streams

**Expected behavior**
I expected the link to provide a list of available streams but it returned a nonetype object. Not even an empty list.

**Output**
Traceback (most recent call last):
  File "G:\Python Projects\YouTubeToMP3\main.py", line 49, in <module>
    print(yt.streams)
  File "C:\Users\patse\.virtualenvs\YouTubeToMP3-mwhV5Kc2\lib\site-packages\pytube\__main__.py", line 292, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\patse\.virtualenvs\YouTubeToMP3-mwhV5Kc2\lib\site-packages\pytube\__main__.py", line 177, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\patse\.virtualenvs\YouTubeToMP3-mwhV5Kc2\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\patse\.virtualenvs\YouTubeToMP3-mwhV5Kc2\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\patse\.virtualenvs\YouTubeToMP3-mwhV5Kc2\lib\site-packages\pytube\cipher.py", line 387, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\patse\.virtualenvs\YouTubeToMP3-mwhV5Kc2\lib\site-packages\pytube\cipher.py", line 301, in get_throttling_function_code
    code_lines_list = find_object_from_startpoint(js, match.span()[1]).split('\n')
AttributeError: 'NoneType' object has no attribute 'span'

**System information**
- Python Version 3.10.2
- Pytube Version 11.0.2
- pipenv install pytube (command used to install pytube)

**Comment by glubsy** [comment]
Duplicate. Thanks for the spam.

**Comment by LightPat** [comment]
This issue was resolved earlier on https://github.com/pytube/pytube/issues/1218

Change line 293 of cipher.py from: ```re.escape(get_throttling_function_name(js))``` to ```name = "iha"```
