### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jelanmathewjames** [pytube/pytube#1226]
**Before creating an issue**

Please confirm that you are on the latest version of pytube by installing from the source.
You can do this by running `python -m pip install git+https://github.com/pytube/pytube`.
Sometimes, the pypi library repository is not up to date, and your issue may have been fixed already!

**Describe the bug**
returning AttributeError: 'NoneType' object has no attribute 'span' due to error in cipher.py, extract.py, __main__.py
filtering cannot be done basic functionality of streams cannot be done

**To Reproduce**
check = yt.streams.filter(resolution=resolution).first()
for all urls 
**Expected behavior**
To return the details of video if video with that resolution exists , else return none.

**Output**
Traceback (most recent call last):
  File "/home/jelan/Desktop/desk_env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/jelan/Desktop/desk_env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jelan/Desktop/yt_downloader/downloader/views.py", line 26, in video
    check = yt.streams.filter(resolution=resolution).first()
  File "/home/jelan/Desktop/desk_env/lib/python3.8/site-packages/pytube/__main__.py", line 292, in streams
    return StreamQuery(self.fmt_streams)
  File "/home/jelan/Desktop/desk_env/lib/python3.8/site-packages/pytube/__main__.py", line 177, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/home/jelan/Desktop/desk_env/lib/python3.8/site-packages/pytube/extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "/home/jelan/Desktop/desk_env/lib/python3.8/site-packages/pytube/cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "/home/jelan/Desktop/desk_env/lib/python3.8/site-packages/pytube/cipher.py", line 387, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "/home/jelan/Desktop/desk_env/lib/python3.8/site-packages/pytube/cipher.py", line 301, in get_throttling_function_code
    code_lines_list = find_object_from_startpoint(js, match.span()[1]).split('\n')
AttributeError: 'NoneType' object has no attribute 'span'

**System information**
Please provide the following information:
python3.8
11.0.2
'pip install pytube' and 'python -m pip install git+https://github.com/pytube/pytube'

**Comment by lerry30** [comment]
I have the same error too

**Comment by rishabh3354** [comment]
https://github.com/pytube/pytube/issues/1199#issuecomment-1028736277

**Comment by MYtelecharger** [comment]
Is anyone fixed this error?
