### ISSUE TITLE
[BUG]KeyError: 'streamingData' for video removed for violating YouTube's Terms of Service

### ISSUE THREAD

**Issue by wkkskskdkkd** [pytube/pytube#1232]
pytube.exceptions.PytubeError: Traceback while accessing title of https://youtube.com/watch?v=32nkdvLq3oQ.

To Reproduce

$ python3
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pytube import YouTube
>>> YouTube('https://youtube.com/watch?v=32nkdvLq3oQ').streams
Expected behavior
Handled in pytube.exceptions.

Output

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\__main__.py", line 292, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\__main__.py", line 172, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\__main__.py", line 157, in streaming_data
    return self.vid_info['streamingData']
KeyError: 'streamingData'

**Comment by d3r1n** [comment]
Are you using the latest version of pytube?

**Comment by Sam-JR-Milburn** [comment]
I too am getting this error.
Using Python 3.* (Python3.9.2)
on Debian (5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux)
Just uninstalled pytube and built from source here 
pip3 install git+https://github.com/pytube/pytube

I have noticed that the KeyError: streamingData is intermittent and usually shows up on videos that you would suspect as being flagged for ToS violations but not removed - 
In the new YouTube format, there's a Download button on any 'normal video' inviting you to try out YouTube premium, for example a Tom Scott video.
However, there are videos where the Download button is in the drop-down "Meatballs Menu" and that's where I'm personally getting the error.

```
  from pytube import YouTube
  link = 'https://youtube.com/watch?v=YouTubevideothatcensorsdon'tlike'
  yt = YouTube(link)
  print(yt.streams)
  #OR
  yt.streams.get_highest_resolution().download()
```

**Comment by omkarpyc** [comment]
I finally got a solution for this KeyError: 'Streaming Data'.
This error arises if you are trying to download videos that require a sign in / login for example Age Restricted videos require sign in or login. I tried to keep an exception for Age Restricted from pytube.exceptions but the error still persists because the statement for exception didn't actually run for some reason. Actually this is not even an error but a bug.

Solution
I included several exception in below example i am trying to download the Youtube 8m dataset.


        for video_id in video_id_list:
            try:
                YouTube('http://youtube.com/watch?v=' + video_id).streams.get_highest_resolution().download(vedio_dir)
            except (VideoUnavailable, HTTPError, ConnectionError,RemoteDisconnected, ConnectTimeout, InvalidURL, ProtocolError, AgeRestrictedError, VideoRegionBlocked, LiveStreamError, RecordingUnavailable, MembersOnly, VideoPrivate, Exception):
                try:
                    YouTube('http://youtube.com/watch?v=' + video_id).streams.get_highest_resolution().download(vedio_dir)
                except (VideoUnavailable, HTTPError, ConnectionError,RemoteDisconnected, ConnectTimeout, InvalidURL, ProtocolError, AgeRestrictedError, VideoRegionBlocked, LiveStreamError, RecordingUnavailable, MembersOnly, VideoPrivate, Exception):
                    print(' http://youtube.com/watch?v=' + video_id)

This made me download those videos without problem.
Kindly try even if my solution looks silly.
