### ISSUE TITLE
pytube.exceptions.RegexMatchError: regex_search: could not find match for (?:v=|\/)([0-9A-Za-z_-]{11}).* [BUG]

### ISSUE THREAD

**Issue by lerry30** [pytube/pytube#1238]
Exception in Tkinter callback
Traceback (most recent call last):
File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
File "c:\Users\me\Desktop\python\main.py", line 51,
    YouTube(clip).streams.get_highest_resolution()
File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\__main__.py", line 71, in __init__
    self.video_id = extract.video_id(url)
File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\extract.py", line 133, in video_id
    return regex_search(r"(?:v=|\/)([0-9A-Za-z_-]{11}).*", url, group=1)
File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\helpers.py", line 129, in regex_search
    raise RegexMatchError(caller="regex_search", pattern=pattern)
pytube.exceptions.RegexMatchError: regex_search: could not find match for (?:v=|\/)([0-9A-Za-z_-]{11}).*

**Comment by glubsy** [comment]
Post the video ID you used to get this error.
