### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by iamDyeus** [pytube/pytube#1245]
**Describe the bug**
`pytube.exceptions.RegexMatchError: regex_search: could not find match for (?:v=|\/)([0-9A-Za-z_-]{11}).* `

**To Reproduce**
def downloader():

    # Object creation using YouTube
    yt = YouTube(str(url_entry))

    #TODO - ERROR CHECKS
    if download_format == "MP4":
        # Filters out all the files with 'mp4' extension 
        video = yt.streams.get_highest_resolution()
        out=video.download(path_entry)
        os.rename(out, entry_4 + '.mp4')
    elif download_format == "MP3":
        video = yt.streams.filter(only_audio=True).first()
        out = video.download(path_entry)
        # Editing the extension
        base = out[:len(out)-4]
        os.rename(out, entry_4 + '.mp3')

**Expected behavior**
it Should have downloaded the video/audio.

**Output**
`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__   
    return self.func(*args)
  File "c:\Users\User\Desktop\Youtube Downloader\v2\gui.py", line 27, in downloader
    yt = YouTube(str(url_entry))
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\__main__.py", line 71, in 
__init__
    self.video_id = extract.video_id(url)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\extract.py", line 133, in 
video_id
    return regex_search(r"(?:v=|\/)([0-9A-Za-z_-]{11}).*", url, group=1)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\helpers.py", line 129, in 
regex_search
    raise RegexMatchError(caller="regex_search", pattern=pattern)
pytube.exceptions.RegexMatchError: regex_search: could not find match for (?:v=|\/)([0-9A-Za-z_-]{11}).* `

**System information**
Please provide the following information:
- Python version - 3.9.7
- Pytube version - 11.0.2
- `python -m pip install Pytube`

**Comment by iamDyeus** [comment]
i found out i had some mistakes in my downloader() code, now the only error I get is the span one.

`def downloader():

    # Object creation using YouTube
    yt = YouTube(str(url_entry.get()))

    if download_format.get() == "MP4":
        # Filters out all the files with 'mp4' extension 
        video = yt.streams.get_highest_resolution()
        out=video.download(path_entry.get())
        os.rename(out, entry_4.get() + '.mp4')
    elif download_format.get() == "MP3":
        video = yt.streams.filter(only_audio=True).first()
        out = video.download(path_entry.get())
        # Editing the extension
        base = out[:len(out)-4]
        os.rename(out, entry_4.get() + '.mp3')`
