### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by omar3110** [pytube/pytube#1247]
**Please help me**

I confirmed that you are on the latest version of pytube by installing from the source.
I did this by running `python -m pip install git+https://github.com/pytube/pytube`.
the pypi library repository is up to date

**Description of the bug**
Whenever I call streams and run it gives me error. However  title, thumbnail, description, views, video_id are working properly.
Please see the code and output below

**The code where the problem is occurring**

from pytube import YouTube

yt = YouTube(
    "https://www.youtube.com/watch?v=Z-SUuov-VdQ&ab_channel=SascoContractors")

print(f"Tile: {yt.title}")

print(f"Thumbnail URL: {yt.thumbnail_url}")

print(f"Description: {yt.description}")

print(f"Views: {yt.views}")

print(f"Video ID: {yt.video_id}")

Stream = yt.streams.first()

Stream.download()

**Expected behavior**

it should download the video

**Output**

Tile: Vancouver's Construction Boom | Deloitte Summit | Sasco Contractors Project Showcase
Thumbnail URL: https://i.ytimg.com/vi/Z-SUuov-VdQ/sddefault.jpg
Description: Today we check out one of downtown Vancouver's latest construction projects, Deloitte Summit. The Summit building located at 410 W Georgia Street is a unique addition to Vancouver's ever-growing skyline. Designed by Toyko-based architecture firm OSO and was inspired by Japanese lanterns.

Sasco is a fullscale electrical contractor based out of British Columbia. With offices in Burnaby, Kamloops and Victoria we can assist you in your next electrical project, big or small.

Follow us on Instagram: https://www.instagram.com/sascocanada/
Like us on Facebook: https://www.facebook.com/sascocanada/
Visit our Website: https://www.sascocontractors.com/
Views: 1110
Video ID: Z-SUuov-VdQ
Traceback (most recent call last):
  File "i:\YouTube Downloader\youtube_downloader.py", line 20, in <module>
    Stream = yt.streams.first()
  File "C:\Users\omar\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\__main__.py", line 296, in streams    return StreamQuery(self.fmt_streams)
  File "C:\Users\omar\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\omar\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\omar\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\cipher.py", line 43, in __init__  
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\omar\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\cipher.py", line 387, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\omar\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\cipher.py", line 301, in get_throttling_function_code
    code_lines_list = find_object_from_startpoint(js, match.span()[1]).split('\n')
AttributeError: 'NoneType' object has no attribute 'span'

**System information**
![Screenshot (58)](https://user-images.githubusercontent.com/66789690/153208073-e4efd0f4-4513-4acf-baac-f0156e080389.png)
![Screenshot (59)](https://user-images.githubusercontent.com/66789690/153208090-1287c81e-3b99-43d8-a7ed-3c26984d1ded.png)

- Python version - Python 3.9.7
- Pytube version - v11.0.2.
- Command used to install pytube - 1. pip install pytube
- 2. git clone git://github.com/pytube/pytube.git
- 3. cd pytube
- 4. python -m pip install

**Comment by glubsy** [comment]
This is spam. Learn to look for existing issues.

**Comment by ifahadone** [comment]
@omar3110

====> https://github.com/pytube/pytube/issues/1243

**Comment by NK-2041** [comment]
Done Following changes and working fine for me:
If you check get_throttling_plan function at 374, it depends on c array.
changes: 264 to 280 file cipher.py
```
    function_patterns = [
        # https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-865985377
        # a.C&&(b=a.get("n"))&&(b=Dea(b),a.set("n",b))}};
        # In above case, `Dea` is the relevant function name
        #r'a\.[A-Z]&&\(b=a\.get\("n"\)\)&&\(b=([^(]+)\(b\)',
        r'try\{c\[',
    ]
    logger.debug('Finding throttling function name')
    for pattern in function_patterns:
        regex = re.compile(pattern)
        function_match = regex.search(js)
        if function_match:
            function_name=re.findall("[A-Za-z]{3}=function\(\w\)",js[:function_match.span()[1]])[-1]
            logger.debug("finished regex search, matched: %s", pattern)
            return function_name[:3]

    raise RegexMatchError(
```

**Comment by Dilshan1997** [comment]
@NK-2041 From this code span error is gone but other testings are failed
