### ISSUE TITLE
[BUG] errors in cli, main, extract and cipher

### ISSUE THREAD

**Issue by hoycch** [pytube/pytube#1249]
**Before creating an issue**

I'm using the latest package 11.0.2

**Describe the bug**
When I start to download, just all error messages

**To Reproduce**
Please provide the following information:
pytube https://www.youtube.com/watch?v=wocC1S4QBRs

**Expected behavior**
it used to be downloading

**Output**
```
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\trio\AppData\Roaming\Python\Python39\Scripts\pytube.exe\__main__.py", line 7, in <module>
  File "C:\Users\trio\AppData\Roaming\Python\Python39\site-packages\pytube\cli.py", line 53, in main
    _perform_args_on_youtube(youtube, args)
  File "C:\Users\trio\AppData\Roaming\Python\Python39\site-packages\pytube\cli.py", line 60, in _perform_args_on_youtube
    download_highest_resolution_progressive(
  File "C:\Users\trio\AppData\Roaming\Python\Python39\site-packages\pytube\cli.py", line 474, in download_highest_resolution_progressive
    stream = youtube.streams.get_highest_resolution()
  File "C:\Users\trio\AppData\Roaming\Python\Python39\site-packages\pytube\__main__.py", line 292, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\trio\AppData\Roaming\Python\Python39\site-packages\pytube\__main__.py", line 177, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\trio\AppData\Roaming\Python\Python39\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\trio\AppData\Roaming\Python\Python39\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\trio\AppData\Roaming\Python\Python39\site-packages\pytube\cipher.py", line 387, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\trio\AppData\Roaming\Python\Python39\site-packages\pytube\cipher.py", line 301, in get_throttling_function_code
    code_lines_list = find_object_from_startpoint(js, match.span()[1]).split('\n')
AttributeError: 'NoneType' object has no attribute 'span'
```

**System information**
Please provide the following information:
- Python version (run `python --version`)  3.9
- Pytube version (run `print(pytube.__version__)` in python) 11.0.2
- Command used to install pytube

**Comment by Dheirya** [comment]
Oh my god please read the other bugs that have been submit, there's been like 10 other posts with the same exact error. Here: https://github.com/pytube/pytube/issues/1218#issuecomment-1031836318

**Comment by Magnarks** [comment]
I have the same problem :/
