### ISSUE TITLE
[BUG] Youtube downloader error

### ISSUE THREAD

**Issue by ASCII-encrypt** [pytube/pytube#1257]
**Before creating an issue**

Please confirm that you are on the latest version of pytube by installing from the source.
You can do this by running `python -m pip install git+https://github.com/pytube/pytube`.
Sometimes, the pypi library repository is not up to date, and your issue may have been fixed already!

**Describe the bug**
I'm using Tkinter to make a simple mp4/mp3 downloader and any time I go to download a video I get an error and I cant quite tell what going wrong its worked when it was made but today i went to use it and nothing worked 
**To Reproduce**
download a video
-what video causes the error
any video will not work
- The code where the problem is occurring.
--------------------------------------------

from pytube import YouTube

root = Tk()
root.geometry('500x300')
root.resizable(0,0)
root.title("ASCII's video downloader")
root.configure(background="#4c4c4c")

Label(root,text = 'Youtube Video Downloader', font ='arial 20 bold',bg = '#4c4c4c').pack()

URL = StringVar()
Label(root, text = 'URL link here:', font = 'arial 15 bold',bg = '#4c4c4c').place(x= 160 , y = 60)
URL_enter = Entry(root, width = 70,textvariable = URL,bg = 'grey').place(x = 32, y = 90)

DownloadPath = StringVar()
Label(root, text = 'Download location Here:', font = 'arial 15 bold',bg = '#4c4c4c').place(x= 160 , y = 120)
DownloadPath_enter = Entry(root, width = 70,textvariable = DownloadPath,bg = 'grey').place(x = 32, y = 150)

def Mp4_Downloader():     
    url = YouTube(str(URL.get()))
    #video = url.streams.filter(progressive=True, file_extension='mp4').order_by('resolution').last()
    video = url.streams.get_highest_resolution()
    video.download(str(DownloadPath.get()))
    Label(root, text = 'DOWNLOADED', font = 'arial 15',bg = '#4c4c4c').place(x= 180 , y = 230)

def Mp3_Downloader():     
    url = YouTube(str(URL.get()))
    video = url.streams.get_audio_only()
    #video = url.streams.filter(progressive=True, file_extension='mp3').order_by('resolution').last()
    video.download(str(DownloadPath.get()))
    Label(root, text = 'DOWNLOADED', font = 'arial 15',bg = '#4c4c4c').place(x= 180 , y = 230)

Button(root,text = 'MP4', font = 'arial 15 bold' ,bg = '#31a7ce',activebackground='#CE5831', padx = 2, command = Mp4_Downloader).place(x=180 ,y = 190)
Button(root,text = 'MP3', font = 'arial 15 bold' ,bg = '#31a7ce',activebackground='#CE5831', padx = 2, command = Mp3_Downloader).place(x=260 ,y = 190)
root.mainloop()

![yt download](https://user-images.githubusercontent.com/95402540/155251280-351ec633-c5ef-480d-817a-895a3f869ad1.JPG)

----------------------------------------------------------------
**Expected behavior**
downloads the video as mp4/mp3 with youTube link and puts it in the typed directory 
**Output**
-----------------------------------------

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\eagle\Desktop\PYthon stuff\yt download\YoutubeDownloader.py", line 27, in Mp4_Downloader
    video = url.streams.get_highest_resolution()
  File "C:\Users\eagle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytube\__main__.py", line 292, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\eagle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytube\__main__.py", line 177, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\eagle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\eagle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\eagle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytube\cipher.py", line 387, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\eagle\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytube\cipher.py", line 301, in get_throttling_function_code
    code_lines_list = find_object_from_startpoint(js, match.span()[1]).split('\n')
AttributeError: 'NoneType' object has no attribute 'span'

-------------------------------------------------------------
**System information**
Please provide the following information:
- Python version Python 3.9.10
- Pytube version 12.0.0
- Command used to install pytube     python -m pip install git+https://github.com/pytube/pytube`.

**Comment by GabrielMendesdc** [comment]
same error here
python 3.8.12
pytube 11.0.1
pytube3 9.6.4

**Comment by KevinKefra1** [comment]
Bonsoir , il faut faire pip3 install pytube==12.0.0

**Comment by Matas001** [comment]
Same issue here on latest
