### ISSUE TITLE
[BUG] A very short video has an error.

### ISSUE THREAD

**Issue by iCodePoet** [pytube/pytube#1266]
**Describe the bug**
A very short video has an error.

The request used for the download does not seem to be able to handle requests for a ***small capacity***.
The ***urllib*** in use in the pytube package cannot handle this.
The error contents are as follows.

**To Reproduce**
Please provide the following information:
- The video or playlist url that is causing the error.
[https://www.youtube.com/watch?v=jb6-LDqLNqk](https://www.youtube.com/watch?v=jb6-LDqLNqk)

- The code where the problem is occurring.
```bash
Traceback (most recent call last):
  File "/home/jayflow/Proejcts/Puzz/video_cron/venv/lib/python3.10/site-packages/rq/worker.py", line 1061, in perform_job
    rv = job.perform()
  File "/home/jayflow/Proejcts/Puzz/video_cron/venv/lib/python3.10/site-packages/rq/job.py", line 821, in perform
    self._result = self._execute()
  File "/home/jayflow/Proejcts/Puzz/video_cron/venv/lib/python3.10/site-packages/rq/job.py", line 844, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/jayflow/Proejcts/Puzz/video_cron/src/providers/youtube.py", line 32, in download_video
    YouTube(
  File "/home/jayflow/Proejcts/Puzz/video_cron/venv/lib/python3.10/site-packages/pytube/streams.py", line 252, in download
    for chunk in request.stream(
  File "/home/jayflow/Proejcts/Puzz/video_cron/venv/lib/python3.10/site-packages/pytube/request.py", line 185, in stream
    chunk = response.read()
  File "/usr/lib/python3.10/http/client.py", line 481, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.10/http/client.py", line 632, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(0 bytes read, 203085 more expected)
```

![image](https://user-images.githubusercontent.com/29420674/159124530-4a014e61-d058-4e5d-a6ed-d3bc535526fc.png)

**My code**
```python
YouTube(
    url=f'https://www.youtube.com/watch?v={video_id}',
    on_complete_callback=lambda stream, file_path:
    self.__on_complete_download(
        YouTubeVideoMeta(
            video_id=video_id,
            file_path=file_path,
            file_name=file_path.split('/')[-1],
            stream=stream,
        ),
    ),
    on_progress_callback=self.__show_download_progress
).streams.get_highest_resolution().download(video_storage_path, filename=file_name)
```
**System information**
Please provide the following information:
- Python version (run `python --version`)
Python 3.10.2

- Pytube version (run `print(pytube.__version__)` in python)
pytube==12.0.0

**Comment by Sposito** [comment]
I am having the same issue here

```
Traceback (most recent call last):
  File "/Users/thiago/PycharmProjects/Youtube-whatsapp-bridge/main.py", line 51, in <module>
    stream.download(f'videos/{vid_id}')
  File "/Users/thiago/PycharmProjects/Youtube-whatsapp-bridge/venv/lib/python3.9/site-packages/pytube/streams.py", line 252, in download
    for chunk in request.stream(
  File "/Users/thiago/PycharmProjects/Youtube-whatsapp-bridge/venv/lib/python3.9/site-packages/pytube/request.py", line 185, in stream
    chunk = response.read()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 476, in read
    s = self._safe_read(self.length)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 628, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(0 bytes read, 7350689 more expected)
```

Is there any reason for using a low-level library like http.client, instead of something more straightforward like requests?

**Comment by 9M729** [comment]
Not to short 12min 10 sec
```
Traceback (most recent call last):
  File "/Users/digiflo/Desktop/videomaker/vi.py", line 15, in <module>
    yt.streams.filter(subtype='mp4',progressive=True).last().download(filename='vi0.mp4')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/streams.py", line 252, in download
    for chunk in request.stream(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/request.py", line 185, in stream
    chunk = response.read()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 481, in read
    s = self._safe_read(self.length)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 632, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(339288 bytes read, 9097896 more expected)
```

**Comment by leemidgley** [comment]
On the end of your .download put: ,max_retries=n
e.g.
yt.streams.filter(subtype='mp4',progressive=True).last().download(filename='vi0.mp4', max_retries=10)

by default it's set to 0.

**Comment by dongyouhong** [comment]
Modify the /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/request.py file as follows:
<img width="882" alt="图片" src="https://user-images.githubusercontent.com/64645404/179394812-87f752cc-1e97-4ceb-a205-6575181e2748.png">

**Comment by dongyouhong** [comment]
Modify the /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/request.py file as follows:
<img width="750" alt="图片" src="https://user-images.githubusercontent.com/64645404/179394856-b2cbf626-ad2c-46c1-b2ff-52e4d3dca7bd.png">

it's ok

**Comment by KairunHanjun** [comment]
Same here when i use to download audio only by using TreadPoolExecutor, the Thread just stuck in there doing absolutely nothing (literally doing nothing, i've been waiting until i lose patient), and when i restart the connection, it seem the error still in the same spot (IncompleteRead). it seem like when the internet down, the download kb/s is down to 0 and never connect back when the connection back.
![2022-07-25 (2)](https://user-images.githubusercontent.com/42841197/180794101-4a9c6069-1157-467c-8e62-8e46d246abe9.png)

**Comment by ArtemKorotkov321** [comment]
+1

Traceback (most recent call last):
  File "/home/telegram_bot/main.py", line 104, in downloadVideo
    yt_obj.streams.get_highest_resolution().download(chat_id, name_file + '.mp4')
  File "/usr/local/lib/python3.9/dist-packages/pytube/streams.py", line 314, in download
    for chunk in request.stream(
  File "/usr/local/lib/python3.9/dist-packages/pytube/request.py", line 189, in stream
    chunk = response.read()
  File "/usr/lib/python3.9/http/client.py", line 476, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.9/http/client.py", line 628, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(248488 bytes read, 9188696 more expected)
