### ISSUE TITLE
[BUG]Pytube Streams create error 429

### ISSUE THREAD

**Issue by princeGedeon** [pytube/pytube#1275]
**Describe the bug**
.HTTP Error 429: Too Many Requests with pytube

**To Reproduce**
#Installer Pytube depuis github
from pytube import YouTube

url="https://www.youtube.com/watch?v=KxdmigBTh74"
#url="https://www.youtube.com/watch?v=9l9Wa-5ph6o"

youtube_video=YouTube(url)

print("Titre : "+youtube_video.title)
print("NB VUES: ",youtube_video.views)
print("AUTHOR :",youtube_video.author)

#Pour une video choisir un flux (selon la resolution, audio ou vidéo)
print("STREAMS")
for stream in youtube_video.streams.fmt_streams:
    print(" ",stream)

**Output**
If pytube raises an exception, please provide the full traceback for the exception.

**Expected behavior**
Traceback (most recent call last):
  File "/home/princeg/Bureau/YoutubeDownalder/main.py", line 15, in <module>
    for stream in youtube_video.streams.fmt_streams:
  File "/home/princeg/Bureau/YoutubeDownalder/venv/lib/python3.9/site-packages/pytube/__main__.py", line 295, in streams
    self.check_availability()
  File "/home/princeg/Bureau/YoutubeDownalder/venv/lib/python3.9/site-packages/pytube/__main__.py", line 210, in check_availability
    status, messages = extract.playability_status(self.watch_html)
  File "/home/princeg/Bureau/YoutubeDownalder/venv/lib/python3.9/site-packages/pytube/__main__.py", line 102, in watch_html
    self._watch_html = request.get(url=self.watch_url)
  File "/home/princeg/Bureau/YoutubeDownalder/venv/lib/python3.9/site-packages/pytube/request.py", line 53, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "/home/princeg/Bureau/YoutubeDownalder/venv/lib/python3.9/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

**System information**
Please provide the following information:
- Python version python 3.9.7
- Pytube version pytube 12.0.0
- Command used to install pytube $ python -m pip install git+https://github.com/pytube/pytube

**Comment by sayyid5416** [comment]
It happens, when you make so many requests from one ip address, so YouTube limits that ip-address. pytube has nothing to do with it.
