### ISSUE TITLE
[BUG] YouTube video gives KeyError: content-length on one script, works fine on another with practically the same code

### ISSUE THREAD

**Issue by Miuzorosaurus** [pytube/pytube#1277]
**Before creating an issue**

Please confirm that you are on the latest version of pytube by installing from the source.
You can do this by running `python -m pip install git+https://github.com/pytube/pytube`.
Sometimes, the pypi library repository is not up to date, and your issue may have been fixed already!

**Describe the bug**
Basically I have two scripts - one is a youtube video processor that turns it into ascii and another one is a CLI youtube downloader. The parts of the code that select and download the video are nearly identical, however, as mentioned previously,

```
def downloadVideo(link):
    yt = YouTube(link)

    stream = yt.streams.filter(res="480p", file_extension="mp4", only_video = True)
    print(stream)

    if len(stream) < 1:
        raise IndexError("No streams found")

    attempts = 0
    maxattempts = 5

    while attempts < maxattempts:
        try:
            stream[0].download(filename=(OUTPUT + ".mp4"))
            break
        except Exception as e:
            print("Error downloading. Retrying... Reason: " + str(e))
            attempts = attempts + 1
    if attempts >= maxattempts:
        print("Error downloading. Exiting...")
        raise ValueError
    attempts = 0
```

This gives the exception `KeyError: content-length` on the line 
`stream[0].download(filename=(OUTPUT + ".mp4"))`

However, the following code does not and executes normally:

```
if dltype == "video":
        attempt = 0
        maxretries = 5
        while attempt < maxretries:
            try:
                if resolution == None:
                    stream = yt.streams.filter(only_video = True, file_extension="mp4")
                elif type(resolution) == str:
                    stream = yt.streams.filter(only_video = True, file_extension="mp4", res=resolution)
                    if len(stream) == 0:
                        print("No suitable video found. Maybe the video quality value is wrong or the video doesn't have that resolution?")
                        exit()
                stream[0].download(filename="videopart.mp4")
                break
            except http.client.IncompleteRead:
                print("Error occured, retrying...")
                attempt = attempt + 1
        if attempt == 5:
            print("Error has occured. Max retries reached. Exiting...")
            exit()
```

I suppose it's worth mentioning that both cases use:
`from pytube import YouTube`

**To Reproduce**
Please provide the following information:
- [The video or playlist url that is causing the error.](https://www.youtube.com/watch?v=bZ2FTFbBxwU)
- The code where the problem is occurring.

In the description above, the first chunk of code is the one that causes the issue.

**Expected behavior**
For the error to happen either in both cases, or in none of the cases.

**Output**
If pytube raises an exception, please provide the full traceback for the exception.

```
Traceback (most recent call last):
  File "/home/miuzore/python/videotoascii/videomaker.py", line 233, in <module>
    for x in output:
  File "/home/miuzore/python/videotoascii/videomaker.py", line 80, in main
    downloadVideo(VIDLINK)
  File "/home/miuzore/python/videotoascii/videomaker.py", line 159, in downloadVideo
    stream[0].download(filename=(OUTPUT + ".mp4"))
  File "/home/miuzore/.local/lib/python3.10/site-packages/pytube/streams.py", line 242, in download
    if skip_existing and self.exists_at_path(file_path):
  File "/home/miuzore/.local/lib/python3.10/site-packages/pytube/streams.py", line 292, in exists_at_path
    and os.path.getsize(file_path) == self.filesize
  File "/home/miuzore/.local/lib/python3.10/site-packages/pytube/streams.py", line 146, in filesize
    self._filesize = request.filesize(self.url)
  File "/home/miuzore/.local/lib/python3.10/site-packages/pytube/request.py", line 200, in filesize
    return int(head(url)["content-length"])
KeyError: 'content-length'
```

**System information**
Please provide the following information:
- Python version (run `python --version`): Python 3.10.4 
- Pytube version (run `print(pytube.__version__)` in python): 12.0.0
- Command used to install pytube: python -m pip install git+https://github.com/pytube/pytube

**Comment by iam048** [comment]
@Miuzorosaurus 

If a Video Contains Below Message
then it has some `Content-ID` Issue on the YouTube Side, due to this media with Content-ID needs to Process differently.

```text
Music in this video
Learn more
Listen ad-free with YouTube Premium
```

You can verify the media which doesn't have `Content-ID` Issues (It 'll work)
