### ISSUE TITLE
[BUG] I can't download using pytube

### ISSUE THREAD

**Issue by SeoJeongguk** [pytube/pytube#1284]
using the latest version pytube 12.0.0

I want get youtube file using pytube like this code 

from pytube import YouTube
YouTube('https://youtu.be/2lAe1cqCOXo').streams.first().download()
yt = YouTube('http://youtube.com/watch?v=2lAe1cqCOXo')
yt.streams.download()

But there are errors like this 

Traceback (most recent call last):
  File "C:\Users\jeong\anaconda3\envs\youtube\lib\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\jeong\anaconda3\envs\youtube\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\jeong\anaconda3\envs\youtube\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\jeong\anaconda3\envs\youtube\lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\jeong\anaconda3\envs\youtube\lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\Users\jeong\anaconda3\envs\youtube\lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jeong\youtube\youtube.py", line 2, in <module>
    YouTube('https://youtu.be/2lAe1cqCOXo').streams.first().download()
  File "C:\Users\jeong\anaconda3\envs\youtube\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\jeong\anaconda3\envs\youtube\lib\site-packages\pytube\__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\jeong\anaconda3\envs\youtube\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\jeong\anaconda3\envs\youtube\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\jeong\anaconda3\envs\youtube\lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\jeong\anaconda3\envs\youtube\lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\Users\jeong\anaconda3\envs\youtube\lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

how can I fix code? I think from youtube block free downloading

**Comment by sayyid5416** [comment]
Already reported in #1281 . Also please use search button before opening any new issue.

**Comment by SeoJeongguk** [comment]
From #1281 I can solve the problem! Thank you :)

**Comment by ashfaaqrifath** [comment]
It was working just fine yesterday. I don't know if youtube blocked something or pytube must update something. i hope they fix it soon.

**Comment by sayyid5416** [comment]
> From #1281 I can solve the problem! Thank you :)

Since it's a duplicate, You should close this issue.

**Comment by BlitzJB** [comment]
> It was working just fine yesterday. I don't know if youtube blocked something or pytube must update something. i hope they fix it soon.

there is a fix described in #1281 . worked for me :)

**Comment by elase3** [comment]
yes something wrong i think because its not working with me also even if you write simple code , i hope they fix problem

**Comment by shivam-grover** [comment]
Check out [this](https://github.com/pytube/pytube/issues/1281#issuecomment-1099824478) fix. It's a rather simple solution but you will have to manually change the library's files until the maintainer merges the PR.
