### ISSUE TITLE
[BUG]Unable to perform download

### ISSUE THREAD

**Issue by CK-Choco** [pytube/pytube#1287]
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Documents\備份影片\下載2.0.py", line 18, in <module>
    video = yt.streams.first()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

**Comment by sayyid5416** [comment]
Use search button before posting issues.

**Comment by thatsyogeshjjr** [comment]
try this:
open C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\cipher.py 
change line 272 ~ 273
```
r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&\s*'
r'\([a-z]\s*=\s*([a-zA-Z0-9$]{2,3})(\[\d+\])?\([a-z]\)'
```

and change line 288
`
nfunc=re.escape(function_match.group(1))),`

**Comment by sketchyboi14** [comment]
> try this: open C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\cipher.py change line 272 ~ 273
> 
> ```
> r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&\s*'
> r'\([a-z]\s*=\s*([a-zA-Z0-9$]{2,3})(\[\d+\])?\([a-z]\)'
> ```
> 
> and change line 288 ` nfunc=re.escape(function_match.group(1))),`

This works for me! Thanks you so much!!

**Comment by quinb96** [comment]
> try this: open C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\cipher.py change line 272 ~ 273
> 
> ```
> r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&\s*'
> r'\([a-z]\s*=\s*([a-zA-Z0-9$]{2,3})(\[\d+\])?\([a-z]\)'
> ```
> 
> and change line 288 ` nfunc=re.escape(function_match.group(1))),`

This works for me! Thank you so much!!

**Comment by slayermm1122** [comment]
works for me as well. thanks!!

> try this: open C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\cipher.py change line 272 ~ 273
> 
> ```
> r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&\s*'
> r'\([a-z]\s*=\s*([a-zA-Z0-9$]{2,3})(\[\d+\])?\([a-z]\)'
> ```
> 
> and change line 288 ` nfunc=re.escape(function_match.group(1))),`

works for me thanks
