### ISSUE TITLE
IncompleteRead

### ISSUE THREAD

**Issue by satan007** [pytube/pytube#1291]
['https://youtube.com/watch?v=BTN7eoYe8Ls\n']

Traceback (most recent call last):
  File "/home/alexey/ytov/ytov.py", line 47, in main
    test = Path(yt.streams.filter(type='video',file_extension='mp4',progressive=True).order_by('resolution').desc().first().download(download_folder))
  File "/usr/local/lib/python3.8/dist-packages/pytube/streams.py", line 252, in download
    for chunk in request.stream(
  File "/usr/local/lib/python3.8/dist-packages/pytube/request.py", line 185, in stream
    chunk = response.read()
  File "/usr/lib/python3.8/http/client.py", line 472, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.8/http/client.py", line 615, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(338751 bytes read, 9098433 more expected)

**Comment by Josh1st** [comment]
So I don't have a solution. But I do have a workaround.

what I did is download the best quality video and audio streams separately then I joined them with ffmpeg.
it takes much longer but you can get above 720p res so that's a plus.

here's my class you can use, its part of a pysimplegui which isn't relevant so you would have to cut out what you don't need

`from asyncio import threads
from pytube import Playlist, YouTube
import time
import threading
from queue import Queue
import os
import re
from pathlib import Path
import ffmpeg
import shutil

class Download():
    def __init__(self, window, update_progress, download_complete, download_start, update_list, destination=None):
        super(Download, self).__init__()
        self.window = window
        self.queue = []
        self.threads_array = []
        self.is_active = False
        self.update_progress = update_progress
        self.download_complete = download_complete
        self.download_start = download_start
        self.update_list = update_list
        self.destination = destination

    def add(self, url):
        urls = []
        is_playlist = '?list' in url
        if is_playlist:
            p = Playlist(url)
            # remove duplicates
            urls = list(dict.fromkeys(p.video_urls))
        else:
            urls.append(url)
        
        for url in urls:
            def update_progress(stream, bytes, remaining, id = url):
                return self.update_progress(stream, bytes, remaining, id)
            yt = YouTube(url, on_progress_callback=update_progress)
            self.queue.append(yt)
        self.update_list(self.queue)
    
    def get_audio(self, streams):
        return streams.filter(only_audio=True).order_by('abr').desc().first()

    def get_video(self, streams, target=2160):
        streams = streams.filter(only_video=True).order_by('resolution').desc()
        stream = streams.filter(only_video=True, video_codec='vp9', resolution=f'{target}p').first()
        if(stream):
            return(stream)
        else:
            for stream in streams:
                resolution = int(''.join(c for c in stream.resolution if c.isdigit()))
                if 'vp9' in stream.video_codec and resolution == target:
                    return stream

        return streams.first()
    

    def download(self):
        while len(self.queue):
            self.is_active = True
            yt = self.queue.pop(0)
            self.download_start(yt, self.queue)
            skip = False
            try:
                file_list = os.listdir(self.destination)
                # print(file_list)
                for file in file_list:
                    title = yt.title
                    title = re.sub('[<>:"/\|?*]+', '', title)
                    if os.path.isfile(os.path.join(self.destination, file)) and file.lower().endswith(("mp4")):
                        if title in file:
                            self.download_complete(self.queue)
                            print(f"skiping {yt.title}")
                            skip = True
                            continue
            except:
                print("Failed to read files")
                pass
            if not skip:
                print(f"Downloading: {yt.title}")
                streams = yt.streams
                title = re.sub('[<>:"/\|?*]+', '', yt.title)

                video_folder = str(os.path.join(self.destination, title))

                if not os.path.exists(video_folder):
                    os.makedirs(video_folder)

                audio = self.get_audio(streams)
                audio_ext = os.path.splitext(audio.get_file_path())[-1]

                video = self.get_video(streams, 1080)
                video_ext = os.path.splitext(video.get_file_path())[-1]

                audio.download(video_folder, 'audio'+audio_ext)
                video.download(video_folder, 'video'+video_ext)

                input_video = ffmpeg.input(str(os.path.join(video_folder, 'video'+video_ext)))
                input_audio = ffmpeg.input(str(os.path.join(video_folder, 'audio'+audio_ext)))
                ffmpeg.concat(input_video, input_audio, v=1, a=1).output(str(os.path.join(self.destination, title+'.mp4'))).run()
                
                try:
                    shutil.rmtree(video_folder)
                except OSError as e:
                    print ("Error: %s - %s." % (e.filename, e.strerror))

                self.download_complete(self.queue)
        self.is_active = False

    def run(self):
        threading.Thread(target=self.download, daemon=True).start()
        `


side note you need to download ffmpeg and either store the executable in the root of your project or install it fully so it is in your path.

**Comment by LaniakeaArmstrong** [comment]
I had that problem too, but I fixed it by closing my VS Code and reopening it.
I think my error appeared because I suspended the computer when the video was downloading.
I don't know if this will be helpful, but I hope so...

**Comment by boludoz** [comment]
try importing requests.get is available
