### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 410: Gone

### ISSUE THREAD

**Issue by eliamazzon** [pytube/pytube#1295]
**Describe the bug**
Trying to download videos with both the CLI interface and pytube module fails with the error: `urllib.error.HTTPError: HTTP Error 410: Gone`

**To Reproduce**
Execute: `$ pytube https://youtube.com/watch?v=2lAe1cqCOXo`

**Expected behavior**
Usually, it just works and downloads the video.

**Output**
`Loading video...
Traceback (most recent call last):
  File "/home/aile_/.local/bin/pytube", line 33, in <module>
    sys.exit(load_entry_point('pytube==12.0.0', 'console_scripts', 'pytube')())
  File "/home/aile_/.local/lib/python3.10/site-packages/pytube/cli.py", line 48, in main
    youtube = YouTube(args.url)
  File "/home/aile_/.local/lib/python3.10/site-packages/pytube/__main__.py", line 91, in __init__
    self.prefetch()
  File "/home/aile_/.local/lib/python3.10/site-packages/pytube/__main__.py", line 181, in prefetch
    self.vid_info_raw = request.get(self.vid_info_url)
  File "/home/aile_/.local/lib/python3.10/site-packages/pytube/request.py", line 36, in get
    return _execute_request(url).read().decode("utf-8")
  File "/home/aile_/.local/lib/python3.10/site-packages/pytube/request.py", line 24, in _execute_request
    return urlopen(request)  # nosec
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: Gone`

**System information**
Please provide the following information:
- Python version `Python 3.10.4`
- Pytube version `9.6.4`
- Command used to install pytube `python -m pip install git+https://github.com/pytube/pytube`

**Comment by sigmund505** [comment]
Same problem with Pytube3 9.6.4 on both Windows 10/Python 3.7.4 and Windows 11/Python 3.10 within the last three days.  Command used to install Pytube3:   pip install pytube3

**Comment by aperumpilly** [comment]
any other solution rather than installing python -m pip install git+https://github.com/pytube/pytube

**Comment by flyinggoatman** [comment]
I'm having this issue as well, only with video links though.

**Comment by glappa** [comment]
this error is still here, when can we expect a fix?
