### ISSUE TITLE
[BUG] pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

### ISSUE THREAD

**Issue by Apps8** [pytube/pytube#1299]
**Before creating an issue**

Please confirm that you are on the latest version of pytube by installing from the source.
You can do this by running `python -m pip install git+https://github.com/pytube/pytube`.
Sometimes, the pypi library repository is not up to date, and your issue may have been fixed already!

**Describe the bug**

**To Reproduce**
Please provide the following information:
- The video or playlist url that is causing the error.
- The code where the problem is occurring.

**Expected behavior**

**Output**
If pytube raises an exception, please provide the full traceback for the exception.

**System information**
Please provide the following information:
- Python version (run `python --version`)
- Pytube version (run `print(pytube.__version__)` in python)
- Command used to install pytube

**Comment by Apps8** [comment]
Hello,
I have problem with streams of YouTube video. I have tried everything I found on the net! I will be grateful for help!
pytube was working fine 2 or 3 weeks ago???

**To Reproduce**
The video url : https://www.youtube.com/watch?v=xfZCFME4Gsw 
**My Code**
    def download_video(self,video_url, video_file_name):
        youtube=pytube.YouTube(video_url)   

        video=youtube.streams.get_highest_resolution
        video.download(video_file_name)

**My Error** 
  File "C:\Users\jjpj1390\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\jjpj1390\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\jjpj1390\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\jjpj1390\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\jjpj1390\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\Users\jjpj1390\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

**System information**
Python 3.10.4
pytube : 12.0.0
pip install git+https://github.com/pytube/pytube

**Comment by devkarim** [comment]
If you want a quick workaround, [this](https://github.com/pytube/pytube/issues/1293#issuecomment-1103362815) fixed the issue.

**Comment by itsEmax64** [comment]
hi, I have the same issue and i have tried the solution that was mentioned but get this error instead
`File "C:\Users\Emax64\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\Emax64\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\Emax64\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\Emax64\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\Emax64\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py", line 406, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\Emax64\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py", line 312, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\Users\Emax64\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py", line 284, in get_throttling_function_name
    idx = function_match.group(2)
IndexError: no such group`

**Comment by thatsyogeshjjr** [comment]
try this:
open the file C:\Users\jjpj1390\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py
change line 272 ~ 273
```
r'a.[a-zA-Z]\s*&&\s*([a-z]\s*=\sa.get("n"))\s&&\s*'
r'([a-z]\s*=\s*([a-zA-Z0-9$]{2,3})([\d+])?([a-z])'
```

and change line 288
`
nfunc=re.escape(function_match.group(1))),`

**Comment by o-i-z-y-s** [comment]
> If you want a quick workaround, [this](https://github.com/pytube/pytube/issues/1293#issuecomment-1103362815) fixed the issue.

Can confirm this fixed the issue on my end as well.

**Comment by krishyadav007** [comment]
I am facing the same error.

Can't try the fix as I am on colab

@thatsyogeshjjr @o-i-z-y-s

**Comment by rajeshp2408** [comment]
Hi there ,

Im still having issue with Pytube download:
Status As on 30/04/2022

**System information:**
>>> print(pytube.__version__)
12.0.0

C:\Users\rajeshp>python
Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

Pytube version download:
python -m pip install git+https://github.com/pytube/pytube


**Code:**

>>> from pytube import YouTube
>>> video = YouTube('https://www.youtube.com/watch?v=G1eGGvrprS0')
>>> video.streams.get_by_itag(251).download()

**Response:**
Traceback (most recent call last):
  File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube\__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple
>>>

**cipher.py**

verified following regex:
    function_patterns = [
        # https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-865985377
        # https://github.com/yt-dlp/yt-dlp/commit/48416bc4a8f1d5ff07d5977659cb8ece7640dcd8
        # var Bpa = [iha];
        # ...
        # a.C && (b = a.get("n")) && (b = Bpa[0](b), a.set("n", b),
        # Bpa.length || iha("")) }};
        # In the above case, `iha` is the relevant function name
        r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&\s*'
        r'\([a-z]\s*=\s*([a-zA-Z0-9$]{3})(\[\d+\])?\([a-z]\)',
    ]

Can i know what has caused the following error? Is the bug fixed. Can i know the workaround or fix?

**Comment by rajeshp2408** [comment]
> Hi there ,
> 
> Im still having issue with Pytube download: Status As on 30/04/2022
> 
> **System information:**
> 
> > > > print(pytube.**version**)
> > > > 12.0.0
> 
> C:\Users\rajeshp>python Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
> 
> Pytube version download: python -m pip install git+https://github.com/pytube/pytube
> 
> **Code:**
> 
> > > > from pytube import YouTube
> > > > video = YouTube('https://www.youtube.com/watch?v=G1eGGvrprS0')
> > > > video.streams.get_by_itag(251).download()
> 
> **Response:** Traceback (most recent call last): File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube__main__.py", line 181, in fmt_streams extract.apply_signature(stream_manifest, self.vid_info, self.js) File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube\extract.py", line 409, in apply_signature cipher = Cipher(js=js) File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube\cipher.py", line 43, in **init** self.throttling_plan = get_throttling_plan(js) File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan raw_code = get_throttling_function_code(js) File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code name = re.escape(get_throttling_function_name(js)) File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name raise RegexMatchError( pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "", line 1, in File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube__main__.py", line 296, in streams return StreamQuery(self.fmt_streams) File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube__main__.py", line 188, in fmt_streams extract.apply_signature(stream_manifest, self.vid_info, self.js) File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube\extract.py", line 409, in apply_signature cipher = Cipher(js=js) File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube\cipher.py", line 43, in **init** self.throttling_plan = get_throttling_plan(js) File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan raw_code = get_throttling_function_code(js) File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code name = re.escape(get_throttling_function_name(js)) File "C:\Users\rajeshp\anaconda3\lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name raise RegexMatchError( pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple
> 
> > > >
> 
> **cipher.py**
> 
> verified following regex: function_patterns = [ # https://github.com/[ytdl-org/youtube-dl/issues/29326](https://github.com/ytdl-org/youtube-dl/issues/29326)#issuecomment-865985377 # https://github.com/yt-dlp/yt-dlp/commit/48416bc4a8f1d5ff07d5977659cb8ece7640dcd8 # var Bpa = [iha]; # ... # a.C && (b = a.get("n")) && (b = Bpa[0](b), a.set("n", b), # Bpa.length || iha("")) }}; # In the above case, `iha` is the relevant function name r'a.[a-zA-Z]\s*&&\s*([a-z]\s*=\s_a.get("n"))\s_&&\s*' r'([a-z]\s*=\s*([a-zA-Z0-9$]{3})([\d+])?([a-z])', ]
> 
> Can i know what has caused the following error? Is the bug fixed. Can i know the workaround or fix?

Resolved based on article Ref.:
https://www.codegrepper.com/code-examples/python/pytube.exceptions.RegexMatchError%3A+get_throttling_function_name%3A+could+not+find+match+for+multiple


line: 272 ~ 273
r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&\s*'
r'\([a-z]\s*=\s*([a-zA-Z0-9$]{2,3})(\[\d+\])?\([a-z]\)'

Difference found in current pytube 12 version:
![image](https://user-images.githubusercontent.com/5087316/166094420-7bae91ce-6334-441c-95da-8924b0cecf2b.png)

**Comment by rcsmit** [comment]
> try this: open the file C:\Users\jjpj1390\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py change line 272 ~ 273
> 
> ```
> r'a.[a-zA-Z]\s*&&\s*([a-z]\s*=\sa.get("n"))\s&&\s*'
> r'([a-z]\s*=\s*([a-zA-Z0-9$]{2,3})([\d+])?([a-z])'
> ```
> 
> and change line 288 ` nfunc=re.escape(function_match.group(1))),`

To make it work, 272-273 have to be

```
r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&\s*'
r'\([a-z]\s*=\s*([a-zA-Z0-9$]{2,3})(\[\d+\])?\([a-z]\)'          
```

(edit: found it somewhere else)

**Comment by numbernumberone** [comment]
> > try this: open the file C:\Users\jjpj1390\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py change line 272 ~ 273
> > ```
> > r'a.[a-zA-Z]\s*&&\s*([a-z]\s*=\sa.get("n"))\s&&\s*'
> > r'([a-z]\s*=\s*([a-zA-Z0-9$]{2,3})([\d+])?([a-z])'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and change line 288 ` nfunc=re.escape(function_match.group(1))),`
> 
> To make it work, 272-273 have to be
> 
> ```
> r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&\s*'
> r'\([a-z]\s*=\s*([a-zA-Z0-9$]{2,3})(\[\d+\])?\([a-z]\)'          
> ```

very nice !

**Comment by GuyARoss** [comment]
Just found this issue today, is there a PR with the fix?

**Comment by Praanshu98** [comment]
Replace the line 272-273 in cipher.py.

r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&\s*'
r'\([a-z]\s*=\s*([a-zA-Z0-9$]{2,3})(\[\d+\])?\([a-z]\)'

**Comment by TinKurbatoff** [comment]
In the parallel branch, I have already answered.
Replace lines 272-273 in cipher.py in another way:
```
        r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&\s*.*\|\|\s*(.*)\(',
        r'\([a-z]\s*=\s*([a-zA-Z0-9$]{3})(\[\d+\])?\([a-z]\)',    

```

**Comment by ghost** [comment]
> In the parallel branch, I have already answered. Replace lines 272-273 in cipher.py in another way:
> 
> ```
>         r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&\s*.*\|\|\s*(.*)\(',
>         r'\([a-z]\s*=\s*([a-zA-Z0-9$]{3})(\[\d+\])?\([a-z]\)',    
> ```


Thanks ☺️🥺🎉

It worked fine.
![Screenshot_20220505-002332](https://user-images.githubusercontent.com/58574822/166841023-31d9e294-6bc4-4d1b-80cd-f2e39701c231.png)

**Comment by TinKurbatoff** [comment]
Fixed in the more correct way:
by [Yu Jhin](https://github.com/uJhin)
lines 272-273 (cipher.py):
```
        r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&\s*'
        r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])?\([a-z]\)',
```

**Comment by TXAVL** [comment]
> 
https://github.com/pytube/pytube/issues/1299#issuecomment-1117526704
It works great for me🥰🥰
