### ISSUE TITLE
streams.get_audio_only fails to parse response from youtube

### ISSUE THREAD

**Issue by fabi321** [pytube/pytube#1313]
**Describe the bug**
video.streams.get_audio_only fails

**To Reproduce**
```python
video = YouTube(f'https://youtube.com/watch?v=RST4ExJTRH4')
stream = video.streams.get_audio_only(subtype='webm')
```

**Expected behavior**
Should not fail

**Output**
```
Traceback (most recent call last):
  File "/main.py", line 122, in process_track
    stream = video.streams.get_audio_only(subtype='webm') or video.streams.get_audio_only()
  File "/.venv/lib/python3.10/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "/.venv/lib/python3.10/site-packages/pytube/__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "/.venv/lib/python3.10/site-packages/pytube/__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
KeyError: 'streamingData'
```

**System information**
- Python version python 3.10.0
- Pytube version 12.0.0
- python -m pip install git+https://github.com/pytube/pytube

**Comment by fabi321** [comment]
I just realized that it is age restricted, and my search for similar issues was not proper.
