### ISSUE TITLE
PyTube Not Working After a Few Downloads [BUG]

### ISSUE THREAD

**Issue by ggkk77121** [pytube/pytube#1320]
pytube https://www.youtube.com/playlist?list=PLrxcNWZXdQ2lCJAkmH0XD0FiNZob0yiTG
Loading playlist...
NEFFEX - Better Days 🙏 [Copyright-Free].mp4 | 8 MB
 ↳ |█████████████████████████████████████████| 100.0%
Traceback (most recent call last):
  File "/home/runner/youtube/venv/bin/pytube", line 8, in <module>
    sys.exit(main())
  File "/home/runner/youtube/venv/lib/python3.8/site-packages/pytube/cli.py", line 46, in main
    _perform_args_on_youtube(youtube_video, args)
  File "/home/runner/youtube/venv/lib/python3.8/site-packages/pytube/cli.py", line 60, in _perform_args_on_youtube
    download_highest_resolution_progressive(
  File "/home/runner/youtube/venv/lib/python3.8/site-packages/pytube/cli.py", line 474, in download_highest_resolution_progressive
    stream = youtube.streams.get_highest_resolution()
  File "/home/runner/youtube/venv/lib/python3.8/site-packages/pytube/__main__.py", line 295, in streams
    self.check_availability()
  File "/home/runner/youtube/venv/lib/python3.8/site-packages/pytube/__main__.py", line 210, in check_availability
    status, messages = extract.playability_status(self.watch_html)
  File "/home/runner/youtube/venv/lib/python3.8/site-packages/pytube/__main__.py", line 102, in watch_html
    self._watch_html = request.get(url=self.watch_url)
  File "/home/runner/youtube/venv/lib/python3.8/site-packages/pytube/request.py", line 53, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "/home/runner/youtube/venv/lib/python3.8/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/nix/store/2vm88xw7513h9pyjyafw32cps51b0ia1-python3-3.8.12/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

**Comment by webriddler** [comment]
This is one of the problems which needs a better solution, that I still don't have.

**Comment by Justxd22** [comment]
This is YouTube blocking your ip for downloading too many videos, restart your router to get a new ip, if it's a server restart your server, make sure you got a new ip by using what's my ip website to check before and after,

Also you can use a vpn to get a new ip

**Comment by pourmand1376** [comment]
That's true. As a workaround, I use this code to save playlist videos in a file
```python
from pytube import Playlist
from pathlib import Path
playlist = Playlist('https://www.youtube.com/playlist?list=PLoEMreTa9CNmuxQeIKWaz7AVFd_ZeAcy4')
Path('all.txt').write_text("\n".join(playlist))
```

Then I manually (depends of the size of video and youtube algorithm to block ip) select first `n` items, and put them in a separate file called (part.txt), then use this one to download first n ones,

```bash
for name in $(cat part.txt);do pytube $name;done
```

Then after some time, I would download some more ...

I have not tried to write some script which does this automatically, but it works with huge playlists. The one I tried with has 513 videos on it.

**Comment by Justxd22** [comment]
@pourmand1376 you can do this in python only without bash, by making a for loop and waiting for x seconds after each download, that will be faster than doing it manually

**Comment by pourmand1376** [comment]
That's a good idea. Thanks!

**Comment by Ivor** [comment]
Is doing the interaction with youtube via an AWS Lambda a viable way to circumvent this issue?
