### ISSUE TITLE
Incomplete Read while downloading a playlist from YouTube[BUG]

### ISSUE THREAD

**Issue by abanand132** [pytube/pytube#1341]
**Describe the bug**
I am downloading a very big playlist from YouTube having 113 videos in it.  Every time after downloading 65 videos, the program throws an error.

**To Reproduce**
Please provide the following information:
- playlist url that is causing the error : https://youtube.com/playlist?list=PLu0W_9lII9agS67Uits0UnJyrYiXhDS6q
- The code where the problem is occurring.
- 
<img width="451" alt="image" src="https://user-images.githubusercontent.com/76703822/173343698-a30814fe-0a8f-4f37-b89a-8ad168851150.png">

**Expected behavior**
I expect that it downloads every video

**Output**
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\python 397\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "D:\Users\PycharmProjects\Angela Yu\Youtube_Downloader\playlist_downlaod.py", line 90, in res_720
    x.download(f"{Download_path.get()}\{p.title}")
  File "C:\python 397\lib\site-packages\pytube\streams.py", line 252, in download
    for chunk in request.stream(
  File "C:\python 397\lib\site-packages\pytube\request.py", line 185, in stream
    chunk = response.read()
  File "C:\python 397\lib\http\client.py", line 475, in read
    s = self._safe_read(self.length)
  File "C:\python 397\lib\http\client.py", line 627, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(171803 bytes read, 9265381 more expected).

**System information**
Please provide the following information:
- Python version (run `python --version`) :  Python 3.9.7
- Pytube version (run `print(pytube.__version__)` in python) : 12.1.0
- Command used to install pytube

**Comment by abanand132** [comment]
Please tell me how to fix this

**Comment by Justxd22** [comment]
@abanand132 You're trying to download stream 22 on all videos from the Playlist, some videos may not have stream 22, instead you can filter out streams and sort them by resolution descending and select what suits your needs the highest quality Will be the first stream and the lowest quality is the last stream

**Comment by abanand132** [comment]
> @abanand132 You're trying to download stream 22 on all videos from the Playlist, some videos may not have stream 22, instead you can filter out streams and sort them by resolution descending and select what suits your needs the highest quality Will be the first stream and the lowest quality is the last stream

that's not true. Each video is present in 720p resolution. I am not understanding that this playlist has 113 videos and each time download stopped at video no. 65. I am attaching a screenshot by traversing through the video list
![Screenshot 2022-06-26 102910](https://user-images.githubusercontent.com/76703822/175800134-9955e614-624d-43ce-87a5-7f593ed04a02.jpg)

**Comment by Justxd22** [comment]
@abanand132 maybe try downloading video 65 separately and see if it reports any error?

**Comment by KairunHanjun** [comment]
This same as me, i have thread that download 5 time in the same times. And that one thread just got stuck (still running, but never end). It's more like the internet goes down for a sec and then back again, but the connection in the stream never back and stuck in there (To fix it, i need to restart my connection)
