### ISSUE TITLE
urlopen error [WinError 10061] with pytube

### ISSUE THREAD

**Issue by TruthSeekerxx** [pytube/pytube#1342]
Hi,

I wanted to use pytube today but it does not work for me. Tried to turn off firewall but it still didn't work.
I am using spyder and I remember that I had problems with setting up localhost. Maybe that has something to do with it...

Edit:
Still trying to fix it. I found out that everything works fine on my laptop. That is untill I connected the wifi adapter that I use on my computer. Now I get the same error on my laptop too. Even after removing that adapter and resetting network settings on my laptop I still get the error.
Its like the adapter changes some settings on the computer which cause this error.
Edit_2:
Resetting windows on my laptop worked, but not going to try inserting my wifi adapter there again.

Here is my code:
```
import pytube
yt = pytube.YouTube('https://www.youtube.com/watch?v=9cBtJYI6itg').streams
```

Here is the error message:
-----------------------------------------------------------------------------
Traceback (most recent call last):

  File "C:\Anaconda\Anaconda3\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,

  File "C:\Anaconda\Anaconda3\lib\http\client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)

  File "C:\Anaconda\Anaconda3\lib\http\client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)

  File "C:\Anaconda\Anaconda3\lib\http\client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)

  File "C:\Anaconda\Anaconda3\lib\http\client.py", line 1034, in _send_output
    self.send(msg)

  File "C:\Anaconda\Anaconda3\lib\http\client.py", line 974, in send
    self.connect()

  File "C:\Anaconda\Anaconda3\lib\http\client.py", line 1441, in connect
    super().connect()

  File "C:\Anaconda\Anaconda3\lib\http\client.py", line 945, in connect
    self.sock = self._create_connection(

  File "C:\Anaconda\Anaconda3\lib\socket.py", line 844, in create_connection
    raise err

  File "C:\Anaconda\Anaconda3\lib\socket.py", line 832, in create_connection
    sock.connect(sa)

ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\user\Desktop\untitled7.py", line 9, in <module>
    yt = pytube.YouTube('https://www.youtube.com/watch?v=9cBtJYI6itg').streams

  File "C:\Anaconda\Anaconda3\lib\site-packages\pytube\__main__.py", line 295, in streams
    self.check_availability()

  File "C:\Anaconda\Anaconda3\lib\site-packages\pytube\__main__.py", line 210, in check_availability
    status, messages = extract.playability_status(self.watch_html)

  File "C:\Anaconda\Anaconda3\lib\site-packages\pytube\__main__.py", line 102, in watch_html
    self._watch_html = request.get(url=self.watch_url)

  File "C:\Anaconda\Anaconda3\lib\site-packages\pytube\request.py", line 53, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)

  File "C:\Anaconda\Anaconda3\lib\site-packages\pytube\request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec

  File "C:\Anaconda\Anaconda3\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)

  File "C:\Anaconda\Anaconda3\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)

  File "C:\Anaconda\Anaconda3\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +

  File "C:\Anaconda\Anaconda3\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)

  File "C:\Anaconda\Anaconda3\lib\urllib\request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,

  File "C:\Anaconda\Anaconda3\lib\urllib\request.py", line 1349, in do_open
    raise URLError(err)

URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>

**Comment by Justxd22** [comment]
This a network issue on your pc, not pytube fault

**Comment by ShenJunkun** [comment]
> This a network issue on your pc, not pytube fault

How Can I fix this problem? I use vpn to access YouTube.
