### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by EsdrasUday** [pytube/pytube#1349]
PYTHON VERSION : 3.10.5
Command:
from pytube import YouTube         

SAVE_PATH = "E:/Uday/Downloads E"
from pytube import YouTube
yt = YouTube('http://youtube.com/watch?v=9bZkp7q19f0')
yt.streams.filter(progressive=True, file_extension='mp4').order_by('resolution').desc().first().download(SAVE_PATH)

Error: 
Traceback (most recent call last):
  File "c:\Users\esdra\OneDrive\Área de Trabalho\BOB\BobAI\modules\Downtest.py", line 6, in <module>
    YouTube('https://youtu.be/9bZkp7q19f0').streams.first().download()
  File "C:\Users\esdra\OneDrive\Área de Trabalho\BOB\BobAI\venv\lib\site-packages\pytube\__main__.py", line 91, in __init__  
    self.prefetch()
  File "C:\Users\esdra\OneDrive\Área de Trabalho\BOB\BobAI\venv\lib\site-packages\pytube\__main__.py", line 181, in prefetch 
    self.vid_info_raw = request.get(self.vid_info_url)
  File "C:\Users\esdra\OneDrive\Área de Trabalho\BOB\BobAI\venv\lib\site-packages\pytube\request.py", line 36, in get        
    return _execute_request(url).read().decode("utf-8")
  File "C:\Users\esdra\OneDrive\Área de Trabalho\BOB\BobAI\venv\lib\site-packages\pytube\request.py", line 24, in _execute_request
    return urlopen(request)  # nosec
  File "C:\Users\esdra\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\esdra\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\esdra\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\esdra\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 557, in error
    result = self._call_chain(*args)
  File "C:\Users\esdra\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\esdra\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\esdra\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\esdra\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\esdra\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\esdra\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\esdra\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default       
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: Gone

**Comment by pxie-d** [comment]
I'm getting the same error. Tried uninstalling and installing pytube, tried running my script via VScode, pycharm, gitbash and nothing works. Please help!!!
