### ISSUE TITLE
[BUG] Not able to download audio for a specific video

### ISSUE THREAD

**Issue by NannoSilver** [pytube/pytube#1355]
Ii have pytube 12.1.0, with the patch at cypher.py patched to fix an existing bug, as the instructions here:
https://github.com/pytube/pytube/issues/1326#issuecomment-1144395745

Python is version 3.10 for Windows.

I am not able to download the audio (itag = 140) for a specific video, while I can download for other videos in the same youtube channel, including videos that are longer (minutes).

This is my code with the video generating the error:

```
from pytube import YouTube

yt = YouTube('https://youtube.com/watch?v=8SbvQ-lNgRg.mp4')

print (yt.streams.filter)

stream = yt.streams.get_by_itag(140)

stream.download()
```

This is the output and error messages I get at running terminal:
```
<bound method StreamQuery.filter of [<Stream: itag="136" mime_type="video/mp4" res="720p" fps="30fps" vcodec="avc1.4d401f" progressive="False" type="video">, <Stream: itag="135" mime_type="video/mp4" res="480p" fps="30fps" vcodec="avc1.4d401f" progressive="False" type="video">, <Stream: itag="134" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.4d401e" progressive="False" type="video">, <Stream: itag="133" mime_type="video/mp4" res="240p" fps="30fps" vcodec="avc1.4d4015" progressive="False" type="video">, <Stream: itag="160" mime_type="video/mp4" res="144p" fps="30fps" vcodec="avc1.4d400c" progressive="False" type="video">, <Stream: itag="139" mime_type="audio/mp4" abr="48kbps" acodec="mp4a.40.5" progressive="False" type="audio">, <Stream: itag="140" mime_type="audio/mp4" abr="128kbps" acodec="mp4a.40.2" progressive="False" type="audio">]>

Traceback (most recent call last):
  File "d:\My docs\test\testes.py", line 24, in <module>
    stream.download()
  File "d:\My docs\test\venv\lib\site-packages\pytube\streams.py", line 247, in download
    bytes_remaining = self.filesize
  File "d:\My docs\test\venv\lib\site-packages\pytube\streams.py", line 146, in filesize
    self._filesize = request.filesize(self.url)
  File "d:\My docs\test\venv\lib\site-packages\pytube\request.py", line 200, in filesize
    return int(head(url)["content-length"])
KeyError: 'content-length'
```

Any idea how to fix?

**Comment by NannoSilver** [comment]
Problem disappeared without any action from my side. Seems it was some instability at Youtube servers.
