### ISSUE TITLE
[BUG] HTTPError: HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by pablobots** [pytube/pytube#1376]
I get the error "HTTP Error 401: Unauthorized" when I run the following code:

```
from pytube import YouTube

video_url = "https://www.youtube.com/watch?v=RnpGRzrYBUc"
vid = YouTube(video_url, use_oauth = True, allow_oauth_cache = True)
vid.streams.filter(progressive=True)
```

This is the output:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/python38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/miniconda3/envs/python38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.vscode/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/ubuntu/.vscode/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/ubuntu/.vscode/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/ubuntu/miniconda3/envs/python38/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/ubuntu/miniconda3/envs/python38/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/ubuntu/miniconda3/envs/python38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/git/scraper-dashboard-integration/tests/test_pytube_oauth.py", line 5, in <module>
    vid.streams.filter(progressive=True)
  File "/home/ubuntu/miniconda3/envs/python38/lib/python3.8/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "/home/ubuntu/miniconda3/envs/python38/lib/python3.8/site-packages/pytube/__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "/home/ubuntu/miniconda3/envs/python38/lib/python3.8/site-packages/pytube/__main__.py", line 157, in streaming_data
    if 'streamingData' in self.vid_info:
  File "/home/ubuntu/miniconda3/envs/python38/lib/python3.8/site-packages/pytube/__main__.py", line 246, in vid_info
    innertube_response = innertube.player(self.video_id)
  File "/home/ubuntu/miniconda3/envs/python38/lib/python3.8/site-packages/pytube/innertube.py", line 300, in player
    return self._call_api(endpoint, query, self.base_data)
  File "/home/ubuntu/miniconda3/envs/python38/lib/python3.8/site-packages/pytube/innertube.py", line 242, in _call_api
    response = request._execute_request(
  File "/home/ubuntu/miniconda3/envs/python38/lib/python3.8/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "/home/ubuntu/miniconda3/envs/python38/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/ubuntu/miniconda3/envs/python38/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/ubuntu/miniconda3/envs/python38/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/ubuntu/miniconda3/envs/python38/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/ubuntu/miniconda3/envs/python38/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/ubuntu/miniconda3/envs/python38/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

- Python version: 3.8.5
- Pytube version: 12.1.0
- Command used to install pytube: python -m pip install git+https://github.com/pytube/pytube

**Comment by pablobots** [comment]
I solved it by reinstalling the library in a new environment.
