### ISSUE TITLE
[BUG] Playlist.title does not work sometimes "KeyError: sidebar"

### ISSUE THREAD

**Issue by ghost** [pytube/pytube#1404]
I want to have the title and description of a playlist, sometimes it works and sometimes I get this error back:
```
Traceback (most recent call last):
  File "/home/pickles/Dokumente/VS/ytd/get_playlist_data.py", line 7, in <module>
    "title": pl.title,
  File "/home/pickles/.local/lib/python3.10/site-packages/pytube/contrib/playlist.py", line 351, in title
    return self.sidebar_info[0]['playlistSidebarPrimaryInfoRenderer'][
  File "/home/pickles/.local/lib/python3.10/site-packages/pytube/contrib/playlist.py", line 93, in sidebar_info
    self._sidebar_info = self.initial_data['sidebar'][
KeyError: 'sidebar'
```

my code:
```python
from pytube import Playlist

pl = Playlist(sys.argv[1]) # https://www.youtube.com/playlist?list=PLk7vaXACP25AJif1AdQBVuFIhPwu5DQ1j

print({
    "title": pl.title,
    "description": pl.description
})
```

Most of the time I get json with title and description back but sometimes the error comes.

My system:
```
Python 3.10.6

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

**Comment by Jonikulov** [comment]
I'm also facing the same issue when  I'm downloading *multiple playlists* at once, and here's the error:

```
Traceback (most recent call last):
  File "/mnt/c/Users/javohir/youtube-dlp/youtube-dlp.py", line 81, in <module>
    pl_dict[pl_id].append(yt.title)
  File "/home/javohir/miniconda3/lib/python3.9/site-packages/pytube/contrib/playlist.py", line 351, in title
    return self.sidebar_info[0]['playlistSidebarPrimaryInfoRenderer'][
  File "/home/javohir/miniconda3/lib/python3.9/site-packages/pytube/contrib/playlist.py", line 93, in sidebar_info
    self._sidebar_info = self.initial_data['sidebar'][
KeyError: 'sidebar'
```

**Comment by ghost** [comment]
Oh yes, I forgot to mention that.
If I use a single playlist it works more often (but not always). If i have an array of playlists the error seems to occur more often

**Comment by ghost** [comment]
you can try to use exception handling until it works, but this is not a solution!
This sucks :/
