### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pietrocaporale** [pytube/pytube#1434]
With
Python 3.10.8
pytube 12.1.0
pip install pytube

I've searched RegexMatchError on the web and it appears it had been fixed, but apparently it repeats itself.

This is the code it's just a test:
class MainPage(App):
def build(self):
c = Channel('https://www.youtube.com/@PyMike/videos')
for url in c.video_urls[:3]:
print(url)
MainPage().run()

With this channel "https://www.youtube.com/@PyMike/videos" I keep getting this error:

Traceback (most recent call last):
File "d:_python\yt_manage\main.py", line 36, in
MainPage().run()
File "d:_python\yt_manage\venv\lib\site-packages\kivy\app.py", line 954, in run
self._run_prepare()
File "d:_python\yt_manage\venv\lib\site-packages\kivy\app.py", line 924, in _run_prepare
root = self.build()
File "d:_python\yt_manage\main.py", line 29, in build
c = Channel('https://www.youtube.com/@PyMike/videos')
File "d:_python\yt_manage\venv\lib\site-packages\pytube\contrib\channel.py", line 24, in init
self.channel_uri = extract.channel_name(url)
File "d:_python\yt_manage\venv\lib\site-packages\pytube\extract.py", line 185, in channel_name

raise RegexMatchError(
pytube.exceptions.RegexMatchError: channel_name: could not find match for patterns

With this other channel "https://www.youtube.com/c/ProgrammingKnowledge/videos" instead:

Traceback (most recent call last):
File "d:_python\yt_manage\venv\lib\site-packages\pytube\helpers.py", line 57, in getitem
next_item = next(self.gen)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "d:_python\yt_manage\main.py", line 35, in
MainPage().run()
File "d:_python\yt_manage\venv\lib\site-packages\kivy\app.py", line 954, in run
self._run_prepare()
File "d:_python\yt_manage\venv\lib\site-packages\kivy\app.py", line 924, in _run_prepare
root = self.build()
File "d:_python\yt_manage\main.py", line 22, in build
for url in c.video_urls[:3]:
File "d:_python\yt_manage\venv\lib\site-packages\pytube\helpers.py", line 60, in getitem
raise IndexError
IndexError

Can you help me? I just started learning python.

**Comment by pietrocaporale** [comment]
With 
Python 3.10.8
pytube  12.1.0
pip install pytube

I've searched RegexMatchError on the web and it appears it had been fixed, but apparently it repeats itself.

This is the code it's just a test:
class MainPage(App):
    def build(self):
        c = Channel('https://www.youtube.com/@PyMike/videos')
        for url in c.video_urls[:3]:
            print(url)
MainPage().run()        

===
With this channel "https://www.youtube.com/@PyMike/videos" I keep getting this error:

Traceback (most recent call last):
   File "d:\_python\yt_manage\main.py", line 36, in <module>
     MainPage().run()
   File "d:\_python\yt_manage\venv\lib\site-packages\kivy\app.py", line 954, in run
     self._run_prepare()
   File "d:\_python\yt_manage\venv\lib\site-packages\kivy\app.py", line 924, in _run_prepare
     root = self.build()
   File "d:\_python\yt_manage\main.py", line 29, in build
     c = Channel('https://www.youtube.com/@PyMike/videos')
   File "d:\_python\yt_manage\venv\lib\site-packages\pytube\contrib\channel.py", line 24, in __init__
     self.channel_uri = extract.channel_name(url)
   File "d:\_python\yt_manage\venv\lib\site-packages\pytube\extract.py", line 185, in channel_name

     raise RegexMatchError(
 pytube.exceptions.RegexMatchError: channel_name: could not find match for patterns

===

With this other channel "https://www.youtube.com/c/ProgrammingKnowledge/videos" instead:

Traceback (most recent call last):
   File "d:\_python\yt_manage\venv\lib\site-packages\pytube\helpers.py", line 57, in __getitem__
     next_item = next(self.gen)
 StopIteration

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "d:\_python\yt_manage\main.py", line 35, in <module>
     MainPage().run()
   File "d:\_python\yt_manage\venv\lib\site-packages\kivy\app.py", line 954, in run
     self._run_prepare()
   File "d:\_python\yt_manage\venv\lib\site-packages\kivy\app.py", line 924, in _run_prepare
     root = self.build()
   File "d:\_python\yt_manage\main.py", line 22, in build
     for url in c.video_urls[:3]:
   File "d:\_python\yt_manage\venv\lib\site-packages\pytube\helpers.py", line 60, in __getitem__
     raise IndexError
 IndexError
===

Can you help me? I just started learning python.

**Comment by pietrocaporale** [comment]
With
Python 3.10.8
pytube 12.1.0
pip install pytube

I've searched RegexMatchError on the web and it appears it had been fixed, but apparently it repeats itself.

This is the code it's just a test:
class MainPage(App):
def build(self):
c = Channel('https://www.youtube.com/@PyMike/videos')
for url in c.video_urls[:3]:
print(url)
MainPage().run()

With this channel "https://www.youtube.com/@PyMike/videos" I keep getting this error:

Traceback (most recent call last):
File "d:_python\yt_manage\main.py", line 36, in
MainPage().run()
File "d:_python\yt_manage\venv\lib\site-packages\kivy\app.py", line 954, in run
self._run_prepare()
File "d:_python\yt_manage\venv\lib\site-packages\kivy\app.py", line 924, in _run_prepare
root = self.build()
File "d:_python\yt_manage\main.py", line 29, in build
c = Channel('https://www.youtube.com/@PyMike/videos')
File "d:_python\yt_manage\venv\lib\site-packages\pytube\contrib\channel.py", line 24, in init
self.channel_uri = extract.channel_name(url)
File "d:_python\yt_manage\venv\lib\site-packages\pytube\extract.py", line 185, in channel_name

 raise RegexMatchError(
pytube.exceptions.RegexMatchError: channel_name: could not find match for patterns

With this other channel "https://www.youtube.com/c/ProgrammingKnowledge/videos" instead:

Traceback (most recent call last):
File "d:_python\yt_manage\venv\lib\site-packages\pytube\helpers.py", line 57, in getitem
next_item = next(self.gen)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "d:_python\yt_manage\main.py", line 35, in
MainPage().run()
File "d:_python\yt_manage\venv\lib\site-packages\kivy\app.py", line 954, in run
self._run_prepare()
File "d:_python\yt_manage\venv\lib\site-packages\kivy\app.py", line 924, in _run_prepare
root = self.build()
File "d:_python\yt_manage\main.py", line 22, in build
for url in c.video_urls[:3]:
File "d:_python\yt_manage\venv\lib\site-packages\pytube\helpers.py", line 60, in getitem
raise IndexError
IndexError

Can you help me? I just started learning python.
