### ISSUE TITLE
ImportError: cannot import name YouTube

### ISSUE THREAD

**Issue by donotdonuts** [pytube/pytube#144]
Please help with this:
Traceback (most recent call last):
  File "D:\Dropbox\Self learning\Python 2-23-2017\Crawler\pytube.py", line 1, in <module>
    from pytube import YouTube
  File "D:\Dropbox\Self learning\Python 2-23-2017\Crawler\pytube.py", line 1, in <module>
    from pytube import YouTube
ImportError: cannot import name YouTube

**Comment by nficano** [comment]
did you use pip to install?

**Comment by AngusTsou** [comment]
Have same question!
```
Traceback (most recent call last):
  File "pytube.py", line 1, in <module>
    from pytube import YouTube
  File "/xxxx/pytube.py", line 1, in <module>
    from pytube import YouTube
ImportError: cannot import name 'YouTube'
```
sure have used pip to install pytube

**Comment by donotdonuts** [comment]
Yes, I did use pip. I uninstalled pytube. and reinstalled. And change the file name from pytube.py to Youtubedownload.py then it works..

**Comment by nficano** [comment]
I identified the issue, please try to upgrade via pip and let me know if the issue persists.

**Comment by AlexNeedsAndProvidesHelp** [comment]
doesn't work for me 

> Traceback (most recent call last):
  File "C:/Users/Mengo/Desktop/python/pytube.py", line 1, in <module>
    import pytube
  File "C:/Users/Mengo/Desktop/python\pytube.py", line 2, in <module>
    yt = YouTube("https://www.youtube.com/watch?v=qrO4YZeyl0I")
NameError: name 'YouTube' is not defined

installed via pip

**Comment by AlexNeedsAndProvidesHelp** [comment]
doesnt work for me

> Traceback (most recent call last):
   NameError: name 'YouTube' is not defined

installed via pip
