### ISSUE TITLE
[BUG] Channe() not working when using the new http://youtube.com/@username url

### ISSUE THREAD

**Issue by flyinggoatman** [pytube/pytube#1443]
**Before creating an issue**

Use the Channel() function with the URL set to the new channel ID urls "http://youtube.com/@username"

**Describe the bug**
the code will not work as expected with this type of URL and returns the following error

You see my full code here: [https://github.com/flyinggoatman/YouTube-Link-Extractor/blob/master/QualityYouTube.py](https://github.com/flyinggoatman/YouTube-Link-Extractor/blob/master/QualityYouTube.py) 

The part of the code that is throwing errors is:

`                if re.search ("/channel/", channelURL) or re.search ("@", channelURL) or re.search ("/user/", channelURL) or re.search ("/c/", channelURL):
                    
                    # This code detects if the given URL is a channel. If the check comes back as True then it grabs the data using pytube.
                
                        
                    c = Channel(channelURL)
                    channel_name = c.channel_name
                    
                    channel_id =  c.channel_id
                    channel_id_link = "http://youtube.com/channel/"+channel_id
                    
                    print("Channel Name: "+channel_name)
                    print("Channel ID: "+channel_id) 
                    print("Channel Link: "+channel_id_link)`

**To Reproduce**
Please provide the following information:
- Install Python3
- Install Pytube
- Get a channel URL that contains a "@" symbol
- put that URL into code.

**Expected behavior**
Expected the pytube library to parse the link like it does with /user/, /channel/ and /c/ links.

**Output**
`←[31mTraceback (most recent call last):
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "c:\Users\[redacted]\test\QualityYouTube.py", line 108, in on_message
    channel_name = c.channel_name
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\contrib\channel.py", line 48, in channel_name
    return self.initial_data['metadata']['channelMetadataRenderer']['title']
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\contrib\playlist.py", line 81, in initial_data
    self._initial_data = extract.initial_data(self.html)
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\contrib\channel.py", line 78, in html
    self._html = request.get(self.videos_url)
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\request.py", line 53, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 557, in error
    result = self._call_chain(*args)
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 557, in error
    result = self._call_chain(*args)
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found←[0m
PS C:\Users\[redacted]\test>  c:; cd 'c:\Users\[redacted]\test'; & 'C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\python.exe' 'c:\Users\[redacted]\.vscode\extensions\ms-python.python-2022.20.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '53915' '--' 'c:\Users\[redacted]\test\QualityYouTube.py'
←[30;1m2022-12-30 02:03:22←[0m ←[34;1mINFO    ←[0m ←[35mdiscord.client←[0m logging in using static token
←[30;1m2022-12-30 02:03:23←[0m ←[34;1mINFO    ←[0m ←[35mdiscord.gateway←[0m Shard ID None has connected to Gateway (Session ID: 8003fa54f91ca34bdc56b56901acc63c).
We have logged in as QualityYouTube Bot#2815
Using Discord channel:  pending-channels
The bot has now fully booted up and may be used.
Please be advised this bot only supports one Discord server at a time. Future updates will allow for more than one server to be active at a time.
←[30;1m2022-12-30 02:20:50←[0m ←[31mERROR   ←[0m ←[35mdiscord.client←[0m Ignoring exception in on_message
←[31mTraceback (most recent call last):
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "c:\Users\[redacted]\test\QualityYouTube.py", line 101, in on_message
    c = Channel(channelURL)
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\contrib\channel.py", line 24, in __init__
    self.channel_uri = extract.channel_name(url)
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\extract.py", line 185, in channel_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: channel_name: could not find match for patterns←[0m`

**System information**
Please provide the following information:
- Python 3.10.9
- pip install pytube

**Comment by flyinggoatman** [comment]
I fixed this issue myself.

https://github.com/pytube/pytube/pull/1444

**Comment by NannoSilver** [comment]
@flyinggoatman can you share your solution for this issue?

**Comment by flyinggoatman** [comment]
I changed the code of extract.py

> @flyinggoatman can you share your solution for this issue?

**Comment by flyinggoatman** [comment]
> @flyinggoatman can you share your solution for this issue?

You can see here 

https://github.com/pytube/pytube/pull/1444/commits/84eccec80f589f0f759f4b4d11e03ee0220efca4

**Comment by flyinggoatman** [comment]
> @flyinggoatman can you share your solution for this issue?

However, I'd highly recommend trying this commit instead
https://github.com/pytube/pytube/pull/1424

Just copy the code from here into your extract.py
https://github.com/pytube/pytube/blob/e78b3bb4ce9464b57c03224965dd57ca1b15bec7/pytube/extract.py

**Comment by DennisMinn** [comment]
I am encountering 404 error using https://github.com/pytube/pytube/pull/1424

```
from pytube import Channel
Channel("https://www.youtube.com/@MrBeast")
```

**Output**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dminn/.local/lib/python3.8/site-packages/pytube/contrib/playlist.py", line 315, in __repr__
    return f"{repr(self.video_urls)}"
  File "/home/dminn/.local/lib/python3.8/site-packages/pytube/helpers.py", line 94, in __repr__
    self.generate_all()
  File "/home/dminn/.local/lib/python3.8/site-packages/pytube/helpers.py", line 105, in generate_all
    next_item = next(self.gen)
  File "/home/dminn/.local/lib/python3.8/site-packages/pytube/contrib/playlist.py", line 281, in url_generator
    for page in self._paginate():
  File "/home/dminn/.local/lib/python3.8/site-packages/pytube/contrib/playlist.py", line 118, in _paginate
    json.dumps(extract.initial_data(self.html))
  File "/home/dminn/.local/lib/python3.8/site-packages/pytube/contrib/channel.py", line 78, in html
    self._html = request.get(self.videos_url)
  File "/home/dminn/.local/lib/python3.8/site-packages/pytube/request.py", line 53, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "/home/dminn/.local/lib/python3.8/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

The url should exist
```
import requests
response = requests.head("https://www.youtube.com/@MrBeast")
print(response.status_code)
```

**Output**
303

**Comment by BartoszBiernacki** [comment]
I solved the problem by modifying the original `channel_name` function in `extract.py` with the following:

```
def channel_name(url: str) -> str:
    """Extract the ``channel_name`` or ``channel_id`` from a YouTube url.

    This function supports the following patterns:

    - :samp:`https://youtube.com/c/{channel_name}/*`
    - :samp:`https://youtube.com/channel/{channel_id}/*
    - :samp:`https://youtube.com/u/{channel_name}/*`
    - :samp:`https://youtube.com/user/{channel_id}/*
    - :samp:`https://youtube.com/@{channel_name}/*`

    :param str url:
        A YouTube url containing a channel name.
    :rtype: str
    :returns:
        YouTube channel name.
    """
    patterns = [
        r"(?:\/(c)\/([%\d\w_\-]+)(\/.*)?)",
        r"(?:\/(channel)\/([%\w\d_\-]+)(\/.*)?)",
        r"(?:\/(u)\/([%\d\w_\-]+)(\/.*)?)",
        r"(?:\/(user)\/([%\w\d_\-]+)(\/.*)?)",
        r"(?:\/(@)([%\d\w_\-]+)(\/.*)?)",
    ]
    for pattern in patterns:
        regex = re.compile(pattern)
        function_match = regex.search(url)
        if function_match:
            logger.debug("finished regex search, matched: %s", pattern)
            uri_style = function_match.group(1)
            uri_identifier = function_match.group(2)

            if uri_style != '@':
                return f'/{uri_style}/{uri_identifier}'
            else:
                return f'/{uri_style}{uri_identifier}'

    raise RegexMatchError(
        caller="channel_name", pattern="patterns"
    )
```

I basically added last regex pattern and an if-else statement to return the proper value, because if the url is in the form `https://youtube.com/@{channel_name}/*`, there is no `/` after `@` unlike in other cases.

**Comment by flyinggoatman** [comment]
> I solved the problem by modifying the original `channel_name` function in `extract.py` with the following:
> 
> ```
> def channel_name(url: str) -> str:
>     """Extract the ``channel_name`` or ``channel_id`` from a YouTube url.
> 
>     This function supports the following patterns:
> 
>     - :samp:`https://youtube.com/c/{channel_name}/*`
>     - :samp:`https://youtube.com/channel/{channel_id}/*
>     - :samp:`https://youtube.com/u/{channel_name}/*`
>     - :samp:`https://youtube.com/user/{channel_id}/*
>     - :samp:`https://youtube.com/@{channel_name}/*`
> 
>     :param str url:
>         A YouTube url containing a channel name.
>     :rtype: str
>     :returns:
>         YouTube channel name.
>     """
>     patterns = [
>         r"(?:\/(c)\/([%\d\w_\-]+)(\/.*)?)",
>         r"(?:\/(channel)\/([%\w\d_\-]+)(\/.*)?)",
>         r"(?:\/(u)\/([%\d\w_\-]+)(\/.*)?)",
>         r"(?:\/(user)\/([%\w\d_\-]+)(\/.*)?)",
>         r"(?:\/(@)([%\d\w_\-]+)(\/.*)?)",
>     ]
>     for pattern in patterns:
>         regex = re.compile(pattern)
>         function_match = regex.search(url)
>         if function_match:
>             logger.debug("finished regex search, matched: %s", pattern)
>             uri_style = function_match.group(1)
>             uri_identifier = function_match.group(2)
> 
>             if uri_style != '@':
>                 return f'/{uri_style}/{uri_identifier}'
>             else:
>                 return f'/{uri_style}{uri_identifier}'
> 
>     raise RegexMatchError(
>         caller="channel_name", pattern="patterns"
>     )
> ```
> 
> I basically added last regex pattern and an if-else statement to return the proper value, because if the url is in the form `https://youtube.com/@{channel_name}/*`, there is no `/` after `@` unlike in other cases.

Yeah I also solved the issue. But I didn't have the same issue your have with a slash after the URL.

**Comment by flyinggoatman** [comment]
> I am encountering 404 error using https://github.com/pytube/pytube/pull/1424
> 
> ```
> from pytube import Channel
> Channel("https://www.youtube.com/@MrBeast")
> ```
> 
> **Output**
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/dminn/.local/lib/python3.8/site-packages/pytube/contrib/playlist.py", line 315, in __repr__
>     return f"{repr(self.video_urls)}"
>   File "/home/dminn/.local/lib/python3.8/site-packages/pytube/helpers.py", line 94, in __repr__
>     self.generate_all()
>   File "/home/dminn/.local/lib/python3.8/site-packages/pytube/helpers.py", line 105, in generate_all
>     next_item = next(self.gen)
>   File "/home/dminn/.local/lib/python3.8/site-packages/pytube/contrib/playlist.py", line 281, in url_generator
>     for page in self._paginate():
>   File "/home/dminn/.local/lib/python3.8/site-packages/pytube/contrib/playlist.py", line 118, in _paginate
>     json.dumps(extract.initial_data(self.html))
>   File "/home/dminn/.local/lib/python3.8/site-packages/pytube/contrib/channel.py", line 78, in html
>     self._html = request.get(self.videos_url)
>   File "/home/dminn/.local/lib/python3.8/site-packages/pytube/request.py", line 53, in get
>     response = _execute_request(url, headers=extra_headers, timeout=timeout)
>   File "/home/dminn/.local/lib/python3.8/site-packages/pytube/request.py", line 37, in _execute_request
>     return urlopen(request, timeout=timeout)  # nosec
>   File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/lib/python3.8/urllib/request.py", line 531, in open
>     response = meth(req, response)
>   File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
>     response = self.parent.error(
>   File "/usr/lib/python3.8/urllib/request.py", line 569, in error
>     return self._call_chain(*args)
>   File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 404: Not Found
> 
> The url should exist
> ```
> import requests
> response = requests.head("https://www.youtube.com/@MrBeast")
> print(response.status_code)
> ```
> 
> **Output**
> 303

I can share my code if you want? You need to handle channel handles differently to video links.

**Comment by DennisMinn** [comment]
> > I am encountering 404 error using #1424
> > ```
> > from pytube import Channel
> > Channel("https://www.youtube.com/@MrBeast")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Output**
> > Traceback (most recent call last):
> > File "", line 1, in 
> > File "/home/dminn/.local/lib/python3.8/site-packages/pytube/contrib/playlist.py", line 315, in **repr**
> > return f"{repr(self.video_urls)}"
> > File "/home/dminn/.local/lib/python3.8/site-packages/pytube/helpers.py", line 94, in **repr**
> > self.generate_all()
> > File "/home/dminn/.local/lib/python3.8/site-packages/pytube/helpers.py", line 105, in generate_all
> > next_item = next(self.gen)
> > File "/home/dminn/.local/lib/python3.8/site-packages/pytube/contrib/playlist.py", line 281, in url_generator
> > for page in self._paginate():
> > File "/home/dminn/.local/lib/python3.8/site-packages/pytube/contrib/playlist.py", line 118, in _paginate
> > json.dumps(extract.initial_data(self.html))
> > File "/home/dminn/.local/lib/python3.8/site-packages/pytube/contrib/channel.py", line 78, in html
> > self._html = request.get(self.videos_url)
> > File "/home/dminn/.local/lib/python3.8/site-packages/pytube/request.py", line 53, in get
> > response = _execute_request(url, headers=extra_headers, timeout=timeout)
> > File "/home/dminn/.local/lib/python3.8/site-packages/pytube/request.py", line 37, in _execute_request
> > return urlopen(request, timeout=timeout)  # nosec
> > File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
> > return opener.open(url, data, timeout)
> > File "/usr/lib/python3.8/urllib/request.py", line 531, in open
> > response = meth(req, response)
> > File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
> > response = self.parent.error(
> > File "/usr/lib/python3.8/urllib/request.py", line 569, in error
> > return self._call_chain(*args)
> > File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
> > result = func(*args)
> > File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
> > raise HTTPError(req.full_url, code, msg, hdrs, fp)
> > urllib.error.HTTPError: HTTP Error 404: Not Found
> > The url should exist
> > ```
> > import requests
> > response = requests.head("https://www.youtube.com/@MrBeast")
> > print(response.status_code)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Output**
> > 303
> 
> I can share my code if you want? You need to handle channel handles differently to video links.

Yes please. I am not working directly with video links, rather I'm trying to scrap the first 'n' videos from a channel.

**Comment by flyinggoatman** [comment]
My code only looks at channel data. It's designed to take any channel link and convert it into channel od version of the channel link.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DennisMinn** [comment]
Thank you for the clarification, I no longer need the code. 

https://github.com/pytube/pytube/pull/1422 addresses the new YouTube format and more.

**Comment by mazz3rr** [comment]
@DennisMinn does it? I still get the impression that properties inherited by Channel from Playlist like `view` or `description` don't work. 

```python
>>> channel.description
Traceback (most recent call last):
  File "/snap/pycharm-community/312/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/home/[snip!]/venv/lib/python3.10/site-packages/pytube/contrib/playlist.py", line 356, in description
    return self.sidebar_info[0]['playlistSidebarPrimaryInfoRenderer'][
  File "/home/[snip!]/venv/lib/python3.10/site-packages/pytube/contrib/playlist.py", line 93, in sidebar_info
    self._sidebar_info = self.initial_data['sidebar'][
KeyError: 'sidebar'
```

**Comment by MohamedAliRashad** [comment]
I have this error now
