### ISSUE TITLE
Cannot install (LICENSE not found)

### ISSUE THREAD

**Issue by Serphentas** [pytube/pytube#145]
When using pip to install pytube, I get this:

```
Collecting pytube
  Using cached pytube-6.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5OxiK_/pytube/setup.py", line 11, in <module>
        with open('LICENSE') as readme_file:
    IOError: [Errno 2] No such file or directory: 'LICENSE'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5OxiK_/pytube/
```

I tried to update pip but it doesn't help.

**Comment by nficano** [comment]
I identified the issue, please try to upgrade via pip and let me know if the issue persists.

**Comment by Serphentas** [comment]
It works now, thanks a lot.

**Comment by nficano** [comment]
Thank you for using it!
