### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by karpatxnegen** [pytube/pytube#1459]
**Python 3.10.6
pytube version: 12.1.2
pip3 install pytube**

The Channel object does not contain video urls.

url: https://www.youtube.com/c/ProgrammingKnowledge/videos

source code:
```
from pytube import Channel

c = Channel('https://www.youtube.com/c/ProgrammingKnowledge/videos')
print(c.channel_name)

for url in c.video_urls[:3]:
    print(url)

```
This is the code from the documentation, expected behaviour: 3 urls on the console

Error reporting:
```
Traceback (most recent call last):
  File "/home/karpati/.local/lib/python3.10/site-packages/pytube/helpers.py", line 57, in __getitem__
    next_item = next(self.gen)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/karpati/Dokumentumok/devx2/tmp/pytube-err/test.py", line 7, in <module>
    for url in c.video_urls[:3]:
  File "/home/karpati/.local/lib/python3.10/site-packages/pytube/helpers.py", line 60, in __getitem__
    raise IndexError
IndexError
```

**Comment by khaledadrani** [comment]
Yes this happened to me too +1

**Comment by DarkPenda** [comment]
ошибка, не выводит ссылки канала!

**Comment by wuxizao** [comment]
the same error +1

**Comment by wuxizao** [comment]
"c.video_urls" return array size is 0!
