### ISSUE TITLE
[BUG] Exception while accessing title

### ISSUE THREAD

**Issue by wgong** [pytube/pytube#1461]
**Before creating an issue**

Please confirm that you are on the latest version of pytube by installing from the source.
You can do this by running `python -m pip install git+https://github.com/pytube/pytube`.
Sometimes, the pypi library repository is not up to date, and your issue may have been fixed already!

**Describe the bug**
pytube exe throws the following exception when downloading a video
```
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=TVgQ_tgWMyU.
```

**To Reproduce**
Please provide the following information:
- The video or playlist url that is causing the error.
- The code where the problem is occurring.

**Expected behavior**

**Output**
```
  File "C:\Users\p2p2l\anaconda3\lib\site-packages\pytube\__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p2p2l\Videos\download_youtube.py", line 23, in <module>
    json_data.update({url : yt.title})
  File "C:\Users\p2p2l\anaconda3\lib\site-packages\pytube\__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=TVgQ_tgWMyU. Please file a bug report at https://github.com/pytube/pytube
```

**System information**
Please provide the following information:
- Python version (run `python --version`)
  Python 3.9.13
- Pytube version (run `print(pytube.__version__)` in python)
  '12.1.2'
- Command used to install pytube
  pip install pytube

However, when I ran the following script in jupyter notebook, it works fine
```
from pytube import YouTube 
yt = YouTube("https://youtube.com/watch?v=TVgQ_tgWMyU")
print(f"title={yt.title}")

# title=How to recover from depression
```

**Comment by wgong** [comment]
re-run the pytube exe for the specific video, it no longer throws exception, so issue is not reproducible

**Comment by wgong** [comment]
close
