### ISSUE TITLE
urllib.error.URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>

### ISSUE THREAD

**Issue by larpedd** [pytube/pytube#1463]
Sometimes I tried to get an author from an video url, it gave me an error.
took couple of tries to get the video author's name
```python
import pytube as pyt
from pytube import *

url = "https://www.youtube.com/watch?v=tu9sfzbHL2c"

vid = YouTube(url)

print(vid.author)
```

**Expected behavior:**
*Shows video author*

**Output**
```python
Traceback (most recent call last):
  File "G:\Program Files\Python38\lib\urllib\request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "G:\Program Files\Python38\lib\http\client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "G:\Program Files\Python38\lib\http\client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "G:\Program Files\Python38\lib\http\client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "G:\Program Files\Python38\lib\http\client.py", line 1011, in _send_output
    self.send(msg)
  File "G:\Program Files\Python38\lib\http\client.py", line 951, in send
    self.connect()
  File "G:\Program Files\Python38\lib\http\client.py", line 1425, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "G:\Program Files\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "G:\Program Files\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "G:\Program Files\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\yt-vidDownload\downloader.py", line 8, in <module>
    print(vid.author)
  File "G:\Program Files\Python38\lib\site-packages\pytube\__main__.py", line 400, in author
    self._author = self.vid_info.get("videoDetails", {}).get(
  File "G:\Program Files\Python38\lib\site-packages\pytube\__main__.py", line 246, in vid_info
    innertube_response = innertube.player(self.video_id)
  File "G:\Program Files\Python38\lib\site-packages\pytube\innertube.py", line 300, in player
    return self._call_api(endpoint, query, self.base_data)
  File "G:\Program Files\Python38\lib\site-packages\pytube\innertube.py", line 242, in _call_api
    response = request._execute_request(
  File "G:\Program Files\Python38\lib\site-packages\pytube\request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "G:\Program Files\Python38\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "G:\Program Files\Python38\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "G:\Program Files\Python38\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "G:\Program Files\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "G:\Program Files\Python38\lib\urllib\request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "G:\Program Files\Python38\lib\urllib\request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>
```

**System information**
Using Python 3.8.16
Pytube Version:
``` python
>>> import pytube
>>> print(pytube.__version__)
12.1.2
```
installed with github `python -m pip install git+https://github.com/pytube/pytube`

**Comment by ThienVie** [comment]
I reinstalled Python in my pc and find this file:

`Install Certificates.command`
```
#!/bin/sh

/Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12 << "EOF"

# install_certifi.py
#
# sample script to install or update a set of default Root Certificates
# for the ssl module.  Uses the certificates provided by the certifi package:
#       https://pypi.org/project/certifi/

import os
import os.path
import ssl
import stat
import subprocess
import sys

STAT_0o775 = ( stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR
             | stat.S_IRGRP | stat.S_IWGRP | stat.S_IXGRP
             | stat.S_IROTH |                stat.S_IXOTH )

def main():
    openssl_dir, openssl_cafile = os.path.split(
        ssl.get_default_verify_paths().openssl_cafile)

    print(" -- pip install --upgrade certifi")
    subprocess.check_call([sys.executable,
        "-E", "-s", "-m", "pip", "install", "--upgrade", "certifi"])

    import certifi

    # change working directory to the default SSL directory
    os.chdir(openssl_dir)
    relpath_to_certifi_cafile = os.path.relpath(certifi.where())
    print(" -- removing any existing file or link")
    try:
        os.remove(openssl_cafile)
    except FileNotFoundError:
        pass
    print(" -- creating symlink to certifi certificate bundle")
    os.symlink(relpath_to_certifi_cafile, openssl_cafile)
    print(" -- setting permissions")
    os.chmod(openssl_cafile, STAT_0o775)
    print(" -- update complete")

if __name__ == '__main__':
    main()
EOF
```

I know this code is not for windows, but I hope this code gives some hints to solve your problem.
