### ISSUE TITLE
Subtiters [BUG]

### ISSUE THREAD

**Issue by aglazkov** [pytube/pytube#1477]
**Describe the bug**
Can't get subtiters

**To Reproduce**
Trying do like in docs: https://pytube.io/en/latest/user/captions.html

```
from pytube import YouTube
yt = YouTube('https://www.youtube.com/watch?v=atPNphv-NEI')
yt.title
yt.thumbnail_url
yt.captions
caption = yt.captions.get_by_language_code("en-GB")
caption.generate_srt_captions()

```
**Output**
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_14544\3973134316.py in <module>
----> 1 caption.generate_srt_captions()

c:\Users\1\anaconda3\lib\site-packages\pytube\captions.py in generate_srt_captions(self)
     58         recompiles them into the "SubRip Subtitle" format.
     59         """
---> 60         return self.xml_caption_to_srt(self.xml_captions)
     61 
     62     @staticmethod

c:\Users\1\anaconda3\lib\site-packages\pytube\captions.py in xml_caption_to_srt(self, xml_captions)
     90             except KeyError:
     91                 duration = 0.0
---> 92             start = float(child.attrib["start"])
     93             end = start + duration
     94             sequence_number = i + 1  # convert from 0-indexed to 1.
```

**Comment by to-sora** [comment]
### I also have the same issues 
```
Traceback (most recent call last):
  File "D:\Program_self\youtubedownload\sub.py", line 33, in <module>
    file_object.write(t.generate_srt_captions())
  File "C:\Users\User\miniconda3\envs\test01\lib\site-packages\pytube\captions.py", line 60, in generate_srt_captions
    return self.xml_caption_to_srt(self.xml_captions)
  File "C:\Users\User\miniconda3\envs\test01\lib\site-packages\pytube\captions.py", line 92, in xml_caption_to_srt
    start = float(child.attrib["start"])
KeyError: 'start'
```

**Comment by dvarrazzo** [comment]
Probably the format of the subtitles xml have changed.

The data looks like:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<timedtext format="3">
  <body>
    <p t="102019" d="4088">I open my eyes and I see nothing.</p>
    <p t="110027" d="3587">I only remember there was some accident.</p>
    ...
```

In order to download subtitles [from this video](https://www.youtube.com/watch?v=PECz8C7m_Yo), I made the following changes on pytube 12.1.3:

```diff
--- captions.py.orig	2023-04-01 03:12:55.176218471 +0200
+++ captions.py	2023-04-01 03:12:59.320187087 +0200
@@ -82,14 +82,14 @@
         """
         segments = []
         root = ElementTree.fromstring(xml_captions)
-        for i, child in enumerate(list(root)):
+        for i, child in enumerate(list(root[0])):
             text = child.text or ""
             caption = unescape(text.replace("\n", " ").replace("  ", " "),)
             try:
-                duration = float(child.attrib["dur"])
+                duration = float(child.attrib["d"]) / 1000.0
             except KeyError:
                 duration = 0.0
-            start = float(child.attrib["start"])
+            start = float(child.attrib["t"]) / 1000.0
             end = start + duration
             sequence_number = i + 1  # convert from 0-indexed to 1.
             line = "{seq}\n{start} --> {end}\n{text}\n".format(
```

it's probably easy to fix the function to account for both the previous format and the current one.

**Comment by gold3bear** [comment]
`for i, child in enumerate(list(root)[1])` is **list(root)[1]**, but not `list(root[0])`

**Comment by 1a2a34v** [comment]
why no PR yet?

**Comment by MYusufY** [comment]
@1a2a34v Hi! You can check my PR:
* #1959
You can test it before merge by:

* Uninstalling original one:
`python3 -m pip uninstall pytube`
* Installing updated one:
`python3 -m pip install git+https://github.com/MYusufY/pytube`

Thank you!
