### ISSUE TITLE
Exception while accessing title of https://youtube.com/watch?v=icOOqUYh9rY.

### ISSUE THREAD

**Issue by saiyam-sandhir** [pytube/pytube#1479]
**Describe the bug**
"pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=icOOqUYh9rY." This error is coming when I iterated through a playlist for testing my project

The error is only coming for the last video of the playlist: https://github.com/pytube/pytube

**To Reproduce**
Please provide the following information:
- [The playlist url that is causing the error.](https://www.youtube.com/playlist?list=PLu39i8zSL9Zv1tvp_wucI6mXGUl28jjoj)
-`
for i, video in enumerate(self.yt.videos):
     self.videos_listbox.insert(i, video.title)
`

**Expected behavior**
expectation was to not show an error and insert the title of the last video along with all other videos in tk.Listbox object

**Output**
`
Traceback (most recent call last):
  File "C:\Users\pc\anaconda3\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\pc\anaconda3\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 549, in _clicked
    self._command()
  File "c:\Users\pc\Desktop\Tkinter-YouTube_Downloader\main.py", line 29, in <lambda>
    load_button = ctk.CTkButton(load_video_frame, text="", image=load_button_img, anchor=tk.CENTER, width=40, corner_radius=10, bg_color = "#242424", fg_color="#242424", hover_color="#EAEAEA", command=lambda: [self.load_youtube(url_entry.get())])
  File "c:\Users\pc\Desktop\Tkinter-YouTube_Downloader\main.py", line 96, in load_youtube
    self.videos_listbox.insert(i, video.title)
  File "C:\Users\pc\anaconda3\lib\site-packages\pytube\__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=icOOqUYh9rY. Please file a bug report at https://github.com/pytube/pytube
`

**System information**
Please provide the following information:
- Python version: 3.8.10
- Pytube version: 12.1.2
- `pip install pytube`

**Comment by saiyam-sandhir** [comment]
It seems like I have found the problem, during the process of getting all the video titles and inserting them if the user clicks on the window or tries to get responses for it, it interrupts the loop, leading to that problem. It's more like a tkinter problem, should I use threads for this purpose, what do you think?

also am I right?

**Comment by cstuart1310** [comment]
> It seems like I have found the problem, during the process of getting all the video titles and inserting them if the user clicks on the window or tries to get responses for it, it interrupts the loop, leading to that problem. It's more like a tkinter problem, should I use threads for this purpose, what do you think?
> 
> also am I right?

I've got a youtube auto-downloader that's command-line only with no tkinter at all and have the same issue. I'm guessing it's specifically video.title? Seems random which videos it doesn't like though

**Comment by saiyam-sandhir** [comment]
> > It seems like I have found the problem, during the process of getting all the video titles and inserting them if the user clicks on the window or tries to get responses for it, it interrupts the loop, leading to that problem. It's more like a tkinter problem, should I use threads for this purpose, what do you think?
> > also am I right?
> 
> I've got a youtube auto-downloader that's command-line only with no tkinter at all and have the same issue. I'm guessing it's specifically video.title? Seems random which videos it doesn't like though

yes, again I noticed that but re-running helped me,

I used try and except to check for that particular pytube exception and then asked python to run that part of the script, inside "try", again

**Comment by KS-HTK** [comment]
Same Issue here. Worked fine some month ago. But after updating pytube and trying to fetch titles for a 200 video playlist I had the very same issue. Used a `try` around my fetching of the title prior to downloading. After downloading the audio track it fetched the title without this issue on every video. So it might be a problem, if only the info is fetched and non of the media?

**Comment by KS-HTK** [comment]
So here is a fun little test:
```python
# Pytube test script
from pytube import YouTube, Playlist

# fetch yt playlist
# TODO: Add you're playlist link
ytp = Playlist('https://www.youtube.com/playlist?list=')

# fetch playlist info
print(ytp.title)

# for each video in playlist fetch info and print it
exception_count = 0
for index, video_url in enumerate(ytp.video_urls):
    yt = YouTube(video_url)
    if not index % 10:
        print(index, exception_count)
    try:
        title = yt.title
    except:
        exception_count += 1
        try:
            stream = yt.streams.first()
        except:
            print('issues accessing stream', index)
        try:
            title = yt.title
        except:
            print('error - skipping', index)

print('done, fetched info for %d videos, encountered %d exceptions' % (index, exception_count))
```

The code will try fetching a title for each video, on failure it will try getting the stream and fetching the title again.
In 207 videos it failed to get the title on first attempt 13 times but never failed in the second attempt…
So it can get the title after fetching a stream? Seems to be a good all be it annoying workaround.

**Comment by mkandan** [comment]
Very weird, but thanks @KS-HTK for the update. This worked. I went from
```py
yt = YouTube(yt_url)

yt_title = yt.title
yt_description = yt.description

yt_stream = yt.streams.filter(only_audio=True).first()
yt_stream.download(output_path=path_to_tmp_folder)
```
to
```py
yt = YouTube(yt_url)
yt_stream = yt.streams.filter(only_audio=True).first()
yt_stream.download(output_path=path_to_tmp_folder)

yt_title = yt.title
yt_description = yt.description
```
and that fixed it haha
