### ISSUE TITLE
line 411, in get_throttling_plan     transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)[BUG]

### ISSUE THREAD

**Issue by marioonor123** [pytube/pytube#1509]
**Before creating an issue**

Please confirm that you are on the latest version of pytube by installing from the source.
You can do this by running `python -m pip install git+https://github.com/pytube/pytube`.
Sometimes, the pypi library repository is not up to date, and your issue may have been fixed already!

**Describe the bug**

**To Reproduce**
Please provide the following information:
- The video or playlist url that is causing the error.
- The code where the problem is occurring.

**Expected behavior**

**Output**
If pytube raises an exception, please provide the full traceback for the exception.

**System information**
Please provide the following information:
- Python version (run `python --version`)
- Pytube version (run `print(pytube.__version__)` in python)
- Command used to install pytube

**Comment by marioonor123** [comment]
from turtle import Screen, Turtle
from pytube import YouTube
import tkinter

screen = Screen()
label = Turtle()
screen.setup(width=500, height=250)
label.hideturtle()
screen.title("Youtube Downloader")


def download(link_again, progress_func=None, complete_func=None, my_proxies=None):
    link = "'" + link_again + "'"
    yt = YouTube(link, on_progress_callback=progress_func, on_complete_callback=complete_func, proxies=my_proxies,
        use_oauth=False,
        allow_oauth_cache=True)
    label.write("Downloading! Please wait...", align="center")
    yt.streams.get_highest_resolution().download()


should_continue = True
while should_continue:
    enter_link = screen.textinput(title="", prompt="Enter your link here!" + "                                                                                   ")
    download(enter_link)
    label.clear()
    tkinter.messagebox.askokcancel("", message="Download Successfully! Paste url to download again.")

screen.exitonclick()


This was functioning before until when I downloaded the last time video on youtube, I already encountered these issues I submitted.

**Comment by DTRIX05** [comment]
i have the same it worked before and since yesterday it doesnt work anymore

**Comment by chickiyeah** [comment]
https://github.com/pytube/pytube/issues/1498

**Comment by CarlosLopezMolina** [comment]
The same error here. I have just updated to the latest version in github with  `python -m pip install git+https://github.com/pytube/pytube`, and still the same error.
```
Traceback (most recent call last):
  File "python-youtube-lr.py", line 7, in <module>
    stream = video_obj.streams.get_lowest_resolution()
  File "/home/clm/.local/lib/python3.8/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "/home/clm/.local/lib/python3.8/site-packages/pytube/__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/home/clm/.local/lib/python3.8/site-packages/pytube/extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "/home/clm/.local/lib/python3.8/site-packages/pytube/cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "/home/clm/.local/lib/python3.8/site-packages/pytube/cipher.py", line 411, in get_throttling_plan
    transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
AttributeError: 'NoneType' object has no attribute 'span'

```

**Comment by CarlosLopezMolina** [comment]
A PR with a fix has been written here: https://github.com/pytube/pytube/pull/1516/commits/d6623d8ce39c777f22a5638307c9fceedc01b047

I tried that fix and worked for me.

**Comment by cluster-coder** [comment]
> A PR with a fix has been written here: [d6623d8](https://github.com/pytube/pytube/commit/d6623d8ce39c777f22a5638307c9fceedc01b047)
> 
> I tried that fix and worked for me.

You are a savior
