### ISSUE TITLE
[BUG] Pytube won't download videos

### ISSUE THREAD

**Issue by BLINMATIC** [pytube/pytube#1517]
# Description Of The Bug
Whenever you put a link into pytube cli such as `pytube https://www.youtube.com/watch?v=gmb1CWY9erQ` it does not download the video. It was working until the 17th of march and suddenly at midnight (UTC+3), it stopped working. So it might be an issue with youtube but all the online video downloaders such as ytmp3.cc works normally.
# How To Reproduce
This works with any video, playlist, or album. it works by entering `pytube <url>` into the command line.
# Expected Behaviour
It is expected that the cli will start downloading the videos
# Output
```Loading video...
Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python38-32\Scripts\pytube.exe\__main__.py", line 7, in <module>
  File "c:\program files (x86)\python38-32\lib\site-packages\pytube\cli.py", line 53, in main
    _perform_args_on_youtube(youtube, args)
  File "c:\program files (x86)\python38-32\lib\site-packages\pytube\cli.py", line 60, in _perform_args_on_youtube
    download_highest_resolution_progressive(
  File "c:\program files (x86)\python38-32\lib\site-packages\pytube\cli.py", line 474, in download_highest_resolution_progressive
    stream = youtube.streams.get_highest_resolution()
  File "c:\program files (x86)\python38-32\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "c:\program files (x86)\python38-32\lib\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "c:\program files (x86)\python38-32\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "c:\program files (x86)\python38-32\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "c:\program files (x86)\python38-32\lib\site-packages\pytube\cipher.py", line 411, in get_throttling_plan
    transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
AttributeError: 'NoneType' object has no attribute 'span'
```
# System Information
Python Version: 3.8.8 (32-bit)
Pytube Version: 12.1.2
Install Command: `python -m pip install git+https://github.com/pytube/pytube`

**Comment by chickiyeah** [comment]
See this issue There's already a solution.
https://github.com/pytube/pytube/issues/1498

**Comment by AnonymousTechDeveloper** [comment]
In Cipher.py, line 411:
transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
Change it to:
transform_plan_raw = js

**Comment by ufuktasdan** [comment]
Same error:

`
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[~\AppData\Local\Temp\ipykernel_22252\239718280.py](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/ufuk/Documents/chatgpt%20kullan%C4%B1m/~/AppData/Local/Temp/ipykernel_22252/239718280.py) in 
     42 format = "mp3"
     43 
---> 44 download_media(youtube_links, format)

[~\AppData\Local\Temp\ipykernel_22252\239718280.py](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/ufuk/Documents/chatgpt%20kullan%C4%B1m/~/AppData/Local/Temp/ipykernel_22252/239718280.py) in download_media(links, format)
     20         if format == 'mp3':
     21             # Get the highest-quality audio stream
---> 22             stream = yt.streams.order_by('abr').last()
     23             # stream = yt.streams.filter(only_audio=True).order_by('abr').last()
     24             if stream is None:

[c:\Users\ufuk\anaconda3\lib\site-packages\pytube\__main__.py](file:///C:/Users/ufuk/anaconda3/lib/site-packages/pytube/__main__.py) in streams(self)
    294         """
    295         self.check_availability()
--> 296         return StreamQuery(self.fmt_streams)
    297 
    298     @property

[c:\Users\ufuk\anaconda3\lib\site-packages\pytube\__main__.py](file:///C:/Users/ufuk/anaconda3/lib/site-packages/pytube/__main__.py) in fmt_streams(self)
    179         # https://github.com/pytube/pytube/issues/1054
    180         try:
--> 181             extract.apply_signature(stream_manifest, self.vid_info, self.js)
...
--> 411     transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
    412 
    413     # Steps are either c[x](c[y]) or c[x](c[y],c[z])

AttributeError: 'NoneType' object has no attribute 'span'`

**Comment by ufuktasdan** [comment]
> In Cipher.py, line 411: transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1) Change it to: transform_plan_raw = js

the same error:

AttributeError: 'NoneType' object has no attribute 'span'
