### ISSUE TITLE
[BUG] Colab ==> 'NoneType' object has no attribute 'span'

### ISSUE THREAD

**Issue by SEYED1424** [pytube/pytube#1519]
Hi guys.
As you all know, we had a bug these recent days. The normal answer is here #1498 , but what about the colab version? I changed the code from [/usr/local/lib/python3.9/dist-packages/pytube/cipher.py] but nothing has happened! 
What do you think I should do? Please help. 🙏🏻
The colab project is [here](https://colab.research.google.com/drive/1mfYhIOgtUO5spOVUrIH-rZsSxGK7N_QW?usp=sharing)

**Comment by i-LUDUS** [comment]
Same experience ...

**Comment by PedroPampolini** [comment]
Same thing happened to me

**Comment by hreffert** [comment]
!pip install --upgrade pytube
from pytube import YouTube
import re

with open('/usr/local/lib/python3.9/dist-packages/pytube/cipher.py', 'r') as file:
    filedata = file.read()

filedata = re.sub(r'transform_plan_raw = find_object_from_startpoint\(raw_code, match.span\(\)\[1\] - 1\)',
                  r'transform_plan_raw = js',
                  filedata)

with open('/usr/local/lib/python3.9/dist-packages/pytube/cipher.py', 'w') as file:
    file.write(filedata)

**Comment by SEYED1424** [comment]
> 

Thanks a lot for your help, but unfortunately it doesn't work!

**Comment by SEYED1424** [comment]
> !pip install --upgrade pytube from pytube import YouTube import re
> 
> with open('/usr/local/lib/python3.9/dist-packages/pytube/cipher.py', 'r') as file: filedata = file.read()
> 
> filedata = re.sub(r'transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)', r'transform_plan_raw = js', filedata)
> 
> with open('/usr/local/lib/python3.9/dist-packages/pytube/cipher.py', 'w') as file: file.write(filedata)


Thanks a lot for your help, but unfortunately it doesn't work!

**Comment by kinni** [comment]
Try to use the following code block:

```
import re

with open('/usr/local/lib/python3.9/dist-packages/pytube/cipher.py', 'r') as file:
  filedata = file.read()

  filedata = filedata.replace('transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)', 'transform_plan_raw = js')

with open('/usr/local/lib/python3.9/dist-packages/pytube/cipher.py', 'w') as file:
  file.write(filedata)

filedata
```

The above code doesn't work because of the `re` regular expression, since it will treat those `(,.[]` characters as special token and thus you will never get a match.

P.S. suggest you restart the runtime if you face any questions. Thanks.

**Comment by SEYED1424** [comment]
Thanks, but even when I replace the code, I face this error 
![Screenshot (293)](https://user-images.githubusercontent.com/99642593/226282730-43095143-5539-4173-bcef-fee0974f8ec8.png)

**Comment by florian-kalisch** [comment]
@SEYED1424 I had the same problem, but as @kinni mentioned, it works after restarting the runtime. Try executing: exit()

**Comment by SEYED1424** [comment]
Oh! Thanks for your hint. @florian-kalisch & @kinni

**Comment by Zhenya-Barannik** [comment]
Thank you @kinni, you solution did work. I changed it in my case because i use conda and my python packages were located in different place. I found my `cipher.py` here: 
`PATH_TO_CIPHER = "/Applications/anaconda3/pkgs/pytube-12.1.2-pyhd8ed1ab_0/site-packages/pytube/cipher.py" `
I am on OS X and this is base conda environment by the way.

I replaced your destinations with this destination. The code given is the one time fix of the source code, you need to execute it only once and outside of your pytube script. 

```
import re

with open('PATH_TO_CIPHER', 'r') as file:
  filedata = file.read()

  filedata = filedata.replace('transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)', 'transform_plan_raw = js')

with open('PATH_TO_CIPHER', 'w') as file:
  file.write(filedata)

filedata
```

**Comment by willotzze** [comment]
help me please

Traceback (most recent call last):
  File "C:/Users/Админ/OneDrive/Рабочий стол/pars/ppp.py", line 3, in <module>
    with open('C:\Python38\Lib\site-packages\pytube', 'r') as file:
PermissionError: [Errno 13] Permission denied: 'C:\\Python38\\Lib\\site-packages\\pytube'

corrected:
made by hand
thanks everything worked

**Comment by nguyenquocthao** [comment]
You can find cipher.py file from error log

 File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/cipher.py", line 411, in get_throttling_plan
    transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)

Replacing `transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)` by `transform_plan_raw = js` works

**Comment by cjdunn** [comment]
@nguyenquocthao this was super helpful, thank you!! I tried running the scripts above and was having issues, until I actually read what the code was doing. I realized the fix is simply a find/replace in the file `cipher.py` which is part of `pytube`, within site packages (in my case in a virtual env). 

For anyone else following along, open `cipher.py` and simply find: 

`transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)` 

replace with: 

`transform_plan_raw = js`

for me, this was on **line 411** of `cipher.py`. Thanks everyone for the quick fix :  )

**Comment by i-LUDUS** [comment]
Thanks for the support!  I updated my code in Google Colab and this works :

> 
> !pip install pytube
>  
> import re
> with open('/usr/local/lib/python3.9/dist-packages/pytube/cipher.py', 'r') as file:
>   filedata = file.read()
>   filedata = filedata.replace('transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)', 'transform_plan_raw = js')
> with open('/usr/local/lib/python3.9/dist-packages/pytube/cipher.py', 'w') as file:
>   file.write(filedata)
> 
> exit(0)

**Comment by HonzaKubita** [comment]
Thanks @kinni your solution worked! (I needed to modify the path for it to work for me)
For anyone on windows with python 3.11 this should work:
```py
import re
from pathlib import Path

path = f"{Path.home()}\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pytube\\cipher.py"

with open(path, 'r') as file:
  filedata = file.read()

  filedata = filedata.replace('transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)', 'transform_plan_raw = js')

with open(path, 'w') as file:
  file.write(filedata)
```

**Comment by amirh-web** [comment]
this bug is fixed?
