### ISSUE TITLE
problem with timeout

### ISSUE THREAD

**Issue by alochym01** [pytube/pytube#152]
Hi
how long does the pytube request to youtube then wait to get response from youtube

from my testing, it took very fast timeout, about < 1s

```
 Traceback (most recent call last):
   File "youtube_feed.py", line 167, in <module>
     yt = YouTube(yt_videoid)
   File "/home/hadn/python3/lib64/python3.5/site-packages/pytube/api.py", line 100, in __init__
     self.from_url(url)
   File "/home/hadn/python3/lib64/python3.5/site-packages/pytube/api.py", line 192, in from_url
     video_data = self.get_video_data()
   File "/home/hadn/python3/lib64/python3.5/site-packages/pytube/api.py", line 292, in get_video_data
     response = urlopen(self.url)
   File "/usr/lib64/python3.5/urllib/request.py", line 163, in urlopen
     return opener.open(url, data, timeout)
   File "/usr/lib64/python3.5/urllib/request.py", line 457, in open
     req.timeout = timeout
 AttributeError: 'int' object has no attribute 'timeout'

```

**Comment by nficano** [comment]
@alochym01 can you please let me know if this is still an issue in the latest release?

**Comment by nficano** [comment]
closing until confirmation this is still an issue.
