### ISSUE TITLE
[BUG]Traceback (most recent call last):

### ISSUE THREAD

**Issue by fidoaddon** [pytube/pytube#1526]
Traceback (most recent call last):
  File "C:\Python\Python310\lib\site-packages\pytube\__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\okru\oblivitube.py", line 35, in <module>
    Youtube_Playlist_Grab_Duration(url)
  File "C:\okru\oblivitube.py", line 18, in Youtube_Playlist_Grab_Duration
    if 'elete' in video.title:
  File "C:\Python\Python310\lib\site-packages\pytube\__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=noJzLBnVxzY. Please file a bug report at https://github.com/pytube/pytube

from urllib.request import urlopen, Request
import re
import os
from pytube import Playlist

url = 'https://www.youtube.com/playlist?list=PLX9_I-EOJPdFuOjcI2zkmTck55homHEBE'
fanart = ''

folder = '.'
new = f'{folder}/new.xml'
print(new)

def Youtube_Playlist_Grab_Duration(url):
    playlist = Playlist(url)

    for video in playlist.videos:
        if 'elete' in video.title:
            continue
        elif 'private Vid' in video.title:
            continue
        else:
            if not os.path.exists(new):
                print_text_file_create = open(new, "w")
            else:
                print_text_file_create = open(new, "a")
            print_text_file_create.write('<item>\n')
            print_text_file_create.write('<title>[COLORred]' + str(video.title) + '[/COLOR]</title>\n')
            print_text_file_create.write('<link>' + str(video.watch_url) + '</link>\n')
            print_text_file_create.write('<thumbnail>' + str(video.thumbnail_url) + '</thumbnail>\n')
            print_text_file_create.write('<fanart>' + fanart + '</fanart>\n')
            print_text_file_create.write('</item>\n\n')

Youtube_Playlist_Grab_Duration(url)

**Comment by fidoaddon** [comment]
the script is supposed to just read the title of the movie and place it in the tag <title></title>
Then get the url and post it in <link></link> 

So finished print looks like this

<item>
<title>[COLORred]She Had to Choose (1934) Ralph Cedar[/COLOR]</title>
<link>https://youtube.com/watch?v=noJzLBnVxzY</link>
<thumbnail>https://i.ytimg.com/vi/noJzLBnVxzY/sddefault.jpg</thumbnail>
<fanart></fanart>
</item>

It starts working, print to file new.xml but after first few links it stops writing and 
errors

**Comment by fidoaddon** [comment]
I have worked out what the problem is, the playlist displayed is not the actual playlist, it is the playlist minus the "Unavailable videos are hidden". Because the next video is in the list of Unavailable videos are hidden or set to private the script doesnt know what to do and errors.
Does anyone know how to fix so it ignores private and hidden videos

**Comment by Breaderick** [comment]
@fidoaddon pytube has its own exceptions class, try to implement a try catch with the VideoUnavailable class and continue from there. if the error isn't classified as a VideoUnavailable error, you can try a general PytubeError catch.
hope this helps!

**Comment by olbermann** [comment]
Again the key error is the same as in #1493, #1495
