### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Mohammed6234** [pytube/pytube#1531]
**Describe the bug**
The bug is that the title of the youtube video can't be found using the link

**To Reproduce**
`for url in videos:
    try:
        loader = YoutubeLoader.from_youtube_channel(url, add_video_info=True)
        result = loader.load()
        texts.extend(text_splitter.split_documents(result))
    except:
        traceback.print_exc()`
The error is thrown on the following videos:
https://youtube.com/watch?v=7sLXhCDRaV8
https://youtube.com/watch?v=JPCJEtMXOu0
    

**Expected behavior**
It should load the video and allow me to get the transcript and split the text. It works for some videos, but doesn't work for others

**Output**
Traceback (most recent call last):
  File "c:\Users\sohai\Desktop\App\venv\Lib\site-packages\pytube\__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\sohai\Desktop\App\whisper.py", line 59, in <module>
    result = loader.load()
             ^^^^^^^^^^^^^
  File "c:\Users\sohai\Desktop\App\venv\Lib\site-packages\langchain\document_loaders\youtube.py", line 129, in load
    video_info = self._get_video_info()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sohai\Desktop\App\venv\Lib\site-packages\langchain\document_loaders\youtube.py", line 166, in _get_video_info
    "title": yt.title,
             ^^^^^^^^
  File "c:\Users\sohai\Desktop\App\venv\Lib\site-packages\pytube\__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=JPCJEtMXOu0. Please file a bug report at https://github.com/pytube/pytube


**System information**
All up to date, using the latest version of pytube via github

**Comment by thedtvn** [comment]
same on get the title of video

PytubeError: Exception while accessing title of https://youtube.com/watch?v=OJGfoS7Bso4. Please file a bug report at https://github.com/pytube/pytube
