### ISSUE TITLE
[BUG] - Exception while accessing title

### ISSUE THREAD

**Issue by eagledeath85** [pytube/pytube#1545]
**Before creating an issue**

Please confirm that you are on the latest version of pytube by installing from the source.
You can do this by running `python -m pip install git+https://github.com/pytube/pytube`.
Sometimes, the pypi library repository is not up to date, and your issue may have been fixed already!

**Describe the bug**
When trying to access the title of a specific video, the error "Exception while accessing title" raises up.
The error doesn't raise up with another video.

**To Reproduce**
- Use the url  "https://www.youtube.com/watch?v=d2-HtllN0NA" for this test
- Create a YouTube object with this url
- Try to retrieve the title of the video

**Expected behavior**
The title is correctly retrieved

**Output**
Traceback (most recent call last):
  File "/home/administrateur/PycharmProjects/youtube_downloader/venv/lib/python3.10/site-packages/pytube/__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/administrateur/PycharmProjects/youtube_downloader/main.py", line 13, in <module>
    print(f"Le titre de la video est : {youtube_video.title}")
  File "/home/administrateur/PycharmProjects/youtube_downloader/venv/lib/python3.10/site-packages/pytube/__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=d2-HtllN0NA. Please file a bug report at https://github.com/pytube/pytube

**System information**
Please provide the following information:
- Python version: 3.10.6 
- Pytube version: 12.1.3
- Command used to install pytube: pip install git+https://github.com/pytube/pytube

**Comment by LaniakeaArmstrong** [comment]
I'm still a newbie to GitHub Issues, so please correct me if I'm wrong or tell me what I could do better.
Just 5 minutes ago, I had both the expected behavior and the error output.

When I pressed F5 in Visual Studio Code, the program ran normally and I got the expected behavior; but when I right-clicked the program and chose the option "Run Python File in Terminal": it returned the error that you mentioned @eagledeath85 

Yes, I updated Pytube to the most up-to-date version, which is 12.1.3.
To update I used the command: "pip install pytube", then I closed VS Code and reopened it: the error kept appearing in the same way as I have described it a paragraph before.

The Python version I use inside VS Code is: 3.10.10

I didn't know what the "Ejecutar archivo de Python en el terminal" command was called in English; so, i changed the language of VS Code, this asks to restart it, so i did.

Then, I tried running the program with F5, as well as with right click and "Run Python File in Terminal": neither of them returned any error.
And yes: I did the "To Reproduce" section, just like this (the code is in Spanish):

"URL = input("\nIngrese su URL: ")

yt = YouTube(URL)
titulo_contenido = yt.title
print(titulo_contenido)"

**Comment by Untit1ed** [comment]
Looks like the prop works fine in the debugger after a short delay, but fails periodically when other props aren't being called.

**Comment by datavisual1919** [comment]
I'm having the same issue, only about 10% of the requests are going through.

**Comment by TorfromNor** [comment]
im having the same issue only at random do request works

**Comment by MylonasDimitris** [comment]
Same issue, so no title at my outputs. Is there any way to bypsas this issue or we have to wait for a fix?

**Comment by maen007** [comment]
Same issue but each time.

**Comment by Szymon-Olstowski** [comment]
Też ma taki sam problem, że niektóre filmy przechodzi normalnie i przechodni do 3 najmowych filmów i za każdym razem wyrzuca błąd

**Comment by borgnetzwerk** [comment]
Same issue here, when in debug mode you can wait and eventually it (sometimes) load the requested resource, but other times, it won't even work there.

**Comment by 0xRaduan** [comment]
I was able to solve it with `retryWithBackoff` approach.

Just put https://pypi.org/project/backoff/ decorator on your function which requests it(if you can afford it and it's idempotent, ofc) and works smoothly for me. 

For those, who don't have time to debug issues with this library.

**Comment by JoaoEmanuell** [comment]
In my case, I avoided this bug by placing the pytube download inside a function and placing an exception to check for KeyError, so if this error occurs, it will call the function again, thus restarting the download. In addition, I put a count to prevent the program from running in an infinite loop.
Note that the last exception serves in case of a different error, that way if the library breaks it will automatically notify you.

```
erros = 0

def test_pytube() -> None:
    try:
        video = YouTube(. . .)
        video.streams.get_audio_only().download()
    except KeyError:
        print('KeyError')
        erros += 1
        if erros == 10:
            break
        else:
            test_pytube()
    except Exception as err:
        print(f"General error!\n{err}")
```

I know it's not the best solution, but it's proven to work.

**Comment by mazz3rr** [comment]
> I was able to solve it with `retryWithBackoff` approach.
> 
> Just put https://pypi.org/project/backoff/ decorator on your function which requests it(if you can afford it and it's idempotent, ofc) and works smoothly for me.
> 
> For those, who don't have time to debug issues with this library.

That is one cool hint. Thanks a lot!

In case someone would be interested I pass my code (it's about description and not title but the issue is the same).

```python
@backoff.on_exception(backoff.expo, (pytube.exceptions.PytubeError, ValueError), max_time=60)
    def _get_description_with_backoff(self) -> str:
        self._pytube = self._get_pytube()  # returns a pytube.YouTube object
        desc = self._pytube.description
        if not desc:
            raise ValueError
        return self._pytube.description
```

**Comment by novanexu** [comment]
> In my case, I avoided this bug by placing the pytube download inside a function and placing an exception to check for KeyError, so if this error occurs, it will call the function again, thus restarting the download. In addition, I put a count to prevent the program from running in an infinite loop. Note that the last exception serves in case of a different error, that way if the library breaks it will automatically notify you.
> 
> ```
> erros = 0
> 
> def test_pytube() -> None:
>     try:
>         video = YouTube(. . .)
>         video.streams.get_audio_only().download()
>     except KeyError:
>         print('KeyError')
>         erros += 1
>         if erros == 10:
>             break
>         else:
>             test_pytube()
>     except Exception as err:
>         print(f"General error!\n{err}")
> ```
> 
> I know it's not the best solution, but it's proven to work.

So you just force it to redownload a few times, and that works? Odd bug

**Comment by wenger9** [comment]
> > I was able to solve it with `retryWithBackoff` approach.
> > Just put https://pypi.org/project/backoff/ decorator on your function which requests it(if you can afford it and it's idempotent, ofc) and works smoothly for me.
> > For those, who don't have time to debug issues with this library.
> 
> That is one cool hint. Thanks a lot!
> 
> In case someone would be interested I pass my code (it's about description and not title but the issue is the same).
> 
> ```python
> @backoff.on_exception(backoff.expo, (pytube.exceptions.PytubeError, ValueError), max_time=60)
>     def _get_description_with_backoff(self) -> str:
>         self._pytube = self._get_pytube()  # returns a pytube.YouTube object
>         desc = self._pytube.description
>         if not desc:
>             raise ValueError
>         return self._pytube.description
> ```

Thank you very much! and to @JoaoEmanuell as well. Very cool.

**Comment by weibahanhan** [comment]
when use WEB it works, but change to android not work on innertube

**Comment by JoaoEmanuell** [comment]
Guys, I solved this problem by following the following [solution](https://github.com/pytube/pytube/pull/1575). 

I hope it works for you, in this case I made an adaptation of the pytube files, to follow the pr changes.

**Comment by Untit1ed** [comment]
> Guys, I solved this problem by following the following [solution](https://github.com/pytube/pytube/pull/1575).
> 
> I hope it works for you, in this case I made an adaptation of the pytube files, to follow the pr changes.

Good job, works well. Thank you.

**Comment by Avinier** [comment]
I still am getting that error, running a simple python script, no ageRestriction, just a simple video
