### ISSUE TITLE
KeyError: 'streamingData' while downloading a playlist in CLI mode[BUG]

### ISSUE THREAD

**Issue by pranayp35** [pytube/pytube#1548]
**Before creating an issue**

Please confirm that you are on the latest version of pytube by installing from the source.
You can do this by running `python -m pip install git+https://github.com/pytube/pytube`.
Sometimes, the pypi library repository is not up to date, and your issue may have been fixed already!

**Describe the bug**

**To Reproduce**
Please provide the following information:
- The video or playlist url that is causing the error.
- The code where the problem is occurring.

**Expected behavior**

**Output**
If pytube raises an exception, please provide the full traceback for the exception.

**System information**
Please provide the following information:
- Python version (run `python --version`)
- Pytube version (run `print(pytube.__version__)` in python)
- Command used to install pytube
------------------------------------------------------------------------------------------
error are as follows:
------------------------------------------------------------------------------------------
PS D:\2. Java Programming> pytube https://www.youtube.com/playlist?list=PLrk5tgtnMN6StFV60jlQ9W-RXyHppbp8G
Loading playlist...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ak776\AppData\Roaming\Python\Python311\Scripts\pytube.exe\__main__.py", line 7, in <module>
  File "C:\Users\ak776\AppData\Roaming\Python\Python311\site-packages\pytube\cli.py", line 46, in main
    _perform_args_on_youtube(youtube_video, args)
  File "C:\Users\ak776\AppData\Roaming\Python\Python311\site-packages\pytube\cli.py", line 60, in _perform_args_on_youtube
    download_highest_resolution_progressive(
  File "C:\Users\ak776\AppData\Roaming\Python\Python311\site-packages\pytube\cli.py", line 474, in download_highest_resolution_progressive
    stream = youtube.streams.get_highest_resolution()
             ^^^^^^^^^^^^^^^
  File "C:\Users\ak776\AppData\Roaming\Python\Python311\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\ak776\AppData\Roaming\Python\Python311\site-packages\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
                                                ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ak776\AppData\Roaming\Python\Python311\site-packages\pytube\__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'streamingData'

**Comment by rayli09** [comment]
same bug here

**Comment by KazukiKazuma** [comment]
I am having the same issue with this. In some occasions in works but it is very inconsistent. If I had to take a shot in the dark, maybe would be that for some reason pytube it too fast in trying to access the streamingData when it so happens that a previous part of the code was now fast enough to retrieve this data from the url and assign it to the dictionary in time?

**Comment by v1-c705** [comment]
I am having the same issue with this. In some occasions in works but it is very inconsistent.
EDIT: I Take back what I said, I've been getting this error constantly every time for the past 50 or so times I tried rerunning the code

**Comment by v1-c705** [comment]
a simple code such as this is the one I'm using to test:





import pytube

try_again = True
while try_again :
    url = input("URL: ")

    youtube = pytube.YouTube(url)

    try:
        obj = youtube.streams.get_highest_resolution()
        print("=====================================================")
        print(obj)
        try_again=False
    except:
        pass

**Comment by sumanthrao-maraboina** [comment]
**First locate pytube library location** 

![Screenshot 2023-04-28 195628](https://user-images.githubusercontent.com/64395686/235274143-5d57a417-3625-433e-ac5f-70fde669afbf.jpg)

**Click on "innertube.py" and edit the code on line 78 replacing client='ANDROID' with client='WEB'**

![image](https://user-images.githubusercontent.com/64395686/235274307-e45c1aeb-498b-45c8-8dff-dcace6a94a46.png)

It worked pretty well for me but the problem is downloading video or audio is slow

**Comment by vcpavao** [comment]
The permanent solution to the issue is [here](https://github.com/pytube/pytube/pull/1559#issuecomment-1526205419). Passing an OAuth parameter into the Youtube declaration and then enabling OAuth on your device by following instructions in CLI resolved all streamingData errors for me.

**Comment by sgarciamu** [comment]
> **First locate pytube library location**
> 
> ![Screenshot 2023-04-28 195628](https://user-images.githubusercontent.com/64395686/235274143-5d57a417-3625-433e-ac5f-70fde669afbf.jpg)
> 
> **Click on "innertube.py" and edit the code on line 78 replacing client='ANDROID' with client='WEB'**
> 
> ![image](https://user-images.githubusercontent.com/64395686/235274307-e45c1aeb-498b-45c8-8dff-dcace6a94a46.png)
> 
> It worked pretty well for me but the problem is downloading video or audio is slow

thank you SO much!!!!!!!!! it's working !!!

**Comment by MohammadAminMusavi** [comment]
when i change ANDROID to WEB, pytube make url that dose not work for me and i got Access to rr4---sn-ab5sznly.googlevideo.com was denied error,
url:
https://rr4---sn-ab5sznly.googlevideo.com/videoplayback?expire=1682861026&ei=ghdOZKulLfuO_9EPudSDgAg&ip=2602%3Aff65%3Aaaa%3Ac014%3A%3A1bef&id=o-AHi6yPrHMJX1LZ2izKfc04-ryzqWQ70ei-Vfo7enouQY&itag=18&source=youtube&requiressl=yes&mh=_p&mm=31%2C26&mn=sn-ab5sznly%2Csn-p5qlsny6&ms=au%2Conr&mv=m&mvi=4&pl=62&gcr=us&initcwndbps=166250&spc=qEK7BzYBiHWQLnBeASMRtKSRGl6uNlGPs50n4fJOUg&vprv=1&mime=video%2Fmp4&ns=zn4A9uFmegN-r05YtmjL1-kN&gir=yes&clen=3094224&ratebypass=yes&dur=166.231&lmt=1676402788453012&mt=1682839025&fvip=5&fexp=24007246&c=WEB&txp=5319224&n=db-2s9uXtufDiPqy2Y&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgeB_yzTDU4rKDFEIsv8K83u2cwq2CljhWY5wB3Z6zjy8CIQCqyrmp2OaWiBTV1-X6w9yYUKvE_MC99UbHlPCievrIMg%3D%3D&sig=OcddzTabdhC3wxc7ol1WVOforviEatjqp0MXIihJiCMuAEOAPoGfdtzoPrde9ADxza%3DHhkTrCPpkbfg0Jzmh6S5tD0PAhIgRw8JQ0qOvqO

and it is one of the url of pytube that i decode it but its didnt work too:

https://rr4---sn-ab5sznly.googlevideo.com/videoplayback?expire=1682861026&ei=ghdOZKulLfuO_9EPudSDgAg&ip=2602%3Aff65%3Aaaa%3Ac014%3A%3A1bef&id=o-AHi6yPrHMJX1LZ2izKfc04-ryzqWQ70ei-Vfo7enouQY&itag=18&source=youtube&requiressl=yes&mh=_p&mm=31%2C26&mn=sn-ab5sznly%2Csn-p5qlsny6&ms=au%2Conr&mv=m&mvi=4&pl=62&gcr=us&initcwndbps=166250&spc=qEK7BzYBiHWQLnBeASMRtKSRGl6uNlGPs50n4fJOUg&vprv=1&mime=video%2Fmp4&ns=zn4A9uFmegN-r05YtmjL1-kN&gir=yes&clen=3094224&ratebypass=yes&dur=166.231&lmt=1676402788453012&mt=1682839025&fvip=5&fexp=24007246&c=WEB&txp=5319224&n=db-2s9uXtufDiPqy2Y&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgeB_yzTDU4rKDFEIsv8K83u2cwq2CljhWY5wB3Z6zjy8CIQCqyrmp2OaWiBTV1-X6w9yYUKvE_MC99UbHlPCievrIMg%3D%3D&sig=OcddzTabdhC3wxc7ol1WVOforviEatjqp0MXIihJiCMuAEOAPoGfdtzoPrde9ADxza%3DHhkTrCPpkbfg0Jzmh6S5tD0PAhIgRw8JQ0qOvqO&mim=video/mp4&title=BAMBA+(Slowed+++Reverb)
