### ISSUE TITLE
[BUG] Getting KeyError 'SideBar' when downloading playlist

### ISSUE THREAD

**Issue by caceresjayder** [pytube/pytube#1550]
When attempting to download videos from playlist link, i'm getting this error.

Traceback (most recent call last):
  File "C:\Users\[username]\Desktop\New\videoDownload.py", line 23, in <module>
    pDir = p.title
           ^^^^^^^
  File "C:\Users\[username]\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\contrib\playlist.py", line 351, in title
    return self.sidebar_info[0]['playlistSidebarPrimaryInfoRenderer'][
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\[username]\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\contrib\playlist.py", line 93, in sidebar_info
    self._sidebar_info = self.initial_data['sidebar'][
                         ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'sidebar'


the last day i was downloading normally.

**Comment by Ripax** [comment]
Hi, this issue is resolved ?

**Comment by ilgarm** [comment]
as a workaround, if you provide -t option, it will not try to access playlist title, which causes this error

**Comment by xoliswangcobo** [comment]
This happened to me because the playlist was 'private'. Try making the playlist 'public' as try again. You may also need to authenticate your computer via the command line.
