### ISSUE TITLE
[BUG] when downloading video getting streamData error when using library

### ISSUE THREAD

**Issue by 4cecoder** [pytube/pytube#1551]
**Describe the bug**
Pytube go boom boom!??

**To Reproduce**
```py
import pytube
import requests

class YouTubeToMp3Converter:
    def __init__(self, url):
        self.url = url

    def download_video(self):
        max_retries = 5
        retries = 0

        while retries < max_retries:
            try:
                youtube = pytube.YouTube(self.url)
                video = youtube.streams.filter().first()

                if not os.path.exists('tmp'):
                    os.makedirs('tmp')

                output_file_path = os.path.join('tmp', video.default_filename)
                video.download(output_path='tmp', filename=video.default_filename)

                return output_file_path
            except Exception as e:
                print(f"Error downloading video: {e}")
                retries += 1
                if retries == max_retries:
                    raise Exception("Failed to download video after 5 attempts")

    def convert_to_wav(self):
        video_file_path = self.download_video()

        audio_file_path = os.path.splitext(video_file_path)[0] + ".wav"
        video_clip = VideoFileClip(video_file_path)

        audio_clip = video_clip.audio
        audio_clip.write_audiofile(audio_file_path, codec='pcm_s16le', bitrate='16k')

        video_clip.close()
        os.remove(video_file_path)

        return audio_file_path

    def convert_to_mp3(self, bitrate="128k", wav_file_path="tmp/test.wav"):
        wav_file_path = self.convert_to_wav()
        mp3_file_path = os.path.splitext(wav_file_path)[0] + ".mp3"
        sound = AudioSegment.from_file(wav_file_path)
        sound.export(mp3_file_path, format="mp3", bitrate=bitrate)
        os.remove(wav_file_path)
        print("mp3_file_path: ", mp3_file_path)

        return mp3_file_path


if __name__ == '__main__':
    url = 'https://www.youtube.com/watch?v=OW-Z9eUM2VI'
    converter = YouTubeToMp3Converter(url)
    wav_file_path = converter.convert_to_wav()
    print(f'Saved WAV file to {wav_file_path}')
    wav_file_path = converter.convert_to_mp3(wav_file_path=wav_file_path)
```

**Expected behavior**
usually downloads youtube video and converts with no errors, this behavior suddenly broke at approximately 6:30pm EST
Perhaps youtube updated their api 

**Output**
If pytube raises an exception, please provide the full traceback for the exception.
```shell
Error downloading video: 'streamingData'
Traceback (most recent call last):
  File "/root/linker/linkai/ai.py", line 25, in download_video
    video = youtube.streams.filter().first()
            ^^^^^^^^^^^^^^^
  File "/root/linker/linkai/venv/lib/python3.11/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "/root/linker/linkai/venv/lib/python3.11/site-packages/pytube/__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
                                                ^^^^^^^^^^^^^^^^^^^
  File "/root/linker/linkai/venv/lib/python3.11/site-packages/pytube/__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'streamingData'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/linker/linkai/ai.py", line 146, in <module>
    wav_file_path = converter.convert_to_wav()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/linker/linkai/ai.py", line 41, in convert_to_wav
    video_file_path = self.download_video()
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/root/linker/linkai/ai.py", line 38, in download_video
    raise Exception("Failed to download video after 5 attempts")
Exception: Failed to download video after 5 attempts
```

**System information**
Please provide the following information:
python 3.9 linux debian bullseye
python 3.11 linux debian bullseye 
python 3.9 MacOS

pytube version:
12.1.3 

- Command used to install pytube
`$ python -m pip install git+https://github.com/pytube/pytube`

**Comment by gianluca-magnabosco** [comment]
I've got the same error

The 5 attempts used to work for me aswell, but now i'm at 100 attempts and it still seems to fail constantly, the same video won't download sometimes, but then a few minutes later it will.

**Comment by Kealtoast** [comment]
I am having the same error. Tried a few other commands as well. Some are working like the image url and other like title are not.

**Comment by 4cecoder** [comment]
> I've got the same error
> 
> The 5 attempts used to work for me aswell, but now i'm at 100 attempts and it still seems to fail constantly, the same video won't download sometimes, but then a few minutes later it will.

i've fixed it by switching libraries and using a different library here's my new code:

`pip install yt-dlp`

Please give me a follow: [4cecoder](https://github.com/4cecoder)
love u! <3

```py

import os
import subprocess

class YouTubeToMp3Converter:
    def __init__(self, url):
        self.url = url

    def download_mp3(self, output_folder='tmp', bitrate="128k"):
        if not os.path.exists(output_folder):
            os.makedirs(output_folder)

        output_file_path = os.path.join(output_folder, '%(title)s.%(ext)s')

        command = [
            "yt-dlp",
            "-x",
            "--audio-format",
            "mp3",
            "--audio-quality",
            bitrate,
            "-o",
            output_file_path,
            self.url,
        ]

        subprocess.call(command)

        # Find the downloaded mp3 file
        for file in os.listdir(output_folder):
            if file.endswith('.mp3'):
                return os.path.join(output_folder, file)
                

   if __name__ == '__main__':
    url = 'https://www.youtube.com/watch?v=OW-Z9eUM2VI'
    converter = YouTubeToMp3Converter(url)
    mp3_file_path = converter.download_mp3()
    print(f'Saved MP3 file to {mp3_file_path}')
            
            
   ```

**Comment by gianluca-magnabosco** [comment]
Thanks! I've implemented a similar version as a backup after some failed retries

```  
async def download_youtube_audio(self, audio):
 
        exception_count = 0
        while not audio.downloaded:
            try:
                stream = audio.video.streams.get_audio_only()
                audio.file_name = audio.video.video_id + f".{stream.mime_type[6:]}"
                stream.download(output_path = "sounds/", filename = audio.file_name)
                
            except: 
                exception_count += 1
                if exception_count > 100:
                    video = YoutubeToMp3(audio.video.watch_url, audio.video.video_id)
                    audio.file_name = video.download_audio()
                    audio.downloaded = True
                
            else:
                audio.downloaded = True
```

```
import os
import subprocess


class YoutubeToMp3:
    
    def __init__(self, url, video_id):
        self.url = url
        self.video_id = video_id
        self.output_dir = "sounds/"
        
        
    def download_audio(self):
        file_name = f"{self.video_id}.mp3"
        
        output_file_path = os.path.join(self.output_dir, file_name)
        
        command = [
            "yt-dlp",
            "-x",
            "--audio-format",
            "mp3",
            "--audio-quality",
            "128k",
            "-o",
            output_file_path,
            self.url,
        ]

        subprocess.call(command)
        
        return file_name
```

**Comment by sumanthrao-maraboina** [comment]
**First locate pytube library location** 

![Screenshot 2023-04-28 195628](https://user-images.githubusercontent.com/64395686/235274143-5d57a417-3625-433e-ac5f-70fde669afbf.jpg)

**Click on "innertube.py" and edit the code on line 78 replacing client='ANDROID' with client='WEB'**

![image](https://user-images.githubusercontent.com/64395686/235274307-e45c1aeb-498b-45c8-8dff-dcace6a94a46.png)

It worked pretty well for me but the problem is downloading video or audio is slow
