### ISSUE TITLE
[BUG] KeyError: 'streamingData' when acessing video streams for downloading

### ISSUE THREAD

**Issue by akumakum** [pytube/pytube#1552]
**Before creating an issue**

Pytube is at latest version :12.1.3

**Bug Description**

Pytube throws KeyError: 'streamingData' when accessing streams

**Reproduction**
Error can be reproduced by executing the following codes:

from pytube import YouTube

video = YouTube("https://www.youtube.com/watch?v=lC5mej1IOug")
video = video.streams.get_highest_resolution()

**Expected behavior**
Pytube should have downloaded the mp4 file with the same name as the video description

**Output**

Full Stack Trace:
Traceback (most recent call last):
  File "E:\joyfiles\python_codes\youtube\download.py", line 4, in <module>
    video = video.streams.get_highest_resolution()
  File "E:\Program files\Python\Python310\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "E:\Program files\Python\Python310\lib\site-packages\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "E:\Program files\Python\Python310\lib\site-packages\pytube\__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
KeyError: 'streamingData'

**System information**
Please provide the following information:

Python version : Python 3.10.4
Pytube version : 12.1.3
Command used to install pytube : python -m pip install git+https://github.com/pytube/pytube

**Comment by sumanthrao-maraboina** [comment]
**First locate pytube library location** 

![Screenshot 2023-04-28 195628](https://user-images.githubusercontent.com/64395686/235274143-5d57a417-3625-433e-ac5f-70fde669afbf.jpg)

**Click on "innertube.py" and edit the code on line 78 replacing client='ANDROID' with client='WEB'**

![image](https://user-images.githubusercontent.com/64395686/235274307-e45c1aeb-498b-45c8-8dff-dcace6a94a46.png)

It worked pretty well for me but the problem is downloading video or audio is slow
