### ISSUE TITLE
[BUG]  the module is showing error while extracting the title sometime 

### ISSUE THREAD

**Issue by NormVg** [pytube/pytube#1555]
**Before creating an issue**

Please confirm that you are on the latest version of pytube by installing from the source.
You can do this by running `python -m pip install git+https://github.com/pytube/pytube`.
Sometimes, the pypi library repository is not up to date, and your issue may have been fixed already!

**Describe the bug**

**To Reproduce**
Please provide the following information:
- The video or playlist url that is causing the error.
- The code where the problem is occurring.

**Expected behavior**

**Output**
If pytube raises an exception, please provide the full traceback for the exception.

**System information**
Please provide the following information:
- Python version (run `python --version`)
- Pytube version (run `print(pytube.__version__)` in python)
- Command used to install pytube

**Comment by NormVg** [comment]
Traceback (most recent call last):
  File "/home/runner/Dusico/venv/lib/python3.10/site-packages/pytube/__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/Dusico/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/runner/Dusico/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/runner/Dusico/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/runner/Dusico/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "main.py", line 43, in player
    data = tubedown.tubedata(id)
  File "/home/runner/Dusico/tubedown.py", line 18, in tubedata
    title = yt.title
  File "/home/runner/Dusico/venv/lib/python3.10/site-packages/pytube/__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=C3BE3jNeHtU. Please file a bug report at https://github.com/pytube/pytube

**Comment by Konnected03** [comment]
I am also having issues with pytube 

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\austi\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\austi\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "c:\Users\austi\OneDrive\Desktop\D1\Visual Studio Projects\GUI\modern_gui.py", line 21, in download
    my_video = vid.streams.get_highest_resolution()
               ^^^^^^^^^^^
  File "C:\Users\austi\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\austi\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
                                                ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\austi\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'streamingData'

**Comment by Pymode-Dev** [comment]
I am also having issue with this.

Traceback (most recent call last):
  File "/home/pymode-dev/.cache/pypoetry/virtualenvs/youtube-cli-XkfgXU7u-py3.10/lib/python3.10/site-packages/pytube/__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pymode-dev/30_python_projects_for_2023/CLI/youtube_cli/youtube_cli/videos.py", line 44, in <module>
    video.main()
  File "/home/pymode-dev/30_python_projects_for_2023/CLI/youtube_cli/youtube_cli/videos.py", line 33, in main
    self.show_video_info()
  File "/home/pymode-dev/30_python_projects_for_2023/CLI/youtube_cli/youtube_cli/videos.py", line 20, in show_video_info
    table.add_row(self.title, self.author, f"{self.views:,}")
  File "/home/pymode-dev/.cache/pypoetry/virtualenvs/youtube-cli-XkfgXU7u-py3.10/lib/python3.10/site-packages/pytube/__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=nKDAuMjZs3s. Please file a bug report at https://github.com/pytube/pytube

**Comment by v1-c705** [comment]
Also having the same issue. Tried with a "only essentials" code and be getting the same error consistently for the past 50 tries or so:


import pytube

try_again = True
while try_again :

    url = input("URL: ")
    youtube = pytube.YouTube(url)

    try:
        obj = youtube.streams.get_highest_resolution()
        print("==========================================================================================================================================")
        print(obj)
        try_again=False
    except:
        pass

**Comment by harshgupta0306** [comment]
> I am also having issue with this.
> 
> Traceback (most recent call last): File "/home/pymode-dev/.cache/pypoetry/virtualenvs/youtube-cli-XkfgXU7u-py3.10/lib/python3.10/site-packages/pytube/**main**.py", line 341, in title self._title = self.vid_info['videoDetails']['title'] KeyError: 'videoDetails'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/pymode-dev/30_python_projects_for_2023/CLI/youtube_cli/youtube_cli/videos.py", line 44, in video.main() File "/home/pymode-dev/30_python_projects_for_2023/CLI/youtube_cli/youtube_cli/videos.py", line 33, in main self.show_video_info() File "/home/pymode-dev/30_python_projects_for_2023/CLI/youtube_cli/youtube_cli/videos.py", line 20, in show_video_info table.add_row(self.title, self.author, f"{self.views:,}") File "/home/pymode-dev/.cache/pypoetry/virtualenvs/youtube-cli-XkfgXU7u-py3.10/lib/python3.10/site-packages/pytube/**main**.py", line 346, in title raise exceptions.PytubeError( pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=nKDAuMjZs3s. Please file a bug report at https://github.com/pytube/pytube

I am having the same issue. It stoped working for some reason.
yesterday it was working fine but today it is throwing this exception.
