### ISSUE TITLE
[BUG]KeyError: 'videoDetails' : pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=8C4Lo0a3YKY. Please file a bug report at https://github.com/pytube/pytube

### ISSUE THREAD

**Issue by q4udebobrota** [pytube/pytube#1556]
Traceback (most recent call last):
File "D:\pythonProjects\youtube-downloader\youtube-downloader-converter-master\code.py", line 35, in
stream = str(yt.streams.filter(progressive=True))
File "D:\pythonProjects\youtube-downloader\env\lib\site-packages\pytube_main_.py", line 296, in streams
return StreamQuery(self.fmt_streams)
File "D:\pythonProjects\youtube-downloader\env\lib\site-packages\pytube_main_.py", line 176, in fmt_streams
stream_manifest = extract.apply_descrambler(self.streaming_data)
File "D:\pythonProjects\youtube-downloader\env\lib\site-packages\pytube_main_.py", line 161, in streaming_data
return self.vid_info['streamingData']
KeyError: 'streamingData'

please help me with a solution

**Comment by D1xx1** [comment]
> Traceback (most recent call last):
> File "D:\pythonProjects\youtube-downloader\youtube-downloader-converter-master\code.py", line 35, in
> stream = str(yt.streams.filter(progressive=True))
> File "D:\pythonProjects\youtube-downloader\env\lib\site-packages\pytube_main_.py", line 296, in streams
> return StreamQuery(self.fmt_streams)
> File "D:\pythonProjects\youtube-downloader\env\lib\site-packages\pytube_main_.py", line 176, in fmt_streams
> stream_manifest = extract.apply_descrambler(self.streaming_data)
> File "D:\pythonProjects\youtube-downloader\env\lib\site-packages\pytube_main_.py", line 161, in streaming_data
> return self.vid_info['streamingData']
> KeyError: 'streamingData'
> 
> please help me with a solution

https://github.com/pytube/pytube/issues/1553#issuecomment-1524956425
I try that solution but download speed leaves much to be desired.

**Comment by ghost** [comment]
C:\Users\ss_ra\Downloads>python Youtube_download.py
Enter the link: https://www.youtube.com/watch?v=WXsD0ZgxjRw
The input link is https://www.youtube.com/watch?v=WXsD0ZgxjRw
Traceback (most recent call last):
  File "C:\Users\ss_ra\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ss_ra\Downloads\Youtube_download.py", line 8, in <module>
    print("Title: ", yt.title)
                     ^^^^^^^^
  File "C:\Users\ss_ra\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=WXsD0ZgxjRw. Please file a bug report at https://github.com/pytube/pytube

**Comment by P1arzival** [comment]
I have the same issue, it started recently for me. I didn’t even change the code

**Comment by lynnlynn2023** [comment]
I have the same issue. My message goes
raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=qrWulBa5Gpc. Please file a bug report at https://github.com/pytube/pytube

**Comment by eyesee1** [comment]
same here, didn't change my code that worked previously.

**Comment by kj3moraes** [comment]
Facing the same issue on Ubuntu Linux. Haven't changed the code either. 

I used [this fix](https://github.com/pytube/pytube/issues/1553#issuecomment-1524956425) but it is outrageously slow now.

**Comment by P1arzival** [comment]
Thankyou brother

**Comment by P1arzival** [comment]
Thankyou!

**Comment by nordic-mountain** [comment]
I fixed it by installing the latest pytube libary
