### ISSUE TITLE
[BUG]KeyError: 'videoDetails' ; Exception while accessing title of https://youtube.com/watch?v=AVYGCjwjUXg. Please file a bug report at https://github.com/pytube/pytube

### ISSUE THREAD

**Issue by kevinb-dev** [pytube/pytube#1557]
My code :
```from pytube import YouTube

url = "https://www.youtube.com/watch?v=AVYGCjwjUXg&t=88s"


def on_download_progress(stream, chunk, bytes_remaining):
    bytes_downloaded = stream.filesize - bytes_remaining
    percent = bytes_downloaded * 100 / stream.filesize
    print(f"Progression du téléchargement : {int(percent)}%")


youtube_video = YouTube(url)

youtube_video.register_on_progress_callback(on_download_progress)

print(f"Titre: {youtube_video.title}")
print(f"Nombre de vues : {youtube_video.views}")

print("Liste des streams")
for stream in youtube_video.fmt_streams:
    print(f" {stream}")

# stream = youtube_video.streams.get_by_itag(18)
stream = youtube_video.streams.get_highest_resolution()
print("Téléchargement ...")
stream.download()
print(f"Téléchargement effectué, la vidéo a une résolution de {stream.resolution}")
```

And the error : 
Traceback (most recent call last):
  File "C:\Users\Skoll\PycharmProjects\YouTube Downloader\venv\lib\site-packages\pytube\__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Skoll\PycharmProjects\YouTube Downloader\main.py", line 20, in <module>
    print(f"Titre: {youtube_video.title}")
  File "C:\Users\Skoll\PycharmProjects\YouTube Downloader\venv\lib\site-packages\pytube\__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=AVYGCjwjUXg. Please file a bug report at https://github.com/pytube/pytube

And if I comment this : print(f"Titre: {youtube_video.title}") print(f"Nombre de vues : {youtube_video.views}"), I have this error : KeyError: 'streamingData'

I have version 12.1.3 of pytube. Can you help me please ?

**Comment by g-sergey** [comment]
Seems YouTube never more provide data if client ==  'ANDROID'

https://github.com/pytube/pytube/blob/master/pytube/__main__.py#L244

Changing this line from:
 innertube = InnerTube(use_oauth=self.use_oauth, allow_cache=self.allow_oauth_cache)
 
 to:
 innertube = InnerTube(use_oauth=self.use_oauth, allow_cache=self.allow_oauth_cache, client='WEB')
 
 made it work again for me.

**Comment by NormVg** [comment]
you should change this in the __main__.py because now it is not working completely

because now the module is working fine

**Comment by g-sergey** [comment]
@NormVg I am not getting  you: "not working completely" or "working fine"?

**Comment by g-sergey** [comment]
Also I checked it with oauth: yt = YouTube(yt_link, use_oauth=True)
It works fine. You just have to authorize it with your youtube account.

**Comment by kevinb-dev** [comment]
Ok thank you @g-sergey it work for me, thank you

**Comment by Dysonsun** [comment]
> Seems YouTube never more provide data if client == 'ANDROID'
> 
> https://github.com/pytube/pytube/blob/master/pytube/__main__.py#L244
> 
> Changing this line from: innertube = InnerTube(use_oauth=self.use_oauth, allow_cache=self.allow_oauth_cache)
> 
> to: innertube = InnerTube(use_oauth=self.use_oauth, allow_cache=self.allow_oauth_cache, client='WEB')
> 
> made it work again for me.

it work for me, thanks
