### ISSUE TITLE
[BUG] KeyError when downloading a video and/or getting infos about the video

### ISSUE THREAD

**Issue by flloschy** [pytube/pytube#1558]
**Describe the bug**
I was redoing a script which automatically downloads YouTube videos. \
In the code I test for the length of the video to not download videos under three minutes. When testing I got the error found below. \
After some trying around I tested the example code which I found in the [docs](https://pytube.io/en/latest/) and got an similar error having something to do with the `vid_info`. \
Yesterday my old script didnt work (which is why im recoding it) because the decapi-youtube API had some problems, I think its possible that this is somewhat the same reason here. \
(decicus *(the maker of decapi)* said "YouTube's API seems to be having issues at the moment, so it may not consistently work." after the API went down, maybe they changed something)

**To Reproduce**
(this is the code found in the [docs](https://pytube.io/en/latest/))
- Open console and start python
- import pytube.Youtube by `>>> from pytube import YouTube`
- try downloading a video by `>>> YouTube('https://youtu.be/9bZkp7q19f0').streams.first().download()`
- get an error

**Expected behavior**
Download the video and not throw an error

**Output**
Error when using `YouTube('https://youtu.be/9bZkp7q19f0').streams.first().download()`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\python\Lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
                                                ^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\pytube\__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'streamingData'
```

Errors when using `YouTube('https://youtu.be/9bZkp7q19f0').title`
```
Traceback (most recent call last):
  File "D:\python\Lib\site-packages\pytube\__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\python\Lib\site-packages\pytube\__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=9bZkp7q19f0. Please file a bug report at https://github.com/pytube/pytube
```

**System information**
python version: `3.11.2`
pytube version: `12.1.3`
pip version: `23.1.2`
Originally: `pip install pytube`
When getting the bug and trying to fix by updating: `python -m pip install git+https://github.com/pytube/pytube` (found in readme of the project)

**Comment by diogo-ms** [comment]
I have exactly the same errors as you. When trying to get the description of a video, pytube throws `none` while there is cleary a description. 

python version: `3.10.9`
pytube version: `12.1.3`
pip version: `23.1.2`

**Comment by g-sergey** [comment]
This is how I fixed it on my project: https://github.com/pytube/pytube/pull/1559

Hopefully it can be fixed soon.

**Comment by isaacramsay** [comment]
Just found something that worked for me. Find the innertube.py file, mine was in the pytube folder. In your error message it should give the path. On line 76 is the InnerTube() class, change the default client from 'ANDROID' to 'WEB'. Hope this helps
python:3.11.3
pytube:12.1.3

**Comment by wenger9** [comment]
> Thank you for contributing to PyTube. Please remember to reference [Contributing.md](https://github.com/pytube/pytube/blob/master/Contributing.md)

Exact same boat here. What's funny is that when grabbing the description and title earlier from the video object (yesterday), it worked just fine. Running again today, on the same video and running into this error.

Sys Info:
python version: 3.10.9
pytube version: 12.1.3
pip version: 23.1.2

**Comment by ArcticSlayy** [comment]
Yea, it seems to be an issue with Pytube currently. Supposedly a fix was the key hotfix in the pull request. Did not work for me as when changing this the video does not download no matter the resolution.

**Comment by AngelSanchezAW** [comment]
I have the same problem. 

pytube 12.1.3
Python 3.10.6
pip 22.0.2

**Comment by KALI-THE-HACKER** [comment]
Same problem this side. I was on a project using pytube, my program was working 2 days-ago, but suddenly got 'streamingData' error today, I tried to fix it with uninstalling and installing pytube & pytube3, and with git too, but still getting error.

**Comment by ShamrockD** [comment]
same problem, but i also mentioned as it was responeded earlier - its a problem from youtube side. I already have a few projects in c# and java with same technology of downloading and there is also this trouble(low speed or dont even works).

**Comment by sumanthrao-maraboina** [comment]
**First locate pytube library location** 

![Screenshot 2023-04-28 195628](https://user-images.githubusercontent.com/64395686/235274143-5d57a417-3625-433e-ac5f-70fde669afbf.jpg)

**Click on "innertube.py" and edit the code on line 78 replacing client='ANDROID' with client='WEB'**

![image](https://user-images.githubusercontent.com/64395686/235274307-e45c1aeb-498b-45c8-8dff-dcace6a94a46.png)

It worked pretty well for me but the problem is downloading video or audio is slow

**Comment by leonantonio** [comment]
@sumanthrao-maraboina thank you for your help I replaced "ANDROID" with "WEB" and now is working :)

**Comment by DavideCarletto** [comment]
> changing this the video does not download no matter the resolution.

That worked for me, thank u!

**Comment by DavideCarletto** [comment]
@sumanthrao-maraboina That worked for me, thank u!
