### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by amith-code** [pytube/pytube#1568]
yes i am using latest version pytube (12.1.3)
**Describe the bug**
KeyError: 'streamingData'

- https://youtu.be/4J2PR9GCad0
-YouTube(video_link).streams.first().download()
lin 296 in __main__.py

**Expected behavior**

**Output**
D:\PYTHON-PROJECTS\pythonProject\venv\Scripts\python.exe D:\PYTHON-PROJECTS\pythonProject\main.py 
enter vedio url from Youtube https://youtu.be/4J2PR9GCad0
vedio downloading...
Traceback (most recent call last):
  File "D:\PYTHON-PROJECTS\pythonProject\main.py", line 4, in <module>
    YouTube(video_link).streams.first().download()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PYTHON-PROJECTS\pythonProject\venv\Lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "D:\PYTHON-PROJECTS\pythonProject\venv\Lib\site-packages\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
                                                ^^^^^^^^^^^^^^^^^^^
  File "D:\PYTHON-PROJECTS\pythonProject\venv\Lib\site-packages\pytube\__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'streamingData'

Process finished with exit code 1


**System information**
Please provide the following information:
python version (3.11.2)
pytube version (12.1.3)

**Comment by player2I0** [comment]
solution is here (worked at least for me): #1565
