### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DeltaForce1322** [pytube/pytube#1573]
Downloader YouTube!

Link Video Youtube : https://youtube.com/shorts/fWi2iaD7Loc?feature=shar
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/pytube/__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 20, in <module>
  File "<string>", line 14, in start
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/pytube/__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=fWi2iaD7Loc. Please file a bug report at https://github.com/pytube/pytube

[Program finished]

**Comment by srisreedhar** [comment]
# Same Error
```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\srisreedhar\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=[ID_Removed]. ```
 Please file a bug report at https://github.com/pytube/pytube

# Through CMD 

```
E:\01May2023>pytube https://www.youtube.com/watch?v=ID_HERE
Loading video...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Scripts\pytube.exe\__main__.py", line 7, in <module>
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\cli.py", line 53, in main
    _perform_args_on_youtube(youtube, args)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\cli.py", line 60, in _perform_args_on_youtube
    download_highest_resolution_progressive(
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\cli.py", line 474, in download_highest_resolution_progressive
    stream = youtube.streams.get_highest_resolution()
             ^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
                                                ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'streamingData'
```

**Comment by opc241** [comment]
I got the same error as the two above. Unisntalled pytube and installing it again was no solution.

**Comment by djisuru2288** [comment]
same here. still not working

**Comment by ennioli** [comment]
same here.

**Comment by yeralin** [comment]
Tracked down the issue to `https://www.youtube.com/youtubei/v1/player` call [here](https://github.com/pytube/pytube/blob/master/pytube/__main__.py#L246)

The API returns an error, most likely due to [planned deprecation](https://developers.google.com/youtube/android/player).

We need to upgrade the library to use `v2` API version.

**Comment by lolzhunter** [comment]
thanks that worked

**Comment by RONNCC** [comment]
i believe new changes should fix - can you check? Also interested in PRs that fix any of the issue :-)

**Comment by lolzhunter** [comment]
had a problem with downloading a while back, speed was capped to really low, this got fixed here
https://github.com/pytube/pytube/issues/1489#issuecomment-1452868684
technically not a PR but its a fix
