### ISSUE TITLE
Please, what's the meaning of this bug?

### ISSUE THREAD

**Issue by Programmerchriz** [pytube/pytube#1581]
**Before creating an issue**

Please confirm that you are on the latest version of pytube by installing from the source.
You can do this by running `python -m pip install git+https://github.com/pytube/pytube`.
Sometimes, the pypi library repository is not up to date, and your issue may have been fixed already!

**Describe the bug**

**To Reproduce**
Please provide the following information:
- The video or playlist url that is causing the error.
- The code where the problem is occurring.

**Expected behavior**

**Output**
If pytube raises an exception, please provide the full traceback for the exception.

**System information**
Please provide the following information:
- Python version (run `python --version`)
- Pytube version (run `print(pytube.__version__)` in python)
- Command used to install pytube

**Comment by Programmerchriz** [comment]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\python_projects\IMCProjects\youtube_video_downloader.py", line 7, in <module>
    print("Title:", yt.title)
                    ^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=qmQ6QwG1b0Q. Please file a bug report at https://github.com/pytube/pytube

**Comment by saikrishnatbijil** [comment]
I have got this same issue

**Comment by flloschy** [comment]
python has this error for a few days now...
For what I understand its because pytube uses an android client and youtube recently changed their api so the way the android client is used doesnt work anymore.
There are fixes in other bug reports and even some forks which fix this issue.

**Comment by RONNCC** [comment]
i believe new changes should fix - can you check? Also interested in PRs that fix any of the issue :-)
