### ISSUE TITLE
[BUG] error where trying to get video title

### ISSUE THREAD

**Issue by firzaelbuho** [pytube/pytube#1591]
when i try to get video's title. faced this error

KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Project\Python\yt-downloader\downloader.py", line 8, in <module>
    print(yt.title)
  File "C:\Project\Python\yt-downloader\venv\lib\site-packages\pytube\__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=CX9i70i3xb8. Please file a bug report at https://github.com/pytube/pytube

**Comment by SnoopiACK** [comment]
Try this, It's work for me. 

https://github.com/pytube/pytube/pull/1595/commits/c0d1aca42c4106e77ab4f8a0600737ea2ad27a96#diff-34b7de4e054a59b9c9a386a81fac050960951773737b50b5c8b746db6a364d47

**Comment by SarmenSinanian** [comment]
I just tried this. Must go into the actual file and swap "ANDROID" with "WEB" as described in your commit. Thank you very much. The library can now pull the title correctly.
