### ISSUE TITLE
[BUG] Exception while accessing title of [link]. Please file a bug report at [github].

### ISSUE THREAD

**Issue by Jankoy** [pytube/pytube#1597]
**Describe the bug**
When I try to read the title of a Youtube object it breaks, and tells me to come to the github.

**To Reproduce**
The URL is: https://www.youtube.com/watch?v=vEQ8CXFWLZU
The code is:
```
from pytube import YouTube
from sys import argv
import os

def show_syntax():
   print("\nSyntax: python/python3 ytdownload.py [-f filename] or [-l link]\n")


def dl_from_link(link):
   vid = YouTube(link)
   print("Title: ", vid.title)


def dl_from_file(filename):
   pass


def main():
  if argv[1] == "-f":
    dl_from_file(argv[2])
  elif argv[1] == "-l":
    dl_from_link(argv[2])
  else:
     show_syntax()


if __name__ == "__main__":
   try:
      main()
   except IndexError:
      show_syntax()
```
The command used to run the script: python ytdownload.py -l "www.youtube.com/watch?v=vEQ8CXFWLZU"

**Expected behavior**
The title of the YouTube object to be returned.

**Output**
![image](https://user-images.githubusercontent.com/107075923/236033943-b33935be-7781-412b-8e21-8a31857de457.png)

**System information**
Please provide the following information:
- Python version: Python 3.10.8
- Pytube version: 12.1.3
- Command used to install pytube: pip install pytube

**Comment by SnoopiACK** [comment]
Try this, It's work for me.

https://github.com/pytube/pytube/commit/c0d1aca42c4106e77ab4f8a0600737ea2ad27a96#diff-34b7de4e054a59b9c9a386a81fac050960951773737b50b5c8b746db6a364d47

**Comment by Dinidiniz** [comment]
Same problem here. Functions like .length and .views are raising errors as well

**Comment by plaban1981** [comment]
I also encounter the same issue :
File "/usr/local/lib/python3.9/site-packages/langchain/document_loaders/youtube.py", line 129, in load
video_info = self._get_video_info()
File "/usr/local/lib/python3.9/site-packages/langchain/document_loaders/youtube.py", line 166, in _get_video_info
"title": yt.title,
File "/usr/local/lib/python3.9/site-packages/pytube/__main__.py", line 346, in title
raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=v6sF8Ed3nTE.Please file a bug report at https://github.com/pytube/pytube

**Comment by DandyDrop** [comment]
I`m getting the same error when running this simple script:

```python
import pytube

v = pytube.Playlist("https://www.youtube.com/watch?v=5qtC-tsQ-wE&list=PLqnslRFeH2UpC8EqlF2aax9A-VLiPDwxP")
print(v.title)
for url in v.video_urls:
    print(url)
    yt = pytube.YouTube(url)
    print(yt.title)
    print(yt.streams.get_highest_resolution())
```

this is the console output:

YouTube Data API - Python Tutorials
https://www.youtube.com/watch?v=5qtC-tsQ-wE
Traceback (most recent call last):
  File "...\pytube\__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...", line 8, in <module>
    print(yt.title)
  File "...\pytube\__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=5qtC-tsQ-wE. Please file a bug report at https://github.com/pytube/pytube

Python version: 3.10.9
pytube version: 12.1.2

**Comment by win20-official** [comment]
> Try this, It's work for me.
> 
> [c0d1aca#diff-34b7de4e054a59b9c9a386a81fac050960951773737b50b5c8b746db6a364d47](https://github.com/pytube/pytube/commit/c0d1aca42c4106e77ab4f8a0600737ea2ad27a96#diff-34b7de4e054a59b9c9a386a81fac050960951773737b50b5c8b746db6a364d47)

Thx for adding my commit

**Comment by SnoopiACK** [comment]
> > Try this, It's work for me.
> > [c0d1aca#diff-34b7de4e054a59b9c9a386a81fac050960951773737b50b5c8b746db6a364d47](https://github.com/pytube/pytube/commit/c0d1aca42c4106e77ab4f8a0600737ea2ad27a96#diff-34b7de4e054a59b9c9a386a81fac050960951773737b50b5c8b746db6a364d47)
> 
> Thx for adding my commit

Thx for your commit.

**Comment by bsobotka** [comment]
> Try this, It's work for me.
> 
> [c0d1aca#diff-34b7de4e054a59b9c9a386a81fac050960951773737b50b5c8b746db6a364d47](https://github.com/pytube/pytube/commit/c0d1aca42c4106e77ab4f8a0600737ea2ad27a96#diff-34b7de4e054a59b9c9a386a81fac050960951773737b50b5c8b746db6a364d47)

Glad people are finding this works, but I keep getting the same error as OP here, even after changing the line in innertube.py.

EDIT: Implementing the workaround found [here](https://github.com/hayabhay/whisper-ui/pull/46/files) solves the problem! Specifically, after importing pytube, putting this line of code in my own seems to work:

`pytube.innertube._default_clients['ANDROID']=pytube.innertube._default_clients['WEB']`

**Comment by mrxwd** [comment]
exception while accessing title of https://youtube.com/watch?v=_hzm0qiuus8. please file a bug report at https://github.com /pytube/pytube



Alguna solución?

**Comment by rijalghodi** [comment]
Still got error... It works in local, but failed in docker container...

**Comment by guilegarcia** [comment]
+1
