### ISSUE TITLE
KeyError: 'videoDetails' [BUG]

### ISSUE THREAD

**Issue by liuyangnorway** [pytube/pytube#1604]
```python
url ='https://www.youtube.com/watch?v=R1XK-fHEkfY'
yt = YouTube(url)
yt.title
```
Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\lib\site-packages\pytube\__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']

KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\JDLU\AppData\Local\Temp\ipykernel_24912\1809451884.py", line 1, in <module>
    yt.title

  File "C:\ProgramData\Anaconda3\lib\site-packages\pytube\__main__.py", line 346, in title
    raise exceptions.PytubeError(

PytubeError: Exception while accessing title of https://youtube.com/watch?v=R1XK-fHEkfY. Please file a bug report at https://github.com/pytube/pytube

**Comment by liuyangnorway** [comment]
Python:  3.9.13 
pytube.__version__: : '12.1.3'

**Comment by arunjohnraphi** [comment]
using python version 3.9.13 and pytube version 12.1.3 can solve this issue?

**Comment by bsobotka** [comment]
> using python version 3.9.13 and pytube version 12.1.3 can solve this issue?

No, OP put that in a separate comment because they didn't include those details in the original post.

**Comment by natanfeitosa** [comment]
Some errors can be solved changing the `client` on `InnerTube` class from **ANDROID** to **WEB**

I'm using the last version on Python 3.8

**Comment by TheDeterminator** [comment]
Are the maintainers working on this? I'm trying to use langchain's youtube loader which relies on this package but this error is blocking that.

**Comment by ZederBreys** [comment]
> Some errors can be solved changing the `client` on `InnerTube` class from **ANDROID** to **WEB**
> 
> I'm using the last version on Python 3.8

Thank you, it worked for me.
I use pytube to get the video info, and yt_dlp to download it
