### ISSUE TITLE
[BUG] Pytube Is broke. Anyone have the fix? Not opposed to building it myself like I did a few months again.

### ISSUE THREAD

**Issue by boardkeystown** [pytube/pytube#1609]
pytube https://www.youtube.com/watch?v=YOiXGBuoq0M
Loading video...
Traceback (most recent call last):
  File "/home/blackbox/.local/bin/pytube", line 8, in <module>
    sys.exit(main())
  File "/home/blackbox/.local/lib/python3.8/site-packages/pytube/cli.py", line 53, in main
    _perform_args_on_youtube(youtube, args)
  File "/home/blackbox/.local/lib/python3.8/site-packages/pytube/cli.py", line 60, in _perform_args_on_youtube
    download_highest_resolution_progressive(
  File "/home/blackbox/.local/lib/python3.8/site-packages/pytube/cli.py", line 474, in download_highest_resolution_progressive
    stream = youtube.streams.get_highest_resolution()
  File "/home/blackbox/.local/lib/python3.8/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "/home/blackbox/.local/lib/python3.8/site-packages/pytube/__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "/home/blackbox/.local/lib/python3.8/site-packages/pytube/__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
KeyError: 'streamingData'

**Comment by mstyushin** [comment]
Got the same thing this week. The only fix I end up with for now is to set kwargs **use_oauth** and **allow_oauth_cache**, like this:
```
from pytube import YouTube
video = YouTube(video_url, use_oauth=True, allow_oauth_cache=True)
```
which will force you to login from your local browser (obviously).

**Comment by AlexanderGermek** [comment]
> Got the same thing this week. The only fix I end up with for now is to set kwargs **use_oauth** and **allow_oauth_cache**, like this:
> 
> ```
> from pytube import YouTube
> video = YouTube(video_url, use_oauth=True, allow_oauth_cache=True)
> ```
> 
> which will force you to login from your local browser (obviously).

but that doesn't solve the problem if pytube is on the server (like railways)

**Comment by AtharvaSolanki** [comment]
> Got the same thing this week. The only fix I end up with for now is to set kwargs **use_oauth** and **allow_oauth_cache**, like this:
> 
> ```
> from pytube import YouTube
> video = YouTube(video_url, use_oauth=True, allow_oauth_cache=True)
> ```
> 
> which will force you to login from your local browser (obviously).

it's not working now

**Comment by PeterPark07** [comment]
I get the same error . Is there no fix? Why is the library not being updated with a fix

**Comment by RONNCC** [comment]
Can you check with current master if it's fixed --> otherwise definitely would love PRs to fix :-)

**Comment by kuba1302** [comment]
Same error, package is not usable. When can we expect fix?

**Comment by lotuswalking** [comment]
> > Got the same thing this week. The only fix I end up with for now is to set kwargs **use_oauth** and **allow_oauth_cache**, like this:
> > ```
> > from pytube import YouTube
> > video = YouTube(video_url, use_oauth=True, allow_oauth_cache=True)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which will force you to login from your local browser (obviously).
> 
> it's not working now

work to me

**Comment by nonameHEX** [comment]
> > Got the same thing this week. The only fix I end up with for now is to set kwargs **use_oauth** and **allow_oauth_cache**, like this:
> > ```
> > from pytube import YouTube
> > video = YouTube(video_url, use_oauth=True, allow_oauth_cache=True)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which will force you to login from your local browser (obviously).
> 
> but that doesn't solve the problem if pytube is on the server (like railways)

Don't know how it works on servers (I assume you can't login in some google account with oauth), but I found some solution that works (it is solved somewhere in issues, not my idea).
You can still download without oauth if you change ANDROID to WEB in innertube.py (pytube.innertube)
```
class InnerTube:
    """Object for interacting with the innertube API."""
    def __init__(self, client='WEB', use_oauth=False, allow_cache=True):
```
But warning, if you do this you will download like 5 minutes video in 5 or maybe more minutes. It is super slow download, but works without oauth.

**Comment by RONNCC** [comment]
@kuba1302  can you post a bug with details on what's broken (+ a potential PR to fix it)

**Comment by jamesslinger** [comment]
I've also been having this issue for a while now. Can anyone confirm the exact reason for this to happen? Is it changes from Google/YouTube's side that have broken Pytube? 

Does anyone have any alternatives to recommend?

**Comment by RONNCC** [comment]
@jamesslinger yes - whenever youtube updates html it breaks the parsing

**Comment by jamesslinger** [comment]
> @jamesslinger yes - whenever youtube updates html it breaks the parsing

Ok ty @RONNCC, I thought so.  I've managed to solve this issue for now following the comment/solution in this thread -https://github.com/pytube/pytube/issues/1602#issuecomment-1537134848

**Comment by RONNCC** [comment]
@jamesslinger  any chance you'd be interested in a PR for the fix against master 😉 ?

**Comment by jamesslinger** [comment]
> @jamesslinger any chance you'd be interested in a PR for the fix against master 😉 ?

Alas it appears to have been short lived success, it's back to not working again :(  

I'm too much of a noob right now to consider contributing but I 100% will in the future when I'm more experienced. :-)

**Comment by boardkeystown** [comment]
> Got the same thing this week. The only fix I end up with for now is to set kwargs **use_oauth** and **allow_oauth_cache**, like this:
> 
> ```
> from pytube import YouTube
> video = YouTube(video_url, use_oauth=True, allow_oauth_cache=True)
> ```
> 
> which will force you to login from your local browser (obviously).

I HAD NO CLUE use_oauth was a option!!!!

This cool
