### ISSUE TITLE
[BUG] in getting youtube video title

### ISSUE THREAD

**Issue by nxxte** [pytube/pytube#1633]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pytube/__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 168, in <module>
    downloadmp3(bool,link,storage)
  File "app.py", line 82, in downloadmp3
    name = yt.title
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pytube/__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=yZsj4UDA61o. Please file a bug report at https://github.com/pytube/pytube

**Comment by RaymonDev** [comment]
Same thing happened to me. I'd like to think this is because of a change in YouTube's API

**Comment by ycui1128** [comment]
same error happens to me , do you know how to fix this?

**Comment by RaymonDev** [comment]
I switched packages and something similar happened

**Comment by klemonade** [comment]
You can try [this](https://github.com/pytube/pytube/issues/1597#issuecomment-1534000904), but the download speed is very low (~500kbps).

Edit 1:
I fix my lib source code according to [this commit](https://github.com/pytube/pytube/commit/c9edd68486c6ecc7b7659a67a7403eee56e22fdd#diff-eba6ec1dd2a6d16880603d383cafcf64603641bbe0524b4d6cbf65485d4b6364) and change `client` param in `innertube.py` to `WEB` and 'User-Agent' (in WEB) to `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36`

I hope this help :)

**Comment by aditya-arolkar-swe** [comment]
Same error happened for me. I think some internal API needs to be updated. Looking at `self.vid_info['playabilityStatus']['errorScreen']`: 

`{'playerErrorMessageRenderer': {'subreason': {'runs': [{'text': 'Watch on the latest version of YouTube.', 'navigationEndpoint': {'clickTrackingParams': 'CAAQu2kiEwjuk5HksqH_AhUyTkwIHWaNCRE=', 'urlEndpoint': {'url': 'market://details?id=com.google.android.youtube&url=https%3A%2F%Fwww.youtube.com%2Fwatch%3Fv%3DYFxVJ0zEdMU', 'target': 'TARGET_NEW_WINDOW'}}}]}, 'learnMore': {'runs': [{'text': 'Learn more', 'navigationEndpoint': {'clickTrackingParams': 'CAAQu2kiEwjuk5HksqH_AhUyTkwIHWaNCRE=', 'urlEndpoint': {'url': '//support.google.com/youtube/answer/12318250?hl=en', 'target': 'TARGET_NEW_WINDOW'}}}]}, 'reason': {'runs': [{'text': 'The following content is not available on this app.'}]}, 'thumbnail': {'thumbnails': [{'url': '//s.ytimg.com/yts/img/meh7-vflGevej7.png', 'width': 140, 'height': 100}, {'url': '//s.ytimg.com/yts/img/meh7-vflGevej7.png', 'width': 140, 'height': 100}]}}}`

**Comment by aditya-arolkar-swe** [comment]
> You can try [this](https://github.com/pytube/pytube/issues/1597#issuecomment-1534000904), but the download speed is very low (~500kbps).
> 
> Edit 1: I fix my lib source code according to [this commit](https://github.com/pytube/pytube/commit/c9edd68486c6ecc7b7659a67a7403eee56e22fdd#diff-eba6ec1dd2a6d16880603d383cafcf64603641bbe0524b4d6cbf65485d4b6364) and change `client` param in `innertube.py` to `WEB` and 'User-Agent' (in WEB) to `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36`
> 
> I hope this help :)

This worked for me, but yes download speed was noticeably slower
