### ISSUE TITLE
[BUG] RegexMatchError

### ISSUE THREAD

**Issue by Max-Pare** [pytube/pytube#1637]
**Describe the bug**
pytube.Channel(url) raises regex error

**To Reproduce**
- [The video or playlist url that is causing the error.](https://www.youtube.com/Zeb89)
- channel_link = "www.youtube.com/Zeb89/"

channel = pytube.Channel(channel_link)

**Expected behavior**
Should return channel object

**Output**
```
Traceback (most recent call last):
  File "E:\Documentoni 2\Coding\Python\download_most_popular_yt_vids\main.py", line 8, in <module>
    channel = pytube.Channel(channel_link)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maste\Python\Lib\site-packages\pytube\contrib\channel.py", line 24, in __init__
    self.channel_uri = extract.channel_name(url)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maste\Python\Lib\site-packages\pytube\extract.py", line 185, in channel_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: channel_name: could not find match for patterns
```

**System information**
Please provide the following information:
- Python 3.10.10
- Pytube version 15.0.0
- python -m pip install git+https://github.com/pytube/pytube

**Comment by preritdas** [comment]
Yes, it appears the `Channel` object doesn't perform properly. The regex error is caused by the new YouTube URL format, ex. youtube.com/name vs the old delineations with /c/ or /u/ or /channel/id etc. Even when you find the Channel ID and provide `Channel` with `url=https://youtube.com/channel/idhere` no videos are returned.

**Comment by KunalKrishna** [comment]
Notably, it is also unable to create `Channel` object for newer YTchannel url format, for example, `https://www.youtube.com/@freecodecamp` 
Problem raised at SO [Pytube and the new @ channel urls](https://stackoverflow.com/questions/74957606/pytube-and-the-new-channel-urls)

**Comment by KunalKrishna** [comment]
attempted following fix : 
added to `extract.py`
line 163    - :samp:`https://youtube.com/@{channel_name}/*` 
line 176    `r"(?:@([%\w\d_\-]+)(\/.*)?)"`
but in vain

**Comment by danielgwilson** [comment]
+1, definitely an issue 💀

**Comment by akash-sarvam** [comment]
Yes, please support the usage of the new Channel Handle format of URL (e.g. `https://www.youtube.com/@freecodecamp`). Working with manually copy-pasted URLs from the address bar is unnecessarily difficult in the current form because this support is lacking.

**Comment by Apoc182** [comment]
Just a workaround for anyone having this problem. Tried to keep it very simple with few dependencies:

```
import requests
import re

def convert_url(url: str) -> str:
    t = requests.get(url).text
    cid = re.search(r'"browseId":"(.+?)"', t).group(1)
    return "https://www.youtube.com/channel/" + cid
 ```

This will convert the @channelName url to channel/id if you at the cost of needing the requests library and an addition request.
