### ISSUE TITLE
KeyError: 'captionTracks'

### ISSUE THREAD

**Issue by Jukkaaf** [pytube/pytube#167]
Linux, python 3.6, pytube 7.0.10

With the following code and video, i got this traceback.
I don't get the traceback with all videos.

```
from pytube import YouTube

yt = YouTube("https://www.youtube.com/watch?v=35YpV77tGm0")
print(yt.streams.filter(only_audio=True).all())
```

```
Traceback (most recent call last):
  File "***.py", line 3, in <module>
    yt = YouTube("https://www.youtube.com/watch?v=35YpV77tGm0")
  File "/home/***/Python/env/***-env/lib/python3.6/site-packages/pytube/__main__.py", line 81, in __init__
    self.prefetch_init()
  File "/home/***/Python/env/***-env/lib/python3.6/site-packages/pytube/__main__.py", line 90, in prefetch_init
    self.init()
  File "/home/***/Python/env/***-env/lib/python3.6/site-packages/pytube/__main__.py", line 129, in init
    self.initialize_caption_objects()
  File "/home/***/Python/env/***-env/lib/python3.6/site-packages/pytube/__main__.py", line 194, in initialize_caption_objects
    ['captionTracks']
KeyError: 'captionTracks'
```

**Comment by nficano** [comment]
Fixed! thanks for reporting
