### ISSUE TITLE
[BUG] Reggex errors with Kivy

### ISSUE THREAD

**Issue by ghost** [pytube/pytube#1676]
**Describe the bug**
PyTube wont work with kivy apps, every-time using pytube in kivy apps lead it to crash with the following output. 

**To Reproduce**
-   Youtube link: (Any)
-  Will Attach code if needed.

**Expected behavior**
Kivy app properly uses pytube to execute its functions.

**Output**
```
 Traceback (most recent call last):
   File "/home/sam/DevSite/main.py", line 38, in <module>
     Gatimaan().run()
   File "/usr/lib/python3/dist-packages/kivy/app.py", line 955, in run
     runTouchApp()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 339, in mainloop
     self.idle()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 383, in idle
     self.dispatch_input()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 334, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 263, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "/usr/lib/python3/dist-packages/kivy/core/window/__init__.py", line 1660, in on_motion
     self.dispatch('on_touch_down', me)
   File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "/usr/lib/python3/dist-packages/kivy/core/window/__init__.py", line 1677, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "/usr/lib/python3/dist-packages/kivy/uix/widget.py", line 589, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "/usr/lib/python3/dist-packages/kivy/uix/widget.py", line 589, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "/usr/lib/python3/dist-packages/kivy/uix/behaviors/button.py", line 151, in on_touch_down
     self.dispatch('on_press')
   File "kivy/_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1191, in kivy._event.EventObservers._dispatch
   File "/usr/lib/python3/dist-packages/kivy/lang/builder.py", line 55, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "/home/sam/DevSite/gatimaan.kv", line 48, in <module>
     on_press: root.press()
   File "/home/sam/DevSite/main.py", line 20, in press
     yt = YouTube(link)
   File "/home/sam/.local/lib/python3.10/site-packages/pytube/__main__.py", line 71, in __init__
     self.video_id = extract.video_id(url)
   File "/home/sam/.local/lib/python3.10/site-packages/pytube/extract.py", line 133, in video_id
     return regex_search(r"(?:v=|\/)([0-9A-Za-z_-]{11}).*", url, group=1)
   File "/home/sam/.local/lib/python3.10/site-packages/pytube/helpers.py", line 129, in regex_search
     raise RegexMatchError(caller="regex_search", pattern=pattern)
 pytube.exceptions.RegexMatchError: regex_search: could not find match for (?:v=|\/)([0-9A-Za-z_-]{11}).*
```

**System information**
- Python version:  Python 3.10.6
- Pytube version: '15.0.0'
- Command used to install pytube
(first pip and then the issue template recommended method)

**Comment by CapeCrusader321** [comment]
The main-code file --> https://git.launchpad.net/gatimaan/tree/main.py?h=main
