### ISSUE TITLE
[BUG] FIX

### ISSUE THREAD

**Issue by oncename** [pytube/pytube#1684]
fully working code pytube 

https://github.com/oncename/pytube/tree/master

fix cipher.py

    function_patterns = [
        # https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-865985377
        # https://github.com/yt-dlp/yt-dlp/commit/48416bc4a8f1d5ff07d5977659cb8ece7640dcd8
        # var Bpa = [iha];
        # ...
        # a.C && (b = a.get("n")) && (b = Bpa[0](b), a.set("n", b),
        # Bpa.length || iha("")) }};
        # In the above case, `iha` is the relevant function name
        r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&.*?\|\|\s*([a-z]+)',
        r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])?\([a-z]\)',
    ]

**Comment by FormulaCarbon** [comment]
worked for me! thanks!
pytube 15.0.0
python 3.11
windows 11

**Comment by oncename** [comment]
> worked for me! thanks! pytube 15.0.0 python 3.11 windows 11

cd Documents
git clone https://github.com/oncename/pytube.git
cd pytube
pip install .

**Comment by EterneralAmbivalence** [comment]
Worked for me!
pytube 15.0.0
python 3.8.5
Windows 7

**Comment by al102030** [comment]
Worked for me!
pytube 15.0.0
python 3.11.3
Ubuntu 22.04

Thanks

**Comment by Wvopper** [comment]
> > worked for me! thanks! pytube 15.0.0 python 3.11 windows 11
> 
> cd Documents git clone https://github.com/oncename/pytube.git cd pytube pip install .

Maybe I've done something wrong, but it didn't worked to me:
pytube 15.0.0
python 3.10
Windows 11

`from pytube import YouTube
import os

# url = 'https://www.youtube.com/watch?v=a-aSBztW0JE'
url = 'https://www.youtube.com/watch?v=BVjROQirpkk'
flag = True
while flag:
    video = YouTube(url)
    audio = video.streams.filter(file_extension='mp4').first()
    audio.download("stack")
    for elem in os.scandir('stack'):
        file = elem.name
        print(file)
    flag = False
`

response is:
`Traceback (most recent call last):
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\test_script.py", line 13, in <module>
    audio = video.streams.filter(file_extension='mp4').first()
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple`

**Comment by projacktor** [comment]
> > worked for me! thanks! pytube 15.0.0 python 3.11 windows 11
> 
> cd Documents git clone https://github.com/oncename/pytube.git cd pytube pip install .

Maybe I've done something wrong, but it didn't worked to me:
pytube 15.0.0
python 3.10
Windows 11

`from pytube import YouTube
import os
url = 'https://www.youtube.com/watch?v=BVjROQirpkk'
flag = True
while flag:
    video = YouTube(url)
    audio = video.streams.filter(file_extension='mp4').first()
    audio.download("stack")
    for elem in os.scandir('stack'):
        file = elem.name
        print(file)
    flag = False
`

response is:
`Traceback (most recent call last):
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\test_script.py", line 13, in <module>
    audio = video.streams.filter(file_extension='mp4').first()
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple`

**Comment by kekewind** [comment]
> fully working code pytube
> 
> https://github.com/oncename/pytube/tree/master
> 
> fix cipher.py
> 
> ```
> function_patterns = [
>     # https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-865985377
>     # https://github.com/yt-dlp/yt-dlp/commit/48416bc4a8f1d5ff07d5977659cb8ece7640dcd8
>     # var Bpa = [iha];
>     # ...
>     # a.C && (b = a.get("n")) && (b = Bpa[0](b), a.set("n", b),
>     # Bpa.length || iha("")) }};
>     # In the above case, `iha` is the relevant function name
>     r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&.*?\|\|\s*([a-z]+)',
>     r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])?\([a-z]\)',
> ]
> ```
def get_throttling_function_name(js: str) -> str

**Comment by kekewind** [comment]
> pytube 15.0.0
> python 3.9
win10    ok  ，FIX

**Comment by MasterCruelty** [comment]
I confirm this fix on <code>cipher.py</code> works.

**Comment by machnine** [comment]
> > > worked for me! thanks! pytube 15.0.0 python 3.11 windows 11
> > 
> > 
> > cd Documents git clone https://github.com/oncename/pytube.git cd pytube pip install .
> 
> Maybe I've done something wrong, but it didn't worked to me: pytube 15.0.0 python 3.10 Windows 11
> 
> `from pytube import YouTube import os url = 'https://www.youtube.com/watch?v=BVjROQirpkk' flag = True while flag: video = YouTube(url) audio = video.streams.filter(file_extension='mp4').first() audio.download("stack") for elem in os.scandir('stack'): file = elem.name print(file) flag = False `
> 


**_v15.0.0_** itself does not work! You either need to modify cipher.py (modified last year) as described by @onename above, or clone and install the current master branch (cipher.py modified 3 days ago)

**Comment by HJ1722** [comment]
Fix on cipher.py it works!
python 3.6.9
pytube 12.1.3
ubuntu 18.04

**Comment by apurohit** [comment]
Can confirm this works. 
python 3.11
pytube 12.1.3
ubuntu server 23.04
mopidy-ytmusic 0.3.8 (this requires pytube 12.1.3 as of now)

**Comment by projacktor** [comment]
> function_patterns = [
>     # https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-865985377
>     # https://github.com/yt-dlp/yt-dlp/commit/48416bc4a8f1d5ff07d5977659cb8ece7640dcd8
>     # var Bpa = [iha];
>     # ...
>     # a.C && (b = a.get("n")) && (b = Bpa[0](b), a.set("n", b),
>     # Bpa.length || iha("")) }};
>     # In the above case, `iha` is the relevant function name
>     r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&.*?\|\|\s*([a-z]+)',
>     r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])?\([a-z]\)',
> ]

Got it dude, thanks. But after fixing there born another mistake

`pytube.exceptions.RegexMatchError: regex_search: could not find match for ema=function\(\w\){[a-z=\.\(\"\)]*;(.*);(?:.+)}`

**Comment by Zebra-0** [comment]
can confirm this cipher.py works for me.
python version: 3.10
Win 10
pytube 15.0.0

**Comment by oncename** [comment]
WIN
cd Documents
git clone https://github.com/oncename/pytube.git
cd pytube
pip install .

linux
sudo apt install git
cd ~
git clone https://github.com/oncename/pytube.git
cd pytube
pip install .

links
https://github.com/oncename/pytube

**Comment by davidgiesemann** [comment]
Confirming this works. Hoping this will be merged soon.

**Comment by cliffcr** [comment]
Just another confirmation - The worked fine for me.

**Comment by jack-fleenor** [comment]
For anyone running into a similar issue in MacOS make sure to do the following:

```A quick google search returns the following: http://blog.wafrat.com/fixing-certificate_verify_failed-when-using-yfinances-ticker-info/

As explained in the website linked above, the issue is due to:

    It turns out it's because I am running Python on Mac OS and I need to install some certificates ([Mac OSX python ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)](https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify)).

And the solution is to:

    So I opened Finder and navigated to Applications, Python 3.7, then ran Install Certificates.command. And it worked indeed!```
    
  source: https://stackoverflow.com/questions/68275857/urllib-error-urlerror-urlopen-error-ssl-certificate-verify-failed-certifica

**Comment by HsdKiat2** [comment]
pyhon 3.10.11 
windows 1o
pytube 15.0.0 
not working,
before this pytube version working fine.

**Comment by MyLastSerenade** [comment]
this fix worked for me
Win 10
python 3.10.7
pytube 15.0.0

**Comment by Xazratbek** [comment]
i was fix cipher.py but not working

```

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming projects\Telegram bots\islam-uz-bot\handlers\users\yt_audio.py", line 39, in get_audio
    audio = url.streams.filter(only_audio=True)
            ^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
             ^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\cipher.py", line 29, in __init__
    self.transform_plan: List[str] = get_transform_plan(js)
                                     ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\cipher.py", line 194, in get_transform_plan
    return regex_search(pattern, js, group=1).split(";")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\helpers.py", line 129, in regex_search
    raise RegexMatchError(caller="regex_search", pattern=pattern)
pytube.exceptions.RegexMatchError: regex_search: could not find match for fma=function\(\w\){[a-z=\.\(\"\)]*;(.*);(?:.+)}
```

**Comment by MyLastSerenade** [comment]
> i was fix cipher.py but not working
> 
> ```
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
>     for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
>                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
>     return await asyncio.gather(*tasks)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
>     response = await handler_obj.handler(*args, **partial_data)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
>     return await self.message_handlers.notify(update.message)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
>     response = await handler_obj.handler(*args, **partial_data)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Programming projects\Telegram bots\islam-uz-bot\handlers\users\yt_audio.py", line 39, in get_audio
>     audio = url.streams.filter(only_audio=True)
>             ^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\__main__.py", line 296, in streams
>     return StreamQuery(self.fmt_streams)
>                        ^^^^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\__main__.py", line 188, in fmt_streams
>     extract.apply_signature(stream_manifest, self.vid_info, self.js)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\extract.py", line 409, in apply_signature
>     cipher = Cipher(js=js)
>              ^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\cipher.py", line 29, in __init__
>     self.transform_plan: List[str] = get_transform_plan(js)
>                                      ^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\cipher.py", line 194, in get_transform_plan
>     return regex_search(pattern, js, group=1).split(";")
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\helpers.py", line 129, in regex_search
>     raise RegexMatchError(caller="regex_search", pattern=pattern)
> pytube.exceptions.RegexMatchError: regex_search: could not find match for fma=function\(\w\){[a-z=\.\(\"\)]*;(.*);(?:.+)}
> ```

Use https://github.com/oncename/pytube/tree/master this pytube, this has a fixed cipher.py
