### ISSUE TITLE
[BUG] pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

### ISSUE THREAD

**Issue by ghost** [pytube/pytube#1690]
Traceback (most recent call last):
  File "C:\Users\Vee\anaconda3\lib\site-packages\pytube\__main__.py", line 181, in 
fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\Vee\anaconda3\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
nit__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\Vee\anaconda3\lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\Vee\anaconda3\lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\Users\Vee\anaconda3\lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Vee\Desktop\slowed reverb\Slowed-Reverb\test.py", line 2, in <module>
    YouTube('https://www.youtube.com/watch?').streams.first().download()  
  File "C:\Users\Vee\anaconda3\lib\site-packages\pytube\__main__.py", line 296, in 
streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\Vee\anaconda3\lib\site-packages\pytube\__main__.py", line 188, in 
fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\Vee\anaconda3\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\Vee\anaconda3\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\Vee\anaconda3\lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\Vee\anaconda3\lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\Users\Vee\anaconda3\lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

**Comment by RichardBaoLei** [comment]
same issue, please fix it~ thanks

**Comment by zaneghost** [comment]
FIX in https://github.com/pytube/pytube/issues/1684

**Comment by paichiwo** [comment]
same here

**Comment by codingbotPark** [comment]
me too help me

**Comment by ghost** [comment]
Please checkout this PR in which I resolved this issue - https://github.com/pytube/pytube/pull/1691

**Comment by paichiwo** [comment]
great, fix worked !!! :)

**Comment by allenkiakshay** [comment]
change in function patterns in cipher file to =
[
r'a.[a-zA-Z]\s*&&\s*([a-z]\s*=\sa.get("n"))\s&&.?||\s([a-z]+)',
r'([a-z]\s*=\s*([a-zA-Z0-9$]+)([\d+])?([a-z])',
]

(line 264 in cipher file of pytube model)

**Comment by NullVoidKage** [comment]
Currently experiencing this on my app

**Comment by WCSin01** [comment]
Currently facing this issue with some videos

**Comment by lanuma** [comment]
i have fast fixing to my repo
`pip install pytube-lanuma`

you can temporary use this package until developer merge the package update

**Comment by ShubhamSalokhe** [comment]
Use this 
```
from pytube import YouTube
import re
def custom_youtube_url_get(youtube_url:str):
    yt = YouTube(youtube_url)

    metadata= yt.streaming_data
    adaptiveFormats_list = metadata.get("adaptiveFormats")

    if adaptiveFormats_list:
        get_highest_resolution = dict()

        bitrate = 0
        for adaptiveFormat in adaptiveFormats_list:
            pattern_found = re.search("video/mp4;", adaptiveFormat.get("mimeType"))
            if pattern_found:
                if bitrate < int(adaptiveFormat.get("bitrate")):
                    # print(adaptiveFormat["bitrate"])
                    bitrate = int(adaptiveFormat.get("bitrate"))
                    get_highest_resolution:dict = adaptiveFormat

        if get_highest_resolution:
            return get_highest_resolution.get("url")
        
    return None
```

**Comment by AtharvaSolanki** [comment]
just download cipher.py file from the repository and replace it with the existing cipher.py file in ur destination where pytube is installed, then it will work

**Comment by NullVoidKage** [comment]
How can I do it on my deployed website it seems the changes haven't been merge yet

**Comment by Rycia** [comment]
Having this issue still. Needs a push request to an official version

**Comment by Rycia** [comment]
> i have fast fixing to my repo `pip install pytube-lanuma`
> 
> you can temporary use this package until developer merge the package update

This returns a error:
HTTP Error 403: Forbidden
