### ISSUE TITLE
[BUG] pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

### ISSUE THREAD

**Issue by allenkiakshay** [pytube/pytube#1692]
Traceback (most recent call last):
  File "C:\python\lib\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\python\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\python\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\python\lib\site-packages\pytube\cipher.py", line 406, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\python\lib\site-packages\pytube\cipher.py", line 312, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\python\lib\site-packages\pytube\cipher.py", line 297, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\IITB\youtube to video\y2v.py", line 6, in <module>
    video.streams.first().download()
  File "C:\python\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\python\lib\site-packages\pytube\__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\python\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\python\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\python\lib\site-packages\pytube\cipher.py", line 406, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\python\lib\site-packages\pytube\cipher.py", line 312, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\python\lib\site-packages\pytube\cipher.py", line 297, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

**Comment by ashmitkx** [comment]
patch cipher.py from https://github.com/pytube/pytube/pull/1691

**Comment by allenkiakshay** [comment]
r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&.?\|\|\s([a-z]+)',
r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])?\([a-z]\)',

(line 264,265 in cipher file of pytube model replace with these lines)

**Comment by Kuchizu** [comment]
> change in function patterns in cipher to = [ r'a.[a-zA-Z]\s*&&\s*([a-z]\s*=\s_a.get("n"))\s_&&.?||\s([a-z]+)', r'([a-z]\s*=\s*([a-zA-Z0-9$]+)([\d+])?([a-z])', ]
> 
> (line 264 in cipher file of pytube model)

error('missing ), unterminated subpattern at position 0')

**Comment by allenkiakshay** [comment]
> > change in function patterns in cipher to = [ r'a.[a-zA-Z]\s*&&\s*([a-z]\s*=\s_a.get("n"))\s_&&.?||\s([a-z]+)', r'([a-z]\s*=\s*([a-zA-Z0-9$]+)([\d+])?([a-z])', ]
> > (line 264 in cipher file of pytube model)
> 
> error('missing ), unterminated subpattern at position 0')

replace line 264,265 with these lines

r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&.?\|\|\s([a-z]+)',
r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])?\([a-z]\)',

**Comment by Kuchizu** [comment]
> > > change in function patterns in cipher to = [ r'a.[a-zA-Z]\s*&&\s*([a-z]\s*=\s_a.get("n"))\s_&&.?||\s([a-z]+)', r'([a-z]\s*=\s*([a-zA-Z0-9$]+)([\d+])?([a-z])', ]
> > > (line 264 in cipher file of pytube model)
> > 
> > 
> > error('missing ), unterminated subpattern at position 0')
> 
> replace line 264,265 with these lines
> 
> r'a.[a-zA-Z]\s*&&\s*([a-z]\s*=\s_a.get("n"))\s_&&.?||\s([a-z]+)', r'([a-z]\s*=\s*([a-zA-Z0-9$]+)([\d+])?([a-z])',

Replaced, now those lines looks like this

```
        The name of the function used to compute the throttling parameter.
    """
    function_patterns = [
        r'a.[a-zA-Z]\s*&&\s*([a-z]\s*=\sa.get("n"))\s&&.?||\s([a-z]+)',
        r'([a-z]\s*=\s*([a-zA-Z0-9$]+)([\d+])?([a-z])',
        # https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-865985377
        # https://github.com/yt-dlp/yt-dlp/commit/48416bc4a8f1d5ff07d5977659cb8ece7640dcd8
        # var Bpa = [iha];
        # ...
        # a.C && (b = a.get("n")) && (b = Bpa[0](b), a.set("n", b),
        # Bpa.length || iha("")) }};
        # In the above case, `iha` is the relevant function name
        r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&\s*'
        r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])?\([a-z]\)',
    ]
    logger.debug('Finding throttling function name')
```

But I'm still getting error:
error('missing ), unterminated subpattern at position 0')

**Comment by WilsonRock** [comment]
Why isn't the change in the main repository?

**Comment by ishfaq034346** [comment]
Date:Dec,24,2023
This is my code
"from pytube import YouTube
from pytube.exceptions import VideoUnavailable

try:
    yt = YouTube('http://youtube.com/watch?v=2lAe1cqCOXo')
    print(yt.title)
except VideoUnavailable as e:
    print(e)
"

But it shows me this error

"Traceback (most recent call last):
  File "C:\Users\ISHFAQ AHMAD\OneDrive\Desktop\pycarm projects\trying_pytube.py", line 5, in <module>
    yt = YouTube('http://youtube.com/watch?v=2lAe1cqCOXo')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python 3.12.0\Lib\site-packages\pytube\__main__.py", line 91, in __init__
    self.prefetch()
  File "C:\python 3.12.0\Lib\site-packages\pytube\__main__.py", line 181, in prefetch
    self.vid_info_raw = request.get(self.vid_info_url)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python 3.12.0\Lib\site-packages\pytube\request.py", line 36, in get
    return _execute_request(url).read().decode("utf-8")
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\python 3.12.0\Lib\site-packages\pytube\request.py", line 24, in _execute_request
    return urlopen(request)  # nosec
           ^^^^^^^^^^^^^^^^
  File "C:\python 3.12.0\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python 3.12.0\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\python 3.12.0\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\python 3.12.0\Lib\urllib\request.py", line 553, in error
    result = self._call_chain(*args)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python 3.12.0\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\python 3.12.0\Lib\urllib\request.py", line 745, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python 3.12.0\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\python 3.12.0\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\python 3.12.0\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python 3.12.0\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\python 3.12.0\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: Gone"
