### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by eopexd** [pytube/pytube#1695]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\eopex\PycharmProjects\projectpy1\venv\Lib\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\eopex\PycharmProjects\projectpy1\venv\Lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
             ^^^^^^^^^^^^^
  File "C:\Users\eopex\PycharmProjects\projectpy1\venv\Lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eopex\PycharmProjects\projectpy1\venv\Lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eopex\PycharmProjects\projectpy1\venv\Lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eopex\PycharmProjects\projectpy1\venv\Lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\eopex\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "D:\pypro\downloader.py", line 55, in Download
    videoStream = getVideo.streams.get_highest_resolution()
                  ^^^^^^^^^^^^^^^^
  File "C:\Users\eopex\PycharmProjects\projectpy1\venv\Lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\eopex\PycharmProjects\projectpy1\venv\Lib\site-packages\pytube\__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\eopex\PycharmProjects\projectpy1\venv\Lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
             ^^^^^^^^^^^^^
  File "C:\Users\eopex\PycharmProjects\projectpy1\venv\Lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eopex\PycharmProjects\projectpy1\venv\Lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eopex\PycharmProjects\projectpy1\venv\Lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eopex\PycharmProjects\projectpy1\venv\Lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

**Comment by dzyphr** [comment]
experiencing this on every call after recently trying to use pytube

**Comment by ghost** [comment]
function_patterns = [
    # https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-865985377
    # https://github.com/yt-dlp/yt-dlp/commit/48416bc4a8f1d5ff07d5977659cb8ece7640dcd8
    # var Bpa = [iha];
    # ...
    # a.C && (b = a.get("n")) && (b = Bpa[0](b), a.set("n", b),
    # Bpa.length || iha("")) }};
    # In the above case, `iha` is the relevant function name
    r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&.*?\|\|\s*([a-z]+)',
    r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])?\([a-z]\)',
]

#fix cipher.py

**Comment by dzyphr** [comment]
> function_patterns = [ # https://github.com/[ytdl-org/youtube-dl/issues/29326](https://github.com/ytdl-org/youtube-dl/issues/29326)#issuecomment-865985377 # https://github.com/yt-dlp/yt-dlp/commit/48416bc4a8f1d5ff07d5977659cb8ece7640dcd8 # var Bpa = [iha]; # ... # a.C && (b = a.get("n")) && (b = Bpa[0](b), a.set("n", b), # Bpa.length || iha("")) }}; # In the above case, `iha` is the relevant function name r'a.[a-zA-Z]\s*&&\s*([a-z]\s*=\s_a.get("n"))\s_&&._?||\s_([a-z]+)', r'([a-z]\s*=\s*([a-zA-Z0-9$]+)([\d+])?([a-z])', ]
> 
> #fix cipher.py

This does not fix the error I am experiencing

**Comment by ghost** [comment]
I have the same error and working now 😅
You can try

**Comment by dzyphr** [comment]
> I have the same error and working now 😅 You can try

Do I just need to modify cipher.py with this patch? If so it does not work. Any further steps to take?

**Comment by eopexd** [comment]
> > I have the same error and working now 😅 You can try
> 
> Do I just need to modify cipher.py with this patch? If so it does not work. Any further steps to take?

i tried modifying cipher.py and it worked for me , so i believe that is all it takes. 
but some people said it only fixes it locally , so if you have a website i am afraid it might not work.
