### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Jameel9** [pytube/pytube#1699]
I did installed pytube using the code below
 `python -m pip install git+https://github.com/pytube/pytube`.
but when I tried to download this video (https://youtu.be/9wjyGxF9to8), I got this error
Traceback (most recent call last):
  File "C:\Users\Lenovo\miniconda3\lib\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\Lenovo\miniconda3\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\Lenovo\miniconda3\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\Lenovo\miniconda3\lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\Lenovo\miniconda3\lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\Users\Lenovo\miniconda3\lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\Downloads\YouTube\youtube.py", line 10, in <module>
    yt.streams.filter(file_extension='mp4')
  File "C:\Users\Lenovo\miniconda3\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\Lenovo\miniconda3\lib\site-packages\pytube\__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\Lenovo\miniconda3\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\Lenovo\miniconda3\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\Lenovo\miniconda3\lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\Lenovo\miniconda3\lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\Users\Lenovo\miniconda3\lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

**System information**
- Python version (3.10.9)
- I updated python to 3.11.3 and still getting the same error.

**Comment by fabcotech** [comment]
I have this exact same error ! It seems that something has changed in the API or whichever web service pytube connects to !

**Comment by fabcotech** [comment]
Apparently it has been identified and resolve, but I don't see a new release not, or release version. I'm quite confused. See [https://github.com/pytube/pytube/pull/1691](https://github.com/pytube/pytube/pull/1691) can someone help ? We're supposed to patch something ?

**Comment by fabcotech** [comment]
This bug is resolved but in a pending PR. You have to manually patch the `cipher.py` like in the PR [https://github.com/pytube/pytube/pull/1691/files](https://github.com/pytube/pytube/pull/1691/files), in your case the file is at `C:\Users\Lenovo\miniconda3\lib\site-packages\pytube\cipher.py`

**Comment by jahknem** [comment]
patching cipher.py did not help in my case. I have the same error. But maybe changing the file was not enough for patching.. on colab. Waiting for a release :/

**Comment by deadzg** [comment]
I have applied the patch for cypher.py from [patch](https://github.com/pytube/pytube/pull/1691/files)  and it worked. 
Thanks

**Comment by allenkiakshay** [comment]
it was solved here by changing in cipher #1692

**Comment by lbatistuta** [comment]
> This bug is resolved but in a pending PR. You have to manually patch the `cipher.py` like in the PR https://github.com/pytube/pytube/pull/1691/files, in your case the file is at `C:\Users\Lenovo\miniconda3\lib\site-packages\pytube\cipher.py`

Was able to patch as instructed

**Comment by Janiekmulder** [comment]
> it was solved here by changing in cipher #1692

The solution in this answer worked for me. Thank you!

But now I have to authorized me to Google for two times. Not so funny.

`Please open https://www.google.com/device and input code ZLP-XMN-WBP
Press enter when you have completed this step.
Please open https://www.google.com/device and input code JTWW-QPRH
Press enter when you have completed this step.
`

After that the download is starting fine.

**Comment by jahknem** [comment]
I don't think this bug should be closed until the PR #1691 has been merged. This bug is a showstopper until patched.

**Comment by XavierLarrea** [comment]
18 august  2023 same error with cipher.py changed. Uninstalled Pytube and new instalation works fine with no change.

**Comment by zerrouki95samir** [comment]
Hello!. Facing the same issue!. Any solution ?

**Comment by limFakson** [comment]
The issue was closed but nothing has been updated, over a year now

**Comment by limFakson** [comment]
> Hello!. Facing the same issue!. Any solution ?

please do you know any other lib for yt dl

**Comment by XavierLarrea** [comment]
Try pytubefix... latest version is working fine

**Comment by limFakson** [comment]
Thanks i will check it out
