### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Mradr** [pytube/pytube#1700]
pytube-15.0.0
Python 3.10
Windows 11

```
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 378, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Owner\Desktop\Naby_AI\ai.py", line 348, in on_message
    audio = yt.streams.first()
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 295, in streams
    self.check_availability()
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 231, in check_availability
    raise exceptions.VideoUnavailable(video_id=self.video_id)
pytube.exceptions.VideoUnavailable: lrprp7mqr7c is unavailable

```
Error trying to use your example - use your example and put in the url... doesnt work

**Comment by amyrot** [comment]
having the same issue but only with shorts that are unavailable if not logged in. But I've authorized an account, normal-sized age restricted videos work fine and those shorts are available in browser.
