### ISSUE TITLE
[BUG] pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

### ISSUE THREAD

**Issue by tonghyun** [pytube/pytube#1704]
**Describe the bug**

```
Failure to download from the playlist.
```

**To Reproduce**

```
DOWNLOAD_FOLDER = "./newsfactory/"

p = Playlist('https://www.youtube.com/watch?v=Vk7CMcVs2PU&list=PLpDZdhM6kelSlKqvKUwMGwbZj1OynPDMR')

for video in p.videos:
    while True:
        try:
            url = "https://www.youtube.com/watch?v=" + video.video_id
            yt = YouTube(url)
            stream = yt.streams.get_highest_resolution()
            stream.download(DOWNLOAD_FOLDER)
            f = open(DOWNLOAD_FOLDER + yt.title.replace('"', '').replace('”', '').replace('?', '') + ".log",'w', encoding='utf-8')
            f.write("URL : " + url + "\r\n")
            f.write("title : " + yt.title + "\r\n")
            f.write("length : " + str(yt.length) + "\r\n")
            f.write("author : " + yt.author)
            f.write("publish_date : " + yt.publish_date.strftime('%Y-%m-%d') + "\r\n")
            f.write("views : " + str(yt.views) + "\r\n")
            f.write("keywords : " + str(yt.keywords) + "\r\n")
            f.write("description : " + yt.description + "\r\n")
            f.write("thumbnail_url : " + yt.thumbnail_url + "\r\n")
            f.close()
        except Exception:
            continue
        break
```

**Expected behavior**

```
The videos in the file list should be downloaded.
```

**Output**

```
Traceback (most recent call last):
  File "/home/linus/.local/lib/python3.8/site-packages/pytube/__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/home/linus/.local/lib/python3.8/site-packages/pytube/extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "/home/linus/.local/lib/python3.8/site-packages/pytube/cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "/home/linus/.local/lib/python3.8/site-packages/pytube/cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "/home/linus/.local/lib/python3.8/site-packages/pytube/cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "/home/linus/.local/lib/python3.8/site-packages/pytube/cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "youtube.py", line 41, in <module>
    stream = yt.streams.get_highest_resolution()
  File "/home/linus/.local/lib/python3.8/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "/home/linus/.local/lib/python3.8/site-packages/pytube/__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/home/linus/.local/lib/python3.8/site-packages/pytube/extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "/home/linus/.local/lib/python3.8/site-packages/pytube/cipher.py", line 29, in __init__
    self.transform_plan: List[str] = get_transform_plan(js)
  File "/home/linus/.local/lib/python3.8/site-packages/pytube/cipher.py", line 194, in get_transform_plan
    name = re.escape(get_initial_function_name(js))
  File "/home/linus/.local/lib/python3.8/site-packages/pytube/cipher.py", line 164, in get_initial_function_name
    function_match = regex.search(js)
```

**System information**

```
Python 3.8.10
pytube 15.0.0
```

**Comment by sangram73** [comment]
i am heaving the same error when i request to pytube module to download a video from youtube link

**Comment by nklido** [comment]
+1

**Comment by Hypocrate-code** [comment]
FIX in https://github.com/pytube/pytube/issues/1684
perfectly working

**Comment by OscarW27** [comment]
Some person already solved the same issue and made a pull request: https://github.com/pytube/pytube/pull/1698

**Comment by tonghyun** [comment]
> FIX in #1684 perfectly working
That's awesome.
Installing the latest pytube as per answer in [#1684](https://github.com/pytube/pytube/issues/1684) solved the problem.

**Comment by tonghyun** [comment]
The latest version fixes the current issue, but introduces other issues.
The code used is the same as before.

Issue link
`https://i.ytimg.com/vi/RFnFnGWUBQI/hq720.jpg?v=64796645`

Output
```
Traceback (most recent call last):
  File "youtube.py", line 39, in <module>
    print("게시날짜 : ", yt.publish_date)
  File "/home/linus/.local/lib/python3.8/site-packages/pytube/__main__.py", line 323, in publish_date
    self._publish_date = extract.publish_date(self.watch_html)
  File "/home/linus/.local/lib/python3.8/site-packages/pytube/__main__.py", line 102, in watch_html
    self._watch_html = request.get(url=self.watch_url)
  File "/home/linus/.local/lib/python3.8/site-packages/pytube/request.py", line 53, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "/home/linus/.local/lib/python3.8/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1358, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
```
