### ISSUE TITLE
RegexMatchError: get_throttling_function_name: could not find match for multiple

### ISSUE THREAD

**Issue by JuanRoccia** [pytube/pytube#1707]
**Before creating an issue**

I have confirmed that I am on the latest version of pytube by installing from the source. I did this by running `!pip install git+https://github.com/pytube/pytube`.

**Describe the bug**

I'm encountering a `RegexMatchError` when trying to download a YouTube video using `pytube`. The error message suggests that the function `get_throttling_function_name` could not find a match for multiple.

**To Reproduce**

The video URL that is causing the error is [https://www.youtube.com/watch?v=Xg9ihH15Uto&ab_channel=Fireship](https://www.youtube.com/watch?v=Xg9ihH15Uto&ab_channel=Fireship).

Here is the code where the problem is occurring:
```python
from pytube import YouTube

def Download(link):
    youtubeObject = YouTube(link)
    youtubeObject = youtubeObject.streams.get_highest_resolution()
    try:
        youtubeObject.download()
    except:
        print("An error has occurred")
    print("Download is completed successfully")

link = 'https://www.youtube.com/watch?v=Xg9ihH15Uto&ab_channel=Fireship'
Download(link)
```

**Expected behavior**

I expected the video to be downloaded without any errors.

**Output**

Here is the full traceback for the exception:
```lua
RegexMatchError: get_throttling_function_name: could not find match for multiple
```

**System information**

- Python version: 3.10.12
- Pytube version: 15.0.0
- Command used to install pytube: `!pip install --upgrade pytube`

**Comment by danilofcosta** [comment]
tbm estou enfretando o mesmo problema 
na linha 
`yt.streams.filter(only_audio=True,abr='128kbps').first()`

acontece o mesmo problema relatado acima e tem esse resultado no prompt 
```
RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

RegexMatchError                           Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/pytube/cipher.py](https://localhost:8080/#) in get_throttling_function_name(js)
    294                     return array[int(idx)]
    295 
--> 296     raise RegexMatchError(
    297         caller="get_throttling_function_name", pattern="multiple"
    298     )

RegexMatchError: get_throttling_function_name: could not find match for multiple)

```

> Contributing.md
>[JuanRoccia](https://github.com/JuanRoccia)

**Comment by HarshitKmr10** [comment]
Even when using `!pytube https://youtube.com/watch?v=2lAe1cqCOXo` for the youtube video on python 3.10 results in the same error. Is there any workaround for the same version ?

**Comment by schnow265** [comment]
I guess that it has to do with something on YouTube's end. I'm getting the same Error.

**Comment by XLG123** [comment]
I've been getting the same error for the past two days. I tried searching up for solutions, and tried some of them, however none of them worked.

**Comment by efeakaroz13** [comment]
My Spotify MP3 downloader script stopped working because of this.

**Comment by srccircumflex** [comment]
### solved

fix the problem by removing the `;` from the pattern in line 287 of pytube.cipher

**Comment by TerminaAS** [comment]
It's no use changing `r'var {nfunc}\s*=\s*(\[.+?\]);'.format(` the problem still exist

**Comment by srccircumflex** [comment]
Changing line 287 of pytube.cipher to exactly `'var {nfunc}\\s*=\\s*(\\[.+?])'.format(` works fine for me.
Perhaps the java scripts differ depending on the region.

**Comment by Highfish93** [comment]
erasing the ; helped me too
thanks a lot @srccircumflex

**Comment by yaitskeshav** [comment]
erasing the ; helped me too
thanks a lot @srccircumflex

**Comment by efeakaroz13** [comment]
@srccircumflex Appreciate it !

**Comment by Iyas01** [comment]
Testing the download() if is not None and removing the ";" solved it for me. Thanks @srccircumflex.

Sample code from binarysmurf with applied fixes.

```
from pytube import YouTube
path = "/Users/user_name" # substitute to where you want to place the downloaded file

def YTDownload(link):
    youTubeObject = YouTube(link)
    youTubeObject = youTubeObject.streams.get_highest_resolution()
    try:
        if youTubeObject is not None:
            youTubeObject.download(path)
    except:
        print("There has been an error.")
    
    print("All good.")
    
link = input("What video URL? ")
YTDownload(link)
```

Source:
https://www.reddit.com/r/learnpython/comments/zn014o/why_is_the_download_method_flagged_as_an_error/?onboarding_redirect=%2Fr%2Flearnpython%2Fcomments%2Fzn014o%2Fwhy_is_the_download_method_flagged_as_an_error%2F

**Comment by Realalirezayazdanpanah** [comment]
removing the ; inside the regex pattern in line 287 of file "pytube.cipher" totally fixed this!
**Thanks to @srccircumflex**

**Comment by Armag67** [comment]
@srccircumflex
Your trick works even on Python 3.11

**Comment by raghunathsmusings** [comment]
> ### solved
> fix the problem by removing the `;` from the pattern in line 287 of pytube.cipher

Thank you very much @srccircumflex. Removing ; solved the problem !

**Comment by Leonardo-DevStrom** [comment]
I'm going to make a video teaching how to make the correction, go to this channel https://www.youtube.com/channel/UCZLD0izYZI-zB20Uuof9u0w and the video will be out soon.

**Comment by DiegoMP-235** [comment]
Me funciono quitando ";" en la línea 287 del archivo "cipher.py"
I have removed the ";" in the line 287 of "cipher.py" and It works

**Comment by aleksejalex** [comment]
Hi everyone, I had the same error and erasing the semicolon in the line 287 of "cipher.py"  also worked for me (thanks https://github.com/pytube/pytube/issues/1707#issuecomment-1624586156 ). 

Please update PyTube so everyone can use my project with unchanged version of pytube.

**Comment by klebersondrl** [comment]
Erasing the semicolon in line 287 helped me too.
Thanks a lot @srccircumflex!

**Comment by allenthomas01** [comment]
Erased the semicolon on line 287 of 'cipher.py' and it got fixed. thank you so much @srccircumflex 🌟

**Comment by AkshayShineKrishna** [comment]
Erasing the semicolon in line 287 helped me too.⚡
Thanks a lot @srccircumflex

**Comment by khoul911** [comment]
if erasing the semicolon on line 287 does not work you can change the lines 272 and 273 to:

r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&.*?\|\|\s*([a-z]+)',
r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])?\([a-z]\)', ]

**Comment by YuriiMaiboroda** [comment]
In the second repexp, the square brackets must be mandatory. Need to remove the question mark after the group with them.
```py
r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&.*?\|\|\s*([a-z]+)',
r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])\([a-z]\)',
```

**Comment by Bikatr7** [comment]
To Fix:

Change in Cipher.py

Line 272 & 273 to :
```
r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&.*?\|\|\s*([a-z]+)',
r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])\([a-z]\)',
```

And remove the ';' from Line 287.

**Comment by yafethtb** [comment]
> To Fix:
> 
> Change in Cipher.py
> 
> Line 272 & 273 to :
> 
> ```
> r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&.*?\|\|\s*([a-z]+)',
> r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])\([a-z]\)',
> ```
> 
> And remove the ';' from Line 287.

This solution works when I try to follow this tutorial (https://www.tutorialspoint.com/download-video-in-mp3-format-using-pytube). 
So at least until now (July; 2024), this solution is still working.

**Comment by shubhamratrey** [comment]
> > To Fix:
> > Change in Cipher.py
> > Line 272 & 273 to :
> > ```
> > r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&.*?\|\|\s*([a-z]+)',
> > r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])\([a-z]\)',
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And remove the ';' from Line 287.
> 
> This solution works when I try to follow this tutorial (https://www.tutorialspoint.com/download-video-in-mp3-format-using-pytube). So at least until now (July; 2024), this solution is still working.

this worked for me

**Comment by liangfener** [comment]
> To Fix:
> 
> Change in Cipher.py
> 
> Line 272 & 273 to :
> 
> ```
> r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&.*?\|\|\s*([a-z]+)',
> r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])\([a-z]\)',
> ```
> 
> And remove the ';' from Line 287.

this worked for me too.thanks

**Comment by MEDBOUAYOUNE** [comment]
Still have the error even if i make this change ... ANY OTHER SOLUTION

**Comment by MEDBOUAYOUNE** [comment]
> > To Fix:
> > Change in Cipher.py
> > Line 272 & 273 to :
> > ```
> > r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&.*?\|\|\s*([a-z]+)',
> > r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])\([a-z]\)',
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And remove the ';' from Line 287.
> 
> this worked for me too.thanks

Thanks it worked

**Comment by Lucasaor** [comment]
thanks guys! that worked for me too!

**Comment by benjamincoven** [comment]
I have an error after the change:

`Traceback (most recent call last):
  File "C:\Users\Ben\Music\pytube\dl.py", line 29, in <module>
    YouTube(url).streams.filter(only_audio=True).first().download()
  File "C:\Users\Ben\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\Ben\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\Ben\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\Ben\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\Ben\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytube\cipher.py", line 411, in get_throttling_plan
    transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
AttributeError: 'NoneType' object has no attribute 'span'`

Thank you for your support

**Comment by benjamincoven** [comment]
This https://github.com/pytube/pytube/issues/1498#issuecomment-1472963944 fixed my issue and may not be related to the current issue

**Comment by lricardo09** [comment]
> To Fix:
> 
> Change in Cipher.py
> 
> Line 272 & 273 to :
> 
> ```
> r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&.*?\|\|\s*([a-z]+)',
> r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])\([a-z]\)',
> ```
> 
> And remove the ';' from Line 287.

this works! thanks a lot!

**Comment by ahmed-ansari-31** [comment]
> I have an error after the change:
> 
> `Traceback (most recent call last): File "C:\Users\Ben\Music\pytube\dl.py", line 29, in <module> YouTube(url).streams.filter(only_audio=True).first().download() File "C:\Users\Ben\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytube\__main__.py", line 296, in streams return StreamQuery(self.fmt_streams) File "C:\Users\Ben\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytube\__main__.py", line 181, in fmt_streams extract.apply_signature(stream_manifest, self.vid_info, self.js) File "C:\Users\Ben\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytube\extract.py", line 409, in apply_signature cipher = Cipher(js=js) File "C:\Users\Ben\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytube\cipher.py", line 43, in __init__ self.throttling_plan = get_throttling_plan(js) File "C:\Users\Ben\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytube\cipher.py", line 411, in get_throttling_plan transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1) AttributeError: 'NoneType' object has no attribute 'span'`
> 
> Thank you for your support

This happens when the url has no audio, 
The issue you're encountering with the video having no audio is due to the fact that some video streams, especially high-resolution ones (such as itag 137 or 313), may only contain the video stream (without audio). This is common on platforms like YouTube, where video and audio streams are often provided separately for higher resolutions.

**Comment by thisguyshouldworkforus** [comment]
This appears to be back -- I see several updates to the most recent file, but in version 8.8.0, its broken (for me) again:

```python
Traceback (most recent call last):
  File "/opt/projects/mytube/venv/lib64/python3.12/site-packages/pytubefix/__main__.py", line 287, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js, self.js_url)
  File "/opt/projects/mytube/venv/lib64/python3.12/site-packages/pytubefix/extract.py", line 455, in apply_signature
    cipher = Cipher(js=js, js_url=url_js)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/projects/mytube/venv/lib64/python3.12/site-packages/pytubefix/cipher.py", line 25, in __init__
    self.throttling_function_name = get_throttling_function_name(js, js_url)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/projects/mytube/venv/lib64/python3.12/site-packages/pytubefix/cipher.py", line 179, in get_throttling_function_name
    raise RegexMatchError(
pytubefix.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple in https://youtube.com/s/player/3bb1f723/player_ias.vflset/en_US/base.js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/projects/mytube/./dannygo.py", line 214, in <module>
    main()
  File "/opt/projects/mytube/./dannygo.py", line 128, in main
    input_audio = yt.streams.filter(adaptive=True, mime_type="audio/webm", abr="160kbps").first().download(f"{TEMP_DIR}",f"{PUBLISH_DATE}.audio.webm")
                  ^^^^^^^^^^
  File "/opt/projects/mytube/venv/lib64/python3.12/site-packages/pytubefix/__main__.py", line 637, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "/opt/projects/mytube/venv/lib64/python3.12/site-packages/pytubefix/__main__.py", line 294, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js, self.js_url)
  File "/opt/projects/mytube/venv/lib64/python3.12/site-packages/pytubefix/extract.py", line 455, in apply_signature
    cipher = Cipher(js=js, js_url=url_js)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/projects/mytube/venv/lib64/python3.12/site-packages/pytubefix/cipher.py", line 25, in __init__
    self.throttling_function_name = get_throttling_function_name(js, js_url)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/projects/mytube/venv/lib64/python3.12/site-packages/pytubefix/cipher.py", line 179, in get_throttling_function_name
    raise RegexMatchError(
pytubefix.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple in https://youtube.com/s/player/3bb1f723/player_ias.vflset/en_US/base.js
```

I tried to be an AI Coding hero, but that ended rather predictably:

```text
The get_throttling_function_name function relies on specific regex patterns to identify the throttling function name from the JavaScript file base.js. After examining both files, here are the observations and suggestions for updating the regex:

The current regex patterns in get_throttling_function_name are designed to match specific formats found in previously analyzed versions of base.js. The base.js file provided here contains highly obfuscated and minified code, and no obvious matches for the existing patterns are immediately apparent.
```

So, at present PyTubeFix is broken for me (_thanks YouTube_).

OS: RHEL 9.4
Python: 3.12
PIP: 24.3.1
PTF: 8.8.0
