### ISSUE TITLE
RegexMatchError when extracting throttling function name in PyTube

### ISSUE THREAD

**Issue by Xazratbek** [pytube/pytube#1711]
**Bug title: RegexMatchError when extracting throttling function name in PyTube
Description: " The error occurred during the handling of a previous exception. It is a pytube.exceptions.RegexMatchError and is raised when the function get_throttling_function_name in the pytube.cipher module fails to find a match for multiple patterns.

The traceback shows the sequence of function calls leading up to the error:

The error originates from the file yt_audio.py at line 39, in the get_audio function.
Within get_audio, the variable url is being accessed to filter the audio streams.
The filter function is called on url.streams, which triggers the streams property in the __main__.py module of the pytube package.
In streams, the StreamQuery class is instantiated with the fmt_streams attribute.
The fmt_streams attribute is obtained by calling apply_signature function in the extract module.
Within apply_signature, the Cipher class is instantiated, passing the js argument.
In the Cipher class constructor, the throttling_plan attribute is set by calling get_throttling_plan function.
Inside get_throttling_plan, the raw_code is assigned by calling get_throttling_function_code.
Finally, within get_throttling_function_code, the name variable is assigned by calling get_throttling_function_name.
The error occurs when get_throttling_function_name fails to find a match for multiple patterns, resulting in the RegexMatchError being raised.
To better understand and diagnose the issue, please provide the additional information requested in the previous response when reporting the bug. "**

Code snippet: 
```
@dp.message_handler(state=YouTube_audio.link)
async def get_audio(message: Message, state: FSMContext):
        link = message.text
        buffer=BytesIO()
        url=YouTube(link)
        del_msg = await message.answer("🎵 ♻️ ")

        audio = url.streams.filter(only_audio=True)
        stream = url.streams.get_by_itag(140)
        stream.download()
        print(stream)
        audio.stream_to_buffer(buffer=buffer)
        buffer.seek(0)
        filename=url.title
        await message.answer_audio(audio=buffer,caption=f"{filename}\n\n@bot_name_bot")
```

Error traceback: " 
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming projects\Telegram bots\islam-uz-bot\handlers\users\yt_audio.py", line 39, in get_audio
    audio = url.streams.filter(only_audio=True)
            ^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
             ^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple 

```
 "
Expected behavior: Get audio file of youtube video
Additional context: Provide any additional information or context that might be helpful for understanding and reproducing the issue.
-- Python version: Python 3.11.4
-- Pytube version: pytube 15.0.0
--  Command used to install pytube: pip install pytube

**Comment by Moustov** [comment]
same issue on my side

**Comment by bbkinglisbon** [comment]
I'm having the same issue. Any solution?

**Comment by Leonardo-DevStrom** [comment]
I'm using pytube version 15, and the same problem is happening.

**Comment by DJAssassin1** [comment]
me too

**Comment by IstiyakV** [comment]
me too

**Comment by Nerdnee** [comment]
I'm getting the same thing now. It was working before so I feel like Google changed something and pytube needs to adjust now. Hopefully it is a quick fix.

**Comment by DJAssassin1** [comment]
same problem and they found fix
https://github.com/pytube/pytube/issues/1707
