### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by alirezainallo** [pytube/pytube#1713]
**Describe the bug**
I have used your library as command line `pytube https://www.youtube.com/watch?v=8ET-YrNWGY8` and worked.
but today when I want to use it return me this error:

**Output**
<pre>root@ubuntu-2gb-nbg1-1:/home# pytube https://www.youtube.com/watch?v=8ET-YrNWGY8
Loading video...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pytube/__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/usr/local/lib/python3.10/dist-packages/pytube/extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "/usr/local/lib/python3.10/dist-packages/pytube/cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "/usr/local/lib/python3.10/dist-packages/pytube/cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "/usr/local/lib/python3.10/dist-packages/pytube/cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "/usr/local/lib/python3.10/dist-packages/pytube/cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pytube", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/pytube/cli.py", line 53, in main
    _perform_args_on_youtube(youtube, args)
  File "/usr/local/lib/python3.10/dist-packages/pytube/cli.py", line 60, in _perform_args_on_youtube
    download_highest_resolution_progressive(
  File "/usr/local/lib/python3.10/dist-packages/pytube/cli.py", line 474, in download_highest_resolution_progressive
    stream = youtube.streams.get_highest_resolution()
  File "/usr/local/lib/python3.10/dist-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "/usr/local/lib/python3.10/dist-packages/pytube/__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/usr/local/lib/python3.10/dist-packages/pytube/extract.py", line 409, inapply_signature
    cipher = Cipher(js=js)
  File "/usr/local/lib/python3.10/dist-packages/pytube/cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "/usr/local/lib/python3.10/dist-packages/pytube/cipher.py", line 405, inget_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "/usr/local/lib/python3.10/dist-packages/pytube/cipher.py", line 311, inget_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "/usr/local/lib/python3.10/dist-packages/pytube/cipher.py", line 296, inget_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple
</pre>

**System information**
- Python version (3.10.6)
- Pytube version (15.0.0)

I test it in my ubuntu and my cloud ubuntuServer and have same error.
have same error for download list command.

**Comment by joeyaramouni1** [comment]
I am also getting the same error.

**Comment by JulianaApolo** [comment]
same error here.

**Comment by sevyne77** [comment]
exact error too...

**Comment by CurtisDS** [comment]
I am as well

**Comment by CurtisDS** [comment]
this pull request fixed it: https://github.com/pytube/pytube/pull/1716/commits/226db37951d6c2d8f0e3e79db7b63b6956f34486

**Comment by eguar11011** [comment]
here is the solution to this problem:  https://github.com/pytube/pytube/issues/1684

**Comment by jhonLaya** [comment]
I was able to fix that error by changing the regular expressions from: (cipher.py -> get_throttling_function_name -> function_patterns) with this one and then it will work.


`function_patterns = [
    # https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-865985377
    # https://github.com/yt-dlp/yt-dlp/commit/48416bc4a8f1d5ff07d5977659cb8ece7640dcd8
    # var Bpa = [iha];
    # ...
    # a.C && (b = a.get("n")) && (b = Bpa[0](b), a.set("n", b),
    # Bpa.length || iha("")) }};
    # In the above case, iha is the relevant function name
    r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&.*?\|\|\s*([a-z]+)',
    r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])?\([a-z]\)', ]`

**Comment by Namesguy3612** [comment]
There is a semi-colon  ;  in line 287, in cipher.py remove the ; and it should work now, at least for me it did, to get to cipher.py
C:AppData\Local\Programs\Python\Python311\Lib\site-packages\pytube
