### ISSUE TITLE
Error with order_by function

### ISSUE THREAD

**Issue by callumdmay** [pytube/pytube#172]
Hi there,

I'm having an issue with the `order_by` function.

**Environment Info**

OS: 64-bit Windows 10
Using pipenv for virtual env

**Call stack:**
```
Traceback (most recent call last):
  File "tools\VideoUtils\VideoDownloader.py", line 25, in <module>
    main()
  File "tools\VideoUtils\VideoDownloader.py", line 23, in main
    vid_downloader.download(sys.argv[1], dst=PATH)
  File "tools\VideoUtils\VideoDownloader.py", line 11, in download
    YouTube(url).streams.filter(subtype='mp4').order_by('resolution').desc().first()
  File "C:\Users\callum\.virtualenvs\app-UodEtD3r\lib\site-packages\pytube\query.py", line 167, in order_by
    key=lambda s: getattr(s, attribute_name),
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

**Comment by callumdmay** [comment]
I figured out the error. For anyone viewing this, you receive a mix of audio and video streams (due to DASH) from the subtype=mp4 filter, and ordering by resolution is not applicable on an audio stream. Sorry for creating the issue!
