### ISSUE TITLE
[BUG]Nie mo -- do not download a file, program crash

### ISSUE THREAD

**Issue by mtmak9** [pytube/pytube#1720]
**Before creating an issue**

Please confirm that you are on the latest version of pytube by installing from the source.
You can do this by running `python -m pip install git+https://github.com/pytube/pytube`.
Sometimes, the pypi library repository is not up to date, and your issue may have been fixed already!

**Describe the bug**
Program do not download a file and instade get error: "Nie mo"

**To Reproduce**
Please provide the following information:

- The video or playlist url that is causing the error:
https://www.youtube.com/watch?v=vEQ8CXFWLZU

- The code where the problem is occurring.
yd = yt.streams.get_highest_resolution()

**Expected behavior**
I just checking if this function is real working and I get output that nothing tell me about what is wrong: "Nie mo"...

**Output** -- (THIS IS FULL OUTPUT WHAT I GET)
If pytube raises an exception, please provide the full traceback for the exception:
Nie mo

**System information**
Please provide the following information:
- Python version (run `python --version`):
Python 3.10.7
- Pytube version (run `print(pytube.__version__)` in python): 
15.0.0
- Command used to install pytube: 
python -m pip install git+https://github.com/pytube/pytube   

FULL CODE:
```
import pytube
from pytube import YouTube
from sys import argv

link = "https://www.youtube.com/watch?v=vEQ8CXFWLZU"
#link = argv[1]
yt = YouTube(link)

print(pytube.__version__)
print("Title: ", yt.title)
print("View: ", yt.views)
yd = yt.streams.get_highest_resolution()

yd.download("\download")
```

**Comment by 24makee** [comment]
Hi there @mtmak9 ,

I ran myself the code and this is the output that I am getting: 
```
15.0.0
Title:  3 PYTHON AUTOMATION PROJECTS FOR BEGINNERS
View:  930315
Traceback (most recent call last):
  File "/mnt/j/git_repos/pytube/testing_venv/lib/python3.10/site-packages/pytube/__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/mnt/j/git_repos/pytube/testing_venv/lib/python3.10/site-packages/pytube/extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "/mnt/j/git_repos/pytube/testing_venv/lib/python3.10/site-packages/pytube/cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "/mnt/j/git_repos/pytube/testing_venv/lib/python3.10/site-packages/pytube/cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "/mnt/j/git_repos/pytube/testing_venv/lib/python3.10/site-packages/pytube/cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "/mnt/j/git_repos/pytube/testing_venv/lib/python3.10/site-packages/pytube/cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/j/git_repos/pytube/testing_venv/canale.py", line 12, in <module>
    yd = yt.streams.get_highest_resolution()
  File "/mnt/j/git_repos/pytube/testing_venv/lib/python3.10/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "/mnt/j/git_repos/pytube/testing_venv/lib/python3.10/site-packages/pytube/__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/mnt/j/git_repos/pytube/testing_venv/lib/python3.10/site-packages/pytube/extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "/mnt/j/git_repos/pytube/testing_venv/lib/python3.10/site-packages/pytube/cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "/mnt/j/git_repos/pytube/testing_venv/lib/python3.10/site-packages/pytube/cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "/mnt/j/git_repos/pytube/testing_venv/lib/python3.10/site-packages/pytube/cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "/mnt/j/git_repos/pytube/testing_venv/lib/python3.10/site-packages/pytube/cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple
```

Currently there is a PR open (#1716 ) regarding this error  ```pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple```. Making the change from this PR locally helped in not getting the exceptions anymore and execute the line to get the video downloaded.

I suggest until the PR gets accepted to make locally the change (it's just one line).

Cheers!
