### ISSUE TITLE
[BUG] HTTP Error 410: Gone

### ISSUE THREAD

**Issue by ahmedfamhy3** [pytube/pytube#1727]
**Describe the bug**
Error happens while trying to get the video link

**To Reproduce**
from pytube import YouTube
video_url = "https://www.youtube.com/watch?v=xro9U8hTbik"
yt = YouTube(video_url)
stream = yt.streams.get_highest_resolution()
download_url = stream.url
print(download_url)

**Expected behavior**
It should had printed the video direct url

**Output**
Traceback (most recent call last):
  File "/root/badr/downloaders/youtube.py", line 3, in <module>
    yt = YouTube(video_url)
  File "/usr/local/lib/python3.10/dist-packages/pytube/__main__.py", line 91, in init
    self.prefetch()
  File "/usr/local/lib/python3.10/dist-packages/pytube/__main__.py", line 181, in prefetch
    self.vid_info_raw = request.get(self.vid_info_url)
  File "/usr/local/lib/python3.10/dist-packages/pytube/request.py", line 36, in get
    return _execute_request(url).read().decode("utf-8")
  File "/usr/local/lib/python3.10/dist-packages/pytube/request.py", line 24, in _execute_request
    return urlopen(request)  # nosec
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: Gone

**System information**
- Python version
 3.10.4
- Pytube version 15.0.0
- Command used to install pytube
 pip install --upgrade pytube

Error after doing this

**Comment by Chechere** [comment]
Same problem here

**Comment by Chechere** [comment]
Any solutions?

**Comment by JosiahFrancis** [comment]
anybody got a solution to this problem?

**Comment by johnnyhoichuen** [comment]
This might be a rare case

I keep reinstalling pytube but to no avail. Until I realise that I have both homebrew version and macos version of python 3.10, but pip keep installing on the wrong directory.

```
❯ python3 -m pip install pytube
Defaulting to user installation because normal site-packages is not writeable
Collecting pytube
  Using cached pytube-15.0.0-py3-none-any.whl.metadata (5.0 kB)
Using cached pytube-15.0.0-py3-none-any.whl (57 kB)
Installing collected packages: pytube
  WARNING: The script pytube is installed in '/Users/johnnycheng/Library/Python/3.10/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pytube-15.0.0
❯ which python3
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3
```

**be reminded that the above paths are not the same. 

As a result, I went to change the path in ~/.zshrc (in your case could be ~/.bashrc) from
export PATH=$PATH:/Library/Frameworks/Python.framework/Versions/3.7/bin
to
export PATH=$PATH:/Users/johnnycheng/Library/Python/3.10/bin

After that do source .zshrc or source .bashrc and reinstall pytube
