### ISSUE TITLE
[BUG] HTTP Error 503

### ISSUE THREAD

**Issue by Cyhne** [pytube/pytube#1748]
**Describe the bug**
Attempting to download youtube videos, receiving HTTP Error 503: Service Unavailable. 

This occurs for any video. Video ends up downloading a small portion and then exception appears. The videos are all still viewable as normal through the web browser.

**To Reproduce**
attempt to execute
`high_res_video = ytObject.streams.get_highest_resolution().download()`

**Expected behavior**
A video downloaded to the project folder.

**Output**
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Cyhne\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Cyhne\AppData\Local\Programs\Python\Python310\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\Cyhne\Desktop\Programming\YoutubeManipulator\YoutubeManipulator\YoutubeManipulator.py", line 25, in startDownload
    high_res_video = ytObject.streams.get_highest_resolution().download()
  File "C:\Users\Cyhne\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\streams.py", line 314, in download
    for chunk in request.stream(
  File "C:\Users\Cyhne\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\request.py", line 157, in stream
    response = _execute_request(
  File "C:\Users\Cyhne\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "C:\Users\Cyhne\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Cyhne\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\Cyhne\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\Cyhne\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 557, in error
    result = self._call_chain(*args)
  File "C:\Users\Cyhne\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\Cyhne\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\Cyhne\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\Cyhne\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\Cyhne\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\Cyhne\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\Cyhne\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
HTTP Error 503: Service Unavailable
```

**System information**
- Windows 10
- Python 3.10.6
- Pytube 15.0.0
- pip install pytube

**Comment by Cyhne** [comment]
Nevermind, it randomly started working again few hours later. Guess it was just a YouTube-side issue.
