### ISSUE TITLE
ERROR:root:__init__: could not find match for ^\w+\W

### ISSUE THREAD

**Issue by A7E28** [pytube/pytube#1768]
WARNING:pytube.contrib.search:Unexpected renderer encountered.
WARNING:pytube.contrib.search:Renderer name: dict_keys(['reelShelfRenderer'])
WARNING:pytube.contrib.search:Search term: tum hi ho
WARNING:pytube.contrib.search:Please open an issue at https://github.com/pytube/pytube/issues and provide this log output.
WARNING:pytube.contrib.search:Unexpected renderer encountered.
WARNING:pytube.contrib.search:Renderer name: dict_keys(['reelShelfRenderer'])
WARNING:pytube.contrib.search:Search term: tum hi ho
WARNING:pytube.contrib.search:Please open an issue at https://github.com/pytube/pytube/issues and provide this log output.
WARNING:pytube.contrib.search:Unexpected renderer encountered.
WARNING:pytube.contrib.search:Renderer name: dict_keys(['reelShelfRenderer'])
WARNING:pytube.contrib.search:Search term: tum hi ho
WARNING:pytube.contrib.search:Please open an issue at https://github.com/pytube/pytube/issues and provide this log output.
ERROR:root:__init__: could not find match for ^\w+\W

yes i am using latest version of pytube

**Comment by perfecto25** [comment]
getting same issue, pytube v 15.0.0


```

mreider@mrx:~/Downloads$ pytube "https://www.youtube.com/watch?v=-sIBAL51gxk"
Loading video...
Traceback (most recent call last):
  File "/home/mreider/.local/lib/python3.10/site-packages/pytube/__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/home/mreider/.local/lib/python3.10/site-packages/pytube/extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "/home/mreider/.local/lib/python3.10/site-packages/pytube/cipher.py", line 33, in __init__
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: __init__: could not find match for ^\w+\W

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mreider/.local/bin/pytube", line 8, in <module>
    sys.exit(main())
  File "/home/mreider/.local/lib/python3.10/site-packages/pytube/cli.py", line 53, in main
    _perform_args_on_youtube(youtube, args)
  File "/home/mreider/.local/lib/python3.10/site-packages/pytube/cli.py", line 60, in _perform_args_on_youtube
    download_highest_resolution_progressive(
  File "/home/mreider/.local/lib/python3.10/site-packages/pytube/cli.py", line 474, in download_highest_resolution_progressive
    stream = youtube.streams.get_highest_resolution()
  File "/home/mreider/.local/lib/python3.10/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "/home/mreider/.local/lib/python3.10/site-packages/pytube/__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/home/mreider/.local/lib/python3.10/site-packages/pytube/extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "/home/mreider/.local/lib/python3.10/site-packages/pytube/cipher.py", line 33, in __init__
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: __init__: could not find match for ^\w+\W

```

**Comment by A7E28** [comment]
It was working fine a few days ago

**Comment by NimaMan** [comment]
I am having a similar problem. It has stopped working this week. I come across a different error whilst using `youtube-dl` as well, which used to work last week.

**Comment by AkshayShineKrishna** [comment]
change line 30 in cipher.py to

```
var_regex = re.compile(r"^\$?\w+\W")
```

#1754

**Comment by NannoSilver** [comment]
This is affecting those that applied the patch described here: https://github.com/pytube/pytube/issues/1754#issuecomment-1675184514
It was working fine, but now no longer.

I reverted line 30 of **cipher.py** to 
`var_regex = re.compile(r"^\$*\w+\W")`
And now seems is working fine again.
