### ISSUE TITLE
[BUG] forbidden 403 error

### ISSUE THREAD

**Issue by ymk201** [pytube/pytube#1769]
**To Reproduce**
cli interface was used
pytube -r 1080p https://www.youtube.com/watch?v=vnGsr7Yk9Yg

**Expected behavior**
Can download larger file with no 403 error

**Output**
Loading video...
Trucks For Kids With Blippi  1 Hour of Blippi Learning For Kids.mp4 | 1199 MB
Traceback (most recent call last):                                                       | 15.8%
  File "/usr/local/bin/pytube", line 33, in <module>
    sys.exit(load_entry_point('pytube==15.0.0', 'console_scripts', 'ytube')())
  File "/usr/local/lib/python3.10/dist-packages/pytube-15.0.0-py3.10.egg/pytube/cli.py", line 53, in main
  File "/usr/local/lib/python3.10/dist-packages/pytube-15.0.0-py3.10.egg/pytube/cli.py", line 76, in _perform_args_on_youtube
  File "/usr/local/lib/python3.10/dist-packages/pytube-15.0.0-py3.10.egg/pytube/cli.py", line 519, in download_by_resolution
  File "/usr/local/lib/python3.10/dist-packages/pytube-15.0.0-py3.10.egg/pytube/cli.py", line 299, in _download
  File "/usr/local/lib/python3.10/dist-packages/pytube-15.0.0-py3.10.egg/pytube/streams.py", line 314, in download
  File "/usr/local/lib/python3.10/dist-packages/pytube-15.0.0-py3.10.egg/pytube/request.py", line 157, in stream
  File "/usr/local/lib/python3.10/dist-packages/pytube-15.0.0-py3.10.egg/pytube/request.py", line 37, in _execute_request
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by SuperZombi** [comment]
Same error
```python
yt = pytube.YouTube(link)
arr = yt.streams.filter(progressive=True).order_by('resolution').desc()
link = arr[0].url
```
After opening link it returns `HTTP ERROR 403`

**Comment by jordibruin** [comment]
Same here.

https://github.com/alexeichhorn/YouTubeKit/issues/20

**Comment by RaulSimioni** [comment]
Same here 
```
video = YouTube(values[0], use_oauth=False, allow_oauth_cache=True)
stream = video.streams.get_highest_resolution()
stream.download(download_dir)
```

this error happens only when downloading long videos urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by kpollackhinds** [comment]
same

**Comment by ymk201** [comment]
it seems that some YouTube especially with high  video quality like 4k 60fps cause this error under condition of when deafualt client at innerpy set to web, android etc.

youtube returns it's available stream by client. android and web returns it's best quality stream but it makes 403 error while downloading. I highly doubt that it has a relationship between authentification.

my setting is android_music and it was that best choice for me. fhd and 4k 30fps streams were OK with out 403 error.
