### ISSUE TITLE
pytube.exceptions.RegexMatchError: __init__: could not find match for ^\$\w+\W[BUG]

### ISSUE THREAD

**Issue by Carlolopespesia** [pytube/pytube#1773]
Lastest version of pytube: 15.0.0

Bug warning: 

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py", line 34, in __init__
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: __init__: could not find match for ^\$\w+\W

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\Users\User\Desktop\Descargador multimedia\descargador.py", line 144, in dowloading_true_mp3_file
    NAME = yt.streams[0].title
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py", line 34, in __init__
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: __init__: could not find match for ^\$\w+\W

The bug ocurrs in line 30 of cipher.py (inside of the pytube folder library).

TO SOLVED IT:

Change the code in 30 line.

Change 

var_regex = re.compile(r"^\$\w+\W")

For the good one

var_regex = re.compile(r"^\w+\W")

**Comment by XANDER001** [comment]
this is work for me
1. `var_regex = re.compile(r"^\w+\W")`
2. to fix `pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple`
i already change a `function_patterns` from `get_throttling_function_name`
`r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&\s*'`
`r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])?\([a-z]\)',`

**Comment by bigbear22941** [comment]
not for me :(

**Comment by XANDER001** [comment]
> not for me

i mean `FOR US` T_T

work in version  `15.0.0`

**Comment by rodolflying** [comment]
> not for me :(
 The first time i copied the code provided by _bigbear22941_  it didnt work, cause i copied and put a additional "," separator.  Then i realized that it hadnt a "," between every line break.

    function_patterns = [
        r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&\s*'
        r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])?\([a-z]\)',
    ]

**Comment by wgong** [comment]
Encountered the same error today, after `pip uninstall pytube`, then `pip install pytube`, (15.0.0)
it worked, examined `cipher.py`, the fix mentioned by @rodolflying  is already in place
Thank you!
