### ISSUE TITLE
[BUG] http 404 error when trying to pull channel id from youtube video links.

### ISSUE THREAD

**Issue by flyinggoatman** [pytube/pytube#1775]
**Before creating an issue**

Please confirm that you are on the latest version of pytube by installing from the source.
I confirm.

**Describe the bug**
My code uses a video link to find out the channel id. It worked fine untill about 5 months ago when it started returning a 404 error.

**To Reproduce**
Please provide the following information:

```
def video_pull(channel_url, DEBUG_MODE):
    YTV = YouTube(channel_url)
    channel_id = YTV.channel_id
    channel_id_link = YTV.channel_url
    c = Channel(channel_id_link)
    channel_name = c.channel_name
    channel_id = c.channel_id
    channel_html = c._about_html
    channel_about = about_pull(c, DEBUG_MODE)
```

**Expected behavior**
- Looks at the video's information and pulls the channel id and adds it to the channel url. Please bare in mind that channel_url is the video_url in this situation.

**Output**
```
Traceback (most recent call last):
  File "C:\Users\fly\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\fly\SERVERS\BOTS\DISCORD\QualityYouTube\QualityYouTubeBot\QualityYouTubeBot.py", line 164, in on_message
    channel_name, channel_id_link, channel_about, channel_id = video_pull(channel_url, DEBUG_MODE)
  File "C:\Users\fly\SERVERS\BOTS\DISCORD\QualityYouTube\QualityYouTubeBot\functions.py", line 86, in video_pull
    channel_name = c.channel_name
  File "C:\Users\fly\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\contrib\channel.py", line 52, in channel_name
    return self.initial_data['metadata']['channelMetadataRenderer']['title']
  File "C:\Users\fly\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\contrib\playlist.py", line 81, in initial_data
    self._initial_data = extract.initial_data(self.html)
  File "C:\Users\fly\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\contrib\channel.py", line 101, in html
    self._html = request.get(self.html_url)
  File "C:\Users\fly\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\request.py", line 53, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "C:\Users\fly\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "C:\Users\fly\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\fly\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\fly\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\fly\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 557, in error
    result = self._call_chain(*args)
  File "C:\Users\fly\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\fly\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\fly\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\fly\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\fly\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 557, in error
    result = self._call_chain(*args)
  File "C:\Users\fly\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\fly\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\fly\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\fly\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\fly\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\fly\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\fly\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**System information**
Please provide the following information:
- Python version (run `python --version`) **Python 3.10.9**
- Pytube version (run `print(pytube.__version__)` in python) **pytube 12.1.3**
```

**Comment by NannoSilver** [comment]
You are running an outdated pytube version.
Latest pytube version is 15.0.0

**Comment by flyinggoatman** [comment]
Okay thanks, I fixed it. However, I still need to manually add in the patch to recognise @ handles. Any idea when this is due to be added?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by NannoSilver** [comment]
> Okay thanks, I fixed it. However, I still need to manually add in the patch to recognise @ handles. Any idea when this is due to be added? 

I am in the same situation regarding the "@" handler.
Have to patch always. I cannot understand why it has not been incorporated already.
