### ISSUE TITLE
NEW ISSUE: Error to download (AttributeError: 'NoneType' object has no attribute 'span')

### ISSUE THREAD

**Issue by NannoSilver** [pytube/pytube#1799]
New issue around to download audio and videos from Youtube.

Here is the code to test:
```
from pytube import YouTube


youtube_episode_id = 'MEmU-VGM62M'   # long

yt = YouTube(f'https://www.youtube.com/watch?v={youtube_episode_id}')

ITAG = 22

stream = yt.streams.get_by_itag(ITAG)
stream.download(output_path='cache', filename=f'{youtube_episode_id}.mp4', skip_existing=True, max_retries=0)
```

Actual result:
```
Traceback (most recent call last):
  File "f:\test\teste11.py", line 12, in <module>
    link = yt.streams.get_by_itag(ITAG).url
  File "f:\test\venv\lib\site-packages\pytube\__main__.py", line 316, in streams
    return StreamQuery(self.fmt_streams)
  File "f:\test\venv\lib\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "f:\test\venv\lib\site-packages\pytube\extract.py", line 411, in apply_signature
    cipher = Cipher(js=js)
  File "f:\test\venv\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "f:\test\venv\lib\site-packages\pytube\cipher.py", line 427, in get_throttling_plan
    transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
AttributeError: 'NoneType' object has no attribute 'span'

Process finished with exit code 1
```

I tested with different Itags and all have the same problem.

**Comment by Bryan-Romas-Bose** [comment]
I'm encountering the same error but am calling `audio_stream = yt.streams.get_audio_only()`

Looks like some regex is failing to find a match (?)

**Comment by ZachMuzzle** [comment]
I was running into this issue as well.
I patched this issue using a comment from a previous issue here: https://github.com/pytube/pytube/issues/1498#issuecomment-1472963944

**Comment by 68a** [comment]
same problem

**Comment by BookCatKid** [comment]
same.

**Comment by NannoSilver** [comment]
> I was running into this issue as well. I patched this issue using a comment from a previous issue here: [#1498 (comment)](https://github.com/pytube/pytube/issues/1498#issuecomment-1472963944)


Worked for me as well in the short tests I did.

**Comment by hzbd** [comment]
may be same problem?

```
In [19]: from pytube import Playlist, YouTube, Channel
    ...: from pytube.exceptions import VideoUnavailable
    ...:
    ...: url = "http://youtube.com/watch?v=2lAe1cqCOXo"
    ...: yt = YouTube(url)
    ...: yt.streams
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-1387a91f0a01> in <module>
      4 url = "http://youtube.com/watch?v=2lAe1cqCOXo"
      5 yt = YouTube(url)
----> 6 yt.streams

/data/pyenv/py3/lib/python3.8/site-packages/pytube/__main__.py in streams(self)
    294         """
    295         self.check_availability()
--> 296         return StreamQuery(self.fmt_streams)
    297
    298     @property

/data/pyenv/py3/lib/python3.8/site-packages/pytube/__main__.py in fmt_streams(self)
    179         # https://github.com/pytube/pytube/issues/1054
    180         try:
--> 181             extract.apply_signature(stream_manifest, self.vid_info, self.js)
    182         except exceptions.ExtractError:
    183             # To force an update to the js file, we clear the cache and retry

/data/pyenv/py3/lib/python3.8/site-packages/pytube/extract.py in apply_signature(stream_manifest, vid_info, js)
    407
    408     """
--> 409     cipher = Cipher(js=js)
    410
    411     for i, stream in enumerate(stream_manifest):

/data/pyenv/py3/lib/python3.8/site-packages/pytube/cipher.py in __init__(self, js)
     41         ]
     42
---> 43         self.throttling_plan = get_throttling_plan(js)
     44         self.throttling_array = get_throttling_function_array(js)
     45

/data/pyenv/py3/lib/python3.8/site-packages/pytube/cipher.py in get_throttling_plan(js)
    409     match = plan_regex.search(raw_code)
    410
--> 411     transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
    412
    413     # Steps are either c[x](c[y]) or c[x](c[y],c[z])

AttributeError: 'NoneType' object has no attribute 'span'
```

**Comment by AtharvaSolanki** [comment]
same issue

**Comment by Bob-King** [comment]
seems same issue.

`from pytube import YouTube

url = 'https://www.youtube.com/watch?v=QRkkaMKLPWs'

yt = YouTube(url)

streams = yt.streams

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/envs/geneface.xy/lib/python3.10/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "/usr/local/anaconda3/envs/geneface.xy/lib/python3.10/site-packages/pytube/__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/usr/local/anaconda3/envs/geneface.xy/lib/python3.10/site-packages/pytube/extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "/usr/local/anaconda3/envs/geneface.xy/lib/python3.10/site-packages/pytube/cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "/usr/local/anaconda3/envs/geneface.xy/lib/python3.10/site-packages/pytube/cipher.py", line 411, in get_throttling_plan
    transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
AttributeError: 'NoneType' object has no attribute 'span'
`

**Comment by Itayt321** [comment]
Does anyone have the fixed issue on a repository so I can pip install it?

**Comment by Fawwad-891** [comment]
Same issue 
'AttributeError: NoneType' object has no attribute span'

**Comment by abanand132** [comment]
I am also facing the same issue.

**Comment by bewithdhanu** [comment]
This solution works!

https://github.com/pytube/pytube/issues/1498#issuecomment-1472963944

**Comment by AtharvaSolanki** [comment]
> This solution works!
> 
> [#1498 (comment)](https://github.com/pytube/pytube/issues/1498#issuecomment-1472963944)

It works in local but when i try on colab this solution doesn't works

**Comment by SantGT5** [comment]
Same error, it happens when I try to use streams:

yt = YouTube(video_url)
video_stream = yt.streams.first()

'NoneType' object has no attribute 'span'

**Comment by jainarpit10** [comment]
#1498  does'nt works it gives 
Access to rr7---sn-gwpa-0qgl.googlevideo.com was denied

using :-
audio = yt.streams.filter(only_audio=True).first()
audio_url = audio.url

**Comment by Bryan-Romas-Bose** [comment]
As a temporary fix I've updated my requirements.txt using the fix in the given branch.

`# pytube==15.0.0 # unpatched error here as of 2023-09-27`
`https://github.com/abanand132/pytube/zipball/master`

**Comment by YuriiMaiboroda** [comment]
Try this: https://github.com/pytube/pytube/pull/1805

**Comment by linuxem** [comment]
python 3.12 on lib/python3.12/site-packages/pytube/cipher.py file 
replace this line "transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)"  ---> "transform_plan_raw = js" fix it
