### ISSUE TITLE
[BUG] error in listing streams 

### ISSUE THREAD

**Issue by Lightkira3843** [pytube/pytube#1800]
**Before creating an issue**
Name: pytube                                                                                                                                                                                    
Version: 15.0.0
Summary: Python 3 library for downloading YouTube Videos.
Home-page: https://github.com/pytube/pytube
Author: Ronnie Ghose, Taylor Fox Dahlin, Nick Ficano
Author-email: hey@pytube.io
License: The Unlicense (Unlicense)
Location: /home/kali/.local/lib/python3.11/site-packages
Requires: 
Required-by: 

**Describe the bug**
it doesn't fetch the streams 
when i print(yt.streams)
i got the following error 

**To Reproduce**
from pytube import YouTube

yt = YouTube("https://youtu.be/4b5d3muPQmA")

print(yt.title)
print(yt.thumbnail_url)

print(yt.streams)

**Expected behavior**
it should have print all the streams available  for this video

**Output**

StatQuest: K-means clustering
https://i.ytimg.com/vi/4b5d3muPQmA/hq720.jpg
Traceback (most recent call last):
  File "/media/kali/Deekshant/playlists/DSTL/try.py", line 8, in <module>
    print(yt.streams)
          ^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/pytube/__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/home/kali/.local/lib/python3.11/site-packages/pytube/extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
             ^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/pytube/cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/pytube/cipher.py", line 411, in get_throttling_plan
    transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
                                                               ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'span'

**System information**
Python 3.11.4 (main, Jun  7 2023, 10:13:09) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytube
>>> pytube.__version__
'15.0.0'
>>>
- Command used to install pytube
git+https://github.com/pytube/pytube.git

**Comment by Noext** [comment]
same issue, was working yesterday and now its not working

**Comment by Alexici** [comment]
Same issue here

**Comment by YuriiMaiboroda** [comment]
Try this: https://github.com/pytube/pytube/pull/1805
