### ISSUE TITLE
[BUG] Can't get the .streams from a YouTube() object

### ISSUE THREAD

**Issue by drmanche** [pytube/pytube#1801]
**Before creating an issue**

I am on the latest version 15.0.0

**Describe the bug**
Can't get the .streams of a YouTube() object for later video download.

**To Reproduce**
print(YouTube('https://www.youtube.com/watch?v=eNLjdPI9zdE').streams)

**Expected behavior**
Expected to get a StreamQuery object

**Output**

Traceback (most recent call last):
  File "/run/user/1000/gvfs/sftp:host=192.168.1.11,user=drmanche/home/drmanche/deruzaku/src/commands/aa.py", line 37, in <module>
    print(YouTube('https://www.youtube.com/watch?v=eNLjdPI9zdE').streams)
  File "/home/drmanche/.local/lib/python3.10/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "/home/drmanche/.local/lib/python3.10/site-packages/pytube/__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/home/drmanche/.local/lib/python3.10/site-packages/pytube/extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "/home/drmanche/.local/lib/python3.10/site-packages/pytube/cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "/home/drmanche/.local/lib/python3.10/site-packages/pytube/cipher.py", line 411, in get_throttling_plan
    transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
AttributeError: 'NoneType' object has no attribute 'span'

**System information**

- Python 3.10.12
- Name: pytube
  Version: 15.0.0
  Summary: Python 3 library for downloading YouTube Videos.
  Home-page: https://github.com/pytube/pytube
  Author: Ronnie Ghose, Taylor Fox Dahlin, Nick Ficano
  Author-email: hey@pytube.io
  License: The Unlicense (Unlicense)
  Location: /home/drmanche/.local/lib/python3.10/site-packages
  Requires: 
  Required-by:
- pip install pytube

**Comment by RomainCrz** [comment]
Hi, it seems that https://github.com/pytube/pytube/issues/1799#issuecomment-1736477433 resolved it

**Comment by drmanche** [comment]
> Hi, it seems that [#1799 (comment)](https://github.com/pytube/pytube/issues/1799#issuecomment-1736477433) resolved it

It's a temporary solution that works, however it doesn't fix the library error overall.

**Comment by abanand132** [comment]
I pull request the temporary fixes until some solid solution come

**Comment by couldbejake** [comment]
Same issue here.

**Comment by Wotox** [comment]
Same issue also.

**Comment by YuriiMaiboroda** [comment]
In function `find_object_from_startpoint` in `parser.py` need to add single quote (`'`) context
```py
context_closers = {
        '{': '}',
        '[': ']',
        '"': '"',
        '\'': '\'',
        '/': '/' # javascript regex
```
```py
if curr_context in ['"', '\'', '/']:
```

PR: https://github.com/pytube/pytube/pull/1805

**Comment by JuanBindez** [comment]
problem solved here -> https://pypi.org/project/pytubefix/

**Comment by Wotox** [comment]
> problem solved here -> https://pypi.org/project/pytubefix/

Thank you, seems to work fine. Is it temporary fix until `pytube` developers update their project or `pytubefix` will be updated further?

**Comment by JuanBindez** [comment]
> > problema resolvido aqui -> [ https://pypi.org/project/pytubefix/ ](https://pypi.org/project/pytubefix/)
> 
> Obrigado, parece funcionar bem. É uma solução temporária até `pytube`desenvolvedores atualizam seu projeto ou `pytubefix`será atualizado ainda mais?

This is another project focused on always being updated, because the original pytube is not being updated, so all failures will be updated quickly in pytubefix

**Comment by JuanBindez** [comment]
> > problem solved here -> https://pypi.org/project/pytubefix/
> 
> Thank you, seems to work fine. Is it temporary fix until `pytube` developers update their project or `pytubefix` will be updated further?

This is another project focused on always being updated, because the original pytube is not being updated, so all failures will be updated quickly in pytubefix
