### ISSUE TITLE
[BUG] urllib.error.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by Hypocrate-code** [pytube/pytube#1803]
I'm using this pytube repo, forked with just a few modifications solving bugs that i'm pretty sure doesn't affect normal functionnalities.
Downloading videos from my playlist, some of them return this error :

 Traceback (most recent call last):
   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1038, in _bootstrap_inner
     self.run()
   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 975, in run
     self._target(*self._args, **self._kwargs)
   File "C:\Users\titia\OneDrive\Bureau\HypLoad\source\main.py", line 671, in download_yt_playlist
     good_one.download(filename=name_of_file, output_path=output)
   File "C:\Users\titia\OneDrive\Bureau\HypLoad\source\pytube\streams.py", line 314, in download
     for chunk in request.stream(
   File "C:\Users\titia\OneDrive\Bureau\HypLoad\source\pytube\request.py", line 157, in stream
     response = _execute_request(
                ^^^^^^^^^^^^^^^^^
   File "C:\Users\titia\OneDrive\Bureau\HypLoad\source\pytube\request.py", line 37, in _execute_request
     return urlopen(request, timeout=timeout)  # nosec
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 216, in urlopen
     return opener.open(url, data, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 525, in open
     response = meth(req, response)
                ^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 634, in http_response
     response = self.parent.error(
                ^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 557, in error
     result = self._call_chain(*args)
              ^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 496, in _call_chain
     result = func(*args)
              ^^^^^^^^^^^
   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 749, in http_error_302
     return self.parent.open(new, timeout=req.timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 525, in open
     response = meth(req, response)
                ^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 634, in http_response
     response = self.parent.error(
                ^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 563, in error
     return self._call_chain(*args)
            ^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 496, in _call_chain
     result = func(*args)
              ^^^^^^^^^^^
   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 643, in http_error_default
     raise HTTPError(req.full_url, code, msg, hdrs, fp)
 urllib.error.HTTPError: HTTP Error 403: Forbidden
 
 I looked at a bunch of solutions on this repo's issues, but i didn't find anything working.
 
 Any ideas ??

**Comment by Vevezinho** [comment]
You are probably trying to access a video that is not public. To access some videos you must be logged in.

**Comment by Hypocrate-code** [comment]
Yeah i know that this can cause some problems, but i don't know how to log in.

I probable figure out why i got this error : in the innertube.py file, the class Innertube Line 223 used ANDROID instead of ANDROID_MUSIC

Changing this solved the issue.

But, why ? And how should i choose between ANDROID, ANDROID_MUSIC, or WEB ?? Anyone knows what does this mean ?
Which client should we use and why ?

**Comment by LeonScholta** [comment]
worked like a charm. Idk why to use it, but I remember having it changed once before and someone smart explained why and when to use which one. Just change it to whatever works ig. Lol

**Comment by aouiniamine** [comment]
> You are probably trying to access a video that is not public. To access some videos you must be logged in.
What worked for me is just uninstall and reinstall the package
to any one who wants to bypass authentification in pytube to download yt videos:
 I - to bypass auth to restricted videos:
  1 - in Lib\site-packages\pytube\__main__.py 
  2 - at def bypass_age_gate change InnerTube:
      => InnerTube(client='ANDROID',[don't change the other arguments])

**Comment by JuanBindez** [comment]
> I'm using this pytube repo, forked with just a few modifications solving bugs that i'm pretty sure doesn't affect normal functionnalities. Downloading videos from my playlist, some of them return this error :
> 
> Traceback (most recent call last): File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1038, in _bootstrap_inner self.run() File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 975, in run self._target(*self._args, **self._kwargs) File "C:\Users\titia\OneDrive\Bureau\HypLoad\source\main.py", line 671, in download_yt_playlist good_one.download(filename=name_of_file, output_path=output) File "C:\Users\titia\OneDrive\Bureau\HypLoad\source\pytube\streams.py", line 314, in download for chunk in request.stream( File "C:\Users\titia\OneDrive\Bureau\HypLoad\source\pytube\request.py", line 157, in stream response = _execute_request( ^^^^^^^^^^^^^^^^^ File "C:\Users\titia\OneDrive\Bureau\HypLoad\source\pytube\request.py", line 37, in _execute_request return urlopen(request, timeout=timeout) # nosec ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 216, in urlopen return opener.open(url, data, timeout) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 525, in open response = meth(req, response) ^^^^^^^^^^^^^^^^^^^ File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 634, in http_response response = self.parent.error( ^^^^^^^^^^^^^^^^^^ File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 557, in error result = self._call_chain(*args) ^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 496, in _call_chain result = func(*args) ^^^^^^^^^^^ File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 749, in http_error_302 return self.parent.open(new, timeout=req.timeout) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 525, in open response = meth(req, response) ^^^^^^^^^^^^^^^^^^^ File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 634, in http_response response = self.parent.error( ^^^^^^^^^^^^^^^^^^ File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 563, in error return self._call_chain(*args) ^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 496, in _call_chain result = func(*args) ^^^^^^^^^^^ File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 643, in http_error_default raise HTTPError(req.full_url, code, msg, hdrs, fp) urllib.error.HTTPError: HTTP Error 403: Forbidden
> 
> I looked at a bunch of solutions on this repo's issues, but i didn't find anything working.
> 
> Any ideas ??

version with the fix available -> pip install pytubefix==1.10.0

**Comment by DevloperAnuj** [comment]
try with this

`pip install pytubefix`

`from pytubefix import YouTube`

**Comment by anglo331** [comment]
> try with this
> 
> `pip install pytubefix`
> 
> `from pytubefix import YouTube`

thanks, It works for me

**Comment by fau1095** [comment]
> > try with this
> > `pip install pytubefix`
> > `from pytubefix import YouTube`
> 
> thanks, It works for me

This worked great

**Comment by moeezrhmn** [comment]
This works bro

**Comment by moeezrhmn** [comment]
> try with this
> 
> `pip install pytubefix`
> 
> `from pytubefix import YouTube`

this works great

**Comment by nviable** [comment]
> try with this
> 
> `pip install pytubefix`
> 
> `from pytubefix import YouTube`

This works. 

Reminder to make sure you download the latest version of pytubefix and not v1.10.0 from an older comment.
