### ISSUE TITLE
[BUG]unable to get video title, KeyError: 'videoDetails'

### ISSUE THREAD

**Issue by XiaosongWen** [pytube/pytube#1829]
tried the quistart code, but unable to get video title. BTW, I am running in windows 10.
```  
File "C:\Users\242107\anaconda3\envs\pytube\lib\site-packages\pytube\__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\242107\Desktop\Project\pytube\download.py", line 8, in <module>
    print(yt.title)
  File "C:\Users\242107\anaconda3\envs\pytube\lib\site-packages\pytube\__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=2lAe1cqCOXo. Please file a bug report at https://github.com/pytube/pytube
```

**Comment by SarthakNikhal** [comment]
@XiaosongWen How can I reproduce the issue? I'll try to solve it

**Comment by pdo-smith** [comment]
I have the identical problem on Ubuntu Linux and python 3.11
