### ISSUE TITLE
[BUG] Not capable to retrieve video DESCRIPTION

### ISSUE THREAD

**Issue by NannoSilver** [pytube/pytube#1833]
I am running pytube 15.0.0.

While requesting the video's description, I get `None` as result, instead the description itself.

Here is the code to test the issue:
```
from pytube import YouTube

video_link = f'https://www.youtube.com/watch?v=0FX4jVAL1eg'
yt = YouTube(video_link)
description = yt.description

print(f'Description: {description}')
```

Expected result:
```
Description: Taken from JRE #2071 w/Kim Congdon & Sara Weinshenk:
https://open.spotify.com/episode/7pQKJRuTXeC7ktiXC7thv6?si=75138c05999d43bd
```

Actual result:
```
Description: None
```

**Comment by SarthakNikhal** [comment]
Can I work on this issue? Please assign me and let me know how I can show the result in the best way.

**Comment by NannoSilver** [comment]
> Can I work on this issue? Please assign me and let me know how I can show the result in the best way.

For sure you can work in the issue, @SarthakNikhal 

I am not the project owner and I am not familiar on how to submit an official change, but you can explain in a message, here, what should be done to fix (eg. at file xxx.py replace `this code` by `this new code`).

At pytubefix (a fork of pytube) this issue has been already fixed:
https://github.com/JuanBindez/pytubefix

**Comment by tribhoon** [comment]
This is an old issue. The yt.description for the video doesn't work and just gives out None as its value. Maybe this is because YouTube doesn't allow you to get the description of a video until you get an API key or something ? Anyways this is the code that works and gives you the description of the video.

```
import requests

api_key = "Your_API_Key_Here"
video_url = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

video_id = video_url.split("=")[-1]
url = f"https://www.googleapis.com/youtube/v3/videos?part=snippet&id={video_id}&key={api_key}"
response = requests.get(url)
response_json = response.json()
video_description = response_json["items"][0]["snippet"]["description"]

response = requests.get(url)
print(video_description)
```

Remember to put your API key in the string of the api_key variable, or it wont work. If you don't know how to make a YouTube API key, you can use [this](https://support.google.com/googleapi/answer/6158862?hl=en) for you reference.

**Comment by NannoSilver** [comment]
@SneakySquid2022 
Pytube was working properly to retrieve the description, at least until last year (2022), without the need for API key.

As my previous comment, at [pytubefix](https://github.com/JuanBindez/pytubefix) (a fork of pytube) this issue has been already fixed. So a fixing is possible.

**Comment by tribhoon** [comment]
@sukhoi47
I agree with you but it's probably because of YouTube making changes at their end and not because of anything being bad at pytube. If a fix comes out and Google changes something again, it would break things again. So, in my opinion, this is currently the most viable option to go for because the program uses Google's official first-party API. A YouTube API key is free anyways.

[Here](https://github.com/pytube/pytube/issues/1626), there is another instance of this same issue.

**Comment by SarthakNikhal** [comment]
@RONNCC Can I add beautiful soup or pandas library as a dependency? Solving issues like these will be very easy with that.

**Comment by NannoSilver** [comment]
> @RONNCC Can I add beautiful soup or pandas library as a dependency? Solving issues like these will be very easy with that.

pytube is a library without dependencies.

**Comment by felipeucelli** [comment]
Hi @sukhoi47, Pytube uses the API request to get the description, and YouTube is no longer sending the description to the ANDROID_MUSIC client. Try using this PR #1825.

**Comment by NannoSilver** [comment]
While there is no solution for pytube...

For those interested in alternatives to retrieve the video's description, here is the code to do it with pytubefix (a fork of pytube) and beautifulsoup. Both are working fine.

Solution with pytubefix:
```
from pytubefix import YouTube   # pip install pytubefix

# video_url = 'https://www.youtube.com/watch?v=Dl-YxCV_h7I'     # URL format


def extract_description_with_pytubefix(video_url):
    ytube = YouTube (video_url)
    video_description = ytube.description
    return video_description
```


Solution with beautifulsoup:
```
from bs4 import BeautifulSoup   # pip install beautifulsoup4
import re
import requests



# video_url = 'https://www.youtube.com/watch?v=Dl-YxCV_h7I'     # URL format


def extract_description_with_beautifulsoup(video_url):
    soup = BeautifulSoup(requests.get(video_url, cookies={'CONSENT': 'YES+1'}).text, 'html.parser')
    pattern = re.compile('(?<=shortDescription":").*(?=","isCrawlable)')
    video_description = pattern.findall(str(soup))[0].replace('\\n', '\n')
    return video_description

```

**Comment by RicardoEscobar** [comment]
> This is an old issue. The yt.description for the video doesn't work and just gives out None as its value. Maybe this is because YouTube doesn't allow you to get the description of a video until you get an API key or something ? Anyways this is the code that works and gives you the description of the video.
> 
> ```
> import requests
> 
> api_key = "Your_API_Key_Here"
> video_url = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
> 
> video_id = video_url.split("=")[-1]
> url = f"https://www.googleapis.com/youtube/v3/videos?part=snippet&id={video_id}&key={api_key}"
> response = requests.get(url)
> response_json = response.json()
> video_description = response_json["items"][0]["snippet"]["description"]
> 
> response = requests.get(url)
> print(video_description)
> ```
> 
> Remember to put your API key in the string of the api_key variable, or it wont work. If you don't know how to make a YouTube API key, you can use [this](https://support.google.com/googleapi/answer/6158862?hl=en) for you reference.

This doesn't work.
```python
def get_video_description(video_url: str) -> str:
    """Get the description of a video.
    args:
        video_url: The url of the video.
    returns:
        The description of the video."""
    # Get the video id
    video_id = video_url.split("=")[-1]

    # Get the video description
    api_key = os.getenv("YOUTUBE_API_KEY")
    url = f"https://www.googleapis.com/youtube/v3/videos?part=snippet&id={video_id}&key={api_key}"
    response = requests.get(url)
    response_json = response.json()
    video_description = response_json["items"][0]["snippet"]["description"]

    return video_description
```
The error is that the key `items` doesn't exists:
```
$ python controller/youtube/youtube_search.py
Unexpected renderer encountered.
Renderer name: dict_keys(['reelShelfRenderer'])
Search term: AMD ryzen 7 5800x3d
Please open an issue at https://github.com/pytube/pytube/issues and provide this log output.
Unexpected renderer encountered.
Renderer name: dict_keys(['reelShelfRenderer'])
Search term: AMD ryzen 7 5800x3d
Please open an issue at https://github.com/pytube/pytube/issues and provide this log output.
Traceback (most recent call last):
  File "C:\Users\Jorge\git\core-ai\controller\youtube\youtube_search.py", line 148, in <module>
    main()
  File "C:\Users\Jorge\git\core-ai\controller\youtube\youtube_search.py", line 143, in main
    result = json.loads(ai_youtube_search(query))
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge\git\core-ai\controller\youtube\youtube_search.py", line 131, in ai_youtube_search
    for data in youtube_query(prompt, max_videos=max_videos, max_tokens=max_tokens):
  File "C:\Users\Jorge\git\core-ai\controller\youtube\youtube_search.py", line 104, in youtube_query
    "video_description": get_video_description(video.watch_url),
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge\git\core-ai\controller\youtube\youtube_search.py", line 41, in get_video_description
    video_description = response_json["items"][0]["snippet"]["description"]
                        ~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'items'
```
If you print the output of the `response_json` you get this:
```json
{
    "error": {
        "code": 403,
        "message": "YouTube Data API v3 has not been used in project 508453389555 before or it is disabled. Enable it by visiting https: //console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=508453389555 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
        "errors": [
            {
                "message": "YouTube Data API v3 has not been used in project 508453389555 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=508453389555 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
                "domain": "usageLimits",
                "reason": "accessNotConfigured",
                "extendedHelp": "https://console.developers.google.com",
            }
        ],
        "status": "PERMISSION_DENIED",
        "details": [
            {
                "@type": "type.googleapis.com/google.rpc.Help",
                "links": [
                    {
                        "description": "Google developers console API activation",
                        "url": "https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=508453389555",
                    }
                ],
            },
            {
                "@type": "type.googleapis.com/google.rpc.ErrorInfo",
                "reason": "SERVICE_DISABLED",
                "domain": "googleapis.com",
                "metadata": {
                    "service": "youtube.googleapis.com",
                    "consumer": "projects/508453389555",
                },
            },
        ],
    }
}
```
Go here __Google developers console API activation__ https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=YOUR_PROJECT_NUMBER and since the YouTube Data API v3 API key has not been used in project before or it is disabled you need to click the Enable button then retry.

If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

**Comment by Sandwich2001** [comment]
> pip install pytubefix

Thank you, this worked straight out of the box.
Lets hope they fix Pytube eventually also :)
