### ISSUE TITLE
[BUG] - error 403 forbidden how do i fix this?

### ISSUE THREAD

**Issue by 0xYc0d0ne** [pytube/pytube#1852]
Traceback (most recent call last):
  File "/home/oxycodone/Documents/youtube-playlist-downloader/playlist_downloader.py", line 23, in <module>
    video.streams.get_highest_resolution().download(output_path=folderName)
  File "/home/oxycodone/anaconda3/lib/python3.11/site-packages/pytube/streams.py", line 314, in download
    for chunk in request.stream(
  File "/home/oxycodone/anaconda3/lib/python3.11/site-packages/pytube/request.py", line 157, in stream
    response = _execute_request(
               ^^^^^^^^^^^^^^^^^
  File "/home/oxycodone/anaconda3/lib/python3.11/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oxycodone/anaconda3/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oxycodone/anaconda3/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/oxycodone/anaconda3/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/home/oxycodone/anaconda3/lib/python3.11/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oxycodone/anaconda3/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/home/oxycodone/anaconda3/lib/python3.11/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oxycodone/anaconda3/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/oxycodone/anaconda3/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/home/oxycodone/anaconda3/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oxycodone/anaconda3/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/home/oxycodone/anaconda3/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

i removed all deleted and privated vidoes from a music playlist of 1775 songs on youtube and changed my client to "client=ANDROID" and i still get this error after about 100 videos or so being downloaded .... does anyone know how i can fix this error???

**Comment by JuanBindez** [comment]
try pytubefix, pip install pytubefix, http://pytubefix.readthedocs.io/

**Comment by koziez** [comment]
> try pytubefix, pip install pytubefix, http://pytubefix.readthedocs.io/

same issue

**Comment by Shermukhammat** [comment]
You have to set the parameter 'use_oauth' to 'True' when using the YouTube class. When you first use new devices, you may encounter a 403 Forbidden error. To resolve this, you should open the URL provided in the terminal and input the code from the terminal. This step is required only once in new devices.

example : 
YouTube(url="https://youtu.be/vMXg4V-fKGw?si=s3vg6o2MFwNT0WBN", use_oauth=True)

**Comment by Priyamvada-iiita** [comment]
still getting that error even after allowing oauth login

**Comment by k-sai-krishna** [comment]
> still getting that error even after allowing oauth login

yes for me also. Is anything worked for you?
its may help me alot if you share something

**Comment by Shermukhammat** [comment]
> > still getting that error even after allowing oauth login
> 
> yes for me also. Is anything worked for you? its may help me alot if you share something

I suggest using ytdlp instead of pytube. I switched to ytdlp and it doesn't have like these isues
