### ISSUE TITLE
[BUG] KeyError: 'start' when Downloading Captions using download

### ISSUE THREAD

**Issue by rjpkuyper** [pytube/pytube#1867]
**Describe the bug**
Encountering a KeyError: 'start' when attempting to download captions using the `download` function in PyTube. The captions file is expected to be downloaded in SRT format, but the process fails with a KeyError, indicating that the expected 'start' attribute is missing in the caption data.

**To Reproduce**
1. URL causing the error: https://www.youtube.com/watch?v=HrfMjHuk93s
2. Code snippet triggering the error:
```python
def download_captions_by_code(url, code, output_dir):
    yt = YouTube(url)
    yt.bypass_age_gate()
    video_title = yt.title.replace(" ", "_")
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    if code in yt.captions:
        caption = yt.captions[code]
        srt_caption_file_path = caption.download(output_path=output_dir, srt=True, title=f"{video_title}_caption")
    else:
        result = {'success': False, 'error': f'Caption with code {code} not found'}
    # Error handling omitted for brevity
```

*Output*
Full traceback of the exception:

```
Traceback (most recent call last):
  File "/Users/robert-jankuyper/Documents/datails/pytube/./scripts/app.py", line 140, in download_captions_by_code
    srt_caption_file_path = caption.download(output_path=output_dir, srt=True, title=f"{video_title}_caption")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pytube/captions.py", line 156, in download
    file_handle.write(self.generate_srt_captions())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pytube/captions.py", line 61, in generate_srt_captions
    return self.xml_caption_to_srt(self.xml_captions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pytube/captions.py", line 93, in xml_caption_to_srt
    start = float(child.attrib["start"])
                  ~~~~~~~~~~~~^^^^^^^^^
KeyError: 'start'
{"success": false, "error": "An error occurred: 'start'"}
```

**System information**
* Python Version: Python 3.11.7
* Pytube Version: 15.0.0
* Installation Command: python -m pip install git+https://github.com/pytube/pytube

**Comment by Sahil481** [comment]
Unable to recreate bug

**Comment by uni-saurabh-vyas** [comment]
getting same issue

**Comment by OceanRamen** [comment]
Wrote a fix: https://github.com/pytube/pytube/pull/1880

**Comment by justSam13** [comment]
This is fixed in #1860  + with added functionality to also be able to parse the auto-generated captions :)

**Comment by OceanRamen** [comment]
> This is fixed in #1860  + with added functionality to also be able to parse the auto-generated captions :)

Is it merged with main? Because I wrote a fix after encountering the problem myself 5 days ago.

**Comment by justSam13** [comment]
> > This is fixed in #1860  + with added functionality to also be able to parse the auto-generated captions :)
> 
> Is it merged with main? Because I wrote a fix after encountering the problem myself 5 days ago.

No, this repository has not been updated by the developers since a long time. The last update was 9 months ago :(

**Comment by stesalps** [comment]
> > > This is fixed in #1860  + with added functionality to also be able to parse the auto-generated captions :)
> > 
> > 
> > Is it merged with main? Because I wrote a fix after encountering the problem myself 5 days ago.
> 
> No, this repository has not been updated by the developers since a long time. The last update was 9 months ago :(

Sam, I’m getting a new error

`import pytube


from pytube import YouTube

youtube_link = 'https://www.youtube.com/watch?v=pvDOnqGbghU'# Replace '...' with your YouTube video link

try:
    yt = YouTube(youtube_link)
    yt.streams.first().captions.get_by_language_code('en').download()
    print(yt.caption_tracks)

except Exception as e:
    print("An error occurred: ", e)`



An error occurred:  'Stream' object has no attribute 'captions'

**Comment by justSam13** [comment]
> > > > This is fixed in #1860  + with added functionality to also be able to parse the auto-generated captions :)
> > > 
> > > 
> > > Is it merged with main? Because I wrote a fix after encountering the problem myself 5 days ago.
> > 
> > 
> > No, this repository has not been updated by the developers since a long time. The last update was 9 months ago :(
> 
> Sam, I’m getting a new error
> 
> `import pytube
> 
> from pytube import YouTube
> 
> youtube_link = 'https://www.youtube.com/watch?v=pvDOnqGbghU'# Replace '...' with your YouTube video link
> 
> try: yt = YouTube(youtube_link) yt.streams.first().captions.get_by_language_code('en').download() print(yt.caption_tracks)
> 
> except Exception as e: print("An error occurred: ", e)`
> 
> An error occurred: 'Stream' object has no attribute 'captions'

This error is because you are trying to get captions attribute from stream but stream object has no attribute captions.
use yt.captions instead

**Comment by justSam13** [comment]
```
from pytube import YouTube
youtube_link = "https://www.youtube.com/watch?v=pvDOnqGbghU"
try:
    yt = YouTube(youtube_link)
    print(yt.caption_tracks)
    yt.captions.get_by_language_code("en").download()
except Exception as e:
    print("An error occurred: ", e)
```

This should work. Also, for the url that you have supplied, the captions seem to be unavailable to pytube.
