### ISSUE TITLE
[BUG] Age restriction fix is no longer working, producing 400, bad request

### ISSUE THREAD

**Issue by partriv** [pytube/pytube#1894]
**Describe the bug**
When you use the age restriction fix that has always worked ([described here](https://stackoverflow.com/questions/75791765/how-to-download-videos-that-require-age-verification-with-pytube)), it now produces bad request.

**To Reproduce**
Please provide the following information:
- innterube.py
- steps to repro: get pytube 15.0.0, try to get video url for an [age restricted video](https://youtu.be/Y4-GSFKZmEg). 
- notice you get age restriction.
- Implement the fix from that SO post. 
- Notice you get 400 bad request

**Expected behavior**
- expected behavior is you get the video link (which you always used to)

**The Fix**
- the fix is present in this fork of pytube, please merge this in: [the inntertube.py commit with fix](https://github.com/JuanBindez/pytubefix/commit/c0c07b046d8b59574552404931f6ce3c6590137d)

**Output**
```
Traceback (most recent call last):
  File "/srv/mememaker-web/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/par/virtualenvs/mememaker/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/par/virtualenvs/mememaker/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/par/virtualenvs/mememaker/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/par/virtualenvs/mememaker/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/srv/mememaker-web/mememaker/management/commands/pytube_oauth.py", line 10, in handle
    thevid = yt.streams.filter(progressive=True, file_extension='mp4').order_by('resolution').desc().first()
  File "/home/par/virtualenvs/mememaker/lib/python3.10/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "/home/par/virtualenvs/mememaker/lib/python3.10/site-packages/pytube/__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "/home/par/virtualenvs/mememaker/lib/python3.10/site-packages/pytube/__main__.py", line 157, in streaming_data
    if 'streamingData' in self.vid_info:
  File "/home/par/virtualenvs/mememaker/lib/python3.10/site-packages/pytube/__main__.py", line 246, in vid_info
    innertube_response = innertube.player(self.video_id)
  File "/home/par/virtualenvs/mememaker/lib/python3.10/site-packages/pytube/innertube.py", line 448, in player
    return self._call_api(endpoint, query, self.base_data)
  File "/home/par/virtualenvs/mememaker/lib/python3.10/site-packages/pytube/innertube.py", line 390, in _call_api
    response = request._execute_request(
  File "/home/par/virtualenvs/mememaker/lib/python3.10/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**System information**
Please provide the following information:
- python  3.10.12
- 15.0.0
- pip3 install pytube

**Comment by borischu** [comment]
Confirming the fix works https://github.com/JuanBindez/pytubefix/commit/c0c07b046d8b59574552404931f6ce3c6590137d

**Comment by JSLBrowning** [comment]
Works great for me!

**Comment by tomegiulio** [comment]
Works for me too thank you very much 🙏🏻

**Comment by nicopyds** [comment]
I have tested the fix from https://github.com/JuanBindez/pytubefix/commit/c0c07b046d8b59574552404931f6ce3c6590137d and it works perfectly.

**Comment by Jason897571** [comment]
Hi there, I tried the solution above and it fixed the issue yesterday. However, when I try it tody, it pops up another error. Any solution for it?

<img width="489" alt="image" src="https://github.com/pytube/pytube/assets/67337624/d26fcd91-d4c2-47c0-815e-050bd7a7cc1f">

**Comment by dill503084699** [comment]
Omgomg it work !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! thank god , I search this answer for THREE DAY to resolve this problem  !!!!

**Comment by Jason897571** [comment]
> Omgomg it work !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! thank god , I search this answer for THREE DAY to resolve this problem !!!!

Does it work? I used the solution above and it worked for one day. But it doesn't work now

**Comment by bageler** [comment]
> > Omgomg it work !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! thank god , I search this answer for THREE DAY to resolve this problem !!!!
> 
> Does it work? I used the solution above and it worked for one day. But it doesn't work now

I installed pytubefix and import that instead of pytube and it works

**Comment by hyunseok-yang** [comment]
Thanks god..

I rellay appreciate !! 

I'm just about to getting CRAZY... (need to see psychiatris...)

**Comment by kaeswar** [comment]
the Fix is Working , thanks guys

**Comment by LinusLangner** [comment]
> > > Omgomg it work !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! thank god , I search this answer for THREE DAY to resolve this problem !!!!
> > 
> > 
> > Does it work? I used the solution above and it worked for one day. But it doesn't work now
> 
> I installed pytubefix and import that instead of pytube and it works

Thank you Thank you Thank you!!!

**Comment by garylin111** [comment]
> **Describe the bug** When you use the age restriction fix that has always worked ([described here](https://stackoverflow.com/questions/75791765/how-to-download-videos-that-require-age-verification-with-pytube)), it now produces bad request.
> 
> **To Reproduce** Please provide the following information:
> 
> * innterube.py
> * steps to repro: get pytube 15.0.0, try to get video url for an [age restricted video](https://youtu.be/Y4-GSFKZmEg).
> * notice you get age restriction.
> * Implement the fix from that SO post.
> * Notice you get 400 bad request
> 
> **Expected behavior**
> 
> * expected behavior is you get the video link (which you always used to)
> 
> **The Fix**
> 
> * the fix is present in this fork of pytube, please merge this in: [the inntertube.py commit with fix](https://github.com/JuanBindez/pytubefix/commit/c0c07b046d8b59574552404931f6ce3c6590137d)
> 
> **Output**
> 
> ```
> Traceback (most recent call last):
>   File "/srv/mememaker-web/manage.py", line 22, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/par/virtualenvs/mememaker/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
>     utility.execute()
>   File "/home/par/virtualenvs/mememaker/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/home/par/virtualenvs/mememaker/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/home/par/virtualenvs/mememaker/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
>     output = self.handle(*args, **options)
>   File "/srv/mememaker-web/mememaker/management/commands/pytube_oauth.py", line 10, in handle
>     thevid = yt.streams.filter(progressive=True, file_extension='mp4').order_by('resolution').desc().first()
>   File "/home/par/virtualenvs/mememaker/lib/python3.10/site-packages/pytube/__main__.py", line 296, in streams
>     return StreamQuery(self.fmt_streams)
>   File "/home/par/virtualenvs/mememaker/lib/python3.10/site-packages/pytube/__main__.py", line 176, in fmt_streams
>     stream_manifest = extract.apply_descrambler(self.streaming_data)
>   File "/home/par/virtualenvs/mememaker/lib/python3.10/site-packages/pytube/__main__.py", line 157, in streaming_data
>     if 'streamingData' in self.vid_info:
>   File "/home/par/virtualenvs/mememaker/lib/python3.10/site-packages/pytube/__main__.py", line 246, in vid_info
>     innertube_response = innertube.player(self.video_id)
>   File "/home/par/virtualenvs/mememaker/lib/python3.10/site-packages/pytube/innertube.py", line 448, in player
>     return self._call_api(endpoint, query, self.base_data)
>   File "/home/par/virtualenvs/mememaker/lib/python3.10/site-packages/pytube/innertube.py", line 390, in _call_api
>     response = request._execute_request(
>   File "/home/par/virtualenvs/mememaker/lib/python3.10/site-packages/pytube/request.py", line 37, in _execute_request
>     return urlopen(request, timeout=timeout)  # nosec
>   File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/lib/python3.10/urllib/request.py", line 525, in open
>     response = meth(req, response)
>   File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
>     response = self.parent.error(
>   File "/usr/lib/python3.10/urllib/request.py", line 563, in error
>     return self._call_chain(*args)
>   File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 400: Bad Request
> ```
> 
> **System information** Please provide the following information:
> 
> * python  3.10.12
> * 15.0.0
> * pip3 install pytube

it worked! thanks a lot!

**Comment by valentimaraujo** [comment]
I have tested the fix from https://github.com/JuanBindez/pytubefix/commit/c0c07b046d8b59574552404931f6ce3c6590137d and it works perfectly.

My code:

```
# pytube==15.0.0
from pytube import YouTube
from pytube.innertube import _default_clients

_default_clients["ANDROID"]["context"]["client"]["clientVersion"] = "19.08.35"
_default_clients["ANDROID_MUSIC"] = _default_clients["ANDROID"]

source_url = "https://www.youtube.com/watch?v=XXXXXXXXXX"
extractYB = YouTube(source_url)
video_stream = extractYB.streams.get_highest_resolution()
destination_path = './video/youtube'
video_stream.download(output_path=destination_path)
video_size_bytes = video_stream.filesize
video_duration_seconds = extractYB.length
```

**Comment by dill503084699** [comment]
> I have tested the fix from [JuanBindez/pytubefix@c0c07b0](https://github.com/JuanBindez/pytubefix/commit/c0c07b046d8b59574552404931f6ce3c6590137d) and it works perfectly.
> 
> My code:
> 
> ```
> # pytube==15.0.0
> from pytube import YouTube
> from pytube.innertube import _default_clients
> 
> _default_clients["ANDROID"]["context"]["client"]["clientVersion"] = "19.08.35"
> _default_clients["ANDROID_MUSIC"] = _default_clients["ANDROID"]
> 
> source_url = "https://www.youtube.com/watch?v=XXXXXXXXXX"
> extractYB = YouTube(source_url)
> video_stream = extractYB.streams.get_highest_resolution()
> destination_path = './video/youtube'
> video_stream.download(output_path=destination_path)
> video_size_bytes = video_stream.filesize
> video_duration_seconds = extractYB.length
> ```

I used your code tonight.It work but  only half of the video downloaded in 'video/youtube' inside .403 and 400 problems  appears when downloading



> > Omgomg it work !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! thank god , I search this answer for THREE DAY to resolve this problem !!!!
> 
> Does it work? I used the solution above and it worked for one day. But it doesn't work now

It worked some time ago, but work not now

**Comment by sayyid5416** [comment]
Thanks for the fix. It's now working fine

**Comment by mdublin** [comment]
None of the approaches in this thread currently work, they are resulting in 403 errors.

```
from pytube import YouTube
from pytube.innertube import _default_clients

_default_clients["ANDROID"]["context"]["client"]["clientVersion"] = "19.08.35"
_default_clients["ANDROID_MUSIC"] = _default_clients["ANDROID"]

source_url = "https://www.youtube.com/watch?app=desktop&v=xpikzXSpNjc"
extractYB = YouTube(source_url)
video_stream = extractYB.streams.get_highest_resolution()
destination_path = './video/youtube'
video_stream.download(output_path=destination_path)
video_size_bytes = video_stream.filesize
video_duration_seconds = extractYB.length
```

the above code returns the following: 

```
Traceback (most recent call last):
  File "/Users/mogreen/Downloads/ytdownloader.py", line 11, in <module>
    video_stream.download(output_path=destination_path)
  File "/Users/mogreen/Library/Python/3.9/lib/python/site-packages/pytube/streams.py", line 314, in download
    for chunk in request.stream(
  File "/Users/mogreen/Library/Python/3.9/lib/python/site-packages/pytube/request.py", line 157, in stream
    response = _execute_request(
  File "/Users/mogreen/Library/Python/3.9/lib/python/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by sayyid5416** [comment]
> None of the approaches in this thread currently work, they are resulting in 404 errors.

- Change `client` in `Innertube` class to `ANDROID`.
- Change client versions.

**Comment by CurtisDS** [comment]
Adding this to the top of my code worked for me:
```python
from pytube.innertube import _default_clients

_default_clients["ANDROID"]["context"]["client"]["clientVersion"] = "19.08.35"
_default_clients["IOS"]["context"]["client"]["clientVersion"] = "19.08.35"
_default_clients["ANDROID_EMBED"]["context"]["client"]["clientVersion"] = "19.08.35"
_default_clients["IOS_EMBED"]["context"]["client"]["clientVersion"] = "19.08.35"
_default_clients["IOS_MUSIC"]["context"]["client"]["clientVersion"] = "6.41"
_default_clients["ANDROID_MUSIC"] = _default_clients["ANDROID_CREATOR"]
```

**Comment by NeonLightning** [comment]
> ```python
> _default_clients["ANDROID"]["context"]["client"]["clientVersion"] = "19.08.35"
> _default_clients["IOS"]["context"]["client"]["clientVersion"] = "19.08.35"
> _default_clients["ANDROID_EMBED"]["context"]["client"]["clientVersion"] = "19.08.35"
> _default_clients["IOS_EMBED"]["context"]["client"]["clientVersion"] = "19.08.35"
> _default_clients["IOS_MUSIC"]["context"]["client"]["clientVersion"] = "6.41"
> _default_clients["ANDROID_MUSIC"] = _default_clients["ANDROID_CREATOR"]
> ```

didn't work for me :(

**Comment by LaughingMaann** [comment]
omg this fixed it

https://github.com/JuanBindez/pytubefix/commit/c0c07b046d8b59574552404931f6ce3c6590137d

url = "https://www.youtube.com/watch?v=RxOBOhRECoo"
yt = YouTube(url)
video = yt.streams.get_highest_resolution()
video.download('D:\media') 

^used to throw error " HTTP Error 400: Bad Request"
but now it works after using new diffs

**Comment by cleong110** [comment]
Ran into this today, and after a `pip install pytubefix` and switching to `import pytubefix`, I was able to download files successfully.

**Comment by cleong110** [comment]
![Screenshot from 2024-07-17 16-37-36](https://github.com/user-attachments/assets/c8d48cac-a271-46ee-ab9d-4bc8cefe0b84)
did a quick diff of the two repos using meld. I first renamed the folder `pytubefix` in the pytubefix repo to `pytube` so that Meld would realize they can be diff'd.

Some notable changes include:
* many many edits to innertube.py
* jsinterp.py, which "contains all the logic needed to interpret the JavaScript obfuscation functions that YouTube uses."
* contains new (July 9, 2024) patterns in cipher.py, probably related to https://github.com/pytube/pytube/issues/1954

Given that _this_ repo was last updated a year ago, I think just using pytubefix is the answer

**Comment by SuryanshuTiwari** [comment]
### Got this error when i switched from pytube to pytubefix

File "/path/to/file/worker.py", line 228, in process_task
    audio_file_path, audio_duration = DownloadAudio(current_url,email)
  File "/path/to/file/worker.py", line 94, in DownloadAudio
    yt = YouTube(current_url)#, use_oauth=oauth_data)
  File "/var/www/path/to/file/venv/lib/python3.10/site-packages/pytubefix/__main__.py", line 110, in __init__
    self.video_id = extract.video_id(url)
  File "/var/www/path/to/file/venv/lib/python3.10/site-packages/pytubefix/extract.py", line 137, in video_id
    return regex_search(r"(?:v=|\/)([0-9A-Za-z_-]{11}).*", url, group=1)
  File "/var/www/path/to/file/venv/lib/python3.10/site-packages/pytubefix/helpers.py", line 129, in regex_search
    raise RegexMatchError(caller="regex_search", pattern=pattern)
pytubefix.exceptions.RegexMatchError: regex_search: **could not find match for (?:v=|\/)([0-9A-Za-z_-]{11}).****


```
from pytubefix import YouTube

def DownloadAudio(current_url, gmail):
        DownloadAudioStartTime = time.time()
        yt = YouTube(current_url)#, use_oauth=oauth_data)
        audio = yt.streams.filter(only_audio=True).first()


        # Use a temporary file to store the audio content
        with tempfile.NamedTemporaryFile(delete=False, suffix=".mp4") as temp_file:
            # Stream the audio content and write it to the temporary file
            audio.stream_to_buffer(temp_file)
            audio_file_path = temp_file.name
        # audio_file_path = noiseReducer(audio_file_path)
        DownloadAudioEndTime = time.time()
        DownloadAudioTotalTime = DownloadAudioEndTime - DownloadAudioStartTime
        print("Download Audio took this much time to do: "+ str(DownloadAudioTotalTime))
        # Get the duration of the audio
        audio_duration = yt.length
        return audio_file_path,audio_duration

```

Any help is truly appreciated.

Thanks!!

**Comment by Dr-Insanity** [comment]
I just wonder why. Despite:
- There being a fix.
- Hundreds of people having the SAME error.
- The bug having 100% accurate reproducing steps.

And yet, the fix is not merged AFTER MONTHS. What's the hold-up? 
Like you ask for contributions on the README.MD and yet nothing is treated.

**Comment by JSLBrowning** [comment]
@Dr-Insanity This repo seems to have been abandoned. Check out [pytubefix](https://github.com/JuanBindez/pytubefix) — it's implemented this fix, as well as others, and is being updated regularly.

**Comment by Dr-Insanity** [comment]
> @Dr-Insanity This repo seems to have been abandoned. Check out [pytubefix](https://github.com/JuanBindez/pytubefix) — it's implemented this fix, as well as others, and is being updated regularly.

Ah, much thanks, @JSLBrowning

**Comment by AlvaroMosGar** [comment]
import pytube as py
import os

link = input("Link: ")

yt = py.YouTube(link)

name = yt.title

des = yt.streams.filter(only_audio=True).first().download()

os.rename(des, name + ".mp3")

is correct??? i have a 400 bad request error ¿?

**Comment by Dr-Insanity** [comment]
> is correct??? i have a 400 bad request error ¿?

It is correct, @AlvaroMosGar. There's just a *very* little problem in pytube. You could do 2 things here:
- Use [pytubefix](https://github.com/JuanBindez/pytubefix)
- Apply the [fix](https://github.com/JuanBindez/pytubefix/commit/c0c07b046d8b59574552404931f6ce3c6590137d) yourself in pytube.

I recommend solution 1 because it is maintained. Applying the fix yourself essentially means you're on your own now with the library. In that case, you might as well make a fork, but yeah, pytubefix exists. But if you think you can do better, by all means, make a fork. Also, please read the comments here in full before posting what's already established... I'm surprised people don't do this automatically...

**Comment by jessicaeverard** [comment]
Use library pytubefix-6.16.2 - line 54             client: str = 'TV_EMBED', finally fixed it
