### ISSUE TITLE
Fails on download

### ISSUE THREAD

**Issue by ifuchs** [pytube/pytube#190]
This was working fine a month ago. I upgraded to the latest version but I am now getting the following:

Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/B86CEE4E-E4A9-4BB4-9CA7-6E13BDA2C2A4/Pythonista3/Documents/youtube_dl.py", line 4, in <module>
    YouTube(appex.get_url()).streams.first().download()
  File "/private/var/mobile/Containers/Shared/AppGroup/B86CEE4E-E4A9-4BB4-9CA7-6E13BDA2C2A4/Pythonista3/Documents/site-packages/pytube/__main__.py", line 81, in __init__
    
  File "/private/var/mobile/Containers/Shared/AppGroup/B86CEE4E-E4A9-4BB4-9CA7-6E13BDA2C2A4/Pythonista3/Documents/site-packages/pytube/__main__.py", line 90, in prefetch_init
    """
  File "/private/var/mobile/Containers/Shared/AppGroup/B86CEE4E-E4A9-4BB4-9CA7-6E13BDA2C2A4/Pythonista3/Documents/site-packages/pytube/__main__.py", line 117, in init
    stream_maps.append('adaptive_fmts')
  File "/private/var/mobile/Containers/Shared/AppGroup/B86CEE4E-E4A9-4BB4-9CA7-6E13BDA2C2A4/Pythonista3/Documents/site-packages/pytube/mixins.py", line 76, in apply_descrambler
    for i in stream_data[key].split(',')
KeyError: 'url_encoded_fmt_stream_map'

**Comment by J0K3RAS** [comment]
This error can be solved by uninstalling pytube and downloading the latest version again.

I had the same problem with pytube 7.0.18 but now with 8.0.X works fine

**Comment by ifuchs** [comment]
Thanks, I did exactly that and it is still failing on Pythonista but works fine on the Mac.
