### ISSUE TITLE
[BUG] can't download this video

### ISSUE THREAD

**Issue by a26364177** [pytube/pytube#1911]
**To Reproduce**
pytube https://www.youtube.com/watch\?v\=J5Z7tIq7bco\&ab_channel\=SukimaSwitchVEVO
pytube https://www.youtube.com/watch?v=J5Z7tIq7bco

**Output**
```
Loading video...
Kanade.mp4 | 5 MB
Traceback (most recent call last):
  File "/Users/david/path/to/venv/bin/pytube", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/david/path/to/venv/lib/python3.12/site-packages/pytube/cli.py", line 53, in main
    _perform_args_on_youtube(youtube, args)
  File "/Users/david/path/to/venv/lib/python3.12/site-packages/pytube/cli.py", line 60, in _perform_args_on_youtube
    download_highest_resolution_progressive(
  File "/Users/david/path/to/venv/lib/python3.12/site-packages/pytube/cli.py", line 479, in download_highest_resolution_progressive
    _download(stream, target=target)
  File "/Users/david/path/to/venv/lib/python3.12/site-packages/pytube/cli.py", line 263, in _download
    stream.download(output_path=target, filename=filename)
  File "/Users/david/path/to/venv/lib/python3.12/site-packages/pytube/streams.py", line 314, in download
    for chunk in request.stream(
  File "/Users/david/path/to/venv/lib/python3.12/site-packages/pytube/request.py", line 189, in stream
    chunk = response.read()
            ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 495, in read
    s = self._safe_read(self.length)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 642, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(120972 bytes read, 5782963 more expected)
**System information**
Please provide the following information:
- Python version (run `python --version`)
- Pytube version (run `print(pytube.__version__)` in python)
- Command used to install pytube

**Comment by josuesalomao** [comment]
Hello! Can you send the code here?

**Comment by SarthakNikhal** [comment]
Created pull request to handle the exception

**Comment by SarthakNikhal** [comment]
@RONNCC Can you please review my contribution? Thanks

**Comment by josuesalomao** [comment]
> @RONNCC Can you please review my contribution? Thanks



> Created pull request to handle the exception

my code 

````py
def capturar():
    link = links.get(1.0,tk.END+'')
    yt = YouTube(link)
    video = yt.streams.filter(type='mp4')
    video = yt.streams.get_highest_resolution()
    video.download(rf'C:\Users\{nomepasta}\Downloads')
    os.joinpath(rf'C:\Users\{nomepasta}\Downloads')
````

**Comment by RONNCC** [comment]
@pedrosalomaodw  sorry i'm a bit confused here -- what should I review?

**Comment by josuesalomao** [comment]
> @pedrosalomaodw sorry i'm a bit confused here -- what should I review?

just for him to see and see what could be wrong with his code

**Comment by SarthakNikhal** [comment]
@RONNCC I was hoping you would review the changes, accept the associated pull request and merge the code
