### ISSUE TITLE
[BUG]pytube stops working

### ISSUE THREAD

**Issue by shen3lu4** [pytube/pytube#1943]
**Before creating an issue**

Please confirm that you are on the latest version of pytube by installing from the source.
You can do this by running `python -m pip install git+https://github.com/pytube/pytube`.
Sometimes, the pypi library repository is not up to date, and your issue may have been fixed already!

**Describe the bug**
pytube doesn't return any valid response when trying to get author, description, publish_date etc. and cannot download the video

**To Reproduce**
from pytube import YouTube
url = "http://youtube.com/watch?v=2lAe1cqCOXo"
myVideo = YouTube(url)
print(myVideo.author)
print(myVideo.description)
print(myVideo.publish_date)
myVideo.streams.get_highest_resolution().download()

**Expected behavior**
expected to get the correct author, description, publish_date and the videos downloaded

**Output**
unknown
None
None
Traceback (most recent call last):
  File "xxxxxx", line 14, in <module>
    myVideo.streams.get_highest_resolution().download()
  File "xxxxxx/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "xxxxxx/__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "xxxxxx/__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
KeyError: 'streamingData'

**System information**
Please provide the following information:
- Python version (run `python --version`) 3.9.13
- Pytube version (run `print(pytube.__version__)` in python) 15.0.0
- Command used to install pytube pip install pytube

**Comment by RicardoEscobar** [comment]
I think YouTube killed pytube remotely, but I'm not sure if something can be done about it.

**Comment by shen3lu4** [comment]
i noticed that I am getting the following in the response:
'status': 'LOGIN_REQUIRED', 'reason': 'Sign in to confirm you’re not a bot'

how to get around this?

**Comment by dracarys69** [comment]
same here

**Comment by dom-ar** [comment]
For me I have issues loading music videos. All of them will throw age-restricted exception in try when using yt.check_availability() yt.bypass_age_gate(). If I remove bypass the vidoe will be loaded, but then also the description wont be extracted, but everything else will be.

If I load a normal video everything seems to work.

**Comment by shen3lu4** [comment]
Found a way to get around the bot issue. Add user_oauth=True and allow_oauth_cache=True to the parameter list:
YouTube(url, use_oauth=True, allow_oauth_cache=True)
First time it will ask you to manually authenticate. Once that's done the token is cached where the pytube is installed. Then the pytube works just as before.

**Comment by RicardoEscobar** [comment]
> Found a way to get around the bot issue. Add user_oauth=True and allow_oauth_cache=True to the parameter list: YouTube(url, use_oauth=True, allow_oauth_cache=True) First time it will ask you to manually authenticate. Once that's done the token is cached where the pytube is installed. Then the pytube works just as before.

It doesn't work.
I tried it like this:
```python
# importing packages
from pytube import YouTube
import os

# url input from user
yt = YouTube(
    use_oauth=True,
    allow_oauth_cache=True,
    url=str(input("Enter the URL of the video you want to download: \n>> ")),
)

# extract only audio
video = yt.streams.filter(only_audio=True).first()

# check for destination to save file
print("Enter the destination (leave blank for current directory)")
destination = str(input(">> ")) or "."

# download the file
out_file = video.download(output_path=destination)

# save the file
base, ext = os.path.splitext(out_file)
new_file = base + ".mp3"
os.rename(out_file, new_file)

# result of success
print(yt.title + " has been successfully downloaded.")
```
I got asked to sign in a YouTube user for a YouTube app for tv, but after that, this is all I get.

I got this error:
```
(venv) jorge@ubuntu-server:~/git/pytube-paralell-processing(main)$ python3.12 run2.py
Enter the URL of the video you want to download:
>> https://youtu.be/Jks0F2vZ6zo?si=4ZkjjNB-PCN1Q05k
Traceback (most recent call last):
  File "/home/jorge/git/pytube-paralell-processing/run2.py", line 13, in <module>
    video = yt.streams.filter(only_audio=True).first()
            ^^^^^^^^^^
  File "/home/jorge/.local/lib/python3.12/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "/home/jorge/.local/lib/python3.12/site-packages/pytube/__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
                                                ^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/.local/lib/python3.12/site-packages/pytube/__main__.py", line 160, in streaming_data
    self.bypass_age_gate()
  File "/home/jorge/.local/lib/python3.12/site-packages/pytube/__main__.py", line 257, in bypass_age_gate
    innertube_response = innertube.player(self.video_id)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/.local/lib/python3.12/site-packages/pytube/innertube.py", line 448, in player
    return self._call_api(endpoint, query, self.base_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/.local/lib/python3.12/site-packages/pytube/innertube.py", line 390, in _call_api
    response = request._execute_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/.local/lib/python3.12/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

I guess YouTube killed pytube. Is not working for me for a couple of months now.
Still looking for an alternative that works.

**Comment by Kar1mAhmed** [comment]
@RicardoEscobar 
Have you find any alternative?

**Comment by RicardoEscobar** [comment]
> @RicardoEscobar 
> Have you find any alternative? 

No. I gave up a long time ago.
I moved on.
I'm learning Polars to do data analysis at my day job.

**Comment by dyestrad** [comment]
> @RicardoEscobar Have you find any alternative?

I found a working alternative using pytubefix, details here: https://stackoverflow.com/questions/78160027/how-to-solve-http-error-400-bad-request-in-pytube

In summary, you can use this branch of pytube that has the fix
https://github.com/JuanBindez/pytubefix/tree/c0c07b046d8b59574552404931f6ce3c6590137d

**Comment by dyestrad** [comment]
> > Found a way to get around the bot issue. Add user_oauth=True and allow_oauth_cache=True to the parameter list: YouTube(url, use_oauth=True, allow_oauth_cache=True) First time it will ask you to manually authenticate. Once that's done the token is cached where the pytube is installed. Then the pytube works just as before.
> 
> It doesn't work. I tried it like this:
> 
> ```python
> # importing packages
> from pytube import YouTube
> import os
> 
> # url input from user
> yt = YouTube(
>     use_oauth=True,
>     allow_oauth_cache=True,
>     url=str(input("Enter the URL of the video you want to download: \n>> ")),
> )
> 
> # extract only audio
> video = yt.streams.filter(only_audio=True).first()
> 
> # check for destination to save file
> print("Enter the destination (leave blank for current directory)")
> destination = str(input(">> ")) or "."
> 
> # download the file
> out_file = video.download(output_path=destination)
> 
> # save the file
> base, ext = os.path.splitext(out_file)
> new_file = base + ".mp3"
> os.rename(out_file, new_file)
> 
> # result of success
> print(yt.title + " has been successfully downloaded.")
> ```
> 
> I got asked to sign in a YouTube user for a YouTube app for tv, but after that, this is all I get.
> 
> I got this error:
> 
> ```
> (venv) jorge@ubuntu-server:~/git/pytube-paralell-processing(main)$ python3.12 run2.py
> Enter the URL of the video you want to download:
> >> https://youtu.be/Jks0F2vZ6zo?si=4ZkjjNB-PCN1Q05k
> Traceback (most recent call last):
>   File "/home/jorge/git/pytube-paralell-processing/run2.py", line 13, in <module>
>     video = yt.streams.filter(only_audio=True).first()
>             ^^^^^^^^^^
>   File "/home/jorge/.local/lib/python3.12/site-packages/pytube/__main__.py", line 296, in streams
>     return StreamQuery(self.fmt_streams)
>                        ^^^^^^^^^^^^^^^^
>   File "/home/jorge/.local/lib/python3.12/site-packages/pytube/__main__.py", line 176, in fmt_streams
>     stream_manifest = extract.apply_descrambler(self.streaming_data)
>                                                 ^^^^^^^^^^^^^^^^^^^
>   File "/home/jorge/.local/lib/python3.12/site-packages/pytube/__main__.py", line 160, in streaming_data
>     self.bypass_age_gate()
>   File "/home/jorge/.local/lib/python3.12/site-packages/pytube/__main__.py", line 257, in bypass_age_gate
>     innertube_response = innertube.player(self.video_id)
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/jorge/.local/lib/python3.12/site-packages/pytube/innertube.py", line 448, in player
>     return self._call_api(endpoint, query, self.base_data)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/jorge/.local/lib/python3.12/site-packages/pytube/innertube.py", line 390, in _call_api
>     response = request._execute_request(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/jorge/.local/lib/python3.12/site-packages/pytube/request.py", line 37, in _execute_request
>     return urlopen(request, timeout=timeout)  # nosec
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/urllib/request.py", line 215, in urlopen
>     return opener.open(url, data, timeout)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/urllib/request.py", line 521, in open
>     response = meth(req, response)
>                ^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/urllib/request.py", line 630, in http_response
>     response = self.parent.error(
>                ^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/urllib/request.py", line 559, in error
>     return self._call_chain(*args)
>            ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/urllib/request.py", line 492, in _call_chain
>     result = func(*args)
>              ^^^^^^^^^^^
>   File "/usr/lib/python3.12/urllib/request.py", line 639, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 400: Bad Request
> ```
> 
> I guess YouTube killed pytube. Is not working for me for a couple of months now. Still looking for an alternative that works.

I found a working alternative using pytubefix, details here: https://stackoverflow.com/questions/78160027/how-to-solve-http-error-400-bad-request-in-pytube

In summary, you can use this branch of pytube that has the fix
https://github.com/JuanBindez/pytubefix/tree/c0c07b046d8b59574552404931f6ce3c6590137d
