### ISSUE TITLE
KeyError : 'streamingData'

### ISSUE THREAD

**Issue by iCodexDev** [pytube/pytube#1977]
```python
WARNING:pytube.__main__:Please open an issue at https://github.com/pytube/pytube/issues and provide this log output.
'streamingData'
```

This error happened, what is the problem?

**Comment by Corny69** [comment]
I'm new to code so don't make fun of me 😭 but is it the capital D in data

**Comment by iCodexDev** [comment]
```python
Loading video...
Traceback (most recent call last):
  File "/usr/local/bin/pytube", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/pytube/cli.py", line 53, in main
    _perform_args_on_youtube(youtube, args)
  File "/usr/local/lib/python3.9/dist-packages/pytube/cli.py", line 60, in _perform_args_on_youtube
    download_highest_resolution_progressive(
  File "/usr/local/lib/python3.9/dist-packages/pytube/cli.py", line 474, in download_highest_resolution_progressive
    stream = youtube.streams.get_highest_resolution()
  File "/usr/local/lib/python3.9/dist-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "/usr/local/lib/python3.9/dist-packages/pytube/__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "/usr/local/lib/python3.9/dist-packages/pytube/__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
KeyError: 'streamingData'

```

anyone can help for this issue?

**Comment by chri204** [comment]
> ```python
> 
> WARNING:pytube.__main__:Please open an issue at https://github.com/pytube/pytube/issues and provide this log output.
> 
> 'streamingData'
> 
> ```
> 
> 
> 
> This error happened, what is the problem? 
Https:// open issue//.'streamData'
> 'startup'
>'open source'
> 'streaming data'
