### ISSUE TITLE
HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by Debayan08** [pytube/pytube#1983]
Traceback (most recent call last):
  File "/home/das/Desktop/Emilia-main/Helpers/ytdl.py", line 17, in <module>
    video_dl("https://youtu.be/fabelAs_m08?si=P10D2uoKkejV_rU0")
  File "/home/das/Desktop/Emilia-main/Helpers/ytdl.py", line 12, in video_dl
    video_stream = yt.streams.get_highest_resolution()
  File "/home/das/.local/lib/python3.10/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "/home/das/.local/lib/python3.10/site-packages/pytube/__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "/home/das/.local/lib/python3.10/site-packages/pytube/__main__.py", line 160, in streaming_data
    self.bypass_age_gate()
  File "/home/das/.local/lib/python3.10/site-packages/pytube/__main__.py", line 257, in bypass_age_gate
    innertube_response = innertube.player(self.video_id)
  File "/home/das/.local/lib/python3.10/site-packages/pytube/innertube.py", line 448, in player
    return self._call_api(endpoint, query, self.base_data)
  File "/home/das/.local/lib/python3.10/site-packages/pytube/innertube.py", line 390, in _call_api
    response = request._execute_request(
  File "/home/das/.local/lib/python3.10/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

**Comment by G4NS** [comment]
I have the same thing. Have you decided yet?

**Comment by G4NS** [comment]
https://github.com/pytube/pytube/issues/1973
