### ISSUE TITLE
[BUG]: pytubefix.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

### ISSUE THREAD

**Issue by Eran9** [pytube/pytube#1991]
I assure that I have updated pytube by running following command:
```shell
pip install git+https://github.com/pytube/pytube`.
```

**Describe the bug**
The library shows an issue trying to match the function name in YouTube's Javascript with the given regex patterns.
However, even when I run something such as
```python
print(pytube.__version__)
```
it throws the same error.

**To Reproduce**
Please provide the following information:
The specific links:
https://youtu.be/O2q59LClA7Q?si=sMnzId1kyu2J74Gi
https://youtu.be/2md4HQNRqJA?si=YCkRtDYVpqGSOUZA

**Expected behavior**
Expected to the get the details of the video and its streams and download the video

**Output**
```shell
Traceback (most recent call last):
  File "c:\Users\ASUS\Documents\Python files\GUI\Projects\YouTubeDownloader_V2.0\DownloadAudio.py", line 88, in <module>
    downloader = DownloadAudio(song)
                 ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ASUS\Documents\Python files\GUI\Projects\YouTubeDownloader_V2.0\DownloadAudio.py", line 14, in __init__
    super().__init__(link)
  File "c:\Users\ASUS\Documents\Python files\GUI\Projects\YouTubeDownloader_V2.0\DownloadVideo.py", line 79, in __init__
    self.video_resolutions = self.get_resolution()
                             ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ASUS\Documents\Python files\GUI\Projects\YouTubeDownloader_V2.0\DownloadAudio.py", line 20, in get_resolution
    audio_files = self.video.streams.filter(adaptive=True, only_audio=True).order_by("abr").desc()
                  ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Documents\Python files\GUI\Projects\YouTubeDownloader_V2.0\.venv\Lib\site-packages\pytubefix\__main__.py", line 565, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Documents\Python files\GUI\Projects\YouTubeDownloader_V2.0\.venv\Lib\site-packages\pytubefix\__main__.py", line 275, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\ASUS\Documents\Python files\GUI\Projects\YouTubeDownloader_V2.0\.venv\Lib\site-packages\pytubefix\extract.py", line 424, in apply_signature
    cipher = Cipher(js=js)
             ^^^^^^^^^^^^^
  File "C:\Users\ASUS\Documents\Python files\GUI\Projects\YouTubeDownloader_V2.0\.venv\Lib\site-packages\pytubefix\cipher.py", line 25, in __init__
    self.throttling_function_name = get_throttling_function_name(js)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Documents\Python files\GUI\Projects\YouTubeDownloader_V2.0\.venv\Lib\site-packages\pytubefix\cipher.py", line 137, in get_throttling_function_name
    raise RegexMatchError(
pytubefix.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple
``` 

**System information**
Please provide the following information:
- Python version : python 3

- Pytube version (run `print(pytube.__version__)` in python) : 
```shell
 15.0.0
 ```
- Command used to install pytube : 
```shell
pip install pytube
```

 - To upgrade to latest version: 
```shell
pip install git+https://github.com/pytube/pytube`.
```

**Comment by guillaume-helg** [comment]
Try this (this is the solution I have used to get it fixed, I got it from #1707) : 

Change in Cipher.py

Line 272 & 273 to :

r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&.*?\|\|\s*([a-z]+)',
r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])\([a-z]\)',
And remove the ';' from Line 287.

**Comment by esp3j0** [comment]
I am also like this, the error of the pytubefix library, should be that youtube's js code has been upgraded again today, I was still fine yesterday

**Comment by MrMonster123** [comment]
> Try this (this is the solution I have used to get it fixed, I got it from #1707) :
> 
> Change in Cipher.py
> 
> Line 272 & 273 to :
> 
> r'a.[a-zA-Z]\s*&&\s*([a-z]\s*=\s_a.get("n"))\s_&&._?||\s_([a-z]+)', r'([a-z]\s*=\s*([a-zA-Z0-9$]+)([\d+])([a-z])', And remove the ';' from Line 287.

I tried this, and the issue still persists. It looks like it does not find the match when parsing "js"

here's what I got

`     r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&.*?\|\|\s*([a-z]+)',
        r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])\([a-z]\)',
    ]
    logger.debug('Finding throttling function name')
    for pattern in function_patterns:
        regex = re.compile(pattern)
        function_match = regex.search(js)
        print(function_match)`

    ^^ above is from cipher.py Lines 272-279 (279 is my print statement)

    `https://www.youtube.com/watch?v=nAm_OPVeS4w
None
<re.Match object; span=(613505, 613517), match='(c=rDa[0](c)'>
None
<re.Match object; span=(613505, 613517), match='(c=rDa[0](c)'>
`

**Comment by asdat3** [comment]
See issues before opening a new one...

https://github.com/pytube/pytube/issues/1954#issuecomment-2218287594

perfect solution, honor to this guy

**Comment by Eran9** [comment]
@asdat3 I tried those but it doesnt work... for me at least. The error changed to 'HTTP Error 400: Bad Request' when i used that.

**Comment by asdat3** [comment]
well thats another issue,

I'd suggest reinstalling `pytube` (15) only changing that array to the new one and trying again, the http 400 can be caused by anything, so I'd first make sure to be able to reach the site manually (via a browser) and get more debug info somehow.

Anyhow I am certain the the bug in the `get_throttling_function_name` function is fixed by the mentioned comment

**Comment by NetanelRotem** [comment]
I think youtube changed something

**Comment by MrMonster123** [comment]
> See issues before opening a new one...
> 
> [#1954 (comment)](https://github.com/pytube/pytube/issues/1954#issuecomment-2218287594)
> 
> perfect solution, honor to this guy

This soultion does not seem to work, the first line in the pattern does not find any matches in the "js" and because of that an error is thrown.

Same Error
