### ISSUE TITLE
480p and 720p video with audio url not fetching

### ISSUE THREAD

**Issue by aslimohitdeveloper** [pytube/pytube#1992]
I already installed latest pytube from `python -m pip install git+https://github.com/pytube/pytube` as on 25-Jul-24 IST
Returning error when fetching streams list 
pytube --list https://www.youtube.com/watch?v=46T5PVljf-Y
Loading video...
Traceback (most recent call last):
  File "\Python\Python312\Lib\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "Python\Python312\Lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
             ^^^^^^^^^^^^^
  File "Python\Python312\Lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "\Python\Python312\Lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Python\Python312\Lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "n\Python312\Lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "\Python\Python312\Scripts\pytube.exe\__main__.py", line 7, in <module>
  File "Python\Python312\Lib\site-packages\pytube\cli.py", line 53, in main
    _perform_args_on_youtube(youtube, args)
  File "\Python\Python312\Lib\site-packages\pytube\cli.py", line 66, in _perform_args_on_youtube
    display_streams(youtube)
  File "Python\Python312\Lib\site-packages\pytube\cli.py", line 491, in display_streams
    for stream in youtube.streams:

Again I done some fixes and installed pytube from my fixed repo that is on 
https://github.com/aslimohitdeveloper/pytube_fix
Now it is working but not providing url for 720p video with audio 

**Output**
{
    "stream_info": [
        {
            "audio_url": "https://rr8---sn-gwpa-cvhs.googlevideo.com/videoplayback?expire=1721899165&ei=PcShZo3TEsLVz7sPtp-ysAc&ip=103.191.208.227&id=o-AHIa-UFwkniOVTDqzth5duDQeMHZe7V0jiKXvcVBWSM9&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=to&mm=31%2C26&mn=sn-gwpa-cvhs%2Csn-h5576nsy&ms=au%2Conr&mv=u&mvi=8&pl=23&vprv=1&mime=audio%2Fwebm&rqh=1&gir=yes&clen=2344427&dur=138.941&lmt=1720238261778987&mt=1721877248&fvip=4&keepalive=yes&c=ANDROID_MUSIC&txp=5308224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAKD8gv54SiPwa8nMGBA26o1fXpRfx71cgzzT5QAc0tIrAiBe3ZC3ksuftzFUwSgKZZFZw9dTg5tR3F8UC4TTcjvE_g%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AGtxev0wRgIhAK0aEsPHnSlkyvuEKvtL6urfec2khjrXCWXLwTGjZodnAiEArFL-o4_FStmIeeswLTQD9G-JQ4E0axH30kCqJYyHp8c%3D",
          
        }
    ],
    "thumbnail_url": "https://i.ytimg.com/vi/zkfBEjKXJps/hq720.jpg?sqp=-oaymwEXCNUGEOADIAQqCwjVARCqCBh4INgESFo&rs=AOn4CLD6Y4hU0XhOd0ZLPo1CGYTzK7ASOA",
    "video_title": "Sambhunath (Official Audio) Harry Lather | Pinna Music | Latest Bholenath Song 2024| Bhole Baba"
}

**System information**
Intel i7 11th gen 12GB
Windows 10
python version 3.12.4

**Comment by Nusab19** [comment]
Bro. Put the responses in a code block at least.

And you should not put this much text in an issue

**Comment by aslimohitdeveloper** [comment]
Updated

**Comment by Nusab19** [comment]
Edit your question to this:

I installed latest pytube using `python -m pip install git+https://github.com/pytube/pytube` as on 25-Jul-24 IST

Pytube returns the following error when fetching stream list
```text
pytube --list https://www.youtube.com/watch?v=46T5PVljf-Y
Loading video...
Traceback (most recent call last):
File "\Python\Python312\Lib\site-packages\pytube_main_.py", line 181, in fmt_streams
extract.apply_signature(stream_manifest, self.vid_info, self.js)
File "Python\Python312\Lib\site-packages\pytube\extract.py", line 409, in apply_signature
cipher = Cipher(js=js)
^^^^^^^^^^^^^
File "Python\Python312\Lib\site-packages\pytube\cipher.py", line 43, in init
self.throttling_plan = get_throttling_plan(js)
^^^^^^^^^^^^^^^^^^^^^^^
File "\Python\Python312\Lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
raw_code = get_throttling_function_code(js)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "Python\Python312\Lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
name = re.escape(get_throttling_function_name(js))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "n\Python312\Lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "", line 198, in _run_module_as_main
File "", line 88, in run_code
File "\Python\Python312\Scripts\pytube.exe_main.py", line 7, in
File "Python\Python312\Lib\site-packages\pytube\cli.py", line 53, in main
_perform_args_on_youtube(youtube, args)
File "\Python\Python312\Lib\site-packages\pytube\cli.py", line 66, in _perform_args_on_youtube
display_streams(youtube)
File "Python\Python312\Lib\site-packages\pytube\cli.py", line 491, in display_streams
for stream in youtube.streams:
```

Again I've done some fixes and installed pytube from my fixed repo that is on
https://github.com/aslimohitdeveloper/pytube_fix
Now it is working but not providing url for 720p video with audio

Output
```json
{
"stream_info": [
{
"audio_url": "https://rr8---sn-gwpa-cvhs.googlevideo.com/videoplayback?expire=1721899165&ei=PcShZo3TEsLVz7sPtp-ysAc&ip=103.191.208.227&id=o-AHIa-UFwkniOVTDqzth5duDQeMHZe7V0jiKXvcVBWSM9&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=to&mm=31%2C26&mn=sn-gwpa-cvhs%2Csn-h5576nsy&ms=au%2Conr&mv=u&mvi=8&pl=23&vprv=1&mime=audio%2Fwebm&rqh=1&gir=yes&clen=2344427&dur=138.941&lmt=1720238261778987&mt=1721877248&fvip=4&keepalive=yes&c=ANDROID_MUSIC&txp=5308224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAKD8gv54SiPwa8nMGBA26o1fXpRfx71cgzzT5QAc0tIrAiBe3ZC3ksuftzFUwSgKZZFZw9dTg5tR3F8UC4TTcjvE_g%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AGtxev0wRgIhAK0aEsPHnSlkyvuEKvtL6urfec2khjrXCWXLwTGjZodnAiEArFL-o4_FStmIeeswLTQD9G-JQ4E0axH30kCqJYyHp8c%3D",

    }
],
"thumbnail_url": "https://i.ytimg.com/vi/zkfBEjKXJps/hq720.jpg?sqp=-oaymwEXCNUGEOADIAQqCwjVARCqCBh4INgESFo&rs=AOn4CLD6Y4hU0XhOd0ZLPo1CGYTzK7ASOA",
"video_title": "Sambhunath (Official Audio) Harry Lather | Pinna Music | Latest Bholenath Song 2024| Bhole Baba"
}
```

### System information
> Intel i7 11th gen 12GB
> Windows 10
> python version 3.12.4

**Comment by Nusab19** [comment]
@aslimohitdeveloper afaik, youtube now doesn't return audio embedded video for resolutions more than `360p`.

I checked the progressive streams. `480p` and `720p` is not _progressive_.

So you have to download the audio separately and merge them using **ffmpeg**
