### ISSUE TITLE
How to fix this error plsss help 

### ISSUE THREAD

**Issue by TIMOTHY1498** [pytube/pytube#1993]
I just want to download some yt videos and convert it to audio. But it just throw an error. This is my code
`from pytube import YouTube
import os, time

urlyt = input("Enter YT Link >>> ")
yt = YouTube(urlyt)
 
# extract audio or full video
video = yt.streams.filter(only_audio=True).first() 
 
# download the MP3
out_file = video.download(output_path='D:/Personal Data/Musik') 
print("Downloading ....")

# save the file
base, ext = os.path.splitext(out_file)
new_MP3_file = base + '.mp3'
os.rename(out_file, new_MP3_file)
print("Downloading .... Done")

# exit func

time.sleep(2)
print("Sucessfully downloaded yt video as audio.. Exiting!")
`
Here's the error!
`Traceback (most recent call last):
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
             ^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\timot\OneDrive\Desktop\YT To Mp3.py", line 8, in <module>
    video = yt.streams.filter(only_audio=True).first()
            ^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
             ^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple`

Any help will be appriciated. Thank you

**Comment by TIMOTHY1498** [comment]
Code
`from pytube import YouTube
import os, time

urlyt = input("Enter YT Link >>> ")
yt = YouTube(urlyt)
 
# extract audio or full video
video = yt.streams.filter(only_audio=True).first() 
 
# download the MP3
out_file = video.download(output_path='D:/Personal Data/Musik') 
print("Downloading ....")

# save the file
base, ext = os.path.splitext(out_file)
new_MP3_file = base + '.mp3'
os.rename(out_file, new_MP3_file)
print("Downloading .... Done")

# exit func

time.sleep(2)
print("Sucessfully downloaded yt video as audio.. Exiting!")
`

**Comment by TIMOTHY1498** [comment]
`Traceback (most recent call last):
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
             ^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\timot\OneDrive\Desktop\YT To Mp3.py", line 8, in <module>
    video = yt.streams.filter(only_audio=True).first()
            ^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
             ^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple
`

**Comment by TIMOTHY1498** [comment]
p
