### ISSUE TITLE
[BUG] raise RegexMatchError( pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

### ISSUE THREAD

**Issue by TIMOTHY1498** [pytube/pytube#1994]
I usually use pytube for downloading audio from yt videos. When I try it now, It just throws an error. 

**Video URLs**
```https://youtu.be/tlTxcIUkEeY?si=GE978inwQ5BB5sfI```
```https://youtu.be/sXtoHLm0UB0?si=vLkSLDm5xfn5kAEd```

**My code**
```python
from pytube import YouTube
import os, time

urlyt = input("Enter YT Link >>> ")
yt = YouTube(urlyt)
 
# extract audio or full video
video = yt.streams.filter(only_audio=True).first() 
 
# download the MP3
out_file = video.download(output_path='D:/Personal Data/Musik') 
print("Downloading ....")

# save the file
base, ext = os.path.splitext(out_file)
new_MP3_file = base + '.mp3'
os.rename(out_file, new_MP3_file)
print("Downloading .... Done")

# exit func

time.sleep(2)
print("Sucessfully downloaded yt video as audio.. Exiting!")
```

**Output**
```
Traceback (most recent call last):
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
             ^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\timot\OneDrive\Desktop\YT To Mp3.py", line 8, in <module>
    video = yt.streams.filter(only_audio=True).first()
            ^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
             ^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python3.12\Lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple
```

**How I Installed Pytube**
```shell
pip uninstall pytube
```
then,
```shell
pip install pytube
```

**Comment by EscapedShadows** [comment]
I have the same Issue here! I also tried using the GitHub Version just in case the pypi version was outdated but nope

**Comment by TIMOTHY1498** [comment]
> I have the same Issue here! I also tried using the GitHub Version just in case the pypi version was outdated but nope

Maybe I found the problem. YouTube updated the restriction for download, and the ```cipher.py``` code is not up to date. That's why It throws an error. I hope the developers is updating this code as fast as possible. Thanks you!

**Comment by zhangliluoyang** [comment]
Hello @TIMOTHY1498 
I am facing the same issue. The script that used to work well has suddenly stopped working and thrown error messages like "HTTP Error 400: Bad Request" and "RegexMatchError". Where did you find out about YouTube restriction updating?

**Comment by Cheesecake2960** [comment]
Hello, @zhangliluoyang
I have the same problem and hope the Pytube developers fix it.

### **Errors**
`pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple`
`urllib.error.HTTPError: HTTP Error 400: Bad Request`

**This is translated text**

**Comment by TIMOTHY1498** [comment]
> Hello @TIMOTHY1498 I am facing the same issue. The script that used to work well has suddenly stopped working and thrown error messages like "HTTP Error 400: Bad Request" and "RegexMatchError". Where did you find out about YouTube restriction updating?

Hello @zhangliluoyang
By looking the ```pytube/cipher.py``` file, You can see that there is an explanation starting from line 1 to line 14. Here is the preview of the code.
```py
"""
This module contains all logic necessary to decipher the signature.

YouTube's strategy to restrict downloading videos is to send a ciphered version
of the signature to the client, along with the decryption algorithm obfuscated
in JavaScript. For the clients to play the videos, JavaScript must take the
ciphered version, cycle it through a series of "transform functions," and then
signs the media URL with the output.

This module is responsible for (1) finding and extracting those "transform
functions" (2) maps them to Python equivalents and (3) taking the ciphered
signature and decoding it.

"""
``` 

After looking the code, I am realizing that YouTube updated the API (maybe), So it's harder to download or extract the video to Python equivalents, signature and decoding it. 

I hope that PyTube developers fix this bug as quick as possible.

Thank you for asking!

**Comment by matrusto** [comment]
Modified `cipher.py` file near line 255. It seems to work.


``` python
def get_throttling_function_name(js: str) -> str:
    """Extract the name of the function that computes the throttling parameter.

    :param str js:
        The contents of the base.js asset file.
    :rtype: str
    :returns:
        The name of the function used to compute the throttling parameter.
    """
    function_patterns = [
        # https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-865985377
        # https://github.com/yt-dlp/yt-dlp/commit/48416bc4a8f1d5ff07d5977659cb8ece7640dcd8
        # var Bpa = [iha];
        # ...
        # a.C && (b = a.get("n")) && (b = Bpa[0](b), a.set("n", b),
        # Bpa.length || iha("")) }};
        # In the above case, `iha` is the relevant function name
        r'(?:\.get\("n"\)\)&&\(b=|(?:b=String\.fromCharCode\(110\)|([a-zA-Z0-9$.]+)&&\(b="nn"\[\+\1\]),c=a\.get\(b\)\)&&\(c=)'
        r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])?\([a-z]\)'
        r'\([a-z]\s*=\s*([a-zA-Z0-9$]+)(\[\d+\])\([a-z]\)'
    ]

```
