### ISSUE TITLE
[BUG] urllib.error.HTTPError: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by ishan65** [pytube/pytube#1999]
**Before creating an issue**

Please confirm that you are on the latest version of pytube by installing from the source.
You can do this by running `python -m pip install git+https://github.com/pytube/pytube` Yes.
Sometimes, the pypi library repository is not up to date, and your issue may have been fixed already!

**Describe the bug**
urllib.error.HTTPError: HTTP Error 400: Bad Request

**To Reproduce**
Please provide the following information:

>>> from pytube import YouTube
>>> YouTube('https://youtu.be/PMZOmcZbGmY').streams.first().download() 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\im530\Videos\freecampcode\venv\Lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\im530\Videos\freecampcode\venv\Lib\site-packages\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
                                                ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\im530\Videos\freecampcode\venv\Lib\site-packages\pytube\__main__.py", line 160, in streaming_data
    self.bypass_age_gate()
  File "C:\Users\im530\Videos\freecampcode\venv\Lib\site-packages\pytube\__main__.py", line 257, in bypass_age_gate
    innertube_response = innertube.player(self.video_id)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\im530\Videos\freecampcode\venv\Lib\site-packages\pytube\innertube.py", line 448, in player
    return self._call_api(endpoint, query, self.base_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\im530\Videos\freecampcode\venv\Lib\site-packages\pytube\innertube.py", line 390, in _call_api
    response = request._execute_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\im530\Videos\freecampcode\venv\Lib\site-packages\pytube\request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

**Expected behavior**
It should have started the download of the video

**Output**
If pytube raises an exception, please provide the full traceback for the exception.
- Aleady provided

**System information**
Please provide the following information:
- Python version (run `python --version`) Python 3.11.9

**Comment by Theanhvu1501** [comment]
You can use [https://github.com/JuanBindez/pytubefix](url) instead

**Comment by oldmat3** [comment]
i am having the same issue, installed newest version and tested different links

**Comment by shakfu** [comment]
Having same issue

**Comment by gnzsnz** [comment]
same issue here

python 3.11.6
pytube 15.0.0

```python
$ pytube  https://www.youtube.com/watch?v=enJRIdmVHRE
Loading video...
Traceback (most recent call last):
  File "/Users/user/.local/bin/pytube", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/user/Library/Application Support/pipx/venvs/pytube/lib/python3.11/site-packages/pytube/cli.py", line 53, in main
    _perform_args_on_youtube(youtube, args)
  File "/Users/user/Library/Application Support/pipx/venvs/pytube/lib/python3.11/site-packages/pytube/cli.py", line 60, in _perform_args_on_youtube
    download_highest_resolution_progressive(
  File "/Users/user/Library/Application Support/pipx/venvs/pytube/lib/python3.11/site-packages/pytube/cli.py", line 474, in download_highest_resolution_progressive
    stream = youtube.streams.get_highest_resolution()
             ^^^^^^^^^^^^^^^
  File "/Users/user/Library/Application Support/pipx/venvs/pytube/lib/python3.11/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "/Users/user/Library/Application Support/pipx/venvs/pytube/lib/python3.11/site-packages/pytube/__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
                                                ^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Library/Application Support/pipx/venvs/pytube/lib/python3.11/site-packages/pytube/__main__.py", line 160, in streaming_data
    self.bypass_age_gate()
  File "/Users/user/Library/Application Support/pipx/venvs/pytube/lib/python3.11/site-packages/pytube/__main__.py", line 257, in bypass_age_gate
    innertube_response = innertube.player(self.video_id)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Library/Application Support/pipx/venvs/pytube/lib/python3.11/site-packages/pytube/innertube.py", line 448, in player
    return self._call_api(endpoint, query, self.base_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Library/Application Support/pipx/venvs/pytube/lib/python3.11/site-packages/pytube/innertube.py", line 390, in _call_api
    response = request._execute_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Library/Application Support/pipx/venvs/pytube/lib/python3.11/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.11.6/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.11.6/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.11.6/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.11.6/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.11.6/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.11.6/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by nobody8v** [comment]
Hi, I'm having the same problem

python 3.10.13
pytube 15.0.0

**Comment by JoesSattes** [comment]
I found this https://github.com/pytube/pytube/issues/1973 issue. You can try this commit https://github.com/pytube/pytube/pull/1990/commits/114cb74cfd6e683510c6272051eea94f405d84ae for solving.

**Comment by dmitrimahayana** [comment]
HI All,
Any update related to this issue?

**Comment by dmitrimahayana** [comment]
I think this is the alternative solution:
https://github.com/pytube/pytube/issues/1973#issuecomment-2232907131

**Comment by fcdiass** [comment]
Same issue here!

**Comment by m-asadullah** [comment]
The last contribution to this repository was committed last year (20-May-2023). This `pytube` is not maintained almost for 18 months, the `pytube-15.0.0` is not working fine with `python-3.12.4`, returning HTTP bad request 400.
This might help you to do same as `pytube` with alternative to it, [`pytubefix` ↗️](https://pypi.org/project/pytubefix/)
