### ISSUE TITLE
[BUG] KeyError: 'videoDetails'

### ISSUE THREAD

**Issue by FaridDadashzade** [pytube/pytube#2000]
pyrogram.dispatcher: Exception while accessing title of https://youtube.com/watch?v=vK5gT0NUruQ. Please file a bug report at https://github.com/pytube/pytube
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/pytube/__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'videoDetails'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/container/bot.py", line 478, in song
    status = await status.edit(strings[language]["downloading_music2"].format(yt.author, yt.title))
                                                                                         ^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/pytube/__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=vK5gT0NUruQ. Please file a bug report at https://github.com/pytube/pytube

**Comment by leo-capvano** [comment]
Hi, updates?
