### ISSUE TITLE
[BUG]: pytube raises HTTP Error 400: Bad Request 

### ISSUE THREAD

**Issue by Olakunleniola** [pytube/pytube#2003]
**Description**
When attempting to download a YouTube video using pytube, an HTTP Error 400: Bad Request is encountered. This error occurs consistently across different YouTube video URLs.

**To Reproduce**

```python
import logging
from pytube import YouTube
from pytube.exceptions import RegexMatchError, VideoUnavailable

logging.basicConfig(level=logging.DEBUG)

def download_youtube_video(url, output_path="videos/"):
    try:
        print(f"Attempting to download video from URL: {url}")
        
        # Create a YouTube object
        yt = YouTube(url)

        print("Successfully created YouTube object")

        # Get the highest resolution stream
        stream = yt.streams.get_highest_resolution()

        print(f"Found highest resolution stream: {stream}")

        # Download the video to the specified output path
        stream.download(output_path)
        print(f"Downloaded: {yt.title}")

    except RegexMatchError:
        print("The URL is invalid. Please enter a valid YouTube URL.")
    except VideoUnavailable:
        print("The video is unavailable. Please enter a valid YouTube URL.")
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == '__main__':
    # Test with a known good URL
    test_url = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"  # Replace with a valid YouTube video URL
    output_path = "videos/"
    download_youtube_video(test_url, output_path)
    print("Download attempt complete!")

```

**Expected behavior**
The video should be downloaded without any errors.

**Actual Behavior:**
An error message is displayed: HTTP Error 400: Bad Request.

**Output**
DEBUG:pytube.helpers:matched regex search: (?:v=|\/)([0-9A-Za-z_-]{11}).*
An error occurred: HTTP Error 400: Bad Request

**Additional Information:**
- The error occurs with different YouTube video URLs.
- The URLs are valid and accessible through a web browser.
- Reinstalling pytube and upgrading to the latest version did not resolve the issue.

**System information**
Please provide the following information:
- Python version 3.10.12
- Pytube version 15.0.0
- Command used to install pytube- pip install pytube
- OS: Windows 10, Ubuntu 20.04]

**Comment by leikoilja** [comment]
i encounter the same now, even tho it has been previously working with no issues. I'm thinking it's caused by some changes on youtube side? 
Edit: just saw that it has already been reported [here](https://github.com/pytube/pytube/issues/1999)

**Comment by xiejianchao** [comment]
I have the same problem. Do you have a solution?

**Comment by zaidrabeh** [comment]
Same problem here !

**Comment by gcavalcantes** [comment]
Just pip installed the program and tried to download via the command line on Windows 10. Got the same error.

```
C:\Users\Cliente\Videos>pytube https://www.youtube.com/watch?v=e_7TZhvQpEg
Loading video...
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Cliente\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\pytube.exe\__main__.py", line 7, in <module>
  File "C:\Users\Cliente\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytube\cli.py", line 53, in main
    _perform_args_on_youtube(youtube, args)
  File "C:\Users\Cliente\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytube\cli.py", line 60, in _perform_args_on_youtube
    download_highest_resolution_progressive(
  File "C:\Users\Cliente\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytube\cli.py", line 474, in download_highest_resolution_progressive
    stream = youtube.streams.get_highest_resolution()
  File "C:\Users\Cliente\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\Cliente\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "C:\Users\Cliente\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytube\__main__.py", line 160, in streaming_data
    self.bypass_age_gate()
  File "C:\Users\Cliente\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytube\__main__.py", line 257, in bypass_age_gate
    innertube_response = innertube.player(self.video_id)
  File "C:\Users\Cliente\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytube\innertube.py", line 448, in player
    return self._call_api(endpoint, query, self.base_data)
  File "C:\Users\Cliente\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytube\innertube.py", line 390, in _call_api
    response = request._execute_request(
  File "C:\Users\Cliente\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytube\request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by Abdullah-2238** [comment]
same issue here
Traceback (most recent call last):
  File "f:\PYtube\p1\app.py", line 53, in <module>
    YouTube('https://youtu.be/NpmFbWO6HPU?si=o9qC7-G8uWxuKbqx').streams().first().download()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\PYtube\.venv\Lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "F:\PYtube\.venv\Lib\site-packages\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
                                                ^^^^^^^^^^^^^^^^^^^
  File "F:\PYtube\.venv\Lib\site-packages\pytube\__main__.py", line 160, in streaming_data
    self.bypass_age_gate()
  File "F:\PYtube\.venv\Lib\site-packages\pytube\__main__.py", line 257, in bypass_age_gate
    innertube_response = innertube.player(self.video_id)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\PYtube\.venv\Lib\site-packages\pytube\innertube.py", line 448, in player
    return self._call_api(endpoint, query, self.base_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\PYtube\.venv\Lib\site-packages\pytube\innertube.py", line 390, in _call_api
    response = request._execute_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\PYtube\.venv\Lib\site-packages\pytube\request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Abdullah\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Abdullah\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Abdullah\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Abdullah\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Abdullah\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\Abdullah\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

**Comment by wastu01** [comment]
I have same problem on that 

using python 3.10.11 , pytube 15.0.0, MacOS system

```
from pytube import YouTube
from urllib.error import HTTPError

try:
    # 設定 YouTube 影片網址
    url = 'https://youtu.be/VSUGN5chbaA'

    # 建立 YouTube 物件
    yt = YouTube(url)

    # 取得影片資訊
    title = yt.title # 標題
    length = yt.length # 長度（秒）
    author = yt.author
    thumbnail = yt.thumbnail_url
    channel = yt.channel_url
    view = yt.views

    # 顯示影片資訊
    print(f"影片標題：{title}")
    print(f"觀看數：{view}")
    print(f"影片長度：{length} 秒")
    print(f"頻道作者：{author}")
    print(f"縮圖網址：{thumbnail}")

    print(yt.streams.all())

    # 選擇最高畫質的影片
    stream = yt.streams.filter(file_extension="mp4").get_highest_resolution()

    # 下載影片
    stream.download(output_path='.', filename='video.mp4')

    print("影片下載完成！")
except HTTPError as e:
    print(f"HTTPError: {e}")
except Exception as e:
    print(f"其他錯誤: {e}")

```

**Comment by Preetthee** [comment]
I am running a simple python script to get the available streams and download the video and I am getting the same HTTPError 400: Bad Request.

The script:
```
from pytube import YouTube

video_url = 'url here'

yt = YouTube(video_url)

streams = yt.streams.all()
for stream in streams:
    print(stream)

stream = yt.streams.filter(res="720p").first()

stream.download(output_path='path/to/save')
```





The full error in VC code:
```
Traceback (most recent call last):
  File "c:\Users\User\Videos\Captures\test.py", line 10, in <module>
    streams = yt.streams.all()
              ^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
                                                ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pytube\__main__.py", line 160, in streaming_data
    self.bypass_age_gate()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pytube\__main__.py", line 257, in bypass_age_gate
    innertube_response = innertube.player(self.video_id)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pytube\innertube.py", line 448, in player
    return self._call_api(endpoint, query, self.base_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pytube\innertube.py", line 390, in _call_api
    response = request._execute_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pytube\request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by wastu01** [comment]
I'm experiencing the same issue! It seems that only YouTube videos in the music category can be downloaded. I've switched to using [pytubefix](https://github.com/JuanBindez/pytubefix) as a workaround.

**Comment by qiuchen001** [comment]
> I'm experiencing the same issue! It seems that only YouTube videos in the music category can be downloaded. I've switched to using [pytubefix](https://github.com/JuanBindez/pytubefix) as a workaround.我遇到了同样的问题！似乎只有音乐类别的 YouTube 视频可以下载。我已经改用 [pytubefix](https://github.com/JuanBindez/pytubefix) 作为解决方法。

It's working.

**Comment by Olakunleniola** [comment]
Yeah!!!!.. Pytubefix works..

**Comment by CServer-byte** [comment]
In Pytueb changing the line 223 from `def __init__(self, client='ANDROID_MUSIC', use_oauth=False, allow_cache=True):`
to ` def __init__(self, client='ANDROID_CREATOR', use_oauth=False, allow_cache=True):`
works.
(otherwise you can only download music in normal pytube)

**Comment by johnwilliams999** [comment]
mpting to download video from URL: https://www.youtube.com/watch?v=dQw4w9WgXcQ
Successfully created YouTube object
An error occurred: HTTP Error 400: Bad Request
Download attempt complete!
