### ISSUE TITLE
[BUG]Not be able to download yt,http 400 error frequently

### ISSUE THREAD

**Issue by Mrgogo777** [pytube/pytube#2013]
C:\Users\Administrator>pytube https://www.youtube.com/watch?v=Bi7B3T8c8hE
Loading video...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Scripts\pytube.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytube\cli.py", line 53, in main
    _perform_args_on_youtube(youtube, args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytube\cli.py", line 60, in _perform_args_on_youtube
    download_highest_resolution_progressive(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytube\cli.py", line 474, in download_highest_resolution_progressive
    stream = youtube.streams.get_highest_resolution()
             ^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
                                                ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytube\__main__.py", line 160, in streaming_data
    self.bypass_age_gate()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytube\__main__.py", line 257, in bypass_age_gate
    innertube_response = innertube.player(self.video_id)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytube\innertube.py", line 448, in player
    return self._call_api(endpoint, query, self.base_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytube\innertube.py", line 390, in _call_api
    response = request._execute_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytube\request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

**Comment by PogoSpin** [comment]
I have this too, even using the prewritten examples from readme.txt:

```
 >>> from pytube import YouTube
 >>> YouTube('https://youtu.be/2lAe1cqCOXo').streams.first().download()
 >>> yt = YouTube('http://youtube.com/watch?v=2lAe1cqCOXo')
 >>> yt.streams
  ... .filter(progressive=True, file_extension='mp4')
  ... .order_by('resolution')
  ... .desc()
  ... .first()
  ... .download()
```
  
Seems like a youtube API change or bad merge that led to issues with request.py. Either way, not being able to use pytube to download anything.

**Comment by nilspolek** [comment]
It seems like YouTube might have updated their servers, and now a lot of those downloaders aren't working. 😕

**Comment by christopherarter** [comment]
> It seems like YouTube might have updated their servers, and now a lot of those downloaders aren't working. 😕

Probably to mitigate the AI scrapers farming it all for training data. Bummer 👎

**Comment by dgslv** [comment]
same here

**Comment by SSujitX** [comment]
same

```
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by sethgw** [comment]
same

**Comment by nilspolek** [comment]
There is a really grate downloader in Go that works from kkdai

**Comment by KamiALK** [comment]
I'm having the same issues.

**Comment by Arbabpouri** [comment]
same

**Comment by WildDIC** [comment]
Try change client to ANDROID_CREATOR near 224 line in file innertube.py

```
"""Object for interacting with the innertube API."""
 # def __init__(self, client='ANDROID_MUSIC', use_oauth=False, allow_cache=True):
def __init__(self, client='ANDROID_CREATOR', use_oauth=False, allow_cache=True):

```

**Comment by KamiALK** [comment]
no work for me

**Comment by dhairyapatel1506** [comment]
Played around with a lot of different links and what I observed is that only a few newer videos are affected by this. Older ones still download without any problem (that is considering you've dealt with the regex issue).

**Comment by zakariaelh** [comment]
Not working for me either

**Comment by DuvyDev** [comment]
same here i've tried everything D:

**Comment by Larmbs** [comment]
yep, has anyone found any alternatives?

**Comment by SSujitX** [comment]
> yep, has anyone found any alternatives?

The [yt_dlp](https://github.com/yt-dlp/yt-dlp) library in Python allows you to download both video and audio. Therefore, I prefer the yt_dlp method.

# video

```
import yt_dlp

while True:
    url = input("Enter the YouTube video URL: ")

    ydl_opts = {
        "format": "bestvideo+bestaudio/best",
        "outtmpl": "%(title)s.%(ext)s",
        "merge_output_format": "mp4",
    }

    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        ydl.download([url])
```


# audio
```

import yt_dlp

while True:
    url = input("Enter the YouTube video URL: ")

    ydl_opts = {
        "format": "mp3/bestaudio/best",
        "outtmpl": "%(title)s.%(ext)s",
        # ℹ️ See help(yt_dlp.postprocessor) for a list of available Postprocessors and their arguments
        "postprocessors": [
            {
                "key": "FFmpegExtractAudio",
                "preferredcodec": "mp3",
            }
        ],
    }

    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        ydl.download([url])
```

**Comment by Arbabpouri** [comment]
> > yep, has anyone found any alternatives?
> 
> The [yt_dlp](https://github.com/yt-dlp/yt-dlp) library in Python allows you to download both video and audio. Therefore, I prefer the yt_dlp method.
> 
> # video
> ```
> import yt_dlp
> 
> while True:
>     url = input("Enter the YouTube video URL: ")
> 
>     ydl_opts = {
>         "format": "bestvideo+bestaudio/best",
>         "outtmpl": "%(title)s.%(ext)s",
>         "merge_output_format": "mp4",
>     }
> 
>     with yt_dlp.YoutubeDL(ydl_opts) as ydl:
>         ydl.download([url])
> ```
> 
> # audio
> ```
> 
> import yt_dlp
> 
> while True:
>     url = input("Enter the YouTube video URL: ")
> 
>     ydl_opts = {
>         "format": "mp3/bestaudio/best",
>         "outtmpl": "%(title)s.%(ext)s",
>         # ℹ️ See help(yt_dlp.postprocessor) for a list of available Postprocessors and their arguments
>         "postprocessors": [
>             {
>                 "key": "FFmpegExtractAudio",
>                 "preferredcodec": "mp3",
>             }
>         ],
>     }
> 
>     with yt_dlp.YoutubeDL(ydl_opts) as ydl:
>         ydl.download([url])
> ```


```

raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] e1nGxkODWAQ: Failed to extract any player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

not work

**Comment by SSujitX** [comment]
> > > yep, has anyone found any alternatives?
> > 
> > 
> > The [yt_dlp](https://github.com/yt-dlp/yt-dlp) library in Python allows you to download both video and audio. Therefore, I prefer the yt_dlp method.
> > # video
> > ```
> > import yt_dlp
> > 
> > while True:
> >     url = input("Enter the YouTube video URL: ")
> > 
> >     ydl_opts = {
> >         "format": "bestvideo+bestaudio/best",
> >         "outtmpl": "%(title)s.%(ext)s",
> >         "merge_output_format": "mp4",
> >     }
> > 
> >     with yt_dlp.YoutubeDL(ydl_opts) as ydl:
> >         ydl.download([url])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > # audio
> > ```
> > 
> > import yt_dlp
> > 
> > while True:
> >     url = input("Enter the YouTube video URL: ")
> > 
> >     ydl_opts = {
> >         "format": "mp3/bestaudio/best",
> >         "outtmpl": "%(title)s.%(ext)s",
> >         # ℹ️ See help(yt_dlp.postprocessor) for a list of available Postprocessors and their arguments
> >         "postprocessors": [
> >             {
> >                 "key": "FFmpegExtractAudio",
> >                 "preferredcodec": "mp3",
> >             }
> >         ],
> >     }
> > 
> >     with yt_dlp.YoutubeDL(ydl_opts) as ydl:
> >         ydl.download([url])
> > ```
> 
> ```
> 
> raise DownloadError(message, exc_info)
> yt_dlp.utils.DownloadError: ERROR: [youtube] e1nGxkODWAQ: Failed to extract any player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
> ```
> 
> not work

what is the error?

**Comment by Arbabpouri** [comment]
> what is the error?


```
raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] e1nGxkODWAQ: Failed to extract any player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by krary** [comment]
yt-dlp is a magnificent tool for downloading videos from YouTube, but the pytube library seemed easier to use, lol.

**Comment by wangqiang9** [comment]
`yt-dlp` can not work now...
very sad!
