### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RishBroProMax** [pytube/pytube#2018]
Pyromod is working! If you like pyromod, please star it at https://github.com/usernein/pyromod

┌ Starting Cyber Youtube Downloader Bot Cloent...
└ Bot Client Started Successfully!
Exception while accessing title of https://youtube.com/watch?v=O0rINyDVZg4. Please file a bug report at https://github.com/pytube/pytube
Traceback (most recent call last):
  File "/root/venv/lib/python3.9/site-packages/pytube/__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/venv/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/venv/lib/python3.9/site-packages/pyrogram/sync.py", line 78, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, main_loop).result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/root/venv/lib/python3.9/site-packages/pyromod/listen/message_handler.py", line 98, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/datasets/_deepnote_work/app.py", line 107, in link
    vid.title,
  File "/root/venv/lib/python3.9/site-packages/pytube/__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while 

This is Erorr FIx That

**Comment by hextor1** [comment]
i am facing this same issue in my website:- 
![error](https://github.com/user-attachments/assets/aab9b91c-897e-42fa-aabe-63e9679314de)
