### ISSUE TITLE
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=ef8qa3CwRqI

### ISSUE THREAD

**Issue by taostein** [pytube/pytube#2039]
https://www.youtube.com/watch?v=ef8qa3CwRqI
Traceback (most recent call last):
  File "/Users/taostein/Scripts/env/lib/python3.12/site-packages/pytube/__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/taostein/Scripts/dl-yt.py", line 44, in <module>
    entry = YouTube(url).title
            ^^^^^^^^^^^^^^^^^^
  File "/Users/taostein/Scripts/env/lib/python3.12/site-packages/pytube/__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=ef8qa3CwRqI. Please file a bug report at https://github.com/pytube/pytube

**Comment by ZFudge** [comment]
Reinstalling 15.0.0 and applying the solution from issue [1954](https://github.com/pytube/pytube/issues/1954#issuecomment-2218287594) fixed it for me.
