### ISSUE TITLE
[BUG] urllib.error.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by Grasiella** [pytube/pytube#2052]
There's a problem in the code, when the download method is called, throws the following error:

```
youtube-video-downloader-1  | Traceback (most recent call last):
youtube-video-downloader-1  |   File "/usr/local/lib/python3.11/dist-packages/pytube/download_helper.py", line 52, in download_video
youtube-video-downloader-1  |     video_stream = yt.streams.get_highest_resolution()
youtube-video-downloader-1  |                    ^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/local/lib/python3.11/dist-packages/pytube/__main__.py", line 312, in streams
youtube-video-downloader-1  |     return StreamQuery(self.fmt_streams)
youtube-video-downloader-1  |                        ^^^^^^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/local/lib/python3.11/dist-packages/pytube/__main__.py", line 179, in fmt_streams
youtube-video-downloader-1  |     stream_manifest = extract.apply_descrambler(self.streaming_data)
youtube-video-downloader-1  |                                                 ^^^^^^^^^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/local/lib/python3.11/dist-packages/pytube/__main__.py", line 163, in streaming_data
youtube-video-downloader-1  |     self.bypass_age_gate()
youtube-video-downloader-1  |   File "/usr/local/lib/python3.11/dist-packages/pytube/__main__.py", line 274, in bypass_age_gate
youtube-video-downloader-1  |     innertube_response = innertube.player(self.video_id)
youtube-video-downloader-1  |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/local/lib/python3.11/dist-packages/pytube/innertube.py", line 403, in player
youtube-video-downloader-1  |     return self._call_api(endpoint, query, self.base_data)
youtube-video-downloader-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/local/lib/python3.11/dist-packages/pytube/innertube.py", line 348, in _call_api
youtube-video-downloader-1  |     response = request._execute_request(
youtube-video-downloader-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/local/lib/python3.11/dist-packages/pytube/request.py", line 37, in _execute_request
youtube-video-downloader-1  |     return urlopen(request, timeout=timeout)  # nosec
youtube-video-downloader-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
youtube-video-downloader-1  |     return opener.open(url, data, timeout)
youtube-video-downloader-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/lib/python3.11/urllib/request.py", line 525, in open
youtube-video-downloader-1  |     response = meth(req, response)
youtube-video-downloader-1  |                ^^^^^^^^^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
youtube-video-downloader-1  |     response = self.parent.error(
youtube-video-downloader-1  |                ^^^^^^^^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/lib/python3.11/urllib/request.py", line 563, in error
youtube-video-downloader-1  |     return self._call_chain(*args)
youtube-video-downloader-1  |            ^^^^^^^^^^^^^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
youtube-video-downloader-1  |     result = func(*args)
youtube-video-downloader-1  |              ^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
youtube-video-downloader-1  |     raise HTTPError(req.full_url, code, msg, hdrs, fp)
youtube-video-downloader-1  | urllib.error.HTTPError: HTTP Error 400: Bad Request
youtube-video-downloader-1  | 
youtube-video-downloader-1  | During handling of the above exception, another exception occurred:
youtube-video-downloader-1  | 
youtube-video-downloader-1  | Traceback (most recent call last):
youtube-video-downloader-1  |   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1463, in wsgi_app
youtube-video-downloader-1  |     response = self.full_dispatch_request()
youtube-video-downloader-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 872, in full_dispatch_request
youtube-video-downloader-1  |     rv = self.handle_user_exception(e)
youtube-video-downloader-1  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/local/lib/python3.11/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
youtube-video-downloader-1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
youtube-video-downloader-1  |                                                 ^^^^^^^^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 870, in full_dispatch_request
youtube-video-downloader-1  |     rv = self.dispatch_request()
youtube-video-downloader-1  |          ^^^^^^^^^^^^^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 855, in dispatch_request
youtube-video-downloader-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
youtube-video-downloader-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
youtube-video-downloader-1  |   File "/app/main.py", line 39, in download_video_youtube
youtube-video-downloader-1  |     retorno = download_video(url=video_link)
youtube-video-downloader-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/local/lib/python3.11/dist-packages/pytube/download_helper.py", line 62, in download_video
youtube-video-downloader-1  |     video_stream.download(output_path="videos", filename=f"{output_video}.mp4")
youtube-video-downloader-1  |   File "/usr/local/lib/python3.11/dist-packages/pytube/streams.py", line 309, in download
youtube-video-downloader-1  |     bytes_remaining = self.filesize
youtube-video-downloader-1  |                       ^^^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/local/lib/python3.11/dist-packages/pytube/streams.py", line 157, in filesize
youtube-video-downloader-1  |     self._filesize = request.filesize(self.url)
youtube-video-downloader-1  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/local/lib/python3.11/dist-packages/pytube/request.py", line 204, in filesize
youtube-video-downloader-1  |     return int(head(url)["content-length"])
youtube-video-downloader-1  |                ^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/local/lib/python3.11/dist-packages/pytube/request.py", line 268, in head
youtube-video-downloader-1  |     response_headers = _execute_request(url, method="HEAD").info()
youtube-video-downloader-1  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/local/lib/python3.11/dist-packages/pytube/request.py", line 37, in _execute_request
youtube-video-downloader-1  |     return urlopen(request, timeout=timeout)  # nosec
youtube-video-downloader-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
youtube-video-downloader-1  |     return opener.open(url, data, timeout)
youtube-video-downloader-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/lib/python3.11/urllib/request.py", line 525, in open
youtube-video-downloader-1  |     response = meth(req, response)
youtube-video-downloader-1  |                ^^^^^^^^^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
youtube-video-downloader-1  |     response = self.parent.error(
youtube-video-downloader-1  |                ^^^^^^^^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/lib/python3.11/urllib/request.py", line 563, in error
youtube-video-downloader-1  |     return self._call_chain(*args)
youtube-video-downloader-1  |            ^^^^^^^^^^^^^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
youtube-video-downloader-1  |     result = func(*args)
youtube-video-downloader-1  |              ^^^^^^^^^^^
youtube-video-downloader-1  |   File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
youtube-video-downloader-1  |     raise HTTPError(req.full_url, code, msg, hdrs, fp)
youtube-video-downloader-1  | urllib.error.HTTPError: HTTP Error 403: Forbidden
youtube-video-downloader-1  | 0 https://www.youtube.com/watch?v=pDNRjL7cY9w
youtube-video-downloader-1  | video_link https://www.youtube.com/watch?v=pDNRjL7cY9w
youtube-video-downloader-1  | 172.25.0.1 - - [15/Oct/2024:14:56:42 -0300] "POST /downloads HTTP/1.1" 500 265 "http://localhost:8002/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
```

**Comment by LeVraiPot2Fleur** [comment]
I have changed the line 223 from innertube.py 
`def __init__(self, client='ANDROID_MUSIC', use_oauth=False, allow_cache=True):`
to 
`def __init__(self, client='ANDROID', use_oauth=False, allow_cache=True):`
And it worked for me. 
Alternatively, I used this above my code instead of editing the file innertube.py :

```
from pytube.innertube import _default_clients

_default_clients["ANDROID"]["context"]["client"]["clientVersion"] = "19.08.35"
_default_clients["IOS"]["context"]["client"]["clientVersion"] = "19.08.35"
_default_clients["ANDROID_EMBED"]["context"]["client"]["clientVersion"] = "19.08.35"
_default_clients["IOS_EMBED"]["context"]["client"]["clientVersion"] = "19.08.35"
_default_clients["IOS_MUSIC"]["context"]["client"]["clientVersion"] = "6.41"
_default_clients["ANDROID_MUSIC"] = _default_clients["ANDROID"]
```
Idk if this will help.

Sources : https://github.com/pytube/pytube/issues/1894 / https://github.com/pytube/pytube/issues/1894#issuecomment-2048612276 / https://github.com/JuanBindez/pytubefix/commit/c0c07b046d8b59574552404931f6ce3c6590137d

**Comment by n0xiv4** [comment]
This fix seems to work for fixing the `HTTP Error 400: Bad Request` error too.

**Comment by Grasiella** [comment]
Unfortunately it didn't work for me :(
Thanks for the help.

**Comment by surak** [comment]
@LeVraiPot2Fleur 
This creates a second error:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/surak/Desktop/lixo/.venv/lib/python3.12/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "/Users/surak/Desktop/lixo/.venv/lib/python3.12/site-packages/pytube/__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/Users/surak/Desktop/lixo/.venv/lib/python3.12/site-packages/pytube/extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
             ^^^^^^^^^^^^^
  File "/Users/surak/Desktop/lixo/.venv/lib/python3.12/site-packages/pytube/cipher.py", line 29, in __init__
    self.transform_plan: List[str] = get_transform_plan(js)
                                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/surak/Desktop/lixo/.venv/lib/python3.12/site-packages/pytube/cipher.py", line 197, in get_transform_plan
    return regex_search(pattern, js, group=1).split(";")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/surak/Desktop/lixo/.venv/lib/python3.12/site-packages/pytube/helpers.py", line 129, in regex_search
    raise RegexMatchError(caller="regex_search", pattern=pattern)
pytube.exceptions.RegexMatchError: regex_search: could not find match for decodeURIComponent=function\(\w\){[a-z=\.\(\"\)]*;(.*);(?:.+)}
```

**Comment by surak** [comment]
And the single-line fix in innertube.py brings a 400 bad request indeed.

**Comment by LeVraiPot2Fleur** [comment]
Hi @surak !
Yes seems like Youtube changed something on their side and maybe the regex doesn't match anymore. 
The code I linked before seems useless now and there is no update from Pytube... 

Currently I'm using [pytubefix](https://github.com/JuanBindez/pytubefix) while waiting for updates...
Hope this will help.

Sources : https://github.com/pytube/pytube/issues/2098

**Comment by surak** [comment]
Me too! :-) but thanks

**Comment by zhenhuahu** [comment]
> Hi [@surak](https://github.com/surak) ! Yes seems like Youtube changed something on their side and maybe the regex doesn't match anymore. The code I linked before seems useless now and there is no update from Pytube...
> 
> Currently I'm using [pytubefix](https://github.com/JuanBindez/pytubefix) while waiting for updates... Hope this will help.
> 
> Sources : [#2098](https://github.com/pytube/pytube/issues/2098)

Thank you so much! This works!
