### ISSUE TITLE
[BUG] Error while accesing title

### ISSUE THREAD

**Issue by MDJoerg** [pytube/pytube#2058]
**Before creating an issue**

**Describe the bug**
The title of the video could not be extracted. An exception occured.

**To Reproduce**
Please provide the following information:
- The video or playlist url that is causing the error.
https://www.youtube.com/watch?v=0FH10da5Ti8 or https://www.youtube.com/watch?v=FxlHVQa5l5Q

- The code where the problem is occurring.
playlist_url = "https://www.youtube.com/playlist?list=PL6RpkC85SLQDHz97qsNTNAE2jnUKj8X5d"

yt_play = Playlist(playlist_url)

for i in yt_play.videos:
  try:
    print(i.watch_url, i.title)
  except Exception as exc:
    print(f"Exception {i.watch_url} - {exc}")  
**Expected behavior**

**Output**
If pytube raises an exception, please provide the full traceback for the exception.

Exception https://youtube.com/watch?v=t61UhKaZkHw - t61UhKaZkHw is streaming live and cannot be loaded
Exception https://youtube.com/watch?v=0FH10da5Ti8 - Exception while accessing title of https://youtube.com/watch?v=0FH10da5Ti8. Please file a bug report at https://github.com/pytube/pytube

**System information**
Please provide the following information:
- Python version (run `python --version`)
- Pytube version (run `print(pytube.__version__)` in python)
- Command used to install pytube
using pytube-15.0.0 and python 3.10.11 with win11

Best regards and thanks for support!
Joerg

**Comment by urbanscribe** [comment]
same here since this morning

3.11
latest release of pytube


`Traceback (most recent call last): File "/usr/src/app/app/tools/web/web_hoovers.py", line 145, in fetch_and_create_document_async title, transcript_text = await self.fetch_title_and_transcript(youtube_url) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped return await fn(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/tenacity/_asyncio.py", line 47, in call do = self.iter(retry_state=retry_state) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/tenacity/init.py", line 325, in iter raise retry_exc.reraise() ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/tenacity/init.py", line 158, in reraise raise self.last_attempt.result() ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result return self.__get_result() ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result raise self._exception File "/usr/local/lib/python3.11/site-packages/tenacity/_asyncio.py", line 50, in call result = await fn(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/app/app/tools/web/web_hoovers.py", line 95, in fetch_title_and_transcript title = yt.title ^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pytube/main.py", line 346, in title raise exceptions.PytubeError( pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=n4K3yyHJ-QM. Please file a bug report at https://github.com/pytube/pytube`

**Comment by konbraphat51** [comment]
same with me

python=3.9.20
pytube=15.0.0

```
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\Hiyoko\.conda\envs\katodb\lib\site-packages\pytube\__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hiyoko\.conda\envs\katodb\lib\site-packages\joblib\externals\loky\process_executor.py", line 463, in _process_worker        
    r = call_item()
  File "C:\Users\Hiyoko\.conda\envs\katodb\lib\site-packages\joblib\externals\loky\process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)  
  File "C:\Users\Hiyoko\.conda\envs\katodb\lib\site-packages\joblib\parallel.py", line 598, in __call__
    return [func(*args, **kwargs)
  File "C:\Users\Hiyoko\.conda\envs\katodb\lib\site-packages\joblib\parallel.py", line 598, in <listcomp>
    return [func(*args, **kwargs)
  File "c:\Storage\python3_project\kato_db\katodb\Scraping\VideoLinkScraper.py", line 74, in get_videos_from_link_youtube
    date = self.get_date(video.title, video.description, video.publish_date)
  File "C:\Users\Hiyoko\.conda\envs\katodb\lib\site-packages\pytube\__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=iI8Ca4rxhB4. Please file a bug report at https://github.com/pytube/pytube
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Storage\python3_project\kato_db\katodb\Scraping\main.py", line 40, in <module>     
    Scraper.run(has_gpu = True)
  File "c:\Storage\python3_project\kato_db\katodb\Scraping\main.py", line 19, in run
    VideoLinkScraper().run()
  File "c:\Storage\python3_project\kato_db\katodb\Scraping\VideoLinkScraper.py", line 22, in run
    df_video_links = self.get_videos_from_links(df_list_links, df_video_links)
  File "c:\Storage\python3_project\kato_db\katodb\Scraping\VideoLinkScraper.py", line 43, in get_videos_from_links
    output = Parallel(n_jobs=-1, verbose=10)([delayed(self.get_videos_from_link_youtube)(row, current_links) for _, row in df_list_links[df_list_links["link"].str.contains("youtube")].iterrows()])
  File "C:\Users\Hiyoko\.conda\envs\katodb\lib\site-packages\joblib\parallel.py", line 2007, in __call__
    return output if self.return_generator else list(output)
  File "C:\Users\Hiyoko\.conda\envs\katodb\lib\site-packages\joblib\parallel.py", line 1650, in _get_outputs
    yield from self._retrieve()
  File "C:\Users\Hiyoko\.conda\envs\katodb\lib\site-packages\joblib\parallel.py", line 1754, in _retrieve
    self._raise_error_fast()
  File "C:\Users\Hiyoko\.conda\envs\katodb\lib\site-packages\joblib\parallel.py", line 1789, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "C:\Users\Hiyoko\.conda\envs\katodb\lib\site-packages\joblib\parallel.py", line 745, in get_result
    return self._return_or_raise()
  File "C:\Users\Hiyoko\.conda\envs\katodb\lib\site-packages\joblib\parallel.py", line 763, in _return_or_raise
    raise self._result
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=iI8Ca4rxhB4. Please file a bug report at https://github.com/pytube/pytube
```

**Comment by touremahi** [comment]
Try using oauth it should solve the problem, as it requires to login in your youtube account though as in Youtube TV version!! this worked for me so far see: https://pytube.io/en/latest/user/quickstart.html#downloading-a-video

**Comment by konbraphat51** [comment]
in my case, simply changing to [pytubefix](https://github.com/JuanBindez/pytubefix) worked.
