### ISSUE TITLE
For all facing issues with Pytube

### ISSUE THREAD

**Issue by ajithbharadwaj1** [pytube/pytube#2059]
Hello everyone , 
Many have started posting issues and many are yet to be resolved by the Dev team , in the mean time I have found an alternative to it in the mean time the dev team is fixing it.

Please install this https://pypi.org/project/pytubefix/

**Comment by linqiu0-0** [comment]
Hi, thanks for sharing this. But when i tried the script on the intro page, I get this error 
```
Traceback (most recent call last):
  File "/home/ubuntu/lin/global-ml/GenConViT/venv/lib/python3.9/site-packages/pytubefix/__main__.py", line 683, in title
    self._title = self.vid_info['videoDetails']['title']
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/lin/global-ml/GenConViT/finetuning/scripts/youtube_video_downloader.py", line 107, in <module>
    print(yt.title)
  File "/home/ubuntu/lin/global-ml/GenConViT/venv/lib/python3.9/site-packages/pytubefix/__main__.py", line 687, in title
    self.check_availability()
  File "/home/ubuntu/lin/global-ml/GenConViT/venv/lib/python3.9/site-packages/pytubefix/__main__.py", line 349, in check_availability
    raise exceptions.BotDetection(video_id=self.video_id)
pytubefix.exceptions.BotDetection: HnRbbSS9Rcg This request was detected as a bot. Use `use_po_token=True` to view. See more details at https://github.com/JuanBindez/pytubefix/pull/209
```
Here is my code 
```
from pytubefix import YouTube
from pytubefix.cli import on_progress
 
url = "https://www.youtube.com/watch?v=HnRbbSS9Rcg"
 
yt = YouTube(url, on_progress_callback = on_progress)
print(yt.title)
 
ys = yt.streams.get_highest_resolution()
ys.download()
```
Do you know how to fix this error?

**Comment by bryanlan** [comment]
Can confirm this seems to have fixed my problems with exceptions while accessing title/metadata that were getting so bad/frequent that pytube was becoming unusable.  THANK YOU!

**Comment by shaikhzaid** [comment]
Any guidance in getting video transcript using this library?

**Comment by ajithbharadwaj1** [comment]
> Any guidance in getting video transcript using this library?

Hi @shaikhzaid  , you cannot use pytube/pytubefix , rather you can use https://pypi.org/project/youtube-transcript-api/

However , let's say for the video ID you have passed let's say transcription is not available , then you can use the pytube/pytubefix in order to download the audio and use openai whisper in order to transcribe it https://pypi.org/project/openai-whisper/
