### ISSUE TITLE
[BUG] urllib.error.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by VitoR-InA** [pytube/pytube#2086]
**Describe the bug**
Just trying to download random video from docs and this exception throws

**To Reproduce**
The code where the problem is occurring. `YouTube("http://www.youtube.com/watch?v=yj-04qAGq2A").streams.first().download()`

**Output**
```
Traceback (most recent call last):
  File "c:\Users\mihai\.vscode\projects\python\MusicPY\test2.py", line 7, in <module>
    YouTube("http://www.youtube.com/watch?v=yj-04qAGq2A").streams.first().download()
  File "C:\Users\mihai\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\mihai\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "C:\Users\mihai\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 160, in streaming_data
    self.bypass_age_gate()
  File "C:\Users\mihai\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 257, in bypass_age_gate
    innertube_response = innertube.player(self.video_id)
  File "C:\Users\mihai\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\innertube.py", line 448, in player
    return self._call_api(endpoint, query, self.base_data)
  File "C:\Users\mihai\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\innertube.py", line 390, in _call_api
    response = request._execute_request(
  File "C:\Users\mihai\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "C:\Users\mihai\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\mihai\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\mihai\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\mihai\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\mihai\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\mihai\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**System information**
- Python version `Python 3.10.11`
- Pytube version `15.0.0`
- Command used to install pytube `python -m pip install git+https://github.com/pytube/pytube`

**Comment by gwashark** [comment]
![image](https://github.com/user-attachments/assets/694b5d8f-1536-4961-8532-116b1ec5ca5f)

I confirm as I recieved the same error as well.

**Comment by sjiwul** [comment]
I'm also getting the same error(urllib.error.HTTPError: HTTP Error 403: Forbidden) when trying to download a random video.

**Comment by mrkarannn03** [comment]
same bro

**Comment by hiephd1** [comment]
This error occurs when downloading a stream with the property `progressive=False`.
You can download using `get_highest_resolution` or `get_lowest_resolution` (filtered with `progressive=True`).
However, I noticed that `fmt_streams` only returns a single stream with `progressive=True` (unfortunately, it's limited to 360p resolution).
I am looking forward to a fix for this issue so that higher-quality videos can be downloaded.

**Comment by WebDevelopmentBD** [comment]
Tried with possible parameter changed and a bounce of links together.
I think its YouTube's latest **cipher issue** while decrypt/decoding the URL signature from "ytInitialPlayerResponse".

Not only PyTube also other solutions like VLC are getting same error.
All sort of scripting is not working right now!

**Comment by trws2** [comment]
The 'urllib.error.HTTPError: HTTP Error 403: Forbidden' error still persists. Tried a bunch of parameter combination with `get_highest_resolution`, `get_lowest_resolution`, `progressive=False`, and `progressive=True`, none of them works.

**Comment by 4ayyar** [comment]
Facing same issue,
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by shekharchander** [comment]
Hi all, I maintain a similar package like pytube and I confirm it has something to do with Youtube's way of sending video request. I don't think there is any solution as of now.

**Comment by pavlinbl4** [comment]
same : urllib.error.HTTPError: HTTP Error 403: Forbidden. 
Python 3.11 macOS v 15.5  Apple M1

**Comment by Mo-to** [comment]
From my quick review of the code and some debugging, the error is caused by a request made by the [InnertubeAPI](https://github.com/tombulled/innertube). The issue arises because users now need to be logged in to make these requests. The InnertubeAPI currently does not implement such a functionality.

<details>
  <summary>Detailed explanation</summary>

  The following request is made to the endpoint:
```bash
curl -X POST "https://www.youtube.com/youtubei/v1/player?videoId=De1pYhxhfPA&key=REDACTED_API_KEY&contentCheckOk=True&racyCheckOk=True" \
-H "Content-Type: application/json" \
-H "User-Agent: com.google.android.apps.youtube.music/" \
-d '{"context": {"client": {"androidSdkVersion": 30, "clientName": "ANDROID_MUSIC", "clientVersion": "5.16.51"}}}'
```

The answer is the following JSON (Sanitized):

```json
{
    "responseContext": {
        "visitorData": "REDACTED",
        "serviceTrackingParams": [
            {
                "service": "GFEEDBACK",
                "params": [
                    { "key": "is_alc_surface", "value": "false" },
                    { "key": "ipcc", "value": "0" },
                    { "key": "is_viewed_live", "value": "False" },
                    { "key": "logged_in", "value": "0" },
                    { "key": "e", "value": "REDACTED" },
                    { "key": "visitor_data", "value": "REDACTED" }
                ]
            },
            {
                "service": "CSI",
                "params": [
                    { "key": "c", "value": "ANDROID_MUSIC" },
                    { "key": "cver", "value": "5.16.51" },
                    { "key": "yt_li", "value": "0" },
                    { "key": "GetPlayer_rid", "value": "REDACTED" }
                ]
            },
            {
                "service": "ECATCHER",
                "params": [
                    { "key": "client.version", "value": "5.16" },
                    { "key": "client.name", "value": "ANDROID_MUSIC" }
                ]
            },
            {
                "service": "LISTNR",
                "params": [
                    { "key": "e", "value": "REDACTED" }
                ]
            }
        ],
        "maxAgeSeconds": 0
    },
    "playabilityStatus": {
        "status": "LOGIN_REQUIRED",
        "reason": "Please sign in",
        "skip": {
            "playabilityErrorSkipConfig": {
                "skipOnPlayabilityError": false
            }
        },
        "contextParams": "REDACTED"
    },
    "trackingParams": "REDACTED",
    "adBreakHeartbeatParams": "REDACTED"
}
```

As you can see in `playabilityStatus`, the status returned is `LOGIN_REQUIRED`

</details>

**Comment by gwashark** [comment]
I knew that Google would do that. 403 is also the HTTP for Unauthorized meaning login. Thanks for the sum @Mo-to

**Comment by Mo-to** [comment]
I just took a look at the `Innertube API` to see if I could at least create a working prototype with OAuth, but let's just say the results are **not promising**.

From what I observed, it seems they are already working on OAuth integration. However, I think it will be quite difficult to get it running because they appear to rely on repurposing other OAuth applications, like the **YouTube on TV** application. Unfortunately, it looks like they have deactivated the **YouTube Data API** for those applications.

From my perspective, the only viable alternatives are:
1. **Using browser cookies** to authenticate requests.
2. **Hosting your own application** in Google Cloud specifically for this API to function and for users to authenticate. 😞

EDIT:
Further midnight testing showed that the results shown above are produced by `InnerTube(client="ANDROID_MUSIC")` but not by `InnerTube(client="WEB")`. As far as i understood, pytube is using `ANDROID_MUSIC` and `ANDROID_EMBED_PLAYER` for the download.
If i find more time for this i will write another more structured message, maybe that helps someone else figuring out what going on.

**Comment by Mo-to** [comment]
Okay, here is a more structured report after a further investigation:

## Description of the error:
HTTP Error 403: Forbidden

## State of investigation:
The error is caused by the lines:
https://github.com/pytube/pytube/blob/a32fff39058a6f7e5e59ecd06a7467b71197ce35/pytube/__main__.py#L155-L161

`self..bypass_age_gate()` is executed, because `streamingData` is not defined in `self.vid_info` because its age restricted.

## Solution (or more like the start of one)
Changing the default client from `ANDROID_MUSIC` to `WEB` in the following lines:
https://github.com/pytube/pytube/blob/a32fff39058a6f7e5e59ecd06a7467b71197ce35/pytube/innertube.py#L221-L223

This change leads to a change in the response. The `playability_status` is now `OK` and the `streamingData` is defined. This makes sense, because opening such age restricted videos in the incognito-browser works just fine without authentication.

## Drawbacks:
Sadly, this "solution" leads to an error in the cipher function:
```
Traceback (most recent call last):
  File "C:\Users\krims\Prog\Python\pytube\bugfix_test.py", line 17, in <module>
    yt.streams.filter(progressive=True, file_extension='mp4').order_by('resolution').desc().first().download()
  File "C:\Users\krims\Prog\Python\pytube\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\krims\Prog\Python\pytube\pytube\__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\krims\Prog\Python\pytube\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\krims\Prog\Python\pytube\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\krims\Prog\Python\pytube\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\krims\Prog\Python\pytube\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\Users\krims\Prog\Python\pytube\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
- pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple
```

Is there a specific need for the `ANDROID_MUSIC` or `ANDROID_EMBEDDED_PLAYER` client apart from the age restriction. I don't have time to further investigate the cipher function. I hope this report at least help you to save some time debugging.

**Comment by theKeval** [comment]
> Okay, here is a more structured report after a further investigation:
> 
> ## Description of the error:
> HTTP Error 403: Forbidden
> 
> ## State of investigation:
> The error is caused by the lines:
> 
> https://github.com/pytube/pytube/blob/a32fff39058a6f7e5e59ecd06a7467b71197ce35/pytube/__main__.py#L155-L161
> 
> `self..bypass_age_gate()` is executed, because `streamingData` is not defined in `self.vid_info` because its age restricted.
> 
> ## Solution (or more like the start of one)
> Changing the default client from `ANDROID_MUSIC` to `WEB` in the following lines:
> 
> https://github.com/pytube/pytube/blob/a32fff39058a6f7e5e59ecd06a7467b71197ce35/pytube/innertube.py#L221-L223
> 
> This change leads to a change in the response. The `playability_status` is now `OK` and the `streamingData` is defined. This makes sense, because opening such age restricted videos in the incognito-browser works just fine without authentication.
> 
> ## Drawbacks:
> Sadly, this "solution" leads to an error in the cipher function:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\krims\Prog\Python\pytube\bugfix_test.py", line 17, in <module>
>     yt.streams.filter(progressive=True, file_extension='mp4').order_by('resolution').desc().first().download()
>   File "C:\Users\krims\Prog\Python\pytube\pytube\__main__.py", line 296, in streams
>     return StreamQuery(self.fmt_streams)
>   File "C:\Users\krims\Prog\Python\pytube\pytube\__main__.py", line 188, in fmt_streams
>     extract.apply_signature(stream_manifest, self.vid_info, self.js)
>   File "C:\Users\krims\Prog\Python\pytube\pytube\extract.py", line 409, in apply_signature
>     cipher = Cipher(js=js)
>   File "C:\Users\krims\Prog\Python\pytube\pytube\cipher.py", line 43, in __init__
>     self.throttling_plan = get_throttling_plan(js)
>   File "C:\Users\krims\Prog\Python\pytube\pytube\cipher.py", line 405, in get_throttling_plan
>     raw_code = get_throttling_function_code(js)
>   File "C:\Users\krims\Prog\Python\pytube\pytube\cipher.py", line 311, in get_throttling_function_code
>     name = re.escape(get_throttling_function_name(js))
>   File "C:\Users\krims\Prog\Python\pytube\pytube\cipher.py", line 296, in get_throttling_function_name
>     raise RegexMatchError(
> - pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple
> ```
> 
> Is there a specific need for the `ANDROID_MUSIC` or `ANDROID_EMBEDDED_PLAYER` client apart from the age restriction. I don't have time to further investigate the cipher function. I hope this report at least help you to save some time debugging.

This is exactly my current state of investigation as well! And as of now, after 3 to 4 hours of research and a little knowledge of regex, I am not able to find it's solution.

**Comment by opsboltz** [comment]
Yea I hate to join in but I got the same

Error: HTTP Error 403: Forbidden
"import tkinter
import customtkinter
from pytube import YouTube
from pytube.exceptions import PytubeError
import requests


def startdownload():
    try:
        ytLink = link.get()  # Get the URL entered by the user

        # Create a custom headers to avoid 403 forbidden error
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }

        # Fetch the YouTube page content using requests with custom headers
        response = requests.get(ytLink, headers=headers)

        if response.status_code == 200:
            # If the request is successful, proceed to download the video
            ytObject = YouTube(ytLink)  # Pass the URL directly to pytube
            video = ytObject.streams.get_highest_resolution()  # Get the highest resolution stream
            video.download()  # Download the video to the current working directory
            print("Download Complete!")  # Print success message to console
        else:
            print(f"Error: Unable to fetch the video. Status Code: {response.status_code}")
    except PytubeError:
        print("Invalid YouTube Link")  # Print error message to console
    except Exception as e:
        print(f"Error: {str(e)}")  # Print other unexpected errors


# Setting up window
customtkinter.set_appearance_mode("System")
customtkinter.set_default_color_theme("blue")

root = customtkinter.CTk()
root.geometry("720x480")

# Title label
title = customtkinter.CTkLabel(root, text="Insert a YouTube Link", font=("Arial", 26, "bold"))
title.pack(padx=10, pady=10)

# Link Input
link = customtkinter.CTkEntry(root, width=350, height=40)
link.pack(padx=10, pady=10)

# Download Button
download = customtkinter.CTkButton(root, text="Download", command=startdownload)
download.pack(pady=10)

root.mainloop()
"

**Comment by EonCuber28** [comment]
This only happens to me when downloading YouTube shorts. The main issue is when I try to get the streams from one. 
Example code with this error: 
`print(Youtube("YouTube shorts URL").streams)`
Error:
`File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden`

Python version: 3.11.2
Pytube version: 15.0.0

**Comment by HDemn** [comment]
I have the issue on any video.
I run 
Python version: 3.11.5
Pytube version: 15.0.0
Jupyter Notebook in a Conda Environment on a Mac, 

 try:
      yt = YouTube(url)
       print(f'Video {url} is available')
    
 shows that the video is available 
 
yt.streams.first().download()
 Returns HTTPError: HTTP Error 403: Forbidden
 Highlighting  -> 257 innertube_response = innertube.player(self.video_id) as described above
