### ISSUE TITLE
[BUG]regex_search: could not find match for decodeURIComponent=function\(\w\){[a-z=\.\(\"\)]*;(.*);(?:.+)}

### ISSUE THREAD

**Issue by YIJUNG212** [pytube/pytube#2098]
**Describe the bug**
After I exec pytube to download mp3 from youtube ,the error came out like under
pytube.exceptions.RegexMatchError: regex_search: could not find match for decodeURIComponent=function\(\w\){[a-z=\.\(\"\)]*;(.*);(?:.+)}

**Output**
Traceback (most recent call last):
  File "/home/seric/venv/bin/pytube", line 8, in <module>
    sys.exit(main())
  File "/home/seric/venv/lib/python3.9/site-packages/pytube/cli.py", line 53, in main
    _perform_args_on_youtube(youtube, args)
  File "/home/seric/venv/lib/python3.9/site-packages/pytube/cli.py", line 60, in _perform_args_on_youtube
    download_highest_resolution_progressive(
  File "/home/seric/venv/lib/python3.9/site-packages/pytube/cli.py", line 474, in download_highest_resolution_progressive
    stream = youtube.streams.get_highest_resolution()
  File "/home/seric/venv/lib/python3.9/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "/home/seric/venv/lib/python3.9/site-packages/pytube/__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/home/seric/venv/lib/python3.9/site-packages/pytube/extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "/home/seric/venv/lib/python3.9/site-packages/pytube/cipher.py", line 29, in __init__
    self.transform_plan: List[str] = get_transform_plan(js)
  File "/home/seric/venv/lib/python3.9/site-packages/pytube/cipher.py", line 197, in get_transform_plan
    return regex_search(pattern, js, group=1).split(";")
  File "/home/seric/venv/lib/python3.9/site-packages/pytube/helpers.py", line 129, in regex_search
    raise RegexMatchError(caller="regex_search", pattern=pattern)
pytube.exceptions.RegexMatchError: regex_search: could not find match for decodeURIComponent=function\(\w\){[a-z=\.\(\"\)]*;(.*);(?:.+)}

**System information**
Please provide the following information:
- Python version (run `python --version`)        Python 3.9.2
- Pytube version (run `print(pytube.__version__)` in python)        pytube2                15.0.11
- Command used to install pytube        pip install pytube2

**Comment by emirgra** [comment]
Is there anyone who can solve this problem?

**Comment by ashishpatel16** [comment]
I used [pytubefix](https://github.com/JuanBindez/pytubefix) instead to get my scripts running again. I hope pytube also fixes it soon!

**Comment by veem461** [comment]
Good afternoon, yes, I have encountered the same issue for several days. As "emirga" mentions, is there anyone working on a solution? The propeller heads out there are normally really on the ball and come up with a solution f-a-s-t! It seems unusually quiet at the moment (demob happy? Pre-Christmas dust-ups?) 

I tried the solution offered by ashishpatel16 but received a different error :-(

Using the code offered on pytube fix i.e.

----------------------------------------------------------------------------
from pytubefix import YouTube
from pytubefix.cli import on_progress

url = "https://www.youtube.com/watch?v=xECHs2EmYIM"

yt = YouTube(url, on_progress_callback=on_progress)
print(yt.title)

ys = yt.streams.get_highest_resolution()
ys.download()

---------------------------------------------------------------------------

I was greeted with the following: Deeeeep joy, happy days. So....... here's hoping the brains of the outfit can figure out a fix to the regex_search issue. ....... fingers crossed. Cheers!

PART 2 - Crying Bride-To-Be Thinks Her Tears Will Get Her A Pass For Sleeping With Ex At Party...
The ANDROID_TESTSUITE client did not get a valid response, trying to use the WEB client.
Video ID: xECHs2EmYIM
Please open an issue at https://github.com/JuanBindez/pytubefix/issues and provide this log output.
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\pytubefix\__main__.py", line 231, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Python311\Lib\site-packages\pytubefix\extract.py", line 415, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Python311\Lib\site-packages\pytubefix\cipher.py", line 25, in __init__
    self.throttling_function_name = get_throttling_function_name(js)
  File "C:\Python311\Lib\site-packages\pytubefix\cipher.py", line 137, in get_throttling_function_name
    raise RegexMatchError(
pytubefix.exceptions.RegexMatchError: [91mget_throttling_function_name: could not find match for multiple[0m

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\2BSorted\Already Sorted\Python\YouTubeApp\zzz.py", line 9, in <module>
    ys = yt.streams.get_highest_resolution()
  File "C:\Python311\Lib\site-packages\pytubefix\__main__.py", line 502, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Python311\Lib\site-packages\pytubefix\__main__.py", line 238, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Python311\Lib\site-packages\pytubefix\extract.py", line 415, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Python311\Lib\site-packages\pytubefix\cipher.py", line 25, in __init__
    self.throttling_function_name = get_throttling_function_name(js)
  File "C:\Python311\Lib\site-packages\pytubefix\cipher.py", line 137, in get_throttling_function_name
    raise RegexMatchError(
pytubefix.exceptions.RegexMatchError: [91mget_throttling_function_name: could not find match for multiple[0m

**Comment by atomicstructure** [comment]
Is there still not a single fix for this?

**Comment by veem461** [comment]
In response to..... "Is there still not a single fix for this?"

The brains of the outfit must be well hungover from their latest Christmas shin dig :-(

Normally these folks steam in with fixes. Que pasa compadres?

**Comment by Rvjonh** [comment]
nothing fixed yet? i have the same problem...

![Image](https://github.com/user-attachments/assets/7741bc3c-8ca4-4eda-af18-e48e44b66040)
