### ISSUE TITLE
[BUG] Unable to print `Video Title`

### ISSUE THREAD

**Issue by Di3Z1E** [pytube/pytube#2102]
### Description
When attempting to retrieve the title of a YouTube video using pytube, a `PytubeError` is raised, preventing access to the video title.

### Environment
- **Python Version:** 3.13.0
- **Pytube Version:** 15.0.0
- **Installation Method:** pip

### Reproduction Steps
1. Use the following code to attempt retrieving a video title:
   ```python
   from pytube import YouTube

   def download_video(yt_url: str) -> None:
       yt = YouTube(yt_url)
       print(yt.title)

   if __name__ == "__main__":
       url: str = "http://youtube.com/watch?v=2lAe1cqCOXo"
       download_video(yt_url=url)
   ```

2. Attempt to print the video title

### Expected Behavior
Successfully print the video title: "YouTube Rewind 2019: For the Record | #YouTubeRewind"

### Actual Behavior
Raises a `PytubeError` with a `KeyError: 'videoDetails'`

### Full Error Traceback
```
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    download_video(yt_url=url)
  File "main.py", line 5, in download_video
    print(yt.title)
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=2lAe1cqCOXo
```

### Possible Causes
- Recent changes in YouTube's API
- Incompatibility between pytube version and current YouTube video metadata structure

### Additional Notes
- The error occurs with any video URL
- Pytube's official bug reporting link was included in the original error message

### Suggested Next Steps
- Verify the video URL is still valid
- Check for any recent pytube updates
- Investigate potential changes in YouTube's video metadata retrieval method

### Reproducibility
☑ Always
☐ Sometimes
☐ Specific to this video

**Comment by saajann** [comment]
It's because of the incompatibility between pytube version and current YouTube video metadata structure

**Comment by Di3Z1E** [comment]
> It's because of the incompatibility between pytube version and current YouTube video metadata structure

I see,

There is a working branch/fork that is currently able to work properly?

**Comment by saajann** [comment]
I don't think there are any. You can use another open-source library, it's called yt-dlp. 
Here's the link to its Github repository: [yt-dlp](https://github.com/yt-dlp/yt-dlp.git)

**Comment by PushUpVijay** [comment]
I'm also getting error. 

KeyError                                  Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/pytube/__main__.py](https://localhost:8080/#) in title(self)
    340         try:
--> 341             self._title = self.vid_info['videoDetails']['title']
    342         except KeyError:

KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

PytubeError                               Traceback (most recent call last)

**Comment by soumya-shome** [comment]
> > It's because of the incompatibility between pytube version and current YouTube video metadata structure
> 
> I see,
> 
> There is a working branch/fork that is currently able to work properly?

There is a library pytubefix , this works

**Comment by Di3Z1E** [comment]
> > > It's because of the incompatibility between pytube version and current YouTube video metadata structure
> > 
> > I see,
> > 
> > There is a working branch/fork that is currently able to work properly?
> 
> There is a library pytubefix , this works

Alright I'll check it out.

Ty

**Comment by theandreibogdan** [comment]
Try `pytube-fix` or `yt_dlp`
