### ISSUE TITLE
[BUG] I can't get the title of a video.

### ISSUE THREAD

**Issue by pablomylovee** [pytube/pytube#2106]
**Before creating an issue**

Please confirm that you are on the latest version of pytube by installing from the source.
You can do this by running `python -m pip install git+https://github.com/pytube/pytube`.
Sometimes, the pypi library repository is not up to date, and your issue may have been fixed already!

**Describe the bug**
I was making some code to download an album from YouTube, but in that playlist there's a song that I don't want, so I made it so that if the same title comes, it will ignore it. But it came up with an error.

**To Reproduce**
Please provide the following information:
- The video or playlist url that is causing the error.
                `https://youtube.com/playlist?list=PLxA687tYuMWhCPUY91XZo1tCPYP3359VP&si=bHCXjwQYj5nD64u0`
- The code where the problem is occurring.
                `if videos.title == "1 Hour Clean Pop Songs Playlist 🎧 Clean Pop Playlist 2024 🎶 Clean Pop Music Mix 🎵 Clean Pop Mix": continue`
**Expected behavior**
                This code was in a for loop, I wanted the for loop to ignore the video if its title was the same title in the if statement.

**Output**
Traceback (most recent call last):
  File "C:\Users\IRQ LAP 016\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pytube\__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\IRQ LAP 016\Desktop\brat\main.py", line 7, in <module>
    if videos.title == "1 Hour Clean Pop Songs Playlist 🎧 Clean Pop Playlist 2024 🎶 Clean Pop Music Mix 🎵 Clean Pop Mix": continue
       ^^^^^^^^^^^^
  File "C:\Users\IRQ LAP 016\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pytube\__main__.py", line 346, in title
    raise exceptions.PytubeError(
    ...<4 lines>...
    )
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=nI6GP8wKJ6o. Please file a bug report at https://github.com/pytube/pytube

**System information**
Please provide the following information:
- Python version: Python 3.13.1
- Pytube version: 15.0.0
- Command used to install pytube: python -m pip install git+https://github.com/pytube/pytube

**Comment by theandreibogdan** [comment]
YouTube changed their UI and `pytube` is not working properly anymore

Try `pytube-fix` or `yt_dlp`

**Comment by rynoian** [comment]
> YouTube changed their UI and `pytube` is not working properly anymore
> 
> Try `pytube-fix` or `yt_dlp`

Is pytube stopped being maintained? Or just haven't pushed the fix yet?
