### ISSUE TITLE
[BUG] Forbidden Request

### ISSUE THREAD

**Issue by azzammuhyala** [pytube/pytube#2108]
```py
from pytube import YouTube

# example
YouTube('https://youtu.be/2lAe1cqCOXo').streams.first().download()
```

Result:
```log
Traceback (most recent call last):
  File "d:\Python\test.py", line 3, in <module>
    YouTube('https://youtu.be/2lAe1cqCOXo').streams.first().download()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ...
  File "C:\Users\USER-PC\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by Moskize91** [comment]
It looks like this repo is in an abandoned state and is currently unavailable.

**Comment by Pulkitabhiwan** [comment]
it Look like youtube Block both the libraray pyTube and yt_dlp 

yt_dlp is running on my local but when i deoply it to server i am getting the error

**Comment by aaocansey582** [comment]
Is there any fix for this ?

**Comment by Pulkitabhiwan** [comment]
You can use Yt_dlp on your local machine it work's fine

**Comment by RuhlMirko** [comment]
Thank you, I thought the code was changed but the amount of issues told me that this repo was abandoned
