### ISSUE TITLE
Unavailable videos throw RegexMatchError

### ISSUE THREAD

**Issue by billd100** [pytube/pytube#250]
When a video or live stream recording is unavailable, a RegexMatchError is thrown.

For instance, https://www.youtube.com/watch?v=IW1mdGDSGYQ throws:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/spiders/lib/python3.6/site-packages/pytube/__main__.py", line 84, in __init__
    self.prefetch_init()
  File "/spiders/lib/python3.6/site-packages/pytube/__main__.py", line 92, in prefetch_init
    self.prefetch()
  File "/spiders/lib/python3.6/site-packages/pytube/__main__.py", line 163, in prefetch
    age_restricted=self.age_restricted,
  File "/spiders/lib/python3.6/site-packages/pytube/extract.py", line 101, in video_info_url
    group=0,
  File "/spiders/lib/python3.6/site-packages/pytube/helpers.py", line 39, in regex_search
    .format(pattern=pattern),
pytube.exceptions.RegexMatchError: regex pattern (\W[\'"]?t[\'"]?: ?[\'"](.+?)[\'"]) had zero matches`

We should consider making this error more transparent. PR to follow.

**Comment by nficano** [comment]
@billd100 I had to revert this out as it prevented all videos from being downloaded

**Comment by billd100** [comment]
@nficano Ah I'm sorry about that. I made another PR with a string that actually seems to discern available and unavailable videos.
