### ISSUE TITLE
Error in cipher.py "could not find python equivalent function for: "

### ISSUE THREAD

**Issue by vovasam** [pytube/pytube#268]
When try to  yt = YouTube("http://youtu.be/Z32gK0QkvkA") meet the error

Traceback (most recent call last):
  File "D:/YandexDisk/Code/Python/youtube.py", line 185, in download_file
    yt = YouTube(youtube_link)
  File "D:\Python\lib\site-packages\pytube\__main__.py", line 83, in __init__
    self.prefetch_init()
  File "D:\Python\lib\site-packages\pytube\__main__.py", line 92, in prefetch_init
    self.init()
  File "D:\Python\lib\site-packages\pytube\__main__.py", line 126, in init
    mixins.apply_signature(self.player_config_args, fmt, self.js)
  File "D:\Python\lib\site-packages\pytube\mixins.py", line 40, in apply_signature
    signature = cipher.get_signature(js, stream['s'])
  File "D:\Python\lib\site-packages\pytube\cipher.py", line 243, in get_signature
    tmap = get_transform_map(js, var)
  File "D:\Python\lib\site-packages\pytube\cipher.py", line 119, in get_transform_map
    fn = map_functions(function)
  File "D:\Python\lib\site-packages\pytube\cipher.py", line 200, in map_functions
    js_func,
pytube.exceptions.RegexMatchError: function(a,b){var c=a[0];a[0]=a[b%a.length];a[b%a.length]=c}: could not find python equivalent function for:

It looks error in cipher.py

**Comment by Mattwmaster58** [comment]
What version of python are you using?
