### ISSUE TITLE
Verify if a video was deleted 

### ISSUE THREAD

**Issue by merlinnusr** [pytube/pytube#279]
pytube crashes if a try to download a deleted video

**Comment by merlinnusr** [comment]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/motorocool/.local/lib/python2.7/site-packages/pytube/__main__.py", line 87, in __init__
    self.prefetch_init()
  File "/home/motorocool/.local/lib/python2.7/site-packages/pytube/__main__.py", line 95, in prefetch_init
    self.prefetch()
  File "/home/motorocool/.local/lib/python2.7/site-packages/pytube/__main__.py", line 166, in prefetch
    age_restricted=self.age_restricted,
  File "/home/motorocool/.local/lib/python2.7/site-packages/pytube/extract.py", line 101, in video_info_url
    group=0,
  File "/home/motorocool/.local/lib/python2.7/site-packages/pytube/helpers.py", line 39, in regex_search
    .format(pattern=pattern),
pytube.exceptions.RegexMatchError: regex pattern (\W[\'"]?t[\'"]?: ?[\'"](.+?)[\'"]) had zero matches
```
