### ISSUE TITLE
issue downloading really long videos

### ISSUE THREAD

**Issue by mkMcMahon** [pytube/pytube#322]
Tried to DL 9hr video and this is the  error. 

```
`C:\Users\athena>pytube https://www.youtube.com/watch?v=7zVOkb3CdZ0 -l
<Stream: itag="22" mime_type="video/mp4" res="720p" fps="30fps" vcodec="avc1.64001F" acodec="mp4a.40.2">
<Stream: itag="43" mime_type="video/webm" res="360p" fps="30fps" vcodec="vp8.0" acodec="vorbis">
<Stream: itag="18" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.42001E" acodec="mp4a.40.2">
<Stream: itag="36" mime_type="video/3gpp" res="240p" fps="30fps" vcodec="mp4v.20.3" acodec="mp4a.40.2">
<Stream: itag="17" mime_type="video/3gpp" res="144p" fps="30fps" vcodec="mp4v.20.3" acodec="mp4a.40.2">
<Stream: itag="137" mime_type="video/mp4" res="1080p" fps="30fps" vcodec="avc1.640028">
<Stream: itag="248" mime_type="video/webm" res="1080p" fps="30fps" vcodec="vp9">
<Stream: itag="136" mime_type="video/mp4" res="720p" fps="30fps" vcodec="avc1.4d401f">
<Stream: itag="247" mime_type="video/webm" res="720p" fps="30fps" vcodec="vp9">
<Stream: itag="135" mime_type="video/mp4" res="480p" fps="30fps" vcodec="avc1.4d401f">
<Stream: itag="244" mime_type="video/webm" res="480p" fps="30fps" vcodec="vp9">
<Stream: itag="134" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.4d401e">
<Stream: itag="243" mime_type="video/webm" res="360p" fps="30fps" vcodec="vp9">
<Stream: itag="133" mime_type="video/mp4" res="240p" fps="30fps" vcodec="avc1.4d4015">
<Stream: itag="242" mime_type="video/webm" res="240p" fps="30fps" vcodec="vp9">
<Stream: itag="160" mime_type="video/mp4" res="144p" fps="30fps" vcodec="avc1.4d400c">
<Stream: itag="278" mime_type="video/webm" res="144p" fps="30fps" vcodec="vp9">
<Stream: itag="140" mime_type="audio/mp4" abr="128kbps" acodec="mp4a.40.2">
<Stream: itag="171" mime_type="audio/webm" abr="128kbps" acodec="vorbis">
<Stream: itag="249" mime_type="audio/webm" abr="50kbps" acodec="opus">
<Stream: itag="250" mime_type="audio/webm" abr="70kbps" acodec="opus">
<Stream: itag="251" mime_type="audio/webm" abr="160kbps" acodec="opus">

C:\Users\athena>pytube https://www.youtube.com/watch?v=7zVOkb3CdZ0 --itag=137

LIVE Professor Christine Blasey Ford & Supreme Court nominee Judge Brett Kavanaugh testify (Day 1).mp4 | 3542203893 bytes
'stty' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\pytube.exe\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\pytube\cli.py", line 64, in main
    download(args.url, args.itag)
  File "c:\python36\lib\site-packages\pytube\cli.py", line 169, in download
    stream.download()
  File "c:\python36\lib\site-packages\pytube\streams.py", line 228, in download
    self.on_progress(chunk, fh, bytes_remaining)
  File "c:\python36\lib\site-packages\pytube\streams.py", line 285, in on_progress
    on_progress(self, chunk, file_handler, bytes_remaining)
  File "c:\python36\lib\site-packages\pytube\cli.py", line 148, in on_progress
    display_progress_bar(bytes_received, filesize)
  File "c:\python36\lib\site-packages\pytube\cli.py", line 121, in display_progress_bar
    _, columns = get_terminal_size()
  File "c:\python36\lib\site-packages\pytube\cli.py", line 98, in get_terminal_size
    rows, columns = os.popen('stty size', 'r').read().split()
ValueError: not enough values to unpack (expected 2, got 0)`
```

Here is the error report I tried to make, must be writing this wrong. 

`pytube https://www.youtube.com/watch?v=7zVOkb3CdZ0 --itag=137 --build-playback-report`

What is the proper code to produce an error report?

**Comment by tekord** [comment]
I have the same issue

**Comment by tekord** [comment]
Any news? Still can't download long video :)
