### ISSUE TITLE
pytube.exceptions.RegexMatchError

### ISSUE THREAD

**Issue by nishikeshKardak** [pytube/pytube#357]
It works fine, but sometimes I got this error for some videos.

```Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\__main__.py", line 88, in __init__
    self.prefetch_init()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\__main__.py", line 97, in prefetch_init
    self.init()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\__main__.py", line 133, in init
    mixins.apply_signature(self.player_config_args, fmt, self.js)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\mixins.py", line 49, in apply_signature
    signature = cipher.get_signature(js, stream['s'])
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\cipher.py", line 250, in get_signature
    tplan = get_transform_plan(js)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\cipher.py", line 72, in get_transform_plan
    return regex_search(pattern, js, group=1).split(';')
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\helpers.py", line 65, in regex_search
    .format(pattern=pattern),
pytube.exceptions.RegexMatchError: regex pattern (encodeURIComponent=function\(\w\){[a-z=\.\(\"\)]*;(.*);(?:.+)}) had zero matches```

**Comment by robly18** [comment]
Also have this problem. Using python 3.6.3. Have tried several of the fixes in #333 

EDIT: This fix worked for me: https://github.com/nficano/pytube/issues/353#issuecomment-455116197

**Comment by imanolpg** [comment]
I had the same problem. I fixed it with `pip install git+https://github.com/grking8/pytube.git@issue-354-regex-match-error`. Issue #354

**Comment by imanolpg** [comment]
Try #355 It works fine for me

**Comment by stdedos** [comment]
Please update with one of the two commands:

```bash
pip install pytube --upgrade
# and/or
pip install git+https://github.com/nficano/pytube.git --upgrade
```

and try again
