### ISSUE TITLE
stream.download() error with output_path contained '~/'

### ISSUE THREAD

**Issue by jihuun** [pytube/pytube#358]
youtube_dl.py in Ubuntu 16.04 
```python
from pytube import YouTube

URL='https://youtu.be/Z78zbnLlPUA'
yt = YouTube(URL)
print('Downloading a video \"%s\"\n' %yt.title)
stream = yt.streams.first()
stream.download('~/project/scripts/')
```

result is..

```
$ python3 youtube_dl.py 
Downloading a video "Intro and loading Images  - OpenCV with Python for Image and Video Analysis 1"

Traceback (most recent call last):
  File "youtube_dl.py", line 9, in <module>
    stream.download('~/project/scripts/')
  File "/home/jihuun/.local/lib/python3.5/site-packages/pytube/streams.py", line 223, in download
    with open(fp, 'wb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '~/project/scripts/Intro and loading Images  - OpenCV with Python for Image and Video Analysis 1.mp4'
```

**Comment by jihuun** [comment]
Can not use '~/' using an absolute path.
