### ISSUE TITLE
Download above 720

### ISSUE THREAD

**Issue by billapto** [pytube/pytube#362]
Hi all,
 i try to download a 2k video via cli with pytube (on windows 10) 
like that pytube https://www.youtube.com/watch?v=nBYZpsbu9ds --itag=313
and i keep getting errors 

Transient - 4K UHD 1000FPS.webm | 255892305 bytes
'stty' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\pytube.exe\__main__.py", line 9, in <module>
  File "c:\program files\python37\lib\site-packages\pytube\cli.py", line 64, in main
    download(args.url, args.itag)
  File "c:\program files\python37\lib\site-packages\pytube\cli.py", line 169, in download
    stream.download()
  File "c:\program files\python37\lib\site-packages\pytube\streams.py", line 228, in download
    self.on_progress(chunk, fh, bytes_remaining)
  File "c:\program files\python37\lib\site-packages\pytube\streams.py", line 285, in on_progress
    on_progress(self, chunk, file_handler, bytes_remaining)
  File "c:\program files\python37\lib\site-packages\pytube\cli.py", line 148, in on_progress
    display_progress_bar(bytes_received, filesize)
  File "c:\program files\python37\lib\site-packages\pytube\cli.py", line 121, in display_progress_bar
    _, columns = get_terminal_size()
  File "c:\program files\python37\lib\site-packages\pytube\cli.py", line 98, in get_terminal_size
    rows, columns = os.popen('stty size', 'r').read().split()
ValueError: not enough values to unpack (expected 2, got 0)

Can anyone help?

regards

**Comment by Medstar117** [comment]
You’re on Windows, I take it? I’ve put up a PR recently that fixes that. Pytube is calling for a bash command that isn’t valid on Windows in order to get the terminal’s geometry. I’ll reference your issue in my PR.

**Comment by jamadagni** [comment]
I found the same problem on Linux (Kubuntu Bionic) when I am piping a list of URLs to pytube so: `cat urls.txt | while read url ; do pytube --itag 22 $url ; done`. Downloading them individually isn't a problem.
