### ISSUE TITLE
JS is None followed by pytube.exceptions.RegexMatchError

### ISSUE THREAD

**Issue by stdedos** [pytube/pytube#368]
```python
# python3
Python 3.5.2 (default, Sep 14 2017, 22:51:06)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pytube import YouTube
>>> yt = YouTube('https://www.youtube.com/watch?v=Ck2jYtY5Hgg')
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pytube/__main__.py", line 133, in init
    mixins.apply_signature(self.player_config_args, fmt, self.js)
  File "/usr/local/lib/python3.5/dist-packages/pytube/mixins.py", line 53, in apply_signature
    raise TypeError('JS is None')
TypeError: JS is None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pytube/__main__.py", line 88, in __init__
    self.prefetch_init()
  File "/usr/local/lib/python3.5/dist-packages/pytube/__main__.py", line 97, in prefetch_init
    self.init()
  File "/usr/local/lib/python3.5/dist-packages/pytube/__main__.py", line 136, in init
    self.embed_html, self.age_restricted,
  File "/usr/local/lib/python3.5/dist-packages/pytube/extract.py", line 146, in js_url
    ytplayer_config = get_ytplayer_config(html, age_restricted)
  File "/usr/local/lib/python3.5/dist-packages/pytube/extract.py", line 194, in get_ytplayer_config
    yt_player_config = regex_search(pattern, html, group=1)
  File "/usr/local/lib/python3.5/dist-packages/pytube/helpers.py", line 65, in regex_search
    .format(pattern=pattern),
pytube.exceptions.RegexMatchError: regex pattern (;yt\.setConfig\(\{'PLAYER_CONFIG':\s*({.*})(,'EXPERIMENT_FLAGS'|;)) had zero matches
# pytube --version
pytube 9.4.0
```

**Comment by grking8** [comment]
submitted PR https://github.com/nficano/pytube/pull/370
