### ISSUE TITLE
cipher regex error

### ISSUE THREAD

**Issue by danielgordon10** [pytube/pytube#392]
I get the following output when trying to download a video
```
Traceback (most recent call last):
  File "/local/targaryen/Documents/workspace/video_representation_learning/utils/video_utils.py", line 281, in download_video
    video = stream.download(video_path, filename=video_id)
  File "/local/targaryen/Documents/workspace/video_representation_learning/utils/video_utils.py", line 195, in download_video
    yt = pytube.YouTube(video_url)
  File "/raid/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/streams.py", line 228, in download
    self.on_progress(chunk, fh, bytes_remaining)
  File "/raid/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/__main__.py", line 88, in __init__
    self.prefetch_init()
  File "/raid/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/streams.py", line 272, in on_progress
    file_handler.write(chunk)
  File "/raid/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/__main__.py", line 97, in prefetch_init
    self.init()
  File "/raid/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/__main__.py", line 133, in init
    mixins.apply_signature(self.player_config_args, fmt, self.js)
  File "/raid/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/mixins.py", line 49, in apply_signature
    signature = cipher.get_signature(js, stream['s'])
KeyboardInterrupt
KeyError: 's'
```
The interesting/surprising thing is if I try to download the same video again, I don't get the error. The video I'm trying to download is `https://www.youtube.com/watch?v=VAAcbCb1meE&has_verified=1`
This isn't specific to this one video, it seems to happen on many.

I separately see a different error consistently on some videos.
```
Traceback (most recent call last):
  File "experiment_scripts/test_each_video.py", line 52, in test_video_id
    yt = pytube.YouTube(video_url)
  File "/home/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/__main__.py", line 88, in __init__
    self.prefetch_init()
  File "/home/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/__main__.py", line 97, in prefetch_init
    self.init()
  File "/home/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/__main__.py", line 130, in init
    mixins.apply_descrambler(self.player_config_args, fmt)
  File "/home/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/mixins.py", line 89, in apply_descrambler
    for i in stream_data[key].split(',')
KeyError: 'url_encoded_fmt_stream_map'
```
for video `https://www.youtube.com/watch?v=YP05PC3ReW0&has_verified=1`

```
  File "experiment_scripts/test_each_video.py", line 52, in test_video_id
    yt = pytube.YouTube(video_url)
  File "/home/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/__main__.py", line 88, in __init__
    self.prefetch_init()
  File "/home/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/__main__.py", line 97, in prefetch_init
    self.init()
  File "/home/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/__main__.py", line 130, in init
    mixins.apply_descrambler(self.player_config_args, fmt)
  File "/home/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/mixins.py", line 89, in apply_descrambler
    for i in stream_data[key].split(',')
KeyError: 'url_encoded_fmt_stream_map'
```
for video `https://www.youtube.com/watch?v=TRXwkqNGpWA&has_verified=1`

They're probably unrelated bugs, but they both have issues with the parsing I think.

**Comment by egrinant** [comment]
I had the same problem, I was running the 9.4 release. I just updated to the latest release (currently 9.5) and it worked again.

**Comment by danielgordon10** [comment]
I am running the 9.5 release from pip, so that can't be it.

**Comment by Alexll82** [comment]
I have the same problem:

`Traceback (most recent call last):
  File "C:\Users\Alex\YandexDisk\python\pytube\pytube_1.py", line 6, in <module>
    yt = YouTube(line)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\__main__.py", line 88, in __init__
    self.prefetch_init()
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\__main__.py", line 97, in prefetch_init
    self.init()
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\__main__.py", line 133, in init
    mixins.apply_signature(self.player_config_args, fmt, self.js)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\mixins.py", line 49, in apply_signature
    signature = cipher.get_signature(js, stream['s'])
KeyError: 's'`

This problem appear on different computers and different versions of python:
Python 3.6, Python 3.7, win7, win8, pytube 9.5.0

Recommendations found on the Internet did not help. Modify the cipher.py file

**Comment by TheHolyLoli** [comment]
I have the same problem with : https://www.youtube.com/watch?v=ciEfKVfKXvI
Win10,pytube 9.5.0,Python3.7.2

**Comment by Choromanski** [comment]
+1

**Comment by AntiMatterAMA** [comment]
I have that error too. This is very unsetteling.

**Comment by msjuck** [comment]
9.5 but same problem

**Comment by bartwroblewski** [comment]
I was getting same cipher error on 9.4. I have upgraded to 9.5, but it did not help.

**Comment by danielgordon10** [comment]
https://github.com/minwook-shin/pytube/commit/f7ed32da09b6387713b15c7eb3ff5f17516e7ea2 seems to fix some of the errors for me.

**Comment by JeffMv** [comment]
> [minwook-shin@f7ed32d](https://github.com/minwook-shin/pytube/commit/f7ed32da09b6387713b15c7eb3ff5f17516e7ea2) seems to fix some of the errors for me.

Indeed. Worked for me too. An explanation given for this fix is [here on SO](https://stackoverflow.com/a/56578696/4418092):
> Apparently from time to time YouTube changes the way the signature is presented in the URL.

**Comment by SainiShiven** [comment]
Hello everyone,
i am getting keyerror 'url'
and 
cipher error

Currently, i'm using pytube3 with python 3.7.7

Just 3 days before everything is working correctly, then all of sudden about 90 % of youtube videos link returns :-
`Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\pytube\extract.py", line 297, in apply_descrambler
    for format_item in formats
  File "C:\Python37\lib\site-packages\pytube\extract.py", line 297, in <listcomp>
    for format_item in formats
KeyError: 'url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    yt = YouTube(link)
  File "C:\Python37\lib\site-packages\pytube\__main__.py", line 92, in __init__
    self.descramble()
  File "C:\Python37\lib\site-packages\pytube\__main__.py", line 132, in descramble
    apply_descrambler(self.player_config_args, fmt)
  File "C:\Python37\lib\site-packages\pytube\extract.py", line 301, in apply_descrambler
    parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
  File "C:\Python37\lib\site-packages\pytube\extract.py", line 301, in <listcomp>
    parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
KeyError: 'cipher'`
Pleas help me! I'm searching for fix since 1 week and everyone suggest me to edit mixins.py but i came to know that this file was found in pytube library not in pytube3.
Please help me! i'm working on a similar project for about 2 months or more and all of sudden everthing stopped working.
Thanks in advance for any help.

**Comment by venkat2k** [comment]
> Hello everyone,
> i am getting keyerror 'url'
> and
> cipher error
> 
> Currently, i'm using pytube3 with python 3.7.7
> 
> Just 3 days before everything is working correctly, then all of sudden about 90 % of youtube videos link returns :-
> `Traceback (most recent call last):
> File "C:\Python37\lib\site-packages\pytube\extract.py", line 297, in apply_descrambler
> for format_item in formats
> File "C:\Python37\lib\site-packages\pytube\extract.py", line 297, in
> for format_item in formats
> KeyError: 'url'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "test.py", line 5, in
> yt = YouTube(link)
> File "C:\Python37\lib\site-packages\pytube__main__.py", line 92, in **init**
> self.descramble()
> File "C:\Python37\lib\site-packages\pytube__main__.py", line 132, in descramble
> apply_descrambler(self.player_config_args, fmt)
> File "C:\Python37\lib\site-packages\pytube\extract.py", line 301, in apply_descrambler
> parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
> File "C:\Python37\lib\site-packages\pytube\extract.py", line 301, in
> parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
> KeyError: 'cipher'`
> Pleas help me! I'm searching for fix since 1 week and everyone suggest me to edit mixins.py but i came to know that this file was found in pytube library not in pytube3.
> Please help me! i'm working on a similar project for about 2 months or more and all of sudden everthing stopped working.
> Thanks in advance for any help.

I have the same issue. It only happens with copyrighted videos though! Any fixes?

**Comment by konnovdev** [comment]
the fix to the recent 'cipher' error is here https://github.com/nficano/pytube/pull/631

**Comment by yeomyeom** [comment]
I think KeyError: 'cipher' problem is sort of Security problem.
In youtube they have video copyright policy.
Some of video block download because of copyright policy.
   
I have 2 examples one is Twice k-pop music video the other is random video in youtube.
   
first Twice music video    
{'itag': 18, 'mimeType': 'video/mp4; codecs="avc1.42001E, mp4a.40.2"', 'bitrate': 692257, 'width': 640, 'height': 360, 'lastModified': '1591139239620763', 'contentLength': '20788503', 'quality': 'medium', 'fps': 24, 'qualityLabel': '360p', 'projectionType': 'RECTANGULAR', 'averageBitrate': 692076, 'audioQuality': 'AUDIO_QUALITY_LOW', 'approxDurationMs': '240303', 'audioSampleRate': '44100', 'audioChannels': 2, '**signatureCipher': ' < Very long url that can not connect to it >**'}
   
as you can see the key of dictionary itag, mimeType, video/mp4 ... are can see in pytube streams object. but there signatureCipher instead of url
Twice music video is download blocked because of copyright!!!
   
Second random video   
{'itag': 18, '**url': '< video download url >'**, 'mimeType': 'video/mp4; codecs="avc1.42001E, mp4a.40.2"', 'bitrate': 212352, 'width': 202, 'height': 360, 'lastModified': '1591434323617096', 'contentLength': '7059825', 'quality': 'small', 'fps': 30, 'qualityLabel': '240p', 'projectionType': 'RECTANGULAR', 'averageBitrate': 212300, 'audioQuality': 'AUDIO_QUALITY_LOW', 'approxDurationMs': '266031', 'audioSampleRate': '44100', 'audioChannels': 2}
   
as you can see url instead of signatureCipher and you can connet and download video through url value
   
conclusion 
   
Because of youtube video copyright policy some video can't download video files
