### ISSUE TITLE
JSON parsing error

### ISSUE THREAD

**Issue by danielgordon10** [pytube/pytube#393]
I get these errors when trying to download certain videos. I don't know if it's the fault of your code or of malformed JSON on youtube's side.
```
Traceback (most recent call last):
  File "experiment_scripts/test_each_video.py", line 52, in test_video_id
    yt = pytube.YouTube(video_url)
  File "/home/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/__main__.py", line 88, in __init__
    self.prefetch_init()
  File "/home/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/__main__.py", line 96, in prefetch_init
    self.prefetch()
  File "/home/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/__main__.py", line 174, in prefetch
    self.js_url = extract.js_url(self.watch_html, self.age_restricted)
  File "/home/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/extract.py", line 147, in js_url
    ytplayer_config = get_ytplayer_config(html, age_restricted)
  File "/home/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/extract.py", line 196, in get_ytplayer_config
    return json.loads(yt_player_config)
  File "/home/xkcd/miniconda3/envs/video-env/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/xkcd/miniconda3/envs/video-env/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/xkcd/miniconda3/envs/video-env/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 17575 (char 17574)
```
for video `https://www.youtube.com/watch?v=qRNqJ5I6PYI&has_verified=1`

```
  File "/home/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/__main__.py", line 133, in init
    mixins.apply_signature(self.player_config_args, fmt, self.js)
  File "/home/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/mixins.py", line 53, in apply_signature
    raise TypeError('JS is None')
TypeError: JS is None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "experiment_scripts/test_each_video.py", line 52, in test_video_id
    yt = pytube.YouTube(video_url)
  File "/home/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/__main__.py", line 88, in __init__
    self.prefetch_init()
  File "/home/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/__main__.py", line 97, in prefetch_init
    self.init()
  File "/home/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/__main__.py", line 136, in init
    self.embed_html, self.age_restricted,
  File "/home/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/extract.py", line 147, in js_url
    ytplayer_config = get_ytplayer_config(html, age_restricted)
  File "/home/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/extract.py", line 195, in get_ytplayer_config
    yt_player_config = regex_search(pattern, html, group=1)
  File "/home/xkcd/miniconda3/envs/video-env/lib/python3.7/site-packages/pytube/helpers.py", line 65, in regex_search
    .format(pattern=pattern),
pytube.exceptions.RegexMatchError: regex pattern (;yt\.setConfig\(\{'PLAYER_CONFIG':\s*({.*})(,'EXPERIMENT_FLAGS'|;)) had zero matches
```
for video `https://www.youtube.com/watch?v=jZLwVPakzwM&has_verified=1`

**Comment by stdedos** [comment]
For https://www.youtube.com/watch?v=qRNqJ5I6PYI:
@nficano `--build-playback-report` could be fixed for this one.

The problem with this video is:
![image](https://user-images.githubusercontent.com/133706/60381353-3ba74f00-9a5c-11e9-9b33-7d1486cfedd3.png)
`};` terminates the regex early
https://github.com/nficano/pytube/blob/7e0cd4e8639ab5754227eafa8a98613939c8b61a/pytube/extract.py#L194

---------------------

For the https://www.youtube.com/watch?v=jZLwVPakzwM video, it seems that regex matching / `JS is None` is solved on the newest version (`pip install git+https://github.com/nficano/pytube.git --upgrade`).
However, you still have the `urllib.error.HTTPError: HTTP Error 403: Forbidden` e.g. #399

**Comment by kylefoley76** [comment]
I have the most up to date version of pytube3 and I'm still getting this error, here is the full traceback

```
  File "/Users/kylefoley/codes/venv/lib/python3.8/site-packages/pytube/__main__.py", line 91, in __init__
    self.prefetch()
  File "/Users/kylefoley/codes/venv/lib/python3.8/site-packages/pytube/__main__.py", line 183, in prefetch
    self.js_url = extract.js_url(self.watch_html)
  File "/Users/kylefoley/codes/venv/lib/python3.8/site-packages/pytube/extract.py", line 143, in js_url
    base_js = get_ytplayer_config(html)["assets"]["js"]
  File "/Users/kylefoley/codes/venv/lib/python3.8/site-packages/pytube/extract.py", line 200, in get_ytplayer_config
    return json.loads(yt_player_config)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 229 (char 228)
```

Here is the video that caused it, I think
https://www.youtube.com/watch?v=q9uVfLfACYU

**Comment by jimmyxp01** [comment]
Yes I'm facing same problem. Anyone please help me

**Comment by RONNCC** [comment]
Hi @danielgordon10,  @jimmyxp01 , @kylefoley76 

Am closing issue as it has been quite a while -- feel free to reopen if this issue still exists 😄 

Thanks
