### ISSUE TITLE
signature = cipher.get_signature(js, stream['s']) key error 's'

### ISSUE THREAD

**Issue by AubHaddad** [pytube/pytube#402]
hey,
I'm trying to download with Youtube module and some videos throws this error :

`Traceback (most recent call last):
  File "download2.py", line 81, in <module>
    isSuccess = downloadYouTube(row['video_id'],path_videos)
  File "download2.py", line 17, in downloadYouTube
    yt = YouTube(url) # gerer video unavailable
  File "/home/aub.haddad/anaconda3/envs/youtube/lib/python3.6/site-packages/pytube/__main__.py", line 88, in __init__
    self.prefetch_init()
  File "/home/aub.haddad/anaconda3/envs/youtube/lib/python3.6/site-packages/pytube/__main__.py", line 97, in prefetch_init
    self.init()
  File "/home/aub.haddad/anaconda3/envs/youtube/lib/python3.6/site-packages/pytube/__main__.py", line 133, in init
    mixins.apply_signature(self.player_config_args, fmt, self.js)
  File "/home/aub.haddad/anaconda3/envs/youtube/lib/python3.6/site-packages/pytube/mixins.py", line 49, in apply_signature
    signature = cipher.get_signature(js, stream['s'])
KeyError: 's'`

can you help me please.
Thank youuu

**Comment by Choromanski** [comment]
Pull request #395 fixes this.

In  pytube/mixins.py chage line 41 from
`if 'signature=' in url:`
to 
`if ('signature=' in url) or ('&sig=' in url) or ('&lsig=' in url):`
