### ISSUE TITLE
NameError: name 'pytube' is not defined

### ISSUE THREAD

**Issue by prashantgonga** [pytube/pytube#404]
Pytube version: 9.5.0
Python version: 3.7.0

Disclaimer: I'm a noob, just downloaded the package and unable to get this code running.

```
from pytube import YouTube

print('Enter the YouTube video URL below')
videoLink = input()

yt = pytube.YouTube(videoLink)
videos = yt.streams.all()

s = 1
for video in videos:
    print(str(s) + " . "+str(video))
    s = s+1

print('Enter the number next to the video quality to download')

videoQuality = int(input())
downloadVideo = videos[videoQuality-1]

print('Enter the folder location where you want to save the file')
destination = input()
downloadVideo.download(destination)

print(yt.filename +" Video downloaded!")

```
**Error Message:**

```
Traceback (most recent call last):
  File "youtube_downloader.py", line 6, in <module>
    yt = pytube.YouTube(videoLink)
NameError: name 'pytube' is not defined

```

**Comment by FearlessENT** [comment]
try this:
yt = YouTube(videoLink)

**Comment by prashantgonga** [comment]
@FearlessENT Thanks for your response.

I tried your recommendation, I'm able to run the program now but I get different set of tracebacks now.


```
Traceback (most recent call last):
  File "youtube_downloader.py", line 21, in <module>
    downloadVideo.download(destination)
  File "C:\Users\Prashant\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\streams.py", line 217, in download
    bytes_remaining = self.filesize
  File "C:\Users\Prashant\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\streams.py", line 164, in filesize
    headers = request.get(self.url, headers=True)
  File "C:\Users\Prashant\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\request.py", line 21, in get
    response = urlopen(url)
  File "C:\Users\Prashant\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Prashant\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\Prashant\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Prashant\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\Prashant\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\Prashant\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden`

```
Here is the video link that I'm trying to download: 
https://www.youtube.com/watch?v=jDn2bn7_YSM
https://www.youtube.com/watch?v=fJ9rUzIMcZQ

I tried the steps mentioned in the below links but no luck so far. I would appreciate if you could guide me in the right direction 

https://stackoverflow.com/questions/28396036/python-3-4-urllib-request-error-http-403
https://stackoverflow.com/questions/16627227/http-error-403-in-python-3-web-scraping

**Comment by FearlessENT** [comment]
@prashantgonga Anytime. 

I believe your second issue is one I also recently had, but I tried a fix by @fofofofofofofofoXD .

That user said to go into the pytube package folder, and edit line 64 of "mixins.py" and change &signiture= to &sig=  . 

If you installed the package using pip or pip3, I believe it is located in your python folder at "\Lib\pytube\mixins.py".
If you have downloaded pytube and are using it locally, (pytube folder is in the same folder as your python script), then simply head inside the pytube folder and edit "mixins.py" . 

Once again credit to @fofofofofofofofoXD for the fix.

I think this will sort the issue out for you until pytube officially updates the issue.

Let me know if you need anymore help :D

Edit: the issue im referencing is at https://github.com/nficano/pytube/issues/399

**Comment by prashantgonga** [comment]
@FearlessENT Thank you so much for your help, I followed the steps mentioned in your previous comment and it fixed the issue.
