### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by MarcBresson** [pytube/pytube#414]
Hello,

I was trying to download some videos but i'am getting error 403 every time. Here is the full error:
`Traceback (most recent call last):
  File "C:\Users\\Music\...", line 88, in <module>
    yt.streams.filter(only_audio=True).first().download("","temp")
  File "C:\Users\\AppData\Local\Python\Python37\lib\site-packages\pytube\streams.py", line 217, in download
    bytes_remaining = self.filesize
  File "C:\Users\\AppData\Local\Python\Python37\lib\site-packages\pytube\streams.py", line 164, in filesize
    headers = request.get(self.url, headers=True)
  File "C:\Users\\AppData\Local\Python\Python37\lib\site-packages\pytube\request.py", line 21, in get
    response = urlopen(url)
  File "C:\Users\\AppData\Local\Python\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\\AppData\Local\Python\Python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\\AppData\Local\Python\Python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\\AppData\Local\Python\Python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\\AppData\Local\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\\AppData\Local\Python\Python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden`

I tried different internet connexions but always kept the same computer.
any ideas from where does the error come from ?

Have a great day

**Comment by python3-dev** [comment]
I have recieved the same error while I was trying to download videos from official channels (for eg: vevo) using pytube. I am assuming that it is some internal mechanism in YouTube to prevent downloads normally. There must be a workaround, though. Waiting for the solution.

**Comment by nhatton96** [comment]
Got the same error. Anyone else?

**Comment by MarcBresson** [comment]
ok so i am a bit of an dumb guy ...
here is the solution: https://github.com/nficano/pytube/issues/399

I had corrected that a week ago but i don't know why, it went back to full "&signature" instead of "&sig"

Sorry for my stupidity
