### ISSUE TITLE
Regex Pattern

### ISSUE THREAD

**Issue by nhatton96** [pytube/pytube#416]
I got this error for video https://www.youtube.com/watch?v=h_nYU9OVCZk
```
Traceback (most recent call last):
  File "DTC.py", line 116, in <module>
    YouTube(youtube_url).streams.first().download(output_path=download_folder,filename=guid)
  File "/usr/lib/python2.7/site-packages/pytube/__main__.py", line 88, in __init__
    self.prefetch_init()
  File "/usr/lib/python2.7/site-packages/pytube/__main__.py", line 97, in prefetch_init
    self.init()
  File "/usr/lib/python2.7/site-packages/pytube/__main__.py", line 133, in init
    mixins.apply_signature(self.player_config_args, fmt, self.js)
  File "/usr/lib/python2.7/site-packages/pytube/mixins.py", line 49, in apply_signature
    signature = cipher.get_signature(js, stream['s'])
  File "/usr/lib/python2.7/site-packages/pytube/cipher.py", line 257, in get_signature
    tplan = get_transform_plan(js)
  File "/usr/lib/python2.7/site-packages/pytube/cipher.py", line 76, in get_transform_plan
    name = re.escape(get_initial_function_name(js))
  File "/usr/lib/python2.7/site-packages/pytube/cipher.py", line 52, in get_initial_function_name
    return regex_search(pattern, js, group=1)
  File "/usr/lib/python2.7/site-packages/pytube/helpers.py", line 42, in regex_search
    .format(pattern=p),
pytube.exceptions.RegexMatchError: regex pattern (\bc\s*&&\s*d\.set\([^,]+\s*,\s*\([^)]*\)\s*\(\s*(?P<sig>[a-zA-Z0-9$]+)\() had zero matches
```

I can't find someone else with this regex pattern error so I think it's a new one.
Also I have changed lines of codes here and there to fix other problem. They may be related so here are all the changes:

- Change line 39 in helpers.py into:

```
                if p == pattern[-1]:
                    raise RegexMatchError(
                        'regex pattern ({pattern}) had zero matches'
                        .format(pattern=p),
                    )
```

- Change the pattern in line 38 in cipher.py into:

```
    pattern = [
        r'(["\'])signature\1\s*,\s*(?P<sig>[a-zA-Z0-9$]+)\(',
        r'\.sig\|\|(?P<sig>[a-zA-Z0-9$]+)\(',
        r'yt\.akamaized\.net/\)\s*\|\|\s*.*?\s*c\s*&&\s*d\.set\([^,]+\s*,\s*(?:encodeURIComponent\s*\()?(?P<sig>[a-zA-Z0-9$]+)\(',
        r'\bc\s*&&\s*d\.set\([^,]+\s*,\s*(?:encodeURIComponent\s*\()?\s*(?P<sig>[a-zA-Z0-9$]+)\(',
        r'\bc\s*&&\s*d\.set\([^,]+\s*,\s*\([^)]*\)\s*\(\s*(?P<sig>[a-zA-Z0-9$]+)\(',
    ]
```
- Change line 41 in mixins.py into:

```
        if ('signature=' in url or ('s' not in stream and ('&sig=' in url or '&lsig=' in url))):
            # For certain videos, YouTube will just provide them pre-signed, in
            # which case there's no real magic to download them and we can skip
            # the whole signature descrambling entirely.
            logger.debug('signature found, skip decipher')
            continue

        if js is not None:
            signature = cipher.get_signature(js, stream['s'])
        else:
            # signature not present in url (line 33), need js to descramble
            # TypeError caught in __main__
            raise TypeError('JS is None')

        logger.debug(
            'finished descrambling signature for itag=%s\n%s',
            stream['itag'], pprint.pformat(
                {
                    's': stream['s'],
                    'signature': signature,
                }, indent=2,
            ),
        )
        stream_manifest[i]['url'] = url + '&sig=' + signature
```

**Comment by stdedos** [comment]
Regex pattern is solved on the newest version. Download the newest version with `pip install git+https://github.com/nficano/pytube.git --upgrade`.

The issue now seems to be `urllib.error.HTTPError: HTTP Error 403: Forbidden` e.g. https://github.com/nficano/pytube/issues/399

**Comment by nhatton96** [comment]
I update to 9.5.1 and apply the same changes I did for mixins in lines 41 (which is also an answer in #399) and I got this:

```
pytube.exceptions.RegexMatchError: regex pattern (yt\.akamaized\.net/\)\s*\|\|\s*.*?\s*c\s*&&\s*d\.set\([^,]+\s*,\s*(?:encodeURIComponent\s*\()?(?P<sig>[a-zA-Z0-9$]+)\() had zero matches

```

**Comment by AntiMatterAMA** [comment]
I updated to 9.5.1 and everything works fine now.
