### ISSUE TITLE
Quickstart Example Title and Downloading not Working

### ISSUE THREAD

**Issue by RSDVA** [pytube/pytube#447]
Trying the example with the latest version 9.5.1 gives errors on the Quickstart example when we get to the part where we return the title.  See below with Python Shell output:

------------------------------------------
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> from pytube import YouTube
>>> yt = YouTube('https://www.youtube.com/watch?v=9bZkp7q19f0')
>>> yt.title
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    yt.title
  File "C:\Users\LTE.DAT.MACHINE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\__main__.py", line 254, in title
    return self.player_config_args['title']
KeyError: 'title'
------------------------------------------

Anyone figure out a fix for this?

Seems it is with the format of player_config_args might have changed from google.

If I look at the player_config_args i can see the title.

**Comment by eyl91** [comment]
Getting the same error too.

**Comment by Skealz** [comment]
Same !

**Comment by Skealz** [comment]
Check #434
The fix is there

**Comment by eyl91** [comment]
So this is updated?  https://pypi.org/project/pytube/

**Comment by RSDVA** [comment]
I updated the changes for both __main__.py and streams.py, but now get additional errors related to filesize.  See below:

Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    stream.download()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\streams.py", line 217, in download
    bytes_remaining = self.filesize
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\streams.py", line 164, in filesize
    headers = request.get(self.url, headers=True)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\request.py", line 21, in get
    response = urlopen(url)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

Has anyone else  tried that update?

**Comment by victorgregorio** [comment]
@RSDVA, https://github.com/nficano/pytube/issues/399 has a fix for `urllib.error.HTTPError: HTTP Error 403: Forbidden`

**Comment by RSDVA** [comment]
I have tried the various fixes in request.py, mixins.py, and cypher.py, but still not having any luck with downloading the basic example video from Quickstart.  Still getting urllib.error.HTTPError: HTTP Error 403: Forbidden.  Any other possible fixes others have tried?  I am using Python 3.7.2

**Comment by SofiyanIfren** [comment]
@RSDVA I also had to add the snippet mentionned [here](https://github.com/nficano/pytube/issues/450#issuecomment-520433737)

**Comment by tomkidumbuyo** [comment]
i went to the streams.py file in the package and changed `title = self.player_config_args['title']` to `title = self.player_config_args['player_response']['videoDetails']['title']`

**Comment by hbmartin** [comment]
fixed in my Python 3 only fork: https://github.com/hbmartin/pytube3
