### ISSUE TITLE
Fails on download

### ISSUE THREAD

**Issue by dai1345291582** [pytube/pytube#449]
Traceback (most recent call last):
  File "D:/pythonWork/daily/youtube/3.py", line 10, in <module>
    pl.download_all()
  File "C:\software\Python\Python36\lib\site-packages\pytube\contrib\playlist.py", line 172, in download_all
    dl_stream.download(download_path, filename_prefix=prefix)
  File "C:\software\Python\Python36\lib\site-packages\pytube\streams.py", line 206, in download
    filename = filename or self.default_filename
  File "C:\software\Python\Python36\lib\site-packages\pytube\streams.py", line 176, in default_filename
    title = self.player_config_args['title']
KeyError: 'title'

**Comment by Skealz** [comment]
See #434

**Comment by hbmartin** [comment]
@dai1345291582 @Skealz   fixed in my Python 3 only fork: https://github.com/hbmartin/pytube3
