### ISSUE TITLE
It's not working in macOS

### ISSUE THREAD

**Issue by iBobbyTS** [pytube/pytube#473]
I used PyCharm and IDLE, both of them are not working, here's my code.

`from pytube import YouTube

yt = YouTube('https://www.youtube.com/watch?v=9bZkp7q19f0')
yt.title`

Here's the error code

`/usr/local/bin/python3.7 "/Users/ibobby/PycharmProjects/YouTube Downloader/test.py"
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1414, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ibobby/PycharmProjects/YouTube Downloader/test.py", line 2, in <module>
    yt = YouTube('https://www.youtube.com/watch?v=9bZkp7q19f0')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/__main__.py", line 88, in __init__
    self.prefetch_init()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/__main__.py", line 96, in prefetch_init
    self.prefetch()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/__main__.py", line 160, in prefetch
    self.watch_html = request.get(url=self.watch_url)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/request.py", line 21, in get
    response = urlopen(url)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>

Process finished with exit code 1
`

<img width="1024" alt="屏幕快照 2019-09-20 下午8 10 46" src="https://user-images.githubusercontent.com/46138297/65364958-6a5c3e00-dbe3-11e9-97fd-0058060f2428.png">

Is there something wrong with my code? It's also not working in my windows 7 virtual machine, but the error code is a different one.

`"C:\Users\iBobby\PycharmProjects\YouTube Downloader\venv\Scripts\python.exe" "C:/Users/iBobby/PycharmProjects/YouTube Downloader/test.py"
Traceback (most recent call last):
  File "C:/Users/iBobby/PycharmProjects/YouTube Downloader/test.py", line 2, in <module>
    yt = YouTube('https://www.youtube.com/watch?v=9bZkp7q19f0')
  File "C:\Users\iBobby\PycharmProjects\YouTube Downloader\venv\lib\site-packages\pytube\__main__.py", line 88, in __init__
    self.prefetch_init()
  File "C:\Users\iBobby\PycharmProjects\YouTube Downloader\venv\lib\site-packages\pytube\__main__.py", line 96, in prefetch_init
    self.prefetch()
  File "C:\Users\iBobby\PycharmProjects\YouTube Downloader\venv\lib\site-packages\pytube\__main__.py", line 162, in prefetch
    raise VideoUnavailable('This video is unavailable.')
pytube.exceptions.VideoUnavailable: This video is unavailable.

Process finished with exit code 1
`

I saw a lot of videos about pytube, but they are working well. Is there a bug recently?

<img width="1136" alt="屏幕快照 2019-09-20 下午8 16 05" src="https://user-images.githubusercontent.com/46138297/65364988-be672280-dbe3-11e9-949d-17f99a9d2743.png">

Can anyone help me? I'm new to python.

**Comment by jscpeterson** [comment]
The SSLCertVerificationError is a problem with permissions on Python 3.6 in macOS.
http://www.cdotson.com/2017/01/sslerror-with-python-3-6-x-on-macos-sierra/
I was able to fix it by running 
`open /Applications/Python\ 3.7/Install\ Certificates.command`
in the Terminal from the directory my project was in.

The VideoUnavailable error I'm not sure about. With pytube-9.5.2 I get 403 `urllib.error.HTTPError: HTTP Error 403: Forbidden`. This error is expanded on in this issue #453 , specifically the solution in this comment https://github.com/nficano/pytube/pull/453#issuecomment-538099715 (using a different fork of this repo by running `pip install -e git+https://github.com/bigg215/pytube.git#egg=pytube` from the Terminal as opposed to `pip install pytube`) seems to have solved the problem for me.
