### ISSUE TITLE
Issue downloading some videos

### ISSUE THREAD

**Issue by sillyfatcat** [pytube/pytube#48]
Traceback (most recent call last):
  File "C:/Users/Shelby/PycharmProjects/blog/Python - YouTube downloader/main.py", line 51, in <module>
    main()
  File "C:/Users/Shelby/PycharmProjects/blog/Python - YouTube downloader/main.py", line 46, in main
    download_video(url)
  File "C:/Users/Shelby/PycharmProjects/blog/Python - YouTube downloader/main.py", line 13, in download_video
    y.url = video_url
  File "E:\Anaconda\lib\site-packages\pytube\api.py", line 95, in url
    self._get_video_info()
  File "E:\Anaconda\lib\site-packages\pytube\api.py", line 252, in _get_video_info
    raise YouTubeError("Cannot decode JSON: {0}".format(e))
pytube.exceptions.YouTubeError: Cannot decode JSON: No JSON object could be decoded

Video url:
doing http://youtu.be/-z_gYTXzM9k

Playlist:
https://www.youtube.com/playlist?list=PL3B92215F18CE89C5

Tried the same through youtube-dl and they didn't run into any problems.

**Comment by coryl** [comment]
I'm having a similar issue, can only download the mp4, 720p version of one file. When I try any other version I just get: 
'NoneType' object has no attribute 'download'

**Comment by nficano** [comment]
this video/playlist is private. can't and won't fix :)

**Comment by sillyfatcat** [comment]
Ah :'( the playlist used to not be private. If I encounter that issue again, I'll be sure to let you know.

**Comment by nficano** [comment]
@sshum00 please do! thank you sir!
