### ISSUE TITLE
re.error raised when creating a YouTube object

### ISSUE THREAD

**Issue by vigarov** [pytube/pytube#486]
When creating a YouTube object the following error is raised : `re.error: redefinition of group name 'sig' as group 2; was group 1 at position 140` . 
I have tested this with several different videos and noticed it only happens with videos tagged as Music by Youtube (e.g. : https://www.youtube.com/watch?v=9bZkp7q19f0), whereas "normal" videos (e.g.: https://www.youtube.com/watch?v=qb4D17Ms1p8 ) instantiate and download correctly.

I recently upgraded to Python 3.7 (it worked back in Python 3.5), could that be the problem?
Any help would be greatly appreciated.

**Comment by vigarov** [comment]
Here is the full traceback :
```
Traceback (most recent call last):
  File "C:/Users/_user_/PycharmProjects/videoDownl/main.py", line 90, in <module>
    vid= YouTube(new_address)
  File "C:\Users\_user_\PycharmProjects\videoDownl\venv\lib\site-packages\pytube\__main__.py", line 88, in __init__
    self.prefetch_init()
  File "C:\Users\_user_\PycharmProjects\videoDownl\venv\lib\site-packages\pytube\__main__.py", line 97, in prefetch_init
    self.init()
  File "C:\Users\_user_\PycharmProjects\videoDownl\venv\lib\site-packages\pytube\__main__.py", line 149, in init
    mixins.apply_signature(self.player_config_args, fmt, self.js)
  File "C:\Users\_user_\PycharmProjects\videoDownl\venv\lib\site-packages\pytube\mixins.py", line 52, in apply_signature
    signature = cipher.get_signature(js, stream['s'])
  File "C:\Users\_user_\PycharmProjects\videoDownl\venv\lib\site-packages\pytube\cipher.py", line 258, in get_signature
    tplan = get_transform_plan(js)
  File "C:\Users\_user_\PycharmProjects\videoDownl\venv\lib\site-packages\pytube\cipher.py", line 77, in get_transform_plan
    name = re.escape(get_initial_function_name(js))
  File "C:\Users\_user_\PycharmProjects\videoDownl\venv\lib\site-packages\pytube\cipher.py", line 53, in get_initial_function_name
    return regex_search(pattern, js, group=1)
  File "C:\Users\_user_\PycharmProjects\videoDownl\venv\lib\site-packages\pytube\helpers.py", line 36, in regex_search
    regex = re.compile(p, flags)
  File "C:\Users\_user_\AppData\Local\Programs\Python\Python37\lib\re.py", line 234, in compile
    return _compile(pattern, flags)
  File "C:\Users\_user_\AppData\Local\Programs\Python\Python37\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\_user_\AppData\Local\Programs\Python\Python37\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\_user_\AppData\Local\Programs\Python\Python37\lib\sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\_user_\AppData\Local\Programs\Python\Python37\lib\sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "C:\Users\_user_\AppData\Local\Programs\Python\Python37\lib\sre_parse.py", line 813, in _parse
    raise source.error(err.msg, len(name) + 1) from None
re.error: redefinition of group name 'sig' as group 2; was group 1 at position 140
```

**Comment by hbmartin** [comment]
@WKstraw This should be fixed in my branch, can you try: https://github.com/hbmartin/pytube3

**Comment by vigarov** [comment]
@hbmartin Used your branch and it works perfectly now, thank you!
