### ISSUE TITLE
Now it doesn't work anymore. 2019-12-20

### ISSUE THREAD

**Issue by Jabyer** [pytube/pytube#531]
yt = YouTube(link)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\pytube\__main__.py", line 88, in __init__
    self.prefetch_init()
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\pytube\__main__.py", line 97, in prefetch_init
    self.init()
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\pytube\__main__.py", line 143, in init
    mixins.apply_descrambler(self.player_config_args, fmt)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\pytube\mixins.py", line 96, in apply_descrambler
    for i in stream_data[key].split(',')
KeyError: 'url_encoded_fmt_stream_map'
>>>

**Comment by rafaelmarques7** [comment]
I am having the same issue I believe:

```
from pytube import YouTube
yt = YouTube('https://www.youtube.com/watch?v=DC471a9qrU4')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/rafael/PycharmProjects/BlackHatPython/venv/lib/python3.6/site-packages/pytube/__main__.py", line 88, in __init__
    self.prefetch_init()
  File "/home/rafael/PycharmProjects/BlackHatPython/venv/lib/python3.6/site-packages/pytube/__main__.py", line 97, in prefetch_init
    self.init()
  File "/home/rafael/PycharmProjects/BlackHatPython/venv/lib/python3.6/site-packages/pytube/__main__.py", line 143, in init
    mixins.apply_descrambler(self.player_config_args, fmt)
  File "/home/rafael/PycharmProjects/BlackHatPython/venv/lib/python3.6/site-packages/pytube/mixins.py", line 96, in apply_descrambler
    for i in stream_data[key].split(',')
KeyError: 'url_encoded_fmt_stream_map'
```

I've been googling this for a while now. Looks like this issue has appeared in the past, and has now re-appeared. I really hope we can find a solution for it.

**Comment by boidushya** [comment]
Yeah same from my side

**Comment by jaewoo-so** [comment]
same here

**Comment by giacaglia** [comment]
Created a fix for this bug. If you want to install the package with the fix before it gets to the main package, run the following:
pip3 install git+https://github.com/giacaglia/pytube.git

**Comment by hbmartin** [comment]
@Jabyer @rafaelmarques7 @nchos88  fixed in my Python 3 only fork: https://github.com/hbmartin/pytube3
