### ISSUE TITLE
SyntaxError: invalid syntax error on self._filesize

### ISSUE THREAD

**Issue by gopaljoshi-brainvire** [pytube/pytube#581]
Just installed pytube in python3 and import statement returns below error

```
Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pytube import YouTube
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gopal_joshi/Projects/Python/youtube-video/py3env/lib/python3.5/site-packages/pytube/__init__.py", line 14, in <module>
    from pytube.streams import Stream
  File "/home/gopal_joshi/Projects/Python/youtube-video/py3env/lib/python3.5/site-packages/pytube/streams.py", line 55
    self._filesize: Optional[int] = None  # filesize in bytes
                  ^
SyntaxError: invalid syntax
```
Any clue over here?

**Comment by hbmartin** [comment]
You need Python 3.6+
