### ISSUE TITLE
Error when try to get video signatures

### ISSUE THREAD

**Issue by leohuang2013** [pytube/pytube#59]
Hi  josegonzalez,

Firstly, very thanks for you sharing this very handy tools.

I checked out version b63b243824, then 
1. installed it 
2. coped example code in " Usage Example" into youtube.py file
3. run it.
got following error.

"
Traceback (most recent call last):
  File "youtube.py", line 10, in <module>
    yt.url = "https://www.youtube.com/watch?v=U0CGsw6h60k"
  File "/usr/local/lib/python2.7/site-packages/pytube/api.py", line 76, in url
    self._get_video_info()
  File "/usr/local/lib/python2.7/site-packages/pytube/api.py", line 241, in _get_video_info
    signature = video_signatures[idx]
IndexError: list index out of range

"

Could you help that.

email: leohwang@yahoo.com.sg

Regards,
Leo

**Comment by nficano** [comment]
Seems to be fixed as of v4.0.0
