### ISSUE TITLE
module error

### ISSUE THREAD

**Issue by ludwich** [pytube/pytube#6]
i get an error on every 2-3 run.
http://www.youtube.com/watch?v=zLTOzu8N1Pg&feature=youtube_gdata
[<Video: MPEG-4 Visual (.3gp) - 144p>, <Video: MPEG-4 Visual (.3gp) - 240p>, <Video: Sorenson H.263 (.flv) - 240p>, <Video: H.264 (.flv) - 360p>, <Video: H.264 (.flv) - 480p>, <Video: H.264 (.mp4) - 360p>, <Video: H.264 (.mp4) - 720p>, <Video: VP8 (.webm) - 360p>, <Video: VP8 (.webm) - 480p>, <Video: VP8 (.webm) - 720p>]
Traceback (most recent call last):
  File "test2.py", line 40, in <module>
    video.download('/c/media')
  File "build/bdist.linux-x86_64/egg/pytube/models.py", line 36, in download
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 407, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 445, in error
    return self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden

**Comment by rbrcsk** [comment]
I can confirm this. I've done some testing:

Here's a link that results in a 403: 

```
http://r3---sn-h5bt5guxax3vh-c0qe.c.youtube.com/videoplayback?cp=U0hUTVVQUl9HSkNONF9NSlZHOk9UamhiYlJhcnVV&itag=17&id=ccb4ceceef0dd4f8&algorithm=throttle-factor&ms=au&key=yt1&mv=m&upn=sK2OTUpIK4w&mt=1358531358&expire=1358554620&ipbits=8&factor=1.25&source=youtube&ip=84.2.179.130&sparams=algorithm%2Cburst%2Ccp%2Cfactor%2Cgcr%2Cid%2Cip%2Cipbits%2Citag%2Csource%2Cupn%2Cexpire&burst=40&fexp=905701%2C906437%2C916613%2C920704%2C912806%2C922403%2C922405%2C929901%2C913605%2C925710%2C929104%2C929110%2C908493%2C920201%2C913302%2C919009%2C911116%2C926403%2C910221%2C901451&sver=3&gcr=hu&newshard=yes&signature=1
```

And here's one that doesn't:

```
http://r3---sn-h5bt5guxax3vh-c0qe.c.youtube.com/videoplayback?source=youtube&sparams=algorithm%2Cburst%2Ccp%2Cfactor%2Cgcr%2Cid%2Cip%2Cipbits%2Citag%2Csource%2Cupn%2Cexpire&gcr=hu&ipbits=8&cp=U0hUTVVQUl9HSkNONF9NSlZHOkFIY1FEOEQ1emc4&fexp=920704%2C912806%2C922403%2C922405%2C929901%2C913605%2C925710%2C929104%2C929110%2C908493%2C920201%2C913302%2C919009%2C911116%2C910221%2C901451&algorithm=throttle-factor&burst=40&upn=ycCR9DKD77w&key=yt1&expire=1358554620&ip=84.2.179.130&id=ccb4ceceef0dd4f8&newshard=yes&mt=1358531479&sver=3&mv=m&factor=1.25&ms=au&itag=17&signature=8C97714CE798D37DEC4396C6AF8F10E5A1687B9F.BCF3B3E4AABB590B36D971313B698E76F760E292
```

You can see just by looking at the length of the URLs that something is not right with the first one. The are several differences like the signature is simply `1` which is clearly incorrect. Modifying the `upn`, `cp` and `signature` parameters to those of the working one, and we get a working link.

I have't looked into that part of the code, but this definitely looks like a problem in the `_get_video_info`  method of the `YouTube` class.

---

Until this is fixed (if it can be) I suggest you to wrap `download` in your own code to except `HTTPError` and retry the whole thing again. (Starting from parsing as that's where the problem is.)

**Comment by nficano** [comment]
Thanks guys! keep em coming - will look into it this weekend

**Comment by rbrcsk** [comment]
I tracked down what's causing this. `parse-qs` can't parse the data returned from `youtube.com/get_video_info` properly and instead of failing, it silently returns some bullshit.. The result can be seen [in this gist.](https://gist.github.com/4572277). I checked a few dozen queries and it was **never** parsed correctly. 

I've tried parsing it with [querystring-parser](https://github.com/bernii/querystring-parser) at least that fails.

@NFicano Did you see this problem before?

**Comment by rbrcsk** [comment]
@NFicano Both this and #5 should be fixed now too.

**Comment by nficano** [comment]
Ah thanks again man  

## 

Nick Ficano

**Comment by Petar-23** [comment]
hey guys, I am facing the same issue again... sometimes I am able to download 3 vids sometimes only 1 before this error occurs. 

ERROR CODE:
Traceback (most recent call last):
  File "C:/Users/petar/Documents/06_Tata/YT_Downloader.py", line 20, in <module>
    pl.download_all(target_dir)
  File "C:\Users\petar\.virtualenvs\06_Tata\lib\site-packages\pytube\contrib\playlist.py", line 172, in download_all
    dl_stream.download(download_path, filename_prefix=prefix)
  File "C:\Users\petar\.virtualenvs\06_Tata\lib\site-packages\pytube\streams.py", line 217, in download
    bytes_remaining = self.filesize
  File "C:\Users\petar\.virtualenvs\06_Tata\lib\site-packages\pytube\streams.py", line 164, in filesize
    headers = request.get(self.url, headers=True)
  File "C:\Users\petar\.virtualenvs\06_Tata\lib\site-packages\pytube\request.py", line 21, in get
    response = urlopen(url)
  File "C:\Users\petar\python_373\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\petar\python_373\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\petar\python_373\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\petar\python_373\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\petar\python_373\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\petar\python_373\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

Sry, for maybe posting this on the wrong forum

**Comment by Codingboy** [comment]
same for me:
2019-06-11 10:15:01,385 - cisum - INFO - downloading: https://www.youtube.com/watch?v=xwsYvBYZcx4
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:/Users/bla/Desktop/projects/cisum/cisum.py", line 87, in run
    self.download(self.json)
  File "C:/Users/bla/Desktop/projects/cisum/cisum.py", line 104, in download
    stream.download(output_path="static/music/", filename=filename)
  File "C:\Users\bla\AppData\Roaming\Python\Python36\site-packages\pytube\streams.py", line 217, in download
    bytes_remaining = self.filesize
  File "C:\Users\bla\AppData\Roaming\Python\Python36\site-packages\pytube\streams.py", line 164, in filesize
    headers = request.get(self.url, headers=True)
  File "C:\Users\bla\AppData\Roaming\Python\Python36\site-packages\pytube\request.py", line 21, in get
    response = urlopen(url)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by prashantgonga** [comment]
> same for me:
> 2019-06-11 10:15:01,385 - cisum - INFO - downloading: https://www.youtube.com/watch?v=xwsYvBYZcx4
> Exception in thread Thread-6:
> Traceback (most recent call last):
> File "C:\Program Files\Python36\lib\threading.py", line 916, in _bootstrap_inner
> self.run()
> File "C:/Users/bla/Desktop/projects/cisum/cisum.py", line 87, in run
> self.download(self.json)
> File "C:/Users/bla/Desktop/projects/cisum/cisum.py", line 104, in download
> stream.download(output_path="static/music/", filename=filename)
> File "C:\Users\bla\AppData\Roaming\Python\Python36\site-packages\pytube\streams.py", line 217, in download
> bytes_remaining = self.filesize
> File "C:\Users\bla\AppData\Roaming\Python\Python36\site-packages\pytube\streams.py", line 164, in filesize
> headers = request.get(self.url, headers=True)
> File "C:\Users\bla\AppData\Roaming\Python\Python36\site-packages\pytube\request.py", line 21, in get
> response = urlopen(url)
> File "C:\Program Files\Python36\lib\urllib\request.py", line 223, in urlopen
> return opener.open(url, data, timeout)
> File "C:\Program Files\Python36\lib\urllib\request.py", line 532, in open
> response = meth(req, response)
> File "C:\Program Files\Python36\lib\urllib\request.py", line 642, in http_response
> 'http', request, response, code, msg, hdrs)
> File "C:\Program Files\Python36\lib\urllib\request.py", line 570, in error
> return self._call_chain(*args)
> File "C:\Program Files\Python36\lib\urllib\request.py", line 504, in _call_chain
> result = func(*args)
> File "C:\Program Files\Python36\lib\urllib\request.py", line 650, in http_error_default
> raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 403: Forbidden

Where you able to fix this error? I'm facing the exact same error
