### ISSUE TITLE
HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by arsalandogar** [pytube/pytube#601]
This piece of code

`from pytube import YouTube`
`yt = YouTube('https://www.youtube.com/watch?v=tPEE9ZwTmy0')`

Throws this error:

Traceback (most recent call last):
  File "test.py", line 2, in <module>
    yt = YouTube('https://www.youtube.com/watch?v=tPEE9ZwTmy0')
  File "/home/user/.local/lib/python3.6/site-packages/pytube/__main__.py", line 91, in __init__
    self.prefetch()
  File "/home/user/.local/lib/python3.6/site-packages/pytube/__main__.py", line 162, in prefetch
    self.watch_html = request.get(url=self.watch_url)
  File "/home/user/.local/lib/python3.6/site-packages/pytube/request.py", line 36, in get
    return _execute_request(url).read().decode("utf-8")
  File "/home/user/.local/lib/python3.6/site-packages/pytube/request.py", line 24, in _execute_request
    return urlopen(request)  # nosec
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

**Comment by dada2010** [comment]
I have the same question, did you solve it?

**Comment by AliAkhtari78** [comment]
Same Problem.

**Comment by bigsandip** [comment]
Waiting for the solution

**Comment by swiftyy-mage** [comment]
@ZD511 @AliAkhtari78 @bigsandip 

Me and @arslandogar were discussing this issue [here](https://github.com/get-pytube/pytube3/issues/72), I was not able to replicate the behaviour on my machine, and was not able to solve it.

Just a few questions that would be helpful if you could answer:

1. Did this ever work for you? If it did work for you previously, when did it stop working?
2. Does this issue happen 100% of the time for you when trying to use it?
3. Does [youtube-dl](https://github.com/ytdl-org/youtube-dl) work for you?
4. Is YouTube blocked in your country?
4. Have you tried using a VPN?
5. What version of Python and what version of pytube are you running?
6. What operating system are you running?

I would recommend you all uninstall pytube completely, make sure it is uninstalled, then install pytube3 and try again. It is best actually if you can create a virtual environment and run 

    pip install pytube3
inside that virtual environment. I hope I can get this working for all of you.

**Comment by bigsandip** [comment]
On localserver it always works but not on live website.I heard this happens because youtube blocked my ip address. Is it true?

**Comment by dada2010** [comment]
I solved it by 'pip uninstall pytube',  'pip uninstall pytube3' and change IP, and I think the main  problem is IP been banned.

**Comment by swiftyy-mage** [comment]
@ZD511 I am glad to hear it! Did you change your IP by resetting the router? Or did you contact your ISP or use a VPN? I hope this will work for everyone else, thank you.

**Comment by alaa-aqeel** [comment]
i fixed this error with add cookies for browser ( Firefox, Chrome )  to request
by use this : [browser_cookie3](https://github.com/borisbabic/browser_cookie3)

[ pytube/request.py](https://github.com/AlaaProg/pytube/commit/212bd154b0684c011769b98d68dcb82204f37df3)

**Comment by gdimitrovdev** [comment]
I have the same problem so I tried @AlaaProg's solution but now I get the following error. Can someone help me?
![image](https://user-images.githubusercontent.com/43970296/81940245-11249d00-9600-11ea-887e-80304aac3a3c.png)

**Comment by alaa-aqeel** [comment]
@G060N0FF  this lib browser_cookie3 need brwoser like firefox or chrome to get cookies from it

**Comment by gdimitrovdev** [comment]
Yeah but how exactly do I get them? Sorry I am not very good with this technology.

**Comment by gdimitrovdev** [comment]
Ah nevermind, I saw that my Cookie file corrupted so I deleted it and created a new one, now everything is working fine. Thanks!

**Comment by godfrednanaowusu** [comment]
Is there any solution for this please, the issue is still there as at 9th July 2020. since March 26, there hasnt been any clear solution. Please if you know how to prevent Youtube from Banning IP Address, kindly let us know.

**Comment by shocklet** [comment]
> i fixed this error with add cookies for browser ( Firefox, Chrome ) to request
> by use this : [browser_cookie3](https://github.com/borisbabic/browser_cookie3)
> 
> [ pytube/request.py](https://github.com/AlaaProg/pytube/commit/212bd154b0684c011769b98d68dcb82204f37df3)

Thanks for your help, I solved the problem by doing just like you.

**Comment by shihyuuuuuuu** [comment]
> I have the same problem so I tried @AlaaProg's solution but now I get the following error. Can someone help me?
> ![image](https://user-images.githubusercontent.com/43970296/81940245-11249d00-9600-11ea-887e-80304aac3a3c.png)

I have the same BrowserCookieError, could you please tell me how you solved this problem? Thank you.

**Comment by infinity-plus** [comment]
Ok, if the issue is fixed by setting up cookies, how can I do it in servers like heroku?
fix on repo is needed

**Comment by RONNCC** [comment]
Hi @arslandogar , @infinity-plus , @shihyuuuuuuu @shocklet  @godfrednanaowusu 

Am closing issue as it has been quite a while -- feel free to reopen if this issue still exists 😄 

Thanks

**Comment by supermomie** [comment]
Your IP has been locked for 24h that's why u have http err 429

**Comment by Teemo15** [comment]
File "/home/youtubbb/.local/lib/python3.9/site-packages/pytube/request.py", line 55, in get
    return _execute_request(url).read().decode("utf-8")
  File "/home/youtubbb/.local/lib/python3.9/site-packages/pytube/request.py", line 34, in _execute_request
    cookies_jar = browser_cookie3.chrome(domain_name='.youtube.com')
  File "/home/youtubbb/.local/lib/python3.9/site-packages/browser_cookie3/__init__.py", line 662, in firefox
    return Firefox(cookie_file, domain_name).load()
  File "/home/youtubbb/.local/lib/python3.9/site-packages/browser_cookie3/__init__.py", line 496, in __init__
    cookie_file = cookie_file or self.find_cookie_file()
  File "/home/youtubbb/.local/lib/python3.9/site-packages/browser_cookie3/__init__.py", line 569, in find_cookie_file
    raise BrowserCookieError('Failed to find Firefox cookie')
browser_cookie3.BrowserCookieError: Failed to find Firefox cookie

How can I fix this?

**Comment by RONNCC** [comment]
Hey @Teemo15 --  please create a new issue in order to keep this one on topic :-) 
also helps us sort + organize them for the future
