### ISSUE TITLE
KeyError: 'formats' error on certain live feeds

### ISSUE THREAD

**Issue by Ircama** [pytube/pytube#609]
Installation (Python 3.6.9, pytube3-9.6.4):

```bash
pip3 uninstall -y pytube3
pip3 install git+https://github.com/nficano/pytube
python3
```

Test:

```python
from pytube import YouTube
YouTube('https://www.youtube.com/watch?v=5YceQ8YqYMc')
```

Error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".local/lib/python3.6/site-packages/pytube/__main__.py", line 92, in __init__
    self.descramble()
  File ".local/lib/python3.6/site-packages/pytube/__main__.py", line 132, in descramble
    apply_descrambler(self.player_config_args, fmt)
  File ".local/lib/python3.6/site-packages/pytube/extract.py", line 281, in apply_descrambler
    formats = json.loads(stream_data["player_response"])["streamingData"]["formats"]
KeyError: 'formats'
```

Ref. https://github.com/get-pytube/pytube3/issues/74 (maybe wrong place there, will remove that note if the issue is answered here)

**Comment by tooxo** [comment]
Opened a pull request on this: #612

**Comment by Ircama** [comment]
Thanks for this PR.

While testing it, I get *pytube.exceptions.RegexMatchError: get_ytplayer_config: could not find match for config_patterns*.

Steps to reproduce the error:

```python
pip3 uninstall -y pytube3
pip3 install "git+https://github.com/tooxo/pytube.git@fix_609"
python3
from pytube import YouTube
YouTube('https://www.youtube.com/watch?v=5YceQ8YqYMc')
```

Error output:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".local/lib/python3.6/site-packages/pytube/__main__.py", line 91, in __init__
    self.prefetch()
  File ".local/lib/python3.6/site-packages/pytube/__main__.py", line 183, in prefetch
    self.js_url = extract.js_url(self.watch_html)
  File ".local/lib/python3.6/site-packages/pytube/extract.py", line 143, in js_url
    base_js = get_ytplayer_config(html)["assets"]["js"]
  File ".local/lib/python3.6/site-packages/pytube/extract.py", line 202, in get_ytplayer_config
    raise RegexMatchError(caller="get_ytplayer_config", pattern="config_patterns")
pytube.exceptions.RegexMatchError: get_ytplayer_config: could not find match for config_patterns
```
