### ISSUE TITLE
TypeError: Instance and class checks can only be used with @runtime protocols

### ISSUE THREAD

**Issue by Srivaths-P** [pytube/pytube#620]
This error occurs when just importing pytube.

Here's the full traceback.

```
Traceback (most recent call last):
  File "C:/Users/Administrator/.PyCharmCE2018.3/config/scratches/scratch.py", line 1, in <module>
    import pytube
  File "C:\Users\Administrator\PycharmProjects\Chess\venv\lib\site-packages\pytube\__init__.py", line 13, in <module>
    from pytube.streams import Stream
  File "C:\Users\Administrator\PycharmProjects\Chess\venv\lib\site-packages\pytube\streams.py", line 22, in <module>
    from pytube.monostate import Monostate
  File "C:\Users\Administrator\PycharmProjects\Chess\venv\lib\site-packages\pytube\monostate.py", line 41, in <module>
    class Monostate:
  File "C:\Users\Administrator\PycharmProjects\Chess\venv\lib\site-packages\pytube\monostate.py", line 47, in Monostate
    duration: Optional[int] = None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\typing.py", line 259, in inner
    return func(*args, **kwds)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\typing.py", line 370, in __getitem__
    return Union[arg, type(None)]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\typing.py", line 259, in inner
    return func(*args, **kwds)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\typing.py", line 364, in __getitem__
    parameters = _remove_dups_flatten(parameters)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\typing.py", line 238, in _remove_dups_flatten
    for t2 in all_params - {t1}):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\typing.py", line 238, in <genexpr>
    for t2 in all_params - {t1}):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\abc.py", line 143, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
  File "C:\Users\Administrator\PycharmProjects\Chess\venv\lib\site-packages\typing_extensions.py", line 1502, in _proto_hook
    raise TypeError("Instance and class checks can only be used with"
TypeError: Instance and class checks can only be used with @runtime protocols
```

**Comment by vkizza** [comment]
I got the same Error after installing TensorFlow and  trying to import tensorflow using:-
import tensorflow as tf
