### ISSUE TITLE
KeyError: 'url' and KeyError: 'cipher' ,please someone update this code or some procedure to fix my code

### ISSUE THREAD

**Issue by saranshbamania-iitb** [pytube/pytube#661]
while downloading youtube video from python i am getting key error.
error:
![Screenshot (4)](https://user-images.githubusercontent.com/49087533/84765066-87ac1600-af83-11ea-925d-b1721ed648cd.png)

**Comment by tristanlatr** [comment]
Having the same error on macOS Catalina

Python
```
% python3 --version
Python 3.7.6
```

Traceback
```
% pytube3 --list "https://www.youtube.com/watch?v=7tLq5FZ0xlY"
Loading video...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pytube/extract.py", line 297, in apply_descrambler
    for format_item in formats
  File "/usr/local/lib/python3.7/site-packages/pytube/extract.py", line 297, in <listcomp>
    for format_item in formats
KeyError: 'url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pytube3", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pytube/cli.py", line 48, in main
    youtube = YouTube(args.url)
  File "/usr/local/lib/python3.7/site-packages/pytube/__main__.py", line 92, in __init__
    self.descramble()
  File "/usr/local/lib/python3.7/site-packages/pytube/__main__.py", line 132, in descramble
    apply_descrambler(self.player_config_args, fmt)
  File "/usr/local/lib/python3.7/site-packages/pytube/extract.py", line 301, in apply_descrambler
    parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
  File "/usr/local/lib/python3.7/site-packages/pytube/extract.py", line 301, in <listcomp>
    parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
KeyError: 'cipher'

```

**Comment by tristanlatr** [comment]
@Hack-Saransh 

Here is the workaround:

kbuilds commented 18 days ago
While waiting for the maintainer to address these PRs, feel free to use our public version with #643 merged in:

https://gitlab.com/obuilds/public/pytube

I use GitLab because I am a savage
You can install the tagged version like so:

pip install git+https://gitlab.com/obuilds/public/pytube@ob-v1
or add the following to your requirements.txt

git+https://gitlab.com/obuilds/public/pytube@ob-v1
Hopefully our boy sees these MRs soon and gets a new release out.

**Comment by cstuart1310** [comment]
The maintainer updated the readme last week saying that they're no longer maintaining the project, so someone else needs to take over :/

**Comment by gustavofuhr** [comment]
It would be good to link the above answer with the workaround to the readme.

**Comment by isaurav0** [comment]
Guys, I have just fixed this issue. 
Let me write steps. 

1. Go to pytube directory in site-packages. If you're not sure where full location is use `pip show pytube3` and you will see location. 
2. In pytube folder opened from above location, you'll see a file called **extract.py**. Open that file in your IDE or text-editor. 
3. You'll see a function called **apply_descrambler** . Inside that function, in **line 301** probably, you'll see something like
`parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)`
4. Replace **cipher** in `formats[i]["cipher"]` with **signatureCipher** . Thus that line becomes, 
`parse_qs(formats[i]["signatureCipher"]) for i, data in enumerate(formats)`
5. Viola ! This should fix your issue.

**Comment by wspek** [comment]
https://github.com/nficano/pytube/issues/661#issuecomment-650766403

Or, replace the line mentioned in step 3 by the following, to make it still support the old format **too** in case it's necessary:

```
parse_qs(formats[i].get("cipher") or formats[i].get("signatureCipher")) for i, data in enumerate(formats)
```

**Comment by barhemo** [comment]
@tristanlatr 
Hey man, it worked last week, but in the last couple of days i get this error. Can u fix it?
`Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Program Files\Python37\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Python37\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python37\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python37\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Program Files\Python37\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Program Files\Python37\lib\http\client.py", line 1384, in connect
    super().connect()
  File "C:\Program Files\Python37\lib\http\client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Program Files\Python37\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\Program Files\Python37\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\בר חמו\Desktop\work\youtube\main.py", line 54, in get_song
    ).streams.get_audio_only().download(str(youtube_id))
  File "C:\Users\בר חמו\AppData\Roaming\Python\Python37\site-packages\pytube\streams.py", line 231, in download
    bytes_remaining = self.filesize
  File "C:\Users\בר חמו\AppData\Roaming\Python\Python37\site-packages\pytube\streams.py", line 146, in filesize
    self._filesize = request.filesize(self.url)
  File "C:\Users\בר חמו\AppData\Roaming\Python\Python37\site-packages\pytube\request.py", line 76, in filesize
    return int(head(url)["content-length"])
  File "C:\Users\בר חמו\AppData\Roaming\Python\Python37\site-packages\pytube\request.py", line 88, in head 
    response_headers = _execute_request(url, method="HEAD").info()
  File "C:\Users\בר חמו\AppData\Roaming\Python\Python37\site-packages\pytube\request.py", line 24, in _execute_request
    return urlopen(request)  # nosec
  File "C:\Program Files\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Python37\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Program Files\Python37\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Program Files\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python37\lib\urllib\request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Program Files\Python37\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>`

**Comment by Melkeydev** [comment]
@isaurav0 But this fix wont be able to work if you deploy the application if your making a local change to the lib?

**Comment by isaurav0** [comment]
> @isaurav0 But this fix wont be able to work if you deploy the application if your making a local change to the lib?

@Amokstakov right, lets hope nficano fixes it soon, so we could easily `pip install` it and it works on the fly. For now, if you want to make it work in production, you can still `ssh` into your server and do all the steps written above manually in the server and expect it to work fine.

**Comment by RONNCC** [comment]
All,

Believe this is fixed in most recent version of Pytube
Let me know if this still doesnt work -- thanks

**Comment by vaccarieli** [comment]
hi I am stuck trying to know how to work with cipher this is my code:

```
html = request.get('https://youtu.be/SXG-b0GIorc')

jsFileLink = extract.js_url(html) # → str[source]

jsContent = request.get(jsFileLink) # → jsContent

unscrambleData = cipher.get_transform_map(jsContent, "fy") # Dict[KT, VT]

unscrambleData = Stream(unscrambleData, monostate=Monostate) #.stream_to_buffer(buffer)

print(unscrambleData)
```

`    self.url = stream["url"]  # signed download url
KeyError: 'url'`

honestly I don't know what u mean by this `Dict[KT, VT]`

Please any help ?
