### ISSUE TITLE
ImportError: cannot import name 'quote' from 'pytube.compat'

### ISSUE THREAD

**Issue by Perzan** [pytube/pytube#672]
Whenever I enter `pytube` into command prompt, I get the following error:

```
Traceback (most recent call last):
  File "c:\program files\python\installations\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python\installations\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\boob\AppData\Roaming\Python\Python38\Scripts\pytube.exe\__main__.py", line 4, in <module>
  File "C:\Users\boob\AppData\Roaming\Python\Python38\site-packages\pytube\__init__.py", line 16, in <module>
    from pytube.streams import Stream
  File "C:\Users\boob\AppData\Roaming\Python\Python38\site-packages\pytube\streams.py", line 17, in <module>
    from pytube import extract
  File "C:\Users\boob\AppData\Roaming\Python\Python38\site-packages\pytube\extract.py", line 7, in <module>
    from pytube.compat import quote
ImportError: cannot import name 'quote' from 'pytube.compat' (C:\Users\boob\AppData\Roaming\Python\Python38\site-packages\pytube\compat.py)
```

**Comment by JakobLewis** [comment]
@Perzan 
Try "pip install pytube3"

**Comment by brett6320** [comment]
> @Perzan
> Try "pip install pytube3"

I had the same issue. This corrected it.

**Comment by aquilesics** [comment]
its worked for me too

**Comment by SaranyaKesavan** [comment]
It's working for me as well. But run
 **pip uninstall pytube** 
before running **pip install pytube3**

**Comment by Bouke** [comment]
Don't install pytube3, it's not build from this repository. To install from the head of this repository:

    pip install git+https://github.com/nficano/pytube.git

**Comment by jiangno111** [comment]
not close yet?which is correct?

**Comment by RONNCC** [comment]
@Bouke  @jiangno111 @SaranyaKesavan @aquilesics @ngen-brett @JakobLewis  @Perzan 

Can you try again and let me know if you're still encountering the issue?
Also pytube3 is not related to  Pytube -- they are different libraries.

Thanks

**Comment by Perzan** [comment]
> @Bouke @jiangno111 @SaranyaKesavan @aquilesics @ngen-brett @JakobLewis @Perzan
> 
> Can you try again and let me know if you're still encountering the issue?
> Also pytube3 is not related to Pytube -- they are different libraries.
> 
> Thanks

The pip/git install worked

**Comment by tfdahlin** [comment]
There is a more recent issue regarding python 2 support [here](https://github.com/nficano/pytube/issues/756), so I'm going to close this issue
