### ISSUE TITLE
urllib2.HTTPError: HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by nhatton96** [pytube/pytube#694]
I'm using pytube with python 2.7 and got this error:

Traceback (most recent call last):
  File "test.py", line 87, in <module>
    local_video = YouTube(url).streams.first().download(download_folder)
  File "/usr/lib/python2.7/site-packages/pytube/__main__.py", line 88, in __init__
    self.prefetch_init()
  File "/usr/lib/python2.7/site-packages/pytube/__main__.py", line 96, in prefetch_init
    self.prefetch()
  File "/usr/lib/python2.7/site-packages/pytube/__main__.py", line 160, in prefetch
    self.watch_html = request.get(url=self.watch_url)
  File "/usr/lib/python2.7/site-packages/pytube/request.py", line 21, in get
    response = urlopen(url)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 429: Too Many Requests

**Comment by kpister** [comment]
This is a common issue. Check out https://github.com/nficano/pytube/issues/601 for discussion on it. Setting your cookies with pytube/request.py should fix the problem.
