### ISSUE TITLE
KeyError 'url' and 'cipher'

### ISSUE THREAD

**Issue by 512DuncanL** [pytube/pytube#699]
when i run this code in python shell:
```
>>> from pytube import YouTube
>>> YouTube('https://youtu.be/9bZkp7q19f0').streams.get_highest_resolution()
```
it gives this error:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytube/extract.py", line 288, in apply_descrambler
    stream_data[key] = [
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytube/extract.py", line 290, in <listcomp>
    "url": format_item["url"],
KeyError: 'url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#9>", line 1, in <module>
    YouTube('https://youtu.be/9bZkp7q19f0').streams.get_highest_resolution()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytube/__main__.py", line 92, in __init__
    self.descramble()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytube/__main__.py", line 132, in descramble
    apply_descrambler(self.player_config_args, fmt)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytube/extract.py", line 300, in apply_descrambler
    cipher_url = [
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytube/extract.py", line 301, in <listcomp>
    parse_qs(formats[i]["signatureCipher"]) for i, data in enumerate(formats)
KeyError: 'cipher'
```

**Comment by 512DuncanL** [comment]
updated extract.py, still not working, now getting error shown in #695

**Comment by light42** [comment]
@512DuncanL Reinstall pytube with this version:

`pip install git+https://gitlab.com/obuilds/public/pytube@ob-v1 --upgrade`

But today this won't worked anymore because of [this](https://github.com/nficano/pytube/issues/695).
