### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by ghost** [pytube/pytube#703]
Traceback (most recent call last):
  File "youtube.py", line 73, in live
    yt = YouTube('https://youtube.com/watch?v={}'.format(link))
  File "/home/pi/music/pytube/__main__.py", line 103, in __init__
    self.descramble()
  File "/home/pi/music/pytube/__main__.py", line 155, in descramble
    apply_signature(self.player_config_args, fmt, self.js)
  File "/home/pi/music/pytube/extract.py", line 238, in apply_signature
    cipher = Cipher(js=js)
  File "/home/pi/music/pytube/cipher.py", line 37, in __init__
    var, _ = self.transform_plan[0].split(".")
ValueError: too many values to unpack (expected 2)

**Comment by EnDroidCN** [comment]
I got the same exception. will follow the issue progress.

**Comment by light42** [comment]
Please look at issue #695.

**Comment by pcshih** [comment]
first, pip3 uninstall pytube3
second, pip3 install git+https://github.com/nficano/pytube.git@refs/pull/701/head
third, change cipher to signatureCipher in extract.py in line318

**Comment by tchakib** [comment]
le lien avec le fixe OK
https://github.com/tchakib/pytube
