### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ljy616** [pytube/pytube#706]
####CODE####
from pytube import YouTube
yt = YouTube('https://www.youtube.com/watch?v=bAWvR2ulCJ4')
print(yt.streams.filter())
####CODE####

STDERR 
##################################
Traceback (most recent call last):
  File "D:\Python\pytube.py", line 7, in <module>
    yt = YouTube('https://www.youtube.com/watch?v=bAWvR2ulCJ4')
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytube\__main__.py", line 92, in __init__
    self.descramble()
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytube\__main__.py", line 140, in descramble
    apply_signature(self.player_config_args, fmt, self.js)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytube\extract.py", line 225, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytube\cipher.py", line 31, in __init__
    var, _ = self.transform_plan[0].split(".")
ValueError: too many values to unpack (expected 2)

**Comment by ljy616** [comment]
Package           Version
----------------- -------
pip               20.2
pytube3           9.6.4
setuptools        47.1.0
typing-extensions 3.7.4.2
Python 3.8.5

**Comment by collinsuzebu** [comment]
Please take a look at this #703 (https://github.com/nficano/pytube/issues/703#issuecomment-665466634) and #695

**Comment by ljy616** [comment]
thanks a lot, 
I fixed it 

deleting pytube3 
installing pytubex
