### ISSUE TITLE
Unable to use the API

### ISSUE THREAD

**Issue by 9u3** [pytube/pytube#716]
I can't even get past the `from pytube import YouTube` part without getting this error

```
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from pytube import YouTube
  File "C:\Users\azerb\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytube\__init__.py", line 16, in <module>
    from pytube.streams import Stream
  File "C:\Users\azerb\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytube\streams.py", line 17, in <module>
    from pytube import extract
  File "C:\Users\azerb\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytube\extract.py", line 7, in <module>
    from pytube.compat import quote
ImportError: cannot import name 'quote' from 'pytube.compat' (C:\Users\azerb\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytube\compat.py)
```  What do i do??

**Comment by sidml** [comment]
@DemonEclipSe 
I think you are using python3 and installed python2 package. 

1. First uninstall pytube `pip uninstall pytube`
2. install pytube for python3. `pip install pytube3`

It should work now.
