### ISSUE TITLE
Issue with certain videos and all playlists

### ISSUE THREAD

**Issue by Asi4nn** [pytube/pytube#723]
Enter the url of the video or playlist: https://www.youtube.com/watch?v=hyfV0GBe18w&

Traceback (most recent call last):
  File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\extract.py", line 297, in apply_descrambler
    for format_item in formats
  File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\extract.py", line 297, in <listcomp>
    for format_item in formats
KeyError: 'url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Documents\Programming\Python-YT-Downloader\Python-YT-Downloader\main.py", line 97, in <module>
    video = YouTube(url)
  File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\__main__.py", line 92, in __init__
    self.descramble()
  File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\__main__.py", line 132, in descramble
    apply_descrambler(self.player_config_args, fmt)
  File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\extract.py", line 301, in apply_descrambler
    parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
  File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\extract.py", line 301, in <listcomp>
    parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
KeyError: 'cipher'

I have this error when trying to create Youtube objects with certain videos

Enter the url of the video or playlist: https://www.youtube.com/playlist?list=PLUCHSyG1Fb9GE6bFQBWqZ0ewJdlEKbN7_

Traceback (most recent call last):
  File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\extract.py", line 297, in apply_descrambler
    for format_item in formats
  File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\extract.py", line 297, in <listcomp>
    for format_item in formats
KeyError: 'url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Documents\Programming\Python-YT-Downloader\Python-YT-Downloader\main.py", line 95, in <module>
    video.append(YouTube(v))
  File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\__main__.py", line 92, in __init__
    self.descramble()
  File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\__main__.py", line 132, in descramble
    apply_descrambler(self.player_config_args, fmt)
  File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\extract.py", line 301, in apply_descrambler
    parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
  File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\extract.py", line 301, in <listcomp>
    parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
KeyError: 'cipher'

A similar thing happens with playlists

Code:

```python
# main.py

import subprocess
import sys
import get_pip
import re


def install(package):
    subprocess.call([sys.executable, "-m", "pip", "install", package])

try:
    from pytube import YouTube
    from pytube import Playlist
except:
    print('Import Error: PyTube3 not installed')
    print('Attempting to install PyTube3 using pip')
    try:
        import pip
        install('pytube3')
        print('PyTube3 has been installed')
    except:
        print('Import Error: pip not installed')
        print('Attempting to install pip')
        get_pip.main()
        print('Pip has been installed')
        try:
            print('Attempting to install PyTube3 using pip')
            import pip
            install('pytube3')
            print('PyTube3 has been installed')
        except:
            print('PyTube3 could not be installed')

from pytube import YouTube
from pytube import Playlist
import pytube


def convert_time(seconds: int):
    '''
    Returns a string of the time in the most optimal units
    Form: hours, minutes, seconds
    '''
    if seconds < 60:
        return str(seconds) + ' seconds'
    elif seconds < 3600:
        return str(seconds // 60) + ' minutes ' + str(seconds % 60) + ' seconds'
    else:
        return str(seconds // 3600) + ' hours ' + str(seconds // 60) + ' minutes ' + str(seconds % 60) + ' seconds'


#####################################
# EDIT THESE
#####################################
download_dir = 'C:\\Users\\leowa\\Music'
audio_itag = 140  # streams have a specific identifying tag, 140 is 128kbps audio only

while True:
    url = input('Enter the url of the video or playlist: ')
    print()
    video = None

    #try:
    if 'list' in url:
        video = []
        playlist = Playlist(url)
        playlist._video_regex = re.compile(r"\"url\":\"(/watch\?v=[\w-]*)")
        print(playlist.video_urls)
        for v in playlist.video_urls:
            video.append(YouTube(v))
    else:
        video = YouTube(url)
    #except:
    print("Couldn't find video at url:", url)

    if video is not None:
        # if its a playlist
        if str(type(video)) == "<class 'list'>":
            print("Videos :", len(video))
            for v in video:
                print("Title  :", v.title)
                print("Length :", convert_time(int(v.length)))
                print("Channel:", v.author)
                print()
        # if its just a video
        else:
            print("Title  : ", video.title)
            print("Length : ", convert_time(int(video.length)))
            print("Channel: ", video.author)
            print()

            # Uncomment this to see all stream types for a given video
            '''
            for s in video.streams:
                print(s)
            '''

            if input("Download this video (Y or N): ").lower() == 'y':
                dl = input("Download video or audio: ")
                while dl.lower() != 'video' and dl.lower() != 'audio':
                    dl = input("Enter video or audio as download options: ")
                    print()
                if dl.lower() == 'video':
                    res = input("Enter desired resolution (or high for highest avaliable): ")
                    if res.lower() == 'high':
                        stream = video.streams.get_highest_resolution()
                    else:
                        stream = video.stream.get_by_resolution(res)

                elif dl.lower() == 'audio':
                    stream = video.streams.get_by_itag(audio_itag)

                if stream is None:
                    print("Error: Unable to find given stream quality or resolution (make sure resolution is in the form xxxxp, example 1080p)")
                else:
                    print("Downloading...")
                    stream.download(output_path=download_dir, filename=video.title)
                    print("Download complete at", download_dir)

    print()
```

**Comment by jayathungek** [comment]
This issue is because of a change that YouTube made - the key ```cipher``` was renamed ```signatureCipher```. Please see #631 for details. 

You can install the patch that fixes this by doing:
```pip install git+git://github.com/nficano/pytube.git@0f32241c89192b22de9cfbfee1303a1bcee18bd3 ```
which is the latest patch that incorporates the fix from #631 

Hope this helps!

**Comment by Asi4nn** [comment]
Thanks! That fixed the problem of certain videos and the error for playlists, however, a new error has appeared for playlists:


Enter the url of the video or playlist: https://www.youtube.com/playlist?list=PLUCHSyG1Fb9FQomeNRuQaJaEvkMPABgwX

Traceback (most recent call last):
  File "D:\Documents\Programming\Python-YT-Downloader\Python-YT-Downloader\main.py", line 92, in <module>
    for v in playlist.videos:
  File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\contrib\playlist.py", line 252, in videos
    yield from (YouTube(url) for url in self.video_urls)
  File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\contrib\playlist.py", line 252, in <genexpr>
    yield from (YouTube(url) for url in self.video_urls)
  File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\__main__.py", line 102, in __init__
    self.prefetch()
  File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\__main__.py", line 203, in prefetch
    self.js_url = extract.js_url(self.watch_html)
  File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\extract.py", line 154, in js_url
    base_js = get_ytplayer_config(html)["assets"]["js"]
  File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\extract.py", line 211, in get_ytplayer_config
    return json.loads(yt_player_config)
  File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 882 (char 881)


Code is the same as original post, thanks in advance!

**Comment by jayathungek** [comment]
That's a new one :sweat_smile:  I've also encountered that particular error on occasion - seems to only happen with some videos. I have no way of knowing this, but I think this might be because of unescaped ```"``` characters somewhere in the JSON. Video descriptions and titles sometimes have double quotes - could be that whatever process generates the JSON fails to escape these sometimes. Would have to do more digging to get to the bottom of this, but I hope I've given you something to try at least  :smiley:

**Comment by Asi4nn** [comment]
I've been doing some testing and it seems to happen almost randomly, sometimes a video will throw this error, sometimes it won't, I guess I'll have to ignore it for now. Thanks again!

**Comment by jayathungek** [comment]
Do you mean the same video will throw this error in one instance and not in the next? That's very strange. I'd say close this issue and open a new one describing what you've tried.

**Comment by Asi4nn** [comment]
Thanks will do
