### ISSUE TITLE
line 91, in __init__     self.prefetch()

### ISSUE THREAD

**Issue by 0212100117** [pytube/pytube#753]
Traceback (most recent call last):
  File "C:\Users\User\Desktop\COMPROG\Comprog 2\Project Proposal\Test.py", line 15, in <module>
    YouTube(url).streams.get_highest_resolution().download(location)
  File "D:\pycharm\venv\lib\site-packages\pytube\__main__.py", line 91, in __init__
    self.prefetch()
  File "D:\pycharm\venv\lib\site-packages\pytube\__main__.py", line 183, in prefetch
    self.js_url = extract.js_url(self.watch_html)
  File "D:\pycharm\venv\lib\site-packages\pytube\extract.py", line 143, in js_url
    base_js = get_ytplayer_config(html)["assets"]["js"]
  File "D:\pycharm\venv\lib\site-packages\pytube\extract.py", line 200, in get_ytplayer_config
    return json.loads(yt_player_config)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 612 (char 611)

**Comment by tfdahlin** [comment]
@0212100117 I believe this problem is related to some breaking changes during the merge from pytube3 back into this repository. How did you install pytube when you encountered this problem? Do you still encounter this problem if you `pip uninstall pytube` and then `python -m pip install git+https://github.com/nficano/pytube'?

**Comment by tfdahlin** [comment]
I'm going to close this issue, as it's been 2 weeks without a response. I believe this issue is coming from using pytube3 instead of pytube, but if you reinstall with `python -m pip install git+https://github.com/nficano/pytube` and still run into this issue, please let us know, and provide more details about how you're using pytube so we can try to assist you further.
