### ISSUE TITLE
KeyError: 'assets'

### ISSUE THREAD

**Issue by eric6506** [pytube/pytube#776]
Here's my log:
`Traceback (most recent call last):
  File "C:\Users\user\Desktop\youtube archiver\youtube.py", line 66, in <module>
    yt = YouTube(love)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39-32\lib\site-packages\pytube\__main__.py", line 91, in __init__
    self.prefetch()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39-32\lib\site-packages\pytube\__main__.py", line 183, in prefetch
    self.js_url = extract.js_url(self.watch_html)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39-32\lib\site-packages\pytube\extract.py", line 143, in js_url
    base_js = get_ytplayer_config(html)["assets"]["js"]
KeyError: 'assets'`

Here's my script:
`from pytube import YouTube`
`love = "https://www.youtube.com/watch?v=vewjKRorasc"`
`yt = YouTube(love)    <------ERROR HERE"
`

**Comment by eric6506** [comment]
For now fixed 100% with this:

https://github.com/nficano/pytube/pull/767#issuecomment-716184994

With anyone else getting this error or issue, run this command in a terminal or cmd:
`python -m pip install git+https://github.com/nficano/pytube`
