### ISSUE TITLE
KeyError: 'playlistVideoRenderer'

### ISSUE THREAD

**Issue by TamaMcGlinn** [pytube/pytube#813]
Downloading a playlist throws an exception:

```
$ pytube https://www.youtube.com/playlist?list=PLHTh1InhhwT6VxYHtoWIvOup9gz0p95Qr
Loading playlist...
Traceback (most recent call last):
  File "/home/tama/.local/bin/pytube", line 10, in <module>
    sys.exit(main())
  File "/home/tama/.local/lib/python3.7/site-packages/pytube/cli.py", line 44, in main
    for youtube_video in playlist.videos:
  File "/home/tama/.local/lib/python3.7/site-packages/pytube/contrib/playlist.py", line 252, in videos
    yield from (YouTube(url) for url in self.video_urls)
  File "/home/tama/.local/lib/python3.7/site-packages/pytube/contrib/playlist.py", line 242, in video_urls
    for page in list(self._paginate())
  File "/home/tama/.local/lib/python3.7/site-packages/pytube/contrib/playlist.py", line 87, in _paginate
    self._extract_json(req)
  File "/home/tama/.local/lib/python3.7/site-packages/pytube/contrib/playlist.py", line 211, in _extract_videos
    videos
  File "/home/tama/.local/lib/python3.7/site-packages/pytube/contrib/playlist.py", line 208, in <lambda>
    f"/watch?v="
KeyError: 'playlistVideoRenderer'
```

Listing the video urls in a playlist also fails:

```
$ pytube https://www.youtube.com/playlist?list=PLHTh1InhhwT6VxYHtoWIvOup9gz0p95Qr --list
Loading playlist...
Traceback (most recent call last):
  File "/home/tama/.local/bin/pytube", line 10, in <module>
    sys.exit(main())
  File "/home/tama/.local/lib/python3.7/site-packages/pytube/cli.py", line 44, in main
    for youtube_video in playlist.videos:
  File "/home/tama/.local/lib/python3.7/site-packages/pytube/contrib/playlist.py", line 252, in videos
    yield from (YouTube(url) for url in self.video_urls)
  File "/home/tama/.local/lib/python3.7/site-packages/pytube/contrib/playlist.py", line 242, in video_urls
    for page in list(self._paginate())
  File "/home/tama/.local/lib/python3.7/site-packages/pytube/contrib/playlist.py", line 87, in _paginate
    self._extract_json(req)
  File "/home/tama/.local/lib/python3.7/site-packages/pytube/contrib/playlist.py", line 69, in _extract_json
    return self._js_regex.search(html).group(1)[0:-1]
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by tfdahlin** [comment]
Just to confirm, did you install pytube with `python -m pip install git+https://github.com/nficano/pytube`? There was an update to how playlists get extracted late last night that's only available by installing from the source code since pypi hasn't been updated yet. If you do have the most recent version, I'll try to look into the problem, but I'm not experiencing this issue locally right now.

**Comment by TamaMcGlinn** [comment]
Interesting. I installed from source (by cloning the repository and running `./setup.py install`, but too early to get that update. Thank you for the instructions.

(bug seems to be fixed, although a different one has immediately popped up in its place - oh well)
