### ISSUE TITLE
pytube.exceptions.RegexMatchError: regex_search: could not find match for 

### ISSUE THREAD

**Issue by kevinkkliu** [pytube/pytube#816]
Hello this is my first time using this tool ,I don't understand how is this happen

Here is error code:
```
>>> from pytube import YouTube
>>> YouTube('https://www.youtube.com/watch?v=0HO_tNU8iG')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pytube/__main__.py", line 89, in __init__
    self.video_id = extract.video_id(url)
  File "/usr/local/lib/python3.6/dist-packages/pytube/extract.py", line 113, in video_id
    return regex_search(r"(?:v=|\/)([0-9A-Za-z_-]{11}).*", url, group=1)
  File "/usr/local/lib/python3.6/dist-packages/pytube/helpers.py", line 40, in regex_search
    raise RegexMatchError(caller="regex_search", pattern=pattern)
pytube.exceptions.RegexMatchError: regex_search: could not find match for (?:v=|\/)([0-9A-Za-z_-]{11}).*

```
and here is pytube version

```
>>> import pytube
>>> pytube.__version__
'9.7.1'
```

**Comment by tfdahlin** [comment]
hi @kevinkkliu I believe that you may have copied the video URL incorrectly -- that link doesn't seem to go to any actual video

**Comment by kevinkkliu** [comment]
Oh! Thanks!
