### ISSUE TITLE
Question: Asyncio support

### ISSUE THREAD

**Issue by deepaerial** [pytube/pytube#829]
I would like to use this library with backend written in [FastAPI](https://fastapi.tiangolo.com/) to download video and submit download status to `asyncio.Queue` but as I understand this library does not support asynchronous code which means I cannot call asynchronous code in `on progress` callback . Are there any plans to add support for `asyncio` in the future?

**Comment by tfdahlin** [comment]
hey @deepaerial, I'd be happy to look into this as an improvement at some point in the future, or you're welcome to try and add the support yourself as a PR. I haven't done a lot of async work myself, so it might take me a while to work out what needs to be done for this to happen

**Comment by tfdahlin** [comment]
Hi @deepaerial I spent a little bit of time looking into a solution for this problem, and I was hopeful I might be able to dynamically convert the necessary functions to async functions, but that doesn't appear to be the case. 

Given how asyncio works, it would require an entire library rewrite in order for async on_progress and on_complete calls to be executed asynchronously, which is a bit outside the scope of the library. However, I have implemented a partial solution in [this branch](https://github.com/tfdahlin/pytube/tree/improvement/async_callbacks) that will call an async function synchronously, as a sort of workaround. Is this something that would work for you? I'm not super familiar with how asyncio works, so I don't know how to test this for your use case

**Comment by deepaerial** [comment]
Hey @tfdahlin I tried your code but unfortunately it doesn't work. As I understood I need to pass coroutine object to `on_progress_callback` but when I try to download video i get this exception:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/deepaerial/Projects/ytdl-web/.venv/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/deepaerial/Projects/ytdl-web/.venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/deepaerial/Projects/ytdl-web/.venv/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/deepaerial/Projects/ytdl-web/.venv/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/deepaerial/Projects/ytdl-web/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/deepaerial/Projects/ytdl-web/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/deepaerial/Projects/ytdl-web/.venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/deepaerial/Projects/ytdl-web/.venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/Users/deepaerial/Projects/ytdl-web/.venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/deepaerial/Projects/ytdl-web/.venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/deepaerial/Projects/ytdl-web/.venv/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/Users/deepaerial/Projects/ytdl-web/.venv/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/Users/deepaerial/Projects/ytdl-web/.venv/lib/python3.8/site-packages/starlette/routing.py", line 44, in app
    await response(scope, receive, send)
  File "/Users/deepaerial/Projects/ytdl-web/.venv/lib/python3.8/site-packages/starlette/responses.py", line 142, in __call__
    await self.background()
  File "/Users/deepaerial/Projects/ytdl-web/.venv/lib/python3.8/site-packages/starlette/background.py", line 35, in __call__
    await task()
  File "/Users/deepaerial/Projects/ytdl-web/.venv/lib/python3.8/site-packages/starlette/background.py", line 18, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/Users/deepaerial/Projects/ytdl-web/ytdl_api/task.py", line 125, in download_pytube
    pytube.YouTube(
  File "/Users/deepaerial/Projects/ytdl-web/.venv/src/pytube/pytube/streams.py", line 265, in download
    self.on_progress(chunk, fh, bytes_remaining)
  File "/Users/deepaerial/Projects/ytdl-web/.venv/src/pytube/pytube/streams.py", line 341, in on_progress
    asyncio.get_event_loop().run_until_complete(
  File "uvloop/loop.pyx", line 1450, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1443, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1351, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 480, in uvloop.loop.Loop._run
RuntimeError: this event loop is already running.
DEBUG:    chunk: data: {"media_id": "d1091cf605d945a083bac3a390ee2794", "status": "download", "progress": 54994935}
```
I think that I can only use this library in my project if it supports `asyncio`. I've already tried something similar that you did using `asycnio.create_task` but with `youtube-dl` but progress hook coroutine was executed after download was finished.

**Comment by deepaerial** [comment]
Okay, I managed to solve my problem by wrapping async code with `asyncio.run` in `on_progress` callback function .

**Comment by tfdahlin** [comment]
@deepaerial glad you were able to sort it out. In that case, I'm going to close this issue and remove my experimental branch.
