### ISSUE TITLE
pytube.exceptions.CipherError: Couldn't cipher the signature. Maybe YouTube has changed the cipher algorithm. Notify this issue on GitHub: Could not find JS function 'cr'

### ISSUE THREAD

**Issue by trohit** [pytube/pytube#83]
$ time pytube -e mp4 -r 720p https://www.youtube.com/watch?v=CevxZvSJLk8
Traceback (most recent call last):
  File "/usr/local/bin/pytube", line 90, in <module>
    main()
  File "/usr/local/bin/pytube", line 30, in main
    yt = YouTube(args.url)
  File "/usr/local/lib/python2.7/dist-packages/pytube/api.py", line 66, in **init**
    self.from_url(url)
  File "/usr/local/lib/python2.7/dist-packages/pytube/api.py", line 189, in from_url
    signature = self._get_cipher(stream_map["s"][idx], js_url)
  File "/usr/local/lib/python2.7/dist-packages/pytube/api.py", line 379, in _get_cipher
    "issue on GitHub: {0}".format(e))
pytube.exceptions.CipherError: Couldn't cipher the signature. Maybe YouTube has changed the cipher algorithm. Notify this issue on GitHub: Could not find JS function 'cr'

real    0m6.093s
user    0m1.040s
sys     0m0.150s

**Comment by trohit** [comment]
Possibly a duplicate of Issue#79 - Cipher Algorithm

**Comment by nficano** [comment]
yeah, this is a duplicate issue, looks like all similar projects are having this issue. Still digging for a solution.
