### ISSUE TITLE
Getting a ValueError with the latest code from the repo

### ISSUE THREAD

**Issue by vijjus** [pytube/pytube#853]
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pytube import YouTube
>>> YouTube('https://youtu.be/2lAe1cqCOXo')
Traceback (most recent call last):
  File "/home/ubuntu/venvnew/lib/python3.6/site-packages/pytube/parser.py", line 81, in parse_for_object_from_startpoint
    return json.loads(full_obj)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/venvnew/lib/python3.6/site-packages/pytube/__main__.py", line 102, in __init__
    self.prefetch()
  File "/home/ubuntu/venvnew/lib/python3.6/site-packages/pytube/__main__.py", line 218, in prefetch
    self.js_url = extract.js_url(self.watch_html)
  File "/home/ubuntu/venvnew/lib/python3.6/site-packages/pytube/extract.py", line 225, in js_url
    base_js = get_ytplayer_config(html)['assets']['js']
  File "/home/ubuntu/venvnew/lib/python3.6/site-packages/pytube/extract.py", line 304, in get_ytplayer_config
    return parse_for_object(html, pattern)
  File "/home/ubuntu/venvnew/lib/python3.6/site-packages/pytube/parser.py", line 24, in parse_for_object
    return parse_for_object_from_startpoint(html, start_index)
  File "/home/ubuntu/venvnew/lib/python3.6/site-packages/pytube/parser.py", line 83, in parse_for_object_from_startpoint
    return ast.literal_eval(full_obj)
  File "/usr/lib/python3.6/ast.py", line 85, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.6/ast.py", line 66, in _convert
    in zip(node.keys, node.values))
  File "/usr/lib/python3.6/ast.py", line 65, in <genexpr>
    return dict((_convert(k), _convert(v)) for k, v
  File "/usr/lib/python3.6/ast.py", line 84, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Name object at 0x7ffae3cdb7b8>

**Comment by tfdahlin** [comment]
hey, i'll take a look at this soon.

**Comment by tfdahlin** [comment]
@vijjus should be fixed with the code I just pushed, can you let me know if it works for you now?
