### ISSUE TITLE
raise InvalidURL(f"URL can't contain control characters. {url!r} "

### ISSUE THREAD

**Issue by rcsmit** [pytube/pytube#855]
Even with the simple example I have this error  : 
 File "C:\Users\rcxsm\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1200, in _validate_path
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
raise InvalidURL(f"URL can't contain control characters. {url!r} "

I commented out these lines, but it didnt help

```
from pytube import YouTube
YouTube('https://www.youtube.com/watch?v=Ic_FnHBiOYo').streams.first().download()
print ("ok")
```

**Comment by tfdahlin** [comment]
hi @rcsmit that error appears to be coming from python's HTTP client code, and not pytube. Can you give the full traceback output from running the program?

**Comment by rcsmit** [comment]
`Traceback (most recent call last):
  File "c:/Users/rcxsm/Documents/phyton_scripts/youtubedownloader.py", line 108, in <module>
    main()
  File "c:/Users/rcxsm/Documents/phyton_scripts/youtubedownloader.py", line 106, in main
    download(url)
  File "c:/Users/rcxsm/Documents/phyton_scripts/youtubedownloader.py", line 72, in download
    YouTube(durl).streams.first().download(filename=_filename)
  File "C:\Users\rcxsm\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__main__.py", line 91, in __init__
    self.prefetch()
  File "C:\Users\rcxsm\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__main__.py", line 184, in prefetch
    self.js = request.get(self.js_url)
  File "C:\Users\rcxsm\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\request.py", line 36, in get
    return _execute_request(url).read().decode("utf-8")
  File "C:\Users\rcxsm\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\request.py", line 24, in _execute_request
    return urlopen(request)  # nosec
  File "C:\Users\rcxsm\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\rcxsm\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\rcxsm\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\rcxsm\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\rcxsm\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\rcxsm\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\rcxsm\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\rcxsm\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1266, in _send_request
    self.putrequest(method, url, **skips)
  File "C:\Users\rcxsm\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1100, in putrequest
    self._validate_path(url)
  File "C:\Users\rcxsm\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1200, in _validate_path
    raise InvalidURL(f"URL can't contain control characters. {url!r} "`

followed by a lot of script

**Comment by tfdahlin** [comment]
@rcsmit this actually appears to be a problem with your python installation. I would recommend uninstalling and reinstalling python to see if that fixes the issue.

That traceback appears to point to a typo in the `http.client` code itself. Since it looks like you're using a windows machine, be sure to install python directly from [python.org](https://www.python.org/downloads/windows/)

**Comment by rcsmit** [comment]
Hello! Thank you for your help. I did, but it didn't resolve my problem. If I am the only one, it seems to be out of scope of pytube though. Thanks again.

**Comment by tfdahlin** [comment]
Sorry that I can't help more, I just can't seem to reproduce this problem myself, even when I copy and paste your code sample, and that error output makes it look like its an issue with the `C:\Users\rcxsm\AppData\Local\Programs\Python\Python38\lib\http\client.py` file
