### ISSUE TITLE
Error 429 :Too many request

### ISSUE THREAD

**Issue by martin73388** [pytube/pytube#858]
Hey,

I just installed the fix from #845 and now I have this problem: "HTTP Error 429: Too Many Requests" 

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Praven73/PycharmProjects/ProjectYT/venv/ProjectYT.py", line 261, in <module>
    video_temp.dl_song_mp4(y, martinmusic.arr_playlist[i].nb_videos,
  File "C:/Users/Praven73/PycharmProjects/ProjectYT/venv/ProjectYT.py", line 194, in dl_song_mp4
    video_yt_object = pytube.YouTube(video_url)
  File "C:\Users\Praven73\PycharmProjects\ProjectYT\venv\lib\site-packages\pytube\__main__.py", line 102, in __init__
    self.prefetch()
  File "C:\Users\Praven73\PycharmProjects\ProjectYT\venv\lib\site-packages\pytube\__main__.py", line 171, in prefetch
    self.watch_html = request.get(url=self.watch_url)
  File "C:\Users\Praven73\PycharmProjects\ProjectYT\venv\lib\site-packages\pytube\request.py", line 42, in get
    return _execute_request(url, headers=extra_headers).read().decode("utf-8")
  File "C:\Users\Praven73\PycharmProjects\ProjectYT\venv\lib\site-packages\pytube\request.py", line 26, in _execute_request
    return urlopen(request)  # nosec
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 563, in error
    result = self._call_chain(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
python-BaseException

**Comment by tfdahlin** [comment]
hi @martin73388 unfortunately this is not really an issue that we can solve in pytube itself. 

The problem you're having stems from the fact that YouTube will occasionally rate limit IP addresses. Usually, this happens because a specific IP has been blacklisted for abuse, but could also happen if an IP is simply making too many requests too quickly. We've had a number of users run into this issue, especially with services hosted on heroku, because they are hosting their code that uses pytube on a server that has been blacklisted for abuse.

One solution to this problem is to use a proxy. There's an explanation for how to use a proxy with pytube [here](https://github.com/nficano/pytube/issues/769#issuecomment-717576449).

**Comment by martin73388** [comment]
Hello,

I tried to run my script with my phone and I don't have the problem of 409 error code but I still got some empty stream list.

Try this URL for example: https://www.youtube.com/watch?v=XPzCzaBhF7s&ab

Or this one: https://www.youtube.com/watch?v=UDn6KXs6Cv8&ab&ab

**Comment by tfdahlin** [comment]
@martin73388 that problem should be fixed with the latest update to pytube; you'll need to update pytube with `python -m pip install git+https://github.com/nficano/pytube`
