### ISSUE TITLE
Unable to create YouTube object

### ISSUE THREAD

**Issue by aryanpanpalia** [pytube/pytube#863]
my code:
```py
from pytube import YouTube
video = YouTube(video_url)
```
I am doing it on several video URLs, each of which I have used before and was able to do so successfully. However no video works anymore and I don't really know why. I talked about this earlier but the issue just magically went away so I never bothered to figure out more. 
```
Traceback (most recent call last):
  File "C:/Users/user/PycharmProjects/SheetsFromSynth/main.py", line 13, in <module>
    youtube_to_frames.get_frames(video_url=VIDEO_URL, video_name=VIDEO_NAME)
  File "C:\Users\user\PycharmProjects\SheetsFromSynth\youtube_to_frames.py", line 8, in get_frames
    video = YouTube(video_url)
  File "C:\Users\user\PycharmProjects\SheetsFromSynth\venv\lib\site-packages\pytube\__main__.py", line 103, in __init__
    self.descramble()
  File "C:\Users\user\PycharmProjects\SheetsFromSynth\venv\lib\site-packages\pytube\__main__.py", line 123, in descramble
    self.player_config_args = get_ytplayer_config(self.watch_html)[
  File "C:\Users\user\PycharmProjects\SheetsFromSynth\venv\lib\site-packages\pytube\extract.py", line 206, in get_ytplayer_config
    caller="get_ytplayer_config", pattern="config_patterns"
pytube.exceptions.RegexMatchError: get_ytplayer_config: could not find match for config_patterns
```
Again, I was able to do this same code with the same URLs last week and it worked so I am also confused about how that would change.

**Comment by tfdahlin** [comment]
hi @aryanpanpalia I believe this is fixed in a most recent version change to pytube (which has not yet been published). 

Can you please try running the following commands and see if it fixes the problem:
`python -m pip uninstall pytube`
`python -m pip install git+https://github.com/nficano/pytube`

This will uninstall your existing pytube installation, and then reinstall from the source code

**Comment by aryanpanpalia** [comment]
Thank you so much! It works!

**Comment by tfdahlin** [comment]
Glad that worked for you
