### ISSUE TITLE
Unable to find start pattern

### ISSUE THREAD

**Issue by joyarzun** [pytube/pytube#87]
Hi there. I wanna report this issue.

```
pi@raspberrypi ~ $ python
Python 2.7.3 (default, Mar 18 2014, 05:13:23) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pytube import YouTube
>>> from pprint import pprint
>>> yt = YouTube("http://www.youtube.com/watch?v=Ik-RsDGPI5Y")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pytube/api.py", line 66, in __init__
    self.from_url(url)
  File "/usr/local/lib/python2.7/dist-packages/pytube/api.py", line 158, in from_url
    video_data = self.get_video_data()
  File "/usr/local/lib/python2.7/dist-packages/pytube/api.py", line 269, in get_video_data
    json_object = self._get_json_data(html)
  File "/usr/local/lib/python2.7/dist-packages/pytube/api.py", line 317, in _get_json_data
    raise PytubeError("Unable to find start pattern.")
pytube.exceptions.PytubeError: Unable to find start pattern.
>>> 
```

This happened with others videos too.
Cheers.

**Comment by joyarzun** [comment]
Please don't consider this issue. Long time ago, I put this line in my host: 

```
127.0.1.1   www.youtube.com
```

Close this issue
Cheers.

**Comment by josegonzalez** [comment]
No youtube browsing at work! :D

**Comment by joyarzun** [comment]
The truth is I have a raspberry pi in my house and through port forwarding I share internet at work. But I do not want to occupy all the bandwidth, so I put the Youtube line in host. hahaa all for the damned firewall.

**Comment by nficano** [comment]
:tanabata_tree:
