### ISSUE TITLE
getting error : cipher changed by youtube

### ISSUE THREAD

**Issue by DefCon-007** [pytube/pytube#88]
Error Log :
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pytube/api.py", line 368, in _get_cipher
    matches = reg_exp.search(self._js_cache)
TypeError: cannot use a string pattern on a bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Ayush/Documents/CODE/GIT_youtube/Project-Youtube/YouTube_Search.py", line 174, in <module>
    download_video_via_url(video_link[int(serial_no[a])-1])
  File "/Users/Ayush/Documents/CODE/GIT_youtube/Project-Youtube/YouTube_Search.py", line 113, in download_video_via_url
    yt=YouTube(video_url)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pytube/api.py", line 66, in **init**
    self.from_url(url)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pytube/api.py", line 189, in from_url
    signature = self._get_cipher(stream_map["s"][idx], js_url)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pytube/api.py", line 379, in _get_cipher
    "issue on GitHub: {0}".format(e))
pytube.exceptions.CipherError: Couldn't cipher the signature. Maybe YouTube has changed the cipher algorithm. Notify this issue on GitHub: cannot use a string pattern on a bytes-like object

**Comment by nficano** [comment]
Can you please give me the video url so I can try to repro this? thanks!

**Comment by DefCon-007** [comment]
Here is the url :     https://www.youtube.com/watch?v=rClUOdS5Zyw   I guess
the problem is with the vevo channels.

**Comment by icemanovich** [comment]
Other video link example with the same bug
https://www.youtube.com/watch?v=gfjhqx3bbdY

**Comment by nficano** [comment]
Can @ayush91195 and @icemanovich give me your Python and pytube versions? Both videos seem to work fine under Python 2.7.11 and pytube 6.1.5.

``` python
>>> from pytube import YouTube
>>> yt = YouTube('https://www.youtube.com/watch?v=rClUOdS5Zyw')
>>> yt.get_videos()
# [<Video: MPEG-4 Visual (.3gp) - 144p - Simple>,
#  <Video: MPEG-4 Visual (.3gp) - 240p - Simple>,
#  <Video: Sorenson H.263 (.flv) - 240p - N/A>,
#  <Video: H.264 (.mp4) - 360p - Baseline>,
#  <Video: H.264 (.mp4) - 720p - High>,
#  <Video: VP8 (.webm) - 360p - N/A>]
>>> yt = YouTube('https://www.youtube.com/watch?v=gfjhqx3bbdY')
>>> yt.get_videos()
# [<Video: MPEG-4 Visual (.3gp) - 144p - Simple>,
#  <Video: MPEG-4 Visual (.3gp) - 240p - Simple>,
#  <Video: Sorenson H.263 (.flv) - 240p - N/A>,
#  <Video: H.264 (.mp4) - 360p - Baseline>,
#  <Video: H.264 (.mp4) - 720p - High>,
#  <Video: VP8 (.webm) - 360p - N/A>]
>>> from pytube import __version__
>>> __version__
# '6.1.5'
>>> import sys
>>> sys.version
# '2.7.11 (default, Dec 26 2015, 17:47:15)'
```

**Comment by DefCon-007** [comment]
my pytube version is 6.1.5 and python 3.5.0

**Comment by icemanovich** [comment]
My Python verion is 3.5.0 and pytube is 6.1.5

**Comment by nficano** [comment]
Gotcha, clearly an issue under ~3.5, looking into it, thanks for reporting!

**Comment by icemanovich** [comment]
When expect fixes for 3.5 version?

**Comment by CZAlmon** [comment]
I have Python 3.4 and Pytube 6.1.5, and I have the same issue.

**Comment by nficano** [comment]
@icemanovich @CZAlmon @ayush91195 please update to the latest release.

``` bash
pip install -U pytube
```

**Comment by DefCon-007** [comment]
Thanks man..

**Comment by madrulzzz** [comment]
pip install -U pytube didnt update mine to 6.1.6

So I manually replaced the files in Lib\site-packages\pytube with the new ones from the zip and deleted _pycache_

Also replaced the pytube file in \Python35\Scripts

It works fine with this.... But Any ideas why pip didnt work for me?

**Comment by CZAlmon** [comment]
@nficano hasn't updated PYPI yet. That is why pip wont work. Only the github has been updated. 

https://pypi.python.org/pypi?%3Aaction=search&term=pytube&submit=search  

The latest version on PYPI is 6.1.5

**Comment by nficano** [comment]
Oops! I updated my pypi password but forgot to fix it in my `.pypirc`. All fixed! https://pypi.python.org/pypi/pytube/6.1.8

**Comment by markdude247** [comment]
Traceback (most recent call last):
  File "C:\Users\Mark\workspace2\Python\xfgbdfh\Pytube.py", line 54, in <module>
    yt = YouTube(URL)
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytube\__main__.py", line 81, in __init__
    self.prefetch_init()
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytube\__main__.py", line 90, in prefetch_init
    self.init()
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytube\__main__.py", line 117, in init
    mixins.apply_descrambler(self.vid_info, fmt)
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytube\mixins.py", line 76, in apply_descrambler
    for i in stream_data[key].split(',')
KeyError: 'url_encoded_fmt_stream_map'
