### ISSUE TITLE
[BUG] KeyError: 'content-length'

### ISSUE THREAD

**Issue by DaFluffyPotato** [pytube/pytube#912]
**Describe the bug**
The download function in 10.4.1 results in a `'content-length'` KeyError.

**To Reproduce**
Here's my code:
```python
from pytube import YouTube

url = input('URL: ')

yt = YouTube(url)
yt.streams.filter(file_extension='mp4').first().download()
```

**Expected behavior**
I expect it to download the video.

**Output**
```
URL: https://www.youtube.com/watch?v=EbNr015DZbM
Traceback (most recent call last):
  File "C:\Users\cmlsc\Desktop\youtube_download.py", line 7, in <module>
    yt.streams.filter(file_extension='mp4').first().download()
  File "D:\Python38\lib\site-packages\pytube\streams.py", line 251, in download
    bytes_remaining = self.filesize
  File "D:\Python38\lib\site-packages\pytube\streams.py", line 158, in filesize
    self._filesize = request.filesize(self.url)
  File "D:\Python38\lib\site-packages\pytube\request.py", line 127, in filesize
    return int(head(url)["content-length"])
KeyError: 'content-length'
```

**System information**
Please provide the following information:
Python Version: 3.8.6
Pytube Version: 10.4.1
Install Command: `D:\Python38\python.exe -m pip install git+https://github.com/pytube/pytube --upgrade`

**Comment by tfdahlin** [comment]
hi @DaFluffyPotato I'm unable to replicate this problem. Can you run it again and see if you have the same issue?

**Comment by DaFluffyPotato** [comment]
I just tested it again. It appears to be working on my end now. I suspect it may be an issue with livestreams archives from livestreams that were recently finished. I'm pretty sure YouTube does some processing for a few hours (or maybe a couple days?) on livestreams after they finish since you can't see the live chat immediately. I'll close this issue and someone can just make a new one if it turns out that there's an issue with fresh livestream archives.

**Comment by tfdahlin** [comment]
sounds good!

**Comment by dovewing** [comment]
i have a same issue
`~\anaconda3\lib\site-packages\pytube\request.py in filesize(url)
    198     :returns: int: size in bytes of remote file
    199     """
--> 200     return int(head(url)["content-length"])
    201 
    202 

KeyError: 'content-length'`

**Comment by Robin-Haupt-1** [comment]
I am also getting the same issue only with the following video, which isn't a recent video or a livestream:

https://www.youtube.com/watch?v=qT4a73ctcmw

```
Traceback (most recent call last):
  File "/hdd/Software Engineering/PyCharm/AHC-Archive-Youtube-Videos/download_youtube/import_youtube_video_into_obsidian_main_vault.py", line 214, in <module>
    y._get(x)
  File "/hdd/Software Engineering/PyCharm/AHC-Archive-Youtube-Videos/download_youtube/import_youtube_video_into_obsidian_main_vault.py", line 154, in _get
    saved_video = ffmpeg.input(video_stream.download(output_path=self.temp_folder))
  File "/hdd/Software Engineering/2022/22-01-02 Python 3.10 Shared/venv/lib/python3.10/site-packages/pytube/streams.py", line 247, in download
    bytes_remaining = self.filesize
  File "/hdd/Software Engineering/2022/22-01-02 Python 3.10 Shared/venv/lib/python3.10/site-packages/pytube/streams.py", line 146, in filesize
    self._filesize = request.filesize(self.url)
  File "/hdd/Software Engineering/2022/22-01-02 Python 3.10 Shared/venv/lib/python3.10/site-packages/pytube/request.py", line 200, in filesize
    return int(head(url)["content-length"])
KeyError: 'content-length'

```

**Comment by GreenArron** [comment]
same issue with these videos 

https://youtu.be/2pmEEW--tXE
https://youtu.be/pxw7wNQpgRM
https://youtu.be/JkhiYR-TtJQ
```
File "/home/container/cogs/Modules/linkman.py", line 269, in yt_download
vids[stream.filesize] = stream.itag

File "/home/container/.local/lib/python3.9/site-packages/pytube/streams.py", line 146, in filesize
self._filesize = request.filesize(self.url)

File "/home/container/.local/lib/python3.9/site-packages/pytube/request.py", line 200, in filesize
return int(head(url)["content-length"])
```

**Comment by ManasKhosla** [comment]
Rather than using "**pyt_obj.filesize**", try using "**pyt_obj._filesize**". That fixed the "KeyError: 'content-length'" for me.

I think the issue is in pytube.requests and pytube.streams as both have conflicting keys here

streams.py
`        self._filesize: Optional[int] = int(stream.get('contentLength', 0))`

requests.py
`@lru_cache()
def filesize(url):
    """Fetch size in bytes of file at given URL

    :param str url: The URL to get the size of
    :returns: int: size in bytes of remote file
    """
    return int(head(url)["content-length"])`

**Comment by tiff1002** [comment]
> Rather than using "**pyt_obj.filesize**", try using "**pyt_obj._filesize**". That fixed the "KeyError: 'content-length'" for me.
> 
> I think the issue is in pytube.requests and pytube.streams as both have conflicting keys here
> 
> streams.py ` self._filesize: Optional[int] = int(stream.get('contentLength', 0))`
> 
> requests.py `@lru_cache() def filesize(url): """Fetch size in bytes of file at given URL
> 
> ```
> :param str url: The URL to get the size of
> :returns: int: size in bytes of remote file
> """
> return int(head(url)["content-length"])`
> ```

From what I can tell my streams.py file already uses _filesize and I still have the issue with the following:

`
>>> test = pytube.YouTube('https://www.youtube.com/watch?v=UQ5_ehVI7mg', use_oauth=True).streams.order_by('resolution').desc().first().download(filename_prefix="video_")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\tiff\AppData\Roaming\Python\Python310\site-packages\pytube\streams.py", line 247, in download
    bytes_remaining = self.filesize
  File "C:\Users\tiff\AppData\Roaming\Python\Python310\site-packages\pytube\streams.py", line 146, in filesize
    self._filesize = request.filesize(self.url)
  File "C:\Users\tiff\AppData\Roaming\Python\Python310\site-packages\pytube\request.py", line 200, in filesize
    return int(head(url)["content-length"])
KeyError: 'content-length'
`

this only happens on certain videos and I am currently skipping ones affected with a try catch but this sucks I hope someone figures it out soon I do not want to switch to youtube-dl
