### ISSUE TITLE
[BUG] urlopen error: Address family not supported by protocol

### ISSUE THREAD

**Issue by chudleycannon** [pytube/pytube#930]
**Describe the bug**
While running pytube in a AWS Lambda i am intermittently getting an error (see below) when initiating a Youtube object

**To Reproduce**
Running on an AWS Lambda in a VPC.
Code snippet is:
```
   from pytube import YouTube
...
    link = body["link"]
    print(link)
    yt = YouTube(link)
    length = yt.length
```

The link is https://www.youtube.com/watch?v=LOS5WB75gkY

(Note this is intermittent, seems to work with some deploys and then error on others with no change to the code around pytube) 

**Expected behavior**
YouTube object is initilized with the linked video and the length variable is populated with the length of the video

**Output**
```
[ERROR] URLError: <urlopen error [Errno 97] Address family not supported by protocol

>Traceback (most recent call last):  File "/var/task/download_video.py", line 25, in lambda_handler 
   yt = YouTube(link)  
File "/var/task/pytube/__main__.py", line 104, in __init__    self.prefetch()  
File "/var/task/pytube/__main__.py", line 202, in prefetch    self.watch_html = request.get(url=self.watch_url)  
File "/var/task/pytube/request.py", line 42, in get    return _execute_request(url, headers=extra_headers).read().decode("utf-8")  
File "/var/task/pytube/request.py", line 26, in _execute_request    return urlopen(request)  # nosec  
File "/var/lang/lib/python3.8/urllib/request.py", line 222, in urlopen    return opener.open(url, data, timeout)  
File "/var/lang/lib/python3.8/urllib/request.py", line 525, in open    response = self._open(req, data)  
File "/var/lang/lib/python3.8/urllib/request.py", line 542, in _open    result = self._call_chain(self.handle_open, protocol, protocol +  
File "/var/lang/lib/python3.8/urllib/request.py", line 502, in _call_chain    result = func(*args)  
File "/var/lang/lib/python3.8/urllib/request.py", line 1393, in https_open    return self.do_open(http.client.HTTPSConnection, req,  
File "/var/lang/lib/python3.8/urllib/request.py", line 1353, in do_open    raise URLError(err)
```

**System information**
Please provide the following information:
- Python version (run `python --version`): AWS Lambda Python 3.8
- Pytube version (run `print(pytube.__version__)` in python) : 10.5.0 (first found on 10.4.1)
- Command used to install pytube: pip install git+https://github.com/nficano/pytube -t .

**Comment by tfdahlin** [comment]
These urllib errors are always the hardest things to figure out. Just to confirm, you aren't making changes to the AWS infrastructure between deploys, are you? A lot of times, when we see errors coming from urllib like this, it's because of a networking issue, such as rate limiting from YouTube, but could also be caused by firewall configurations. It *looks* like the underlying issue has something to do with ipv6 (based on a cursory google search), but it's really hard to pinpoint where in your stack that issue lies

**Comment by chudleycannon** [comment]
I'm not making changes but its a lambda so the underlying infrastructure probably changes often.

**Comment by tfdahlin** [comment]
Hmmmmmmm. Is your VPC set up with an ipv6 address space? Every other example of somebody having a problem like this with urllib seems to be related to ipv6

**Comment by chudleycannon** [comment]
IPv6 wasn't set up. I tried adding it and it didn't help either. I can probably work around the error for now, and if you need any more info let me know

**Comment by ilu123** [comment]
hi, am facing the same problem, any updates?

**Comment by tfdahlin** [comment]
Unfortunately have not made any headway on this because I can't reproduce it myself. @ilu123 are you running this in a lambda as well? What does your setup look like for this problem?

**Comment by ilu123** [comment]
@tfdahlin  I ran the lambda in a VPC's public subnet and that error came out. but if I donnot setup lambda to run in VPC, it works well. Well, the VPC and subnet are ipv6 disabled already. And when I request the same url with `curl` in the EC2 located in the same subnet, it works also well.

**Comment by chudleycannon** [comment]
Thats the same as what I experience. In a VCP I get the error above, outside the VPC pytube works as expected.

**Comment by tfdahlin** [comment]
@ilu123 are you able to download a video on the EC2 instance in the subnet? e.g. if you make a simple script like this:
```python
from pytube import YouTube
yt = YouTube('http://youtube.com/watch?v=2lAe1cqCOXo')
yt.streams.first().download()
```
do you run into the same error? I'd be curious to know if you get the same error from pytube on an ec2 instance on the vpc, or if this is a lambda-exclusive

**Comment by 0xPiranhaCodes** [comment]
Even I am facing the same issue. Any resolution for this?

I tried running this in lambda with ipv6 disabled in vpc and subnet.

**Comment by xdrkot** [comment]
I face the same issue with urllib without pytube, just queried yahoo API. It's really intermittent and takes place when infrastructure is unchangeable.
The code is running is AWS Lambda in VPC's public subnet. I don't use ipv6

```[ERROR] URLError: <urlopen error [Errno 97] Address family not supported by protocol>
Traceback (most recent call last):
  File "/var/task/index.py", line 419, in handler
    var = get_var(tr_res)
  File "/var/task/index.py", line 247, in get_var
    prices = get_rates_from_api(symbol)
  File "/var/task/index.py", line 326, in get_rates_from_api
    with urllib.request.urlopen(url) as response:
  File "/var/lang/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/var/lang/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/var/lang/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/var/lang/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/var/lang/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/var/lang/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
```
