### ISSUE TITLE
"pytube.exceptions.RegexMatchError: get_ytplayer_config: could not find match for config_patterns" In previously functioning code

### ISSUE THREAD

**Issue by 54321nicko** [pytube/pytube#941]
______________________________________________________________________________________
python 3.9.1+
pytube 9.6.4   <-- pip install pytube3
pytube @ git+https://github.com/nficano/pytube@4e12eb54d1ee72e41e9a7e53a3d708e300ccf661 
               ^-- python -m pip install git+https://github.com/nficano/pytube
______________________________________________________________________________________

Hi,
I'm using pytube, in the backed for a tkinter gui, to download captions from youtube videos so I can process them. Everything was working as intended and the code responsible for this operation hasn't been touched in days, but when I tried to run my program today,I got this error :

url= https://www.youtube.com/watch?v=lT-wFK4SgJc&list=PL1tiwbzkOjQxD0jjAE7PsWoaCrs0EkBH2&index=16

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1884, in __call__
    return self.func(*args)
  File "/home/nick/Desktop/python/projects/youtubeanalysis/screens/addvideo.py", line 75, in button_submit
    self.controller.AddAvailableVideo(
  File "/home/nick/Desktop/python/projects/youtubeanalysis/controller.py", line 60, in AddAvailableVideo
    model.GetProcessedTranscription(
  File "/home/nick/Desktop/python/projects/youtubeanalysis/model.py", line 260, in GetProcessedTranscription
    filename, path, b = GetVideoTranscription(vid_url)
  File "/home/nick/Desktop/python/projects/youtubeanalysis/model.py", line 320, in GetVideoTranscription
    filename, path, new_path = _DownloadRawCaptions(vid_url, lang)
  File "/home/nick/Desktop/python/projects/youtubeanalysis/model.py", line 341, in _DownloadRawCaptions
    **yt = YouTube(vid_url)**
  File "/home/nick/Desktop/python/projects/youtubeanalysis/venv/lib/python3.9/site-packages/pytube/__main__.py", line 91, in __init__
    self.prefetch()
  File "/home/nick/Desktop/python/projects/youtubeanalysis/venv/lib/python3.9/site-packages/pytube/__main__.py", line 183, in prefetch
    self.js_url = extract.js_url(self.watch_html)
  File "/home/nick/Desktop/python/projects/youtubeanalysis/venv/lib/python3.9/site-packages/pytube/extract.py", line 143, in js_url
    base_js = get_ytplayer_config(html)["assets"]["js"]
  File "/home/nick/Desktop/python/projects/youtubeanalysis/venv/lib/python3.9/site-packages/pytube/extract.py", line 202, in get_ytplayer_config
    raise RegexMatchError(caller="get_ytplayer_config", pattern="config_patterns")
pytube.exceptions.RegexMatchError: get_ytplayer_config: could not find match for config_patterns
```

- I've tried using different videos but this didn't work.
- I've updated everything and followed the instructions in the bug report window but this didn't work.
- I've checked my own code to see if I altered something up stream but this wasn't the case.
- I've checked my logs but nothing was out of the ordinary.

The error occurs at the very beginning when I do something in the lines of: 
```
from pytube import YouTube 

.....
# With vid_url a string, directly taken from the input of the user. 
yt =  YouTube(vid_url) 

```
But all this worked before and this bit was copied almost literally from the docs so I'm fairly certain the problem isn't on my end... 

Anyway, I hope you'll fix this soon because pytube is absolutely fantastic (and I don't want to have to redo all my code with a crappy substitute...)

Thanks

**Comment by tfdahlin** [comment]
hi @54321nicko I'm fairly certain this is an issue with the split/merge of pytube/pytube3 a little over a year ago. pytube and pytube3 share a namespace, and create conflicts when both are installed, but pytube3 hasn't been touched in about a year now. 
If running
```python
import pytube
print(pytube.__version__)
```
prints 9.6.4, then you have pytube3 installed.

There have been several forks of pytube that were maintained briefly, then dropped, so to make sure you have pytube installed properly, you should uninstall all existing version of pytube first with `python -m pip uninstall pytube pytube3 pytubex`.
Then after doing that, run `python -m pip install --upgrade pytube`.

If it has installed correctly, you should have version 10.5.1, not 9.6.4

**Comment by 54321nicko** [comment]
@tfdahlin Thanks for the quick response. It appears you're right. I uninstalled everything and reinstalled in the way you mentioned and now it works. Thank you very much!

**Comment by tfdahlin** [comment]
Glad that worked for you!
