### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TimDSChoi** [pytube/pytube#949]
**Before creating an issue**

Please confirm that you are on the latest version of pytube by installing from the source.
You can do this by running `python -m pip install git+https://github.com/pytube/pytube`.
Sometimes, the pypi library repository is not up to date, and your issue may have been fixed already!

**Describe the bug**
urllib.error.HTTPError: HTTP Error 404: Not Found

**To Reproduce**
>>> import pytube
>>> p = pytube.Playlist('https://www.youtube.com/playlist?list=PLg0OBzfAXdsrNhPhH85_LSs7fDjYW_7sX')
>>> p.videos # <generator object Playlist.videos at 0x7feffe799c80>
>>> p  <- error Occured

**Expected behavior**
>>> p 
>>> ['video1_url', 'video2_url',...] 

**Output**
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/dooseop/PycharmProjects/snji_bot/venv/lib/python3.8/site-packages/pytube/contrib/playlist.py", line 230, in __repr__
    return f"{self.video_urls}"
  File "/Users/dooseop/PycharmProjects/snji_bot/venv/lib/python3.8/site-packages/pytube/contrib/playlist.py", line 211, in video_urls
    for page in list(self._paginate())
  File "/Users/dooseop/PycharmProjects/snji_bot/venv/lib/python3.8/site-packages/pytube/contrib/playlist.py", line 78, in _paginate
    req = request.get(load_more_url, extra_headers=headers)
  File "/Users/dooseop/PycharmProjects/snji_bot/venv/lib/python3.8/site-packages/pytube/request.py", line 42, in get
    return _execute_request(url, headers=extra_headers).read().decode("utf-8")
  File "/Users/dooseop/PycharmProjects/snji_bot/venv/lib/python3.8/site-packages/pytube/request.py", line 26, in _execute_request
    return urlopen(request)  # nosec
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**System information**
Please provide the following information:
- Python 3.8 
- MacOS Bigsur
- pytube version 10.5.1

Yesterday, It worked without any problem.
However, when I ran the program today, the following error occurred. I don't know why. 
Please check.

Thanks a lot.

**Comment by p2xcode** [comment]
Same problem on my end but it's not consistent.

For example playlist url causes that same error = https://www.youtube.com/playlist?list=PLdgoQ6C3ckQv0XCp8S9zSswMuiss8lvcC
But this playlist url works = https://www.youtube.com/playlist?list=PLhu1QCKrfgPVI4oP_bKz1NvbPgsRaE8AQ

**Comment by bigbluedeer** [comment]
Youtube changed their way of formatting the load_more responses and also which requests you need to make on march 2/3. My script (which does this manually) broke as well. I guess the error is in the _build_continuation_url function of the playlist class. Ill work on providing a quick pull later today
