### ISSUE TITLE
KeyError: 'dur'  for specific url both using playlist and youtube object approach.

### ISSUE THREAD

**Issue by 54321nicko** [pytube/pytube#957]
Hi there,
I have code automatically running through a playlist's videos and downloading the captions for each one, to be processed later.
Everything works great for the 100+ videos in the list, except for this one video somewhere midway through. 
For some reason, this one throws a KeyError: 'dur'  that originates somewhere in the pytube caption files.

I tried using the same url in a different function that downloads the captions of a single video and it throws the same error.

This is the error i'm getting:
```
ERROR:func.transcription:GetProcessedTranscription: Error occured while processing https://www.youtube.com/watch?v=FJ25t2cM6Ws&list=PL1tiwbzkOjQxD0jjAE7PsWoaCrs0EkBH2&index=31
Traceback (most recent call last):
  File "/home/nick/Desktop/python/projects/youtubeanalysis/youtubeanalysis/func/transcription.py", line 51, in GetProcessedTranscription
    filename, _, path, b = GetVideoTranscription(vid_url)
  File "/home/nick/Desktop/python/projects/youtubeanalysis/youtubeanalysis/func/transcription.py", line 112, in GetVideoTranscription
    filename, path, new_path = _DownloadRawCaptions(vid_url, lang)
  File "/home/nick/Desktop/python/projects/youtubeanalysis/youtubeanalysis/func/transcription.py", line 147, in _DownloadRawCaptions
    cap = xml.generate_srt_captions()
  File "/home/nick/Desktop/python/projects/youtubeanalysis/venv/lib/python3.9/site-packages/pytube/captions.py", line 44, in generate_srt_captions
    return self.xml_caption_to_srt(self.xml_captions)
  File "/home/nick/Desktop/python/projects/youtubeanalysis/venv/lib/python3.9/site-packages/pytube/captions.py", line 72, in xml_caption_to_srt
    duration = float(child.attrib["dur"])
KeyError: 'dur'
```
url: https://www.youtube.com/watch?v=FJ25t2cM6Ws&list=PL1tiwbzkOjQxD0jjAE7PsWoaCrs0EkBH2&index=31
python v.3.9.1+
pytube v.10.5.3
Linux

Anyway, I don't know if it's a bug or something on my part but I could really use you guys' help.

Thanks.

**Comment by tfdahlin** [comment]
I'll try to look into this sometime today, what language are you downloading the captions for?

**Comment by 54321nicko** [comment]
Thanks. I'm downloading the English subtitles.

**Comment by nipunasudha** [comment]
Any update on this? I also get the same error for this specific video only

https://www.youtube.com/watch?v=wyFmfiaHucY&t=3629s&ab_channel=TommyInnit

**Comment by nipunasudha** [comment]
I found the reason for this issue! some subtitles doesn't contain the `dur` key! to fix this issue, you may have to check for absence of `dur` and skip those subtitles.

![image](https://user-images.githubusercontent.com/17500323/111085631-2b8c1780-853e-11eb-911e-ad52d9477473.png)
