### ISSUE TITLE
[BUG] in python 3.4.4

### ISSUE THREAD

**Issue by spyrosmas** [pytube/pytube#962]
trying to run pytube.exe and getting: 

Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\pytube.exe\__main__.py", line 5, in <module>
  File "c:\python34\lib\site-packages\pytube\__init__.py", line 16, in <module>
    from pytube.streams import Stream
  File "c:\python34\lib\site-packages\pytube\streams.py", line 17, in <module>
    from pytube import extract
  File "c:\python34\lib\site-packages\pytube\extract.py", line 7, in <module>
    from pytube.compat import quote
ImportError: cannot import name 'quote'

**Comment by tfdahlin** [comment]
hi @spyrosmas, pytube does not support python versions before 3.6 -- we recommend that you update to a more recent version of python
