### ISSUE TITLE
MaxRetriesExceeded on 10.7.1

### ISSUE THREAD

**Issue by mayank250004** [pytube/pytube#976]
Previous Version giving Error 404 Not Found (10.6.1) on the same Video (144P) and now this one.

Please check following logs 

Traceback (most recent call last):
  File "ytube.py", line 168, in <module>
    downloadRawYoutube("https://youtu.be/DIGVb2gR8mc","TestingsDelete/Course/TestingNow")
  File "ytube.py", line 84, in downloadRawYoutube
    yt_obj.streams.get_by_itag(160).download()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytube/streams.py", line 255, in download
    for chunk in request.stream(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytube/request.py", line 153, in stream
    raise MaxRetriesExceeded()
pytube.exceptions.MaxRetriesExceeded

**Comment by tfdahlin** [comment]
@mayank250004 good catch, I slightly messed up my logic in v10.7.0 when I added timeout and retry support for downloads. I'll fix this issue now

**Comment by tfdahlin** [comment]
This should be fixed in pytube 10.7.2 which is available on pypi
