### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by m0binasadi** [pytube/pytube#981]
>>> yt = YouTube('http://www.youtube.com/watch?v=Ik-RsDGPI5Y')
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    yt = YouTube('http://www.youtube.com/watch?v=Ik-RsDGPI5Y')
  File "C:\Users\pardaz_Rayan\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\__main__.py", line 91, in __init__
    self.prefetch()
  File "C:\Users\pardaz_Rayan\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\__main__.py", line 183, in prefetch
    self.js_url = extract.js_url(self.watch_html)
  File "C:\Users\pardaz_Rayan\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\extract.py", line 143, in js_url
    base_js = get_ytplayer_config(html)["assets"]["js"]
  File "C:\Users\pardaz_Rayan\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\extract.py", line 202, in get_ytplayer_config
    raise RegexMatchError(caller="get_ytplayer_config", pattern="config_patterns")
pytube.exceptions.RegexMatchError: get_ytplayer_config: could not find match for config_patterns
>>>

**Comment by tfdahlin** [comment]
@m0binasadi you're using an outdated version of pytube. Please update to the latest version (currently 10.7.2) with `python -m pip install --upgrade pytube`, and it should fix your problem.
