### ISSUE TITLE
Return 404 for YouTube shorts videos[BUG]

### ISSUE THREAD

**Issue by meomkarchavan** [pytube/pytube#997]
This is the Video link am using 
[https://www.youtube.com/watch?v=IFK-80J4GhE](Viral Block Video)
This is the code I used
```
from pytube import YouTube

url="https://www.youtube.com/watch?v=IFK-80J4GhE"
vid = YouTube(url)
print(vid.length)
```
This is the response object am getting for all the attributes:

```Traceback (most recent call last):
  File "e:/Omkar/Upwork/Devils Call/Untitled-1.py", line 5, in <module>
    print(vid.length)
  File "E:\Omkar\Upwork\Devils Call\.venv\lib\site-packages\pytube\__main__.py", line 383, in length
    self.player_config_args.get("length_seconds")
  File "E:\Omkar\Upwork\Devils Call\.venv\lib\site-packages\pytube\__main__.py", line 187, in player_config_args
    self._player_config_args = self.vid_info
  File "E:\Omkar\Upwork\Devils Call\.venv\lib\site-packages\pytube\__main__.py", line 278, in vid_info
    return dict(parse_qsl(self.vid_info_raw))
  File "E:\Omkar\Upwork\Devils Call\.venv\lib\site-packages\pytube\__main__.py", line 108, in vid_info_raw
    self._vid_info_raw = request.get(self.vid_info_url)
  File "E:\Omkar\Upwork\Devils Call\.venv\lib\site-packages\pytube\request.py", line 52, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "E:\Omkar\Upwork\Devils Call\.venv\lib\site-packages\pytube\request.py", line 36, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 563, in error
    result = self._call_chain(*args)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```
I am only able to get 
```video_id
watch_url
watch_html
publish_date
```

Rest all gives the above error.

**Comment by Ssuwani** [comment]
It works for me [PR](https://github.com/pytube/pytube/pull/996)
```bash
pip uninstall pytube
python -m pip install git+https://github.com/ssuwani/pytube
```

**Comment by meomkarchavan** [comment]
Thanks
