### ISSUE TITLE
[BUG] Demo example not working

### ISSUE THREAD

**Issue by Engin1980** [pytube/pytube#999]
Hello, I was trying to get working the example at the main page, slightly updated to:

```
from pytube import YouTube
yt = YouTube('https://youtu.be/2lAe1cqCOXo')
print(yt.title) # <-- here is the exception
```
.. but got an 404 exception (see below for full stack trace).

Installed environment is `pytube 10.8.2` from the GitHub source.

**System information**
Python 3.7.6
PyTube 10.8.2

Exception:

```
`C:\Users\Vajgl\pythonEnvironments\youtube\Scripts\python.exe "C:/Users/Vajgl/Documents/Visual Studio 2017/Projects/mepac/pythonProject/main.py"
Traceback (most recent call last):
  File "C:/Users/Vajgl/Documents/Visual Studio 2017/Projects/mepac/pythonProject/main.py", line 3, in <module>
    yt = YouTube('https://youtu.be/2lAe1cqCOXo')
  File "C:\Users\Vajgl\pythonEnvironments\youtube\lib\site-packages\pytube\__main__.py", line 104, in __init__
    self.prefetch()
  File "C:\Users\Vajgl\pythonEnvironments\youtube\lib\site-packages\pytube\__main__.py", line 221, in prefetch
    self.vid_info_raw = request.get(self.vid_info_url)
  File "C:\Users\Vajgl\pythonEnvironments\youtube\lib\site-packages\pytube\request.py", line 42, in get
    return _execute_request(url, headers=extra_headers).read().decode("utf-8")
  File "C:\Users\Vajgl\pythonEnvironments\youtube\lib\site-packages\pytube\request.py", line 26, in _execute_request
    return urlopen(request)  # nosec
  File "C:\Program Files\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Program Files\Python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files\Python37\lib\urllib\request.py", line 563, in error
    result = self._call_chain(*args)
  File "C:\Program Files\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python37\lib\urllib\request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Program Files\Python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Program Files\Python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files\Python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Program Files\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

Process finished with exit code 1
``

**Comment by iim-ayush** [comment]
I don't think that is even a bug.

I suggest you to re-install pytube for your device

![image](https://user-images.githubusercontent.com/65385476/119224244-27bad980-bb1b-11eb-8c87-abc0295c3d07.png)

**Comment by Mahmoudgarwallane** [comment]
@killer069  
thanks you !!

**Comment by Mahmoudgarwallane** [comment]
@killer069  **thank you**  _!!_

**Comment by Engin1980** [comment]
You were right, I got lost in environments. Thank you for your time.
